### ISSUE TITLE
Working Example WinRT in Unreal

### ISSUE THREAD

**Issue by jworch** [MicrosoftDocs/mixed-reality#102]
Hi, is it possible to get a working copy of the presented example? Because no matter what I do, I cannot get it running. I think  I followed every step but I must have overseen something. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 74770102-2289-8f0a-cabc-a5e15b5a4a88
* Version Independent ID: 61fa1f2b-f423-81f3-d42f-9fe9867950c8
* Content: [WinRT in Unreal - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unreal/unreal-winrt)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-winRT.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-winRT.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @fieldsJacksonG
* Microsoft Alias: **jacksonf**

**Comment by hferrone** [comment]
@fieldsJacksonG Do you have a final build for this doc?

**Comment by hferrone** [comment]
@jworch Are you getting any specific errors or console output that could help us pinpoint the issue for you?

**Comment by jworch** [comment]
Finally I had some time to work on that again. Right now I get the following error message when compiling the Consumewinrt solution:

`Error	LNK2019	unresolved external symbol "public: static void __cdecl AWinrtActor::OpenFileDialogue(void)" (?OpenFileDialogue@AWinrtActor@@SAXXZ) referenced in function "public: static void __cdecl AWinrtActor::execOpenFileDialogue(class UObject *,struct FFrame &,void * const)" (?execOpenFileDialogue@AWinrtActor@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z)	Consumewinrt	C:\Data-NoBackup\Unreal\Consumewinrt\Intermediate\ProjectFiles\WinrtActor.gen.cpp.obj	1	
`

before that I changed the line 
`    UFUNCTION(BlueprintCallable)`
`    static void OpenFileDialogue;`
to
`    UFUNCTION(BlueprintCallable)`
`   static void OpenFileDialogue();`
which should probably be updated in the readme as well.

**Comment by hferrone** [comment]
@fieldsJacksonG bump :)

**Comment by jworch** [comment]
Any updates here?

**Comment by fieldsJacksonG** [comment]
Looks like some transcription errors in the doc.  BeginPlay should load the DLL, referencing the same path as the runtime dependency in the build.cs:
void AWinrtActor::BeginPlay()
{
	Super::BeginPlay();

	const FString BinDir = FPaths::ProjectDir() / 
		"ThirdParty" / "HoloLensWinrtDLL" / 
		"arm64" / "Release" / "HoloLensWinrtDLL";
	void * dllHandle = FPlatformProcess::GetDllHandle(
		*(BinDir / "HoloLensWinrtDLL.dll"));
}

Then the UFUNCTION body in the cpp should look like this:
void AWinrtActor::OpenFileDialogue()
{
#if PLATFORM_HOLOLENS
	HoloLensWinrtDLL::OpenFileDialogue();
#endif
}

Make sure you revert your change to the header, the definition should still look like it does in the doc:
UFUNCTION(BlueprintCallable)
static void OpenFileDialogue;

**Comment by jworch** [comment]
Minor update: I was able to compile, and add the Winrtactor as well as the OpenFileDialog Call to the blueprint. Unfortunately I cannot test that right now. Probably gonna take another week or two. Nevertheless, it does NOT compile when reverting the changes in the header. 

`UFUNCTION(BlueprintCallable)`
`static void OpenFileDialogue`**()**`;`

() are necessary for me, to make it compile. Also I am a bit confused by a function definition without paranthesis. Never seen that. Could you explain that to me?

**Comment by fieldsJacksonG** [comment]
Sorry, you are totally correct, parens are definitely needed.  Dug up the original project used to create the doc, see it here:
https://1drv.ms/u/s!AmC-atmmBtrhm6pGO9xlg3nepiYK5g?e=wDGD1y

**Comment by jworch** [comment]
Awesome. Thanks a lot. I had first rough look and it seems to be similar to what compiles for me now. Should work then. In that case, I'll close this issue. When I have time again and it's not working I'll reopen. Thanks again.

**Comment by jworch** [comment]
Just a minor addition: These changes should be incorporated into the docs.

```
void AWinrtActor::BeginPlay()
{
	Super::BeginPlay();

	const FString BinDir = FPaths::ProjectDir() / 
		"ThirdParty" / "HoloLensWinrtDLL" / 
		"arm64" / "Release" / "HoloLensWinrtDLL";
	void * dllHandle = FPlatformProcess::GetDllHandle(
		*(BinDir / "HoloLensWinrtDLL.dll"));
}
```

```
UFUNCTION(BlueprintCallable)
static void OpenFileDialogue();
```
