### ISSUE TITLE
Can not build ARM due to \build\bin\ARM\Release\GameAssembly.lib is missing

### ISSUE THREAD

**Issue by Seajanjan** [MicrosoftDocs/mixed-reality#103]
I'm trying to deploy my app to my HoloLens 2 and after "Start Without Debugging" I'm getting this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	Input file"C:\Users\MyName\MyOneDrive\Desktop\MyProject\build\bin\ARM\Release\GameAssembly.lib" was unable to open.	MyProject	C:\Users\MyName\MyOneDrive\Desktop\MyPrject\MyProjectName\LINK	1

**Comment by Seajanjan** [comment]
I've worked through https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio#deploying-an-app-over-usb---hololens-2 this tutorial.

Versions: 
 - Unity 2019.4.4f1
 - VS2019 16.7.6

Note: I have 2 errors in the Unity console.
First error:
Error: Could not load signature of Microsoft.Azure.Storage.Core.Auth.BlobSharedAccessSignatureHelper:GetSignature due to: Could not resolve type with token 01000030 (from typeref, class/assembly Microsoft.Azure.Storage.UserDelegationKey, Microsoft.Azure.Storage.Common, Version=11.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) assembly:Microsoft.Azure.Storage.Common, Version=11.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:Microsoft.Azure.Storage.UserDelegationKey member:(null) signature:<none>

Second error:
Unloading broken assembly Assets/Plugin/Microsoft.Azure.Storage.Blob.dll, this assembly can cause crashes in the runtime

But the build in Unity just worked fine for me.

**Comment by hferrone** [comment]
@pbarnettms Can you assist or mention someone who can? (You're listed as the doc author)

**Comment by hferrone** [comment]
Hi @Seajanjan, the issues with the Azure dll isn't related to the doc you're following or Visual Studio. Please see the support info on this page: https://docs.microsoft.com/en-us/hololens/hololens-feedback

**Comment by AlexP-Coding** [comment]
@Seajanjan , did you figure out the origin?
