### ISSUE TITLE
Windows SDK 18362

### ISSUE THREAD

**Issue by ActiveNick** [MicrosoftDocs/mixed-reality#1033]
There should be a preliminary step or cross-ref to a separate "setup" page that explains the need to install the proper Windows SDK 18362 *before* creating any new project. The minimum platform version should also be set to 18362 in the build settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [MR Learning Base Module Project Initialization and First Application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@ActiveNick Windows SDK 18362 is listed as a prerequisite in the main page: https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base.md

If you feel this needs to be repeated again prior to starting lesson 1, let me know and I can add in a note. Also, I believe the project will still run even if the minimum platform version isn't set to 18362 in the build settings.

**Comment by mr0ng** [comment]
@jessemcculloch feel free to close issue if you feel it's resolved
