### ISSUE TITLE
Link to BaseModule assets not working

### ISSUE THREAD

**Issue by davidraguilar** [MicrosoftDocs/mixed-reality#1040]
https://github.com/Microsoft/MixedRealityLearning/releases/tag/V1.1 = 404 :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e480f6-30d8-9538-bff1-74ba54dc310e
* Version Independent ID: 1cb31b72-b828-d8d3-74fa-6641a61f3750
* Content: [MR Learning Base Module 3D Object Interaction - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by jessemcculloch** [comment]
@davidraguilar - Can you try again, this should be fixed.  If so, can you please close the issue?

**Comment by davidraguilar** [comment]
@jessemcculloch works now. Thank you!
