### ISSUE TITLE
Is broken.

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/mixed-reality#1047]
NullReferenceException: Object reference not set to an instance of an object.
   at SpatialMapping.Start()
   at SpatialMapping.$Invoke1Start(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: &lt;Unknown&gt; Line: 0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3e0711-ce63-b64a-2933-4656a33acf68
* Version Independent ID: f368c378-4847-555e-8db5-aa960532a7a9
* Content: [MR and Azure 310 - Object detection - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-310)
* Content Source: [mixed-reality-docs/mr-azure-310.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-310.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @DrNeil
* Microsoft Alias: **jemccull**

**Comment by LuGar54** [comment]
I know my answer is late, but in case anybody else has the same issue, to fix it you have to remove the missing script on the spatial mapping gameobject and add a SpatialMappingCollider.
