### ISSUE TITLE
Inconsistency between the text and the screenshot

### ISSUE THREAD

**Issue by mchikobava** [MicrosoftDocs/mixed-reality#105]
In the Hierarchy window, select the RoverAssembly object, then in the Inspector window, configure the Tap To Place (Script) component as follows:

Uncheck the checkbox next to its name to make it inactive by default
In the **On Placing Started ()** event section, click the + icon to add a new event:
Assign the RoverExplorer > RoverAssembly object to the None (Object) field
From the No Function dropdown, select TapToPlace > bool Enabled to update this property value when the event is triggered
Verify that the argument checkbox is unchecked

On the screenshot, it is **On Placing Stopped ()**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d5ccf2-6270-b146-f5ca-3da70c886028
* Version Independent ID: 23fdfa60-4d98-86d3-a069-fdd316a3bd23
* Content: [Getting started tutorials - 6. Creating user interfaces - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-06)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @mchikobava, yes that was a typo, it's been fixed. Thanks for filling feedback!
