### ISSUE TITLE
Use a brighter color for highlights in the pictures

### ISSUE THREAD

**Issue by Reynolds-Beta** [MicrosoftDocs/mixed-reality#1051]
SUGGESTION
I have been going through many of the documents and find my eyes straining to see the red (I assume they are red) highlights being used in the pictures: Small boxes, rectangles, arrows seem to blend into the background, while the larger ones are visible. It really depends on the thickness and vibrancy of the lines being used. I happen to know I'm at least partially red/green color blind, which is actually pretty common among men. Perhaps yellow for highlights, with maybe a bit thicker lines?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5ff554d8-c68d-28a2-1331-3177bc8f6d71
* Version Independent ID: a4419d7e-9355-76fd-4ca7-9ea26cb0a5aa
* Content: [MR Learning Base Module - User Interface, Hand Tracking, and Mixed Reality Toolkit Configuration - Mixed Reality](https://docs.microsoft.com/ja-jp/windows/mixed-reality/mrlearning-base-ch2?WT.mc_id=mixedreality-twitter-machiy)
* Content Source: [mixed-reality-docs/mrlearning-base-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@Reynolds-Beta Great feedback Jeff. We're currently going back through all the images and increasing the thickness and vibrancy of the rectangles and highlights. Would you mind reviewing this image to see if this is adequate or if you would like the rectangles to be further modified? Thank you! https://github.com/MicrosoftDocs/mixed-reality/blob/MRLearningSpeech/mixed-reality-docs/images/module4chapter1step3im.PNG

**Comment by Reynolds-Beta** [comment]
Thanks Sean. I’ll get to it today. Right now I’m at the hospital waiting for a family member to get out of surgery. WiFi and cell signal sucks 😉

Jeff Reynolds
- Xbox Live, Microsoft

Jeff Reynolds
206.979.4047
________________________________

**Comment by Reynolds-Beta** [comment]
Sean,

Oh heck yeah that's better! Much more obvious and easy to see. Thanks!

Jeff

________________________________
