### ISSUE TITLE
How to disable the OpenXR runtime?

### ISSUE THREAD

**Issue by tksharpless** [MicrosoftDocs/mixed-reality#107]
The OpenXR runtime, installed I guess by Win10 2004 update, is interfering with testing apps under development -- partly because it kills SteamVR, and partly because it does not seem to work as inteded.  For example the WMR OpenXR DevTool is unable to show its demo scene; and the MS supplied sample BasicXrApp builds but gets exceptions from the runtime.

So I need to bbe able to disable it.  This page should say how.

My system is a Dell 5577 gaming laptop with Intel Integrated Graphics + nVidia GTX 1050.  I suspect the runtime is undable to deal properly with IIG -- a not uncommon fault.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b0b469b-075e-0476-4d19-103c4bea67f0
* Version Independent ID: 2a82b90e-24c0-d186-1e85-5d725c1748db
* Content: [OpenXR troubleshooting - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-troubleshooting)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/native/openxr-troubleshooting.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/native/openxr-troubleshooting.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
@thetuvix Can you assist with this?

**Comment by tksharpless** [comment]
It appears that the WMR runtime has not changed.  The issue with SteamVR + Win10 2004 has been resolved by some Steam beta updates.  However the basic problem with WMR remains: several Microsoft apps fail to enter VR, without any error indication.






i

**Comment by hferrone** [comment]
Hey @tksharpless, please file a support ticket - https://docs.microsoft.com/en-us/hololens/hololens-feedback, thanks!

**Comment by thetuvix** [comment]
For Windows Mixed Reality VR headsets, the Feedback Hub info you'll need is here: https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/filing-feedback

Hybrid integrated/discrete laptop GPU setups can indeed have unique issues - filing a bug through Feedback Hub will help us gather the right details from your system setup to get this fixed!  Thanks so much!
