### ISSUE TITLE
Typo, need to change word "tyoe" to "type"

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#1073]
""Error: CS0246 = The tyoe or namespace name “XX” could not be found (are you missing a using directive or an assembly reference?)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [MR Learning Base Module - Project Initialization and First Application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by jessemcculloch** [comment]
Fixed with PR #1152 and pushed live with #1155 , thank you for flagging
