### ISSUE TITLE
New MRTK Steps Need Screenshots

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/mixed-reality#1079]
The MRTK will now ask for a profile selection.

This occurs between Step 1 and Step 2 in the "Configure the Mixed Reality Toolkit"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [MR Learning Base Module - Project Initialization and First Application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by LanceMcCarthy** [comment]
To be specific here's what happens:

![image](https://user-images.githubusercontent.com/3520532/57167490-d19f6000-6db2-11e9-8aa8-602cbff129ef.png)

Then clicking OK shows the following:

![image](https://user-images.githubusercontent.com/3520532/57167517-e54ac680-6db2-11e9-85fa-400ba312b7a3.png)

**Comment by mr0ng** [comment]
Thank you @LanceMcCarthy ! We'll integrate these screenshots into the lessons
