### ISSUE TITLE
HoloLens 2 Emulator input controls not working

### ISSUE THREAD

**Issue by wearablesdsa** [MicrosoftDocs/mixed-reality#1083]
Released an app to the HoloLens 2 Emulator but I have no controls in the emulator. Can not move the cursor or navigate with keys.

I used the InteractablesExample scene from the MRTKv2.0.0-RC1 Foundation Unity package. Built the app as standard in Unity. Open the VS solution. Set it to Release/x64/Hololens 2 Emulator (also tried changing it to Debug and x86 but the result was same). The Emulator starts and I get this message in VS

![emulator_retry](https://user-images.githubusercontent.com/48983327/57218937-ea985300-6ff6-11e9-9d04-28849ed33d85.PNG)

I Retry and the Emulator starts but I dont have any input controls.

![emulator_main](https://user-images.githubusercontent.com/48983327/57220445-a5c2eb00-6ffb-11e9-8501-51358b82db23.PNG)

I also set a message in VS that there were deployment errors and after that that Bootstrapper could not connect to machine.

![emulator_depl_err](https://user-images.githubusercontent.com/48983327/57220472-ba06e800-6ffb-11e9-9c75-adcae7f07605.PNG)

![emulator_bootstrp](https://user-images.githubusercontent.com/48983327/57220512-e0c51e80-6ffb-11e9-8166-9d35418a07e0.PNG)

In the Output window I get:

DEP6953: Failed to launch remote debugger with the following error: 'Command failed: 0x80270254'.

And in the Error List i get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6100: The following unexpected error occurred during bootstrapping stage 'Connecting to the device '475D2000-0BFD-816F-5DFF-91985AF2F434'.': ObjectDisposedException - Cannot access a disposed object.
Object name: 'XdeServiceClient10_0'. [0x80131622]	HoloLens2 Emulator testing			

And this:

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6953: Failed to launch remote debugger with the following error: 'Command failed: 0x80270254'.	HoloLens2 Emulator testing

**Comment by pbarnettms** [comment]
Per the Troubleshooting section at https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator, please try running Visual Studio as Administrator and let us know if this does not resolve your issue.

**Comment by wearablesdsa** [comment]
> Per the Troubleshooting section at https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator, please try running Visual Studio as Administrator and let us know if this does not resolve your issue.

That worked, I now have control in the emulator but it seams very buggy. Main menu keeps randomly popping up and closing, I loose control of the cursor periodically, the emulator reboots by itself... Is this normal?

**Comment by pbarnettms** [comment]
The main menu will appear or disappear in response to pressing F2 or the Windows key when the emulator window has focus.  It will also respond to gamepad input (e.g., the Xbox button on an Xbox controller).  Is there any chance you are pressing any of these keys/buttons?  Do you have a controller/gamepad attached?  If so, do you see this problem if you disconnect it?

**Comment by pbarnettms** [comment]
If you do have a controller/gamepad attached, instead of disconnecting it you can uncheck "Use gamepad for simulation" or press F6 which is the shortcut key for that.  Does that help?

**Comment by wearablesdsa** [comment]
No, I am not pressing any of these buttons unintentionally and I am not using a controller. I did uncheck "use gamepad for simulation" which somehow seams to helped. I have better control of the cursor now, the menu does not pop-up and close on its own anymore but the emulator will not run my app, it just fails and restarts the emulator. The same app runs on HoloLens1 device fine.

**Comment by pbarnettms** [comment]
What version of Windows 10 are you running? (i.e., what is the output of "ver" at a command prompt?)  Is there any chance you've installed any gamepad emulation software or other simulation input devices between your first (good) and second (bad) experience?

What is the nature of your app?  Does the emulator restart at a specific point in your app or just when trying to deploy?  If you can provide a min repro or specific API that your app is calling that's triggering the problem, that would be helpful.

**Comment by pbarnettms** [comment]
Closing this issue as the customer has not responded in 2 months.  The latest version of the emulator (10.0.18362.1021) no longer requires elevation and so the original issue will not reproduce.
