### ISSUE TITLE
HoloLens 2 Emulator input controls not working

### ISSUE THREAD

**Issue by wearablesdsa** [MicrosoftDocs/mixed-reality#1084]
Released an app to the HoloLens 2 Emulator but I have no controls in the emulator. Can not move the cursor or navigate with keys.

View on GitHub: https://github.com/MicrosoftDocs/mixed-reality/issues/1083

I used the InteractablesExample scene from the MRTKv2.0.0-RC1 Foundation Unity package. Built the app as standard in Unity. Open the VS solution. Set it to Release/x64/Hololens 2 Emulator (also tried changing it to Debug and x86 but the result was same). The Emulator starts and I get this message in VS

![emulator_retry](https://user-images.githubusercontent.com/48983327/57218937-ea985300-6ff6-11e9-9d04-28849ed33d85.PNG)

I Retry and the Emulator starts but I dont have any input controls.

![emulator_main](https://user-images.githubusercontent.com/48983327/57220445-a5c2eb00-6ffb-11e9-8501-51358b82db23.PNG)

I also set a message in VS that there were deployment errors and after that that Bootstrapper could not connect to machine.

![emulator_depl_err](https://user-images.githubusercontent.com/48983327/57220472-ba06e800-6ffb-11e9-9c75-adcae7f07605.PNG)

![emulator_bootstrp](https://user-images.githubusercontent.com/48983327/57220512-e0c51e80-6ffb-11e9-8166-9d35418a07e0.PNG)

In the Output window I get:

DEP6953: Failed to launch remote debugger with the following error: 'Command failed: 0x80270254'.

And in the Error List i get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6100: The following unexpected error occurred during bootstrapping stage 'Connecting to the device '475D2000-0BFD-816F-5DFF-91985AF2F434'.': ObjectDisposedException - Cannot access a disposed object.
Object name: 'XdeServiceClient10_0'. [0x80131622]	HoloLens2 Emulator testing			

And this:

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6953: Failed to launch remote debugger with the following error: 'Command failed: 0x80270254'.	HoloLens2 Emulator testing			

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment]
This is the same as issue 1083.  Closing this instance.
