### ISSUE TITLE
Render from the PV Camera for MRC.

### ISSUE THREAD

**Issue by zhangypcn** [MicrosoftDocs/mixed-reality#109]
[在此处输入反馈]

The return value of the camera captured image obtained through **GetARCameraImage** has been invalid. I have made relevant settings, including enabling Webcam, StartCameraCapture, and SetEnabledMixedRealityCamera.

Has anyone tested the GetARCameraImage node, and can you share your successful experience?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2ab48859-8e85-d45a-fb32-86c98af47c30
* Version Independent ID: c3840bec-aae8-2e88-3048-57f985c62a0e
* Content: [Unreal 中的 HoloLens 照片/视频摄像头 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unreal/unreal-hololens-camera)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-hololens-camera.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-hololens-camera.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by zhangypcn** [comment]
@hferrone

**Comment by hferrone** [comment]
@sw5813 Who can we ping to get this rolling?

**Comment by sw5813** [comment]
@fieldsJacksonG can you offer any guidance here?

**Comment by fieldsJacksonG** [comment]
Can you check your logs in the device portal under: 
"System/ File explorer/ LocalAppData/ %PackageName%/ LocalState/ %ProjectName%/ Save/ Logs/ %ProjectName%.log

Any failures to start the PV camera will be logged here.

Also important to note that StartCameraCapture should be called after StartARSession - you will see an error in your log if this was called too soon.

Future versions of this use UARBlueprintLibrary::ToggleARCapture which will return false for failure cases.

**Comment by zhangypcn** [comment]
I connected and debugged through Holographic Remoting, so there is no log information in the device portal. I was sure that StartCameraCapture was called after StartARSession, and I even delayed a few seconds.

**Comment by zhangypcn** [comment]
> Can you check your logs in the device portal under:
> "System/ File explorer/ LocalAppData/ %PackageName%/ LocalState/ %ProjectName%/ Saved/ Logs/ %ProjectName%.log
> 
> Any failures to start the PV camera will be logged here.
> 
> Also important to note that StartCameraCapture should be called after StartARSession - you will see an error in your log if this was called too soon.
> 
> Future versions of this use UARBlueprintLibrary::ToggleARCapture which will return false for failure cases.

I connected and debugged through Holographic Remoting, so there is no log information in the device portal. I was sure that StartCameraCapture was called after StartARSession, and I even delayed a few seconds.

**Comment by fieldsJacksonG** [comment]
Unfortunately the PV camera is not supported over remoting.

Check the output log in your Unreal project, and you will probably see a warning log:
"HoloLens remoting does not support the device forward facing camera.  No images will be collected."

**Comment by zhangypcn** [comment]
> Unfortunately the PV camera is not supported over remoting.
> 
> Check the output log in your Unreal project, and you will probably see a warning log:
> "HoloLens remoting does not support the device forward facing camera. No images will be collected."

That's really unfortunate! Rendering on the PC is an irreplaceable step in my project.

**Comment by fieldsJacksonG** [comment]
When remoting, you could use a webcam attached to your PC to simulate the HoloLens PV camera.

**Comment by zhangypcn** [comment]
> When remoting, you could use a webcam attached to your PC to simulate the HoloLens PV camera.

Sounds worth a try, can you describe it in more detail?
