### ISSUE TITLE
Click eye for Rover Assembly not Rover Explorer

### ISSUE THREAD

**Issue by Arundelain** [MicrosoftDocs/mixed-reality#11]
Your document says:
To make it easier to work with your scene, in the Hierarchy window, click the eye icon to the left of the object to toggle the scene visibility for the **RoverExplorer** object off. This hides the object in the Scene window without changing its in-game visibility:

This makes everything invisible even the parts that you are manipulating. It should say:
To make it easier to work with your scene, in the Hierarchy window, click the eye icon to the left of the object to toggle the scene visibility for the **RoverAssembly** object off. This hides the object in the Scene window without changing its in-game visibility:

Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340a4a6c-bcfc-9c46-699b-b8d3a61f5fc2
* Version Independent ID: 90437a82-b687-e409-c8ee-da4e4d1fee2f
* Content: [Getting started tutorials - 4. Positioning objects in the scene - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-04)
* Content Source: [mixed-reality-docs/mr-learning-base-04.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-04.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter Is this correct?

**Comment by hferrone** [comment]
@mr0ng @martinwilter Following up :)

**Comment by martinwilter** [comment]
@Arundelain, thanks for pointing out this typo.

@hferrone, we will make a PR for this issue shortly.
