### ISSUE TITLE
AMD wmr reprojection support. 

### ISSUE THREAD

**Issue by JPinlac** [MicrosoftDocs/mixed-reality#110]
Document states that AMD RX470 or better is supported. I currently have an rx5700 and after following the steps there is no reprojection settings for me to toggle. In addition to RDNA1(rx5700/xt) support, will newer RDNA2(rx6800/xt, rx6800) cards be supported? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7290b872-634d-f755-d81c-a6bdb4ddb6a2
* Version Independent ID: c3a75771-abd8-1632-09ff-a1bd56df64dd
* Content: [Using SteamVR with Windows Mixed Reality - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/using-steamvr-with-windows-mixed-reality#enabling-motion-reprojection-for-steamvr-apps)
* Content Source: [enthusiast-guide/using-steamvr-with-windows-mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/using-steamvr-with-windows-mixed-reality.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by JPinlac** [comment]
Stumbled on the settings.

**Comment by hferrone** [comment]
@tesych Is this something you can answer or ping someone your team who can?
