### ISSUE TITLE
HL does not appear in list of devices

### ISSUE THREAD

**Issue by Lindaae** [MicrosoftDocs/mixed-reality#111]
Hi,
I encounter a couple of problem with debugging my apps on the HoloLens and unfortunately microsoft docs could not solve these issues.
When I do as described in this guide (https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unity/managed-debugging-with-unity-il2cpp), first issues is on point 6. Usually I prefer to deploy my apps to the HoloLens via USB as described here: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio#deploying-an-app-over-usb---hololens-2
When I successfully deployed the app to the HL and then disconnect the USB cable, the app on the HL is minimized. I am not sure if this contributes to the issue.

I re-start the app from the menu and continue to follow the guide and to attach a Unity Debugger. But my HL is not showing up  in the list of devices, altough I connected both my laptop and the HL to my home network, which supports multicast.

If I re-connect with USB, it shows in the list of devices but if I click OK to attach the Unity Debugger, nothing happens.

If I try debugging as decribed in the other guide (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-visual-studio#debugging-an-installed-or-running-app), I do not receive any error but also no debug logs.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e939e65b-3ef6-0a64-4a02-90d51b2e3934
* Version Independent ID: 77ee79c6-95df-cc3f-9e55-384661e3b00e
* Content: [Verwaltetes Debuggen mit Unity IL2CPP - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unity/managed-debugging-with-unity-il2cpp)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/managed-debugging-with-unity-il2cpp.md](https://github.com/MicrosoftDocs/mixed-reality-pr.de-de/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/managed-debugging-with-unity-il2cpp.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
Hi @Lindaae, please file a support issue - https://docs.microsoft.com/en-us/hololens/hololens-feedback, thanks!

**Comment by pinkwerks** [comment]
@Lindaae where you able to resolve this? I'm having very similar problems.

**Comment by Lindaae** [comment]
Well, the problem somehow magically resolved itself someday. When I tried debugging again a few month later, it worked. It even works over USB now. But I have really no idea at all what I did to resolve the issue. Sorry about that!
