### ISSUE TITLE
Import of BaseModuleAssets introduces build errors

### ISSUE THREAD

**Issue by Luukjn** [MicrosoftDocs/mixed-reality#1126]
When I import de BaseModuleAssets from step 2 the following build errors are introduced:
Assets\MixedRealityToolkit.SDK\Features\UX\Scripts\Slate\DragEnabler.cs(8,43): error CS0535: 'DragEnabler' does not implement interface member 'IMixedRealityPointerHandler.OnPointerDragged(MixedRealityPointerEventData)'
Assets\MixedRealityToolkit.SDK\Features\UX\Scripts\Slate\SlateEnabler.cs(7,44): error CS0535: 'SlateEnabler' does not implement interface member 'IMixedRealityPointerHandler.OnPointerDragged(MixedRealityPointerEventData)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e480f6-30d8-9538-bff1-74ba54dc310e
* Version Independent ID: 1cb31b72-b828-d8d3-74fa-6641a61f3750
* Content: [MR Learning Base Module - 3D Object Interaction - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@Luukjn Please provide details on which version of the MRTK you're using and which version of Unity you're using. Happy to help you troubleshoot this.

**Comment by Luukjn** [comment]
I'm using unity 2019.1.2f1 and MRTK version 2.0.0-RC1-Refresh

**Comment by Fozybear** [comment]
I'm having the same problem using unity 2018.3.14
-the associated script can not be loaded
-Assets\MixedRealityToolkit.SDK\Features\UX\Scripts\Slate\SlateEnabler.cs(7,44): error CS0535: 'SlateEnabler' does not implement interface member 'IMixedRealityPointerHandler.OnPointerDragged(MixedRealityPointerEventData)'
-Assets\MixedRealityToolkit.SDK\Features\UX\Scripts\Slate\DragEnabler.cs(8,43): error CS0535: 'DragEnabler' does not implement interface member 'IMixedRealityPointerHandler.OnPointerDragged(MixedRealityPointerEventData)'

All scripts where working until I downloaded the Base Module Assets

**Comment by mr0ng** [comment]
@Fozybear I believe the issue may stem from the fact that the Base Module Assets package includes the MRTK examples, but from a MRTK version different than your RC1-Refresh version, which may be causing conflicts. We are working to decouple the MRTK examples from Base Module Assets to reduce the size and also limit potential compatibility issues such as these. Feel free to check in on progress. Thank you!

**Comment by mtaulty** [comment]
Same problem for me here - I hit the same issues that @Fozybear is hitting. I experimented with only importing the prefabs/scripts from the 'BaseModuleAssets' but didn't come to a 2-min solution.

**Comment by Bugs95** [comment]
I was able to solve the problems as follows:
1. Save your scene objects as prefabs
2. Delete the BaseModuleAsset and ExampleAsset
3. Import the ExampleAsset again
4 Load your prefabs in your scene.
