### ISSUE TITLE
The emulator is unable to verify that the virtual machine is running

### ISSUE THREAD

**Issue by sanoopborn1994** [MicrosoftDocs/mixed-reality#1159]
So I have been trying to setup HoloLens 2 emulator on my windows 10, Have been stuck with this issue for more than one week.

Any kind of help is totally appreciated.

![issue_image](https://user-images.githubusercontent.com/50730459/57907035-b3992b80-7899-11e9-9b3c-99d8a87cb3c6.png)

**Comment by pbarnettms** [comment]
The error suggests that the virtual disk might be corrupted.  Have you attempted to mount the .vhdx at all via other means, such as PowerShell or Windows Explorer, or have you experienced any disk corruption recently, such as Windows wanting to repair your disk on boot?

You could attempt to delete the file specified in the error message first -- it will be recreated on the next launch of the emulator.  If that does not resolve the issue, please uninstall and reinstall the emulator and let us know if this does not resolve the issue for you.

**Comment by sanoopborn1994** [comment]
@pbarnettms Yes, I did tried the steps, but it didn't helped at all and also PC is having no issues with disk.

**Comment by pbarnettms** [comment]
@sanoopborn1994 What version of Windows 10 are you using?  You can get this by running "ver" or "winver", such as from a command prompt.

**Comment by sanoopborn1994** [comment]
@pbarnettms  Please find the details attached. 
![snip](https://user-images.githubusercontent.com/50730459/58532987-d2d27a00-8204-11e9-9b2e-5cfdb624ebad.PNG)

**Comment by pbarnettms** [comment]
@sanoopborn1994 Thank you for the detail.  It looks like you're running the April 2018 Update of Windows 10.  The HoloLens 2 Emulator is not supported on this version, as it requires the October 2018 update or newer as noted in the "HoloLens Emulator system requirements" section of https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator.  Please update your operating system.

**Comment by sanoopborn1994** [comment]
@pbarnettms I have update the Windows, This is the latest version details,

![image](https://user-images.githubusercontent.com/50730459/58683970-1b6c6d80-8394-11e9-9487-215670142d28.png)

But still getting the same error upon reinstalling the Emulator, please help out!!

![unnamed](https://user-images.githubusercontent.com/50730459/58684416-d34e4a80-8395-11e9-8eb8-be6a3b3d595d.png)

**Comment by pbarnettms** [comment]
@sanoopborn1994 The Windows 10 October 2018 update is version 1809, build 10.0.17763.  Please update to at least that version.  The version you have installed is not supported for the HoloLens 2 Emulator.

**Comment by sanoopborn1994** [comment]
@pbarnettms 
Well this is a noobie question, please do help, I have tried checking for updates and all, but its says Its currently upto date. 
Then I downloaded Windows10Upgrade.exe file from windows download section, But the installation gets cancelled in between.

**Comment by sanoopborn1994** [comment]
Ok, Finally i was able to update Windows to version 1903
![image](https://user-images.githubusercontent.com/50730459/58862891-4fff6280-86cf-11e9-8cac-deb794306508.png)

But when I try to launch the Emulator, this pop up window is coming, 
![image](https://user-images.githubusercontent.com/50730459/58862891-4fff6280-86cf-11e9-8cac-deb794306508.png)

And when I run using retry method, the Emulator will be stuck at saying OS is starting for more than 1-2 Hours.

Please help

**Comment by pbarnettms** [comment]
Did you perform an OS upgrade or clean install?  If it was an upgrade, please uninstall and reinstall the HoloLens 2 Emulator, as your previous experience with the unsupported OS version may have left the installation in a bad state.

Please also refer to the Troubleshooting section at https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator.  One relevant step here is to run Visual Studio as Administrator.

**Comment by sanoopborn1994** [comment]
@pbarnettms Yes, I did uninstall and reinstall the Emulator under Administrator privilege, but it didn't helped. But when I run visual studio code as administrator, it does remove the initial retry pop up, but still stuck on this screen.

**Comment by pbarnettms** [comment]
@sanoopborn1994 The HoloLens 2 Emulator will not appear in Hyper-V Manager.  This is an intentional change from the HoloLens 1 Emulator.

Does your system meet the hardware requirements for the emulator, as documented at https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator?  If you just barely meet the requirements and are running other virtual machines (as suggested in the third screenshot), please try freeing up system resources by saving/turning off other virtual machines.

Lastly, if the above doesn't work and your system meets all of the listed requirements, you can try disabling graphics hardware acceleration.  The instructions for doing that are at the very bottom of the Troubleshooting section at the link I provided above.

**Comment by sanoopborn1994** [comment]
@pbarnettms I just went through the link, BTW, my PC meets the hardware requirements and has a lot Disk space, RAM and even Graphics. 
Then tried the second step you suggested ( regedit ), following the link, I was suggested to make a reg value under directory HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\XDE\10.0 
But the problem is the directory is only available till Microsoft, there is no sub folder named XDE under Microsoft. 
Please help!!

**Comment by pbarnettms** [comment]
@sanoopborn1994 Please create the XDE folder under Microsoft.  It's ok that it doesn't already exist.

**Comment by sanoopborn1994** [comment]
@pbarnettms  Thanks a lot, Finally worked, Thanks a lot once again for keep on providing suggestions and help, Closing the issue. :) :)
