### ISSUE TITLE
Not able to import spatial data

### ISSUE THREAD

**Issue by iamslan** [MicrosoftDocs/mixed-reality#1182]
Hi there,

I am not able to import spatial data between computers.

What I did on the first PC:
• I removed all the environment data (Settings -&gt; Mixed Reality -&gt; Environment -&gt; Clear data)
• I launched Mixed Reality Portal and did a fresh calibration and tutorial
• I exported with the given script according to the documentation:

> .\MRSpatialPackagerHelperScript.ps1 -AppName holoshell -UserName Administrator -Mode export -MapxPath C:\wmr_scale\ -LockMap 0
> 
> Package Family Name for holoshell: HoloShell_cw5n1h2txyewy
> 
> User SID for Administrator: S-1-5-21-3555177167-2840961754-1875856896-500
> 
> Lock map value succesfully set to 0
> 
> Running: C:\Users\administrator\Desktop\MixedRealitySpatialDataPackager\MixedRealitySpatialDataPackager.exe export C:\wmr_scale\ HoloShell_cw5n1h2txyewy
> 
> Attempting to disable Windows MR driver
> 
> Driver disabled
> 
> Validating spatial data version information...
> 
> Device spatial data version OK
> 
> Stopping SPECTRUM
> 
> Stopped SPECTRUM
> 
> Stopping SHAREDREALITYSVC
> 
> Stopped SHAREDREALITYSVC
> 
> SUCCESS: Packed Space from C:\ProgramData\WindowsHolographicDevices\SpatialStore\HoloLensSensors\{00000000-4321-0000-0000-000000000000} to
> 
> C:\wmr_scale\\het.mapx
> 
> Space folder name (staging) is not a GUID. Using {F36675F1-6D51-4651-ABBA-D1C3D91E5BB9} as the Space ID for packaging.
> 
> SUCCESS: Packed Space from C:\Users\administrator\AppData\Local\Temp\temp\staging to
> 
> C:\wmr_scale\\sa.mapx
> 
> Attempting to enable Windows MR driver
> 
> Driver enabled
> 
> Starting SHAREDREALITYSVC
> 
> Started SHAREDREALITYSVC
> 
> Starting SPECTRUM
> 
> Started SPECTRUM
> 
> EXPORT SUCCESS

Then, on the other PC:

• I removed all the environment data (Settings -&gt; Mixed Reality -&gt; Environment -&gt; Clear data)
• I run the import script:

> .\MRSpatialPackagerHelperScript.ps1 -AppName holoshell -UserName Administrator -Mode import -MapxPath C:\wmr_scale\ -LockMap 1
> 
> Package Family Name for holoshell: HoloShell_cw5n1h2txyewy
> 
> User SID for Administrator: S-1-5-21-3555177167-2840961754-1875856896-500
> 
> Lock map value succesfully set to 1
> 
> Running: C:\Users\administrator\Desktop\MixedRealitySpatialDataPackager\MixedRealitySpatialDataPackager.exe import C:\wmr_scale\ HoloShell_cw5n1h2txyewy S-1-5-21-3555177167-2840961754-1875856896-500
> 
> Attempting to disable Windows MR driver
> 
> Driver disabled
> 
> Validating spatial data version information...
> 
> Device spatial data version OK
> 
> External spatial data version OK
> 
> Importing spatial anchors for user account Administrator
> 
> Stopping SPECTRUM
> 
> Stopped SPECTRUM
> 
> Stopping SHAREDREALITYSVC
> 
> Stopped SHAREDREALITYSVC
> 
> Space ID is {00000000-4321-0000-0000-000000000000}
> 
> SUCCESS: Unpacked Space from C:\wmr_scale\\het.mapx to
> 
> C:\ProgramData\WindowsHolographicDevices\SpatialStore\HoloLensSensors\{00000000-4321-0000-0000-000000000000}\
> 
> Space ID is {EC81F032-0D67-42C2-AF35-3BEC64414DE4}
> 
> SUCCESS: Unpacked Space from C:\wmr_scale\\sa.mapx to
> 
> C:\ProgramData\Microsoft\Spectrum\PersistedSpatialAnchors\
> 
> Attempting to enable Windows MR driver
> 
> Driver enabled
> 
> Starting SHAREDREALITYSVC
> 
> Started SHAREDREALITYSVC
> 
> Starting SPECTRUM
> 
> Started SPECTRUM
> 
> IMPORT SUCCESS

Only success shown, no error, but when Mixed Reality Portal starts, it has the warning line saying that the headset is running without any delimitation. Import did not work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f0765a-3f92-5214-4bcd-2f5ad9d93c1a
* Version Independent ID: 7f34bdfd-70ca-1922-4858-3379ed1c9068
* Content: [Mixed Reality Spatial Data Packager Documentation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixedrealityspatialdatapackager#feedback)
* Content Source: [mixed-reality-docs/mixedrealityspatialdatapackager.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixedrealityspatialdatapackager.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @alfred-msft
* Microsoft Alias: **alreynol**

**Comment by alfred-msft** [comment]
Hi iamslan, the console output here suggests the import generally worked. To get further support you will need to engage our CSE engineers or use our LBE help email address (lbemr@microsoft.com).
