### ISSUE TITLE
Discrepency in "Enabling Objects to Follow Tracked Hands"

### ISSUE THREAD

**Issue by MikeChemi** [MicrosoftDocs/mixed-reality#1194]
The terminology in the radial view script has changed. The documentation says to set the reference direction to "Orient with Tracked Object", however the option I see in the MRTK is "Object Oriented"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a77974e-95c6-8d98-08de-53c55ecf8600
* Version Independent ID: d60ba94b-87b2-6be0-1675-f4b2114b7bbd
* Content: [MR Learning Base Module - Dynamic Content Placement and Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch3)
* Content Source: [mixed-reality-docs/mrlearning-base-ch3.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch3.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@MikeChemi Yes, the MRTK has been updated since this was published. We're planning to update text and screenshots to reflect some of these recent changes. I'll post an update here once this feedback has been addressed. Thank you!

**Comment by martinwilter** [comment]
@jessemcculloch This issue was addressed with PR #1868, commit https://github.com/MicrosoftDocs/mixed-reality/commit/23e6883b5caaf34affc2843b79ef38720437d5a6.
