### ISSUE TITLE
Typo in LaunchLunarModule script

### ISSUE THREAD

**Issue by MikeChemi** [MicrosoftDocs/mixed-reality#1201]
The LaunchLunarModule script has a "StartThruster" and a "StopThruster" function. Unfortonately, both functions have typos in them, and they are instead "StartThurster" and "StopThurster"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d715666-5a8f-a497-db0e-152491d52813
* Version Independent ID: be21949e-301f-78cb-ccc2-0fe6eb87c009
* Content: [MR Learning Base Module - Lunar Module Assembly Sample Experience - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch6#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch6.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch6.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
Wow, good catch! Yes, we'll fix the typo and provide an update here once the fix is live. Thank you

**Comment by jessemcculloch** [comment]
@mr0ng, do you know if this was corrected yet?

**Comment by martinwilter** [comment]
@jessemcculloch This issue was addressed with PR #1868, commit https://github.com/MicrosoftDocs/mixed-reality/commit/f807e57597b92d6189f40695e8d388e28bd44403.
