### ISSUE TITLE
UNET was not removed in 2019.1+

### ISSUE THREAD

**Issue by jeromemaurey** [MicrosoftDocs/mixed-reality#1204]
Please see this forum thread for details: https://forum.unity.com/threads/unet-deprecation-thread.543501/
UNET LLAPI will be supported throughout 2019.x, including 2019.4 LTS. The HLAPI is available via the Package Manager in 2019.x.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee0cfd0-8f75-e71c-a947-0f131e360ed5
* Version Independent ID: bf6057d7-09ca-be04-578b-af44aab5785c
* Content: [Getting your app ready for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide#feedback)
* Content Source: [mixed-reality-docs/mrtk-porting-guide.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrtk-porting-guide.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @grbury
* Microsoft Alias: **grbury**

**Comment by jessemcculloch** [comment]
Resolved
