### ISSUE TITLE
Old Chira and PixieLib references?

### ISSUE THREAD

**Issue by sostel** [MicrosoftDocs/mixed-reality#1223]
I saw that the screenshot has several assets still referring to Chira and PixieLib. Maybe time to update that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [MR Learning Base Module - Project Initialization and First Application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by sostel** [comment]
In particular this screenshot that mostly shows Chira assets: https://docs.microsoft.com/en-us/windows/mixed-reality/images/lesson1chapter2step3.jpg. Maybe just pick a different screenshot.

**Comment by jessemcculloch** [comment]
@mr0ng

**Comment by mr0ng** [comment]
Thanks @sostel @jessemcculloch - With the latest UI differences with MRTC RC2, we'll be going back through and replacing many of the screenshots, this one included. I'll update this issue as soon as the screenshot is updated. Thank you!

**Comment by jessemcculloch** [comment]
@mr0ng - Was this resolved in the PR #1399?

**Comment by martinwilter** [comment]
@jessemcculloch, this was resolved in PR #1816.

**Comment by mr0ng** [comment]
@sostel @jessemcculloch this issue can be closed
