### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by whitneyana** [MicrosoftDocs/mixed-reality#1234]
In the "Sharp text rendering quality with proper dimension" section, the hyperlink reading "text prefabs with UI Text and 3D Text Mesh" goes to a 404 page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9f9ed3-b6cd-2a1c-c106-fd719dbfb624
* Version Independent ID: 507bf69d-3d81-4ac1-5106-c677e29ce7f0
* Content: [Text in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity#feedback)
* Content Source: [mixed-reality-docs/text-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/text-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by jessemcculloch** [comment]
@cre8ivepark - Can you take a look at this?

**Comment by irwinwilliams** [comment]
Yep, I think the link is pointing to Text Prefabs in git, it SHOULD BE this: https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MRTK/SDK/StandardAssets/Prefabs/Text

But it's currently set to this: https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text
