### ISSUE TITLE
Minor descrepency in WMR driver release dates

### ISSUE THREAD

**Issue by davejones74** [MicrosoftDocs/mixed-reality#124]
The page https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/mixed-reality-software page has the WMR device update for 10.0.19041.2034 released on October 8th 2020, yet when you click on the link the published date is September 16th 2020 (9/16/2020).

**Comment by hferrone** [comment]
@tesych Can you confirm?

**Comment by tesych** [comment]
That is correct. We published the driver on September 16th for testing before releasing it to the public on October 8th.
