### ISSUE TITLE
Details are out of date

### ISSUE THREAD

**Issue by iandixon** [MicrosoftDocs/mixed-reality#1247]
The document does not show the changes to the May 2019 Update. There is a new start menu, desktop apps and in-app menus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b6689f-e323-1e40-7743-9ce0271144e6
* Version Independent ID: 05ddbb12-d8da-280d-e37d-2242097a5d93
* Content: [Release notes - October 2018 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes-october-2018#feedback)
* Content Source: [mixed-reality-docs/release-notes-october-2018.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/release-notes-october-2018.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Hey @mattzmsft - Do you or someone on your team have release notes for the May 2019 update for WMR Immersive?

**Comment by jessemcculloch** [comment]
Updated with new release notes today 👍

**Comment by iandixon** [comment]
Thanks. 
Next question is there any documentation on what is changing in 20H1? ;)
