### ISSUE TITLE
Typo in all hand-rigs 

### ISSUE THREAD

**Issue by lukas-walker** [MicrosoftDocs/mixed-reality#125]
Hello!

As far as I can tell, in all Handrigs that you provide for the HandCoach feature (left, right, both), there's a typo in the third middlefinger joint. It says "middel" instead of "middle". This lead to a lot of confusion when I was trying to implement an automated HandCoach feature in Unity for the Hololens. 

That this typo hasn't been found tells me that the handrig isn't used much. Is it possible that I'm looking at an outdated version?
Also, out of curiosity, why is it that there seems to be no automated HandCoach record/play function yet? All functionality for recording gestures is given, but the recordings have nothing to do with the handrig you provide. I'm building a "manual editor framework" in the style of HandCoach that lets you record and replay hand movements. I had previously assumend this pipeline was already implemented and was dissapointed when I found out that it isn't.
I'm happy about any feedback!

Best
Lukas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f034e2-2d0b-f409-b24c-d8f4efa80303
* Version Independent ID: 57d1f991-b1ca-a531-226f-6ece34f9ede2
* Content: [Hand coach - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/design/hand-coach)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/hand-coach.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/design/hand-coach.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @grayclee
* Microsoft Alias: **glee**

**Comment by grayclee** [comment]
Hi! thank you for bringing this to my attention!
I have updated the rigs and submitted a new PR
https://github.com/MicrosoftDocs/mixed-reality/pull/127#issue-522026634

**Comment by jessemcculloch** [comment]
We have merged PR #127 and that should resolve the typo part of this issue.
