### ISSUE TITLE
"Example of problematic boxing via nullable value types" - Incorrect information?

### ISSUE THREAD

**Issue by Pepin-** [MicrosoftDocs/mixed-reality#128]
Hey, I was reading the section on boxing and looking at the MyParticle example. It seems to say that using a nullable return value will always entail boxing. I don't think that's true since `Nullable<T>` is a basic struct wrapping the underlying value. I believe boxing would only occur if the nullable itself were boxed, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b548ae6-f9c1-f8ac-172b-efc80b7b1d26
* Version Independent ID: b5a2db60-a656-daae-ab4a-c47fda79791c
* Content: [Performance recommendations for Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/performance-recommendations-for-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/performance-recommendations-for-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/performance-recommendations-for-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Thanks for this callout @Pepin!
