### ISSUE TITLE
Only works if Network supports Multicast

### ISSUE THREAD

**Issue by cefoot** [MicrosoftDocs/mixed-reality#1290]
If the current network does not support multicast, the "UWPPlayerARM" does not appear in the "Select Unity Instance"-dialog. And that's why we don't get to know the port that is open on the HoloLens.  
I'm still looking for a solution for this problem :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e939e65b-3ef6-0a64-4a02-90d51b2e3934
* Version Independent ID: 77ee79c6-95df-cc3f-9e55-384661e3b00e
* Content: [Managed debugging with Unity IL2CPP - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/managed-debugging-with-unity-il2cpp#feedback)
* Content Source: [mixed-reality-docs/managed-debugging-with-unity-il2cpp.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/managed-debugging-with-unity-il2cpp.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ronak1997** [comment]
How did you solve this issue? I am facing the same issue.

**Comment by cefoot** [comment]
Hi, so I try to avoid it but when it's necessary:

- Start UWP Application from VS as DEBUG with USB-cable or over WIFI
- search the Output Window ("Show output from: Debug") for this Log-Message:
"Starting managed debugger on port 56078"
- with this and the IP from you HoloLens you can than enter the IP and Port manually in the Managed Script VS (Debug>Attach Unity Instance>Input IP)

hope this helps.

**Comment by Phatage** [comment]
Thanks for the suggestion @cefoot. I'm having this issue as well but don't see any log message like the one you described, and manually inputting in the devices IP didn't seem to work either. I've logged into my router and confirmed IMGP is enabled, but I can't find any more settings on IMGP; is having it enabled sufficient for ensuring the Multicast requirement?
