### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by hwinstonuconn** [MicrosoftDocs/mixed-reality#13]
[Enter feedback here]
The instructions on this page direct the student to add a second On Placing Started () event. However, the associated screen shot shows the creation of a On Placing Stopped () event. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d5ccf2-6270-b146-f5ca-3da70c886028
* Version Independent ID: 23fdfa60-4d98-86d3-a069-fdd316a3bd23
* Content: [Getting started tutorials - 6. Creating user interfaces - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-06)
* Content Source: [mixed-reality-docs/mr-learning-base-06.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-06.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter Can you weigh in on this?

**Comment by martinwilter** [comment]
@hwinstonuconn, this is a typo and the image is correct, an On Placing Stopped () event should be added, not a second On Placing Started () event. Thanks for pointing this out!

@hferrone we will make a PR for this shortly.
