### ISSUE TITLE
UXTools version updated

### ISSUE THREAD

**Issue by Eddiechui** [MicrosoftDocs/mixed-reality#132]
[The version of UXTools is updated to UXTools.0.10.0 and there is no BP_ButtonHoloLens2 in it. Can the tutorial get updated? Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by Eddiechui** [comment]
I have tried to combine both UXTools.0.10.0 and UXTools.0.9.0 and put it in the Plugins folder. The BP_ButtonHololens2 blueprint is shown as 'Blueprint Bad' instead of the blue icon shown in the tutorial. Can anyone please advise?

**Comment by hferrone** [comment]
Hi @Eddiechui, we've got an update coming for all our tutorials to use UXTools 0.10. You'll have to hold tight for the moment. 

@sw5813 Can you assist in any way?

**Comment by Eddiechui** [comment]
Sure I can wait. Thanks!

**Comment by sw5813** [comment]
@Eddiechui - the tutorial update to use UXT 0.10 is now live!
