### ISSUE TITLE
Integration Azure Storage failed / Set Object gets stuck at please wait...

### ISSUE THREAD

**Issue by Seajanjan** [MicrosoftDocs/mixed-reality#134]
Hey, I've followed this tutorial: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-02 , I'm using Unity 2019.4.4 and VS2019 Version 16.7.6. In Unity I could push data to my Azure Table Storage as showen here: https://prnt.sc/vpt3sv . Then I deployed the application to my HoloLens 2. after pressing **Set Object**, entered a name and pressing **Set Object** an message occured: Please wait... I've waited for 10 minutes and it was still stuck. I've made a screenshot with the hololens to show you where I'm at rn: https://prnt.sc/vptd0c .
The output from opening the app to this:

https://user-images.githubusercontent.com/51320511/100229000-d642e080-2f23-11eb-8c0d-9d63409f9b10.png

How do I push data to my azure storage table?

**Comment by hferrone** [comment]
@martinwilter, @mr0ng or team - can you assist or is this a support question?

**Comment by martinwilter** [comment]
Hi @hferrone, unfortunately, I'm not familiar with the details of this tutorial series.

**Comment by hferrone** [comment]
Hi @Seajanjan, please file a support issue - https://docs.microsoft.com/en-us/hololens/hololens-feedback, thanks!
