### ISSUE TITLE
Cannot download Holographic Remoting Player on Microsoft store on Hololens

### ISSUE THREAD

**Issue by YIREN1** [MicrosoftDocs/mixed-reality#139]
![20201204_003409_HoloLens](https://user-images.githubusercontent.com/39056160/101140991-a647bb80-364e-11eb-9ee5-6bb7ee7db967.jpg)
Please help :)

**Comment by hferrone** [comment]
Hi @YIREN1, please file a support ticket (https://docs.microsoft.com/en-us/hololens/hololens-feedback) - thanks!
