### ISSUE TITLE
The examples do not work as described.

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#14]
The documentation is out of date, wrong, or incomplete. Cannot make the simplest action work as described in this document. This is true of practically all the Unity and MRTK documentation. Go ahead as usual and close the ticket, not enough information is provided. I cannot explain more. Get a new computer, install all the software recommended. Follow the instructions, when you get a working example, send it to me. Don't check any box or make any adjustment that is not described in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5336e04e-dfe1-2c66-c216-67432cc317b0
* Version Independent ID: 2793cf1a-6a2b-bfb3-26a4-30fdb0d1a199
* Content: [MRTK 101 - How to use Mixed Reality Toolkit Unity for Basic Interactions (HoloLens 2, HoloLens, Windows Mixed Reality, Open VR) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-101?source=docs)
* Content Source: [mixed-reality-docs/mrtk-101.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mrtk-101.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
Hi @laultman, we're currently going through a complete Unity + MRTK documentation overhaul. As to closing the tickets, I left the main one open so our team could keep a channel of communication open with you and closed the rest of them because they were duplicate or adjacent issues. We appreciate your patience as we update our documentation.
