### ISSUE TITLE
Link to MR Base module Asset Pack broken

### ISSUE THREAD

**Issue by NoelCross** [MicrosoftDocs/mixed-reality#1407]
MR Base module Asset Pack results in a 404 error message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec854a93-806e-cef4-1c69-ba551a604724
* Version Independent ID: 0ad6eb8d-3e25-80c4-cc2a-b6774cd5b64f
* Content: [MR Learning ASA module Azure Spatial Anchor on HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1#feedback)
* Content Source: [mixed-reality-docs/mrlearning-asa-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-asa-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@NoelCross Thanks for identifying this. This issue has just now been fixed and part of Pull Request #1399 

https://github.com/MicrosoftDocs/mixed-reality/pull/1399/commits/1fcb9c70c0b91ad916789f0569da31e081dcabd1

The issue will be resolved once the PR is merged. Thanks for the feedback!

**Comment by jessemcculloch** [comment]
PR has been merged, closing this issue.  Thanks everyone
