### ISSUE TITLE
Need these samples updated prior to 2/2021 since ASA SDK 2.7 is absolutely required per SDK release last month

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#142]
The entire ASA samples series needs to be redone since it is promoting to use the old ASA 2.3 SDK versus what is going to be obsolete in less than two months.   ASA 2.7 SDK (and higher in future) is now going to be the only supported SDK for Microsoft support

Also, these docs are pointing to old Unity 2019.3.x as well.  We need to get onto LTS  and revamp all these docs prior to February 2021.  

These will be call generators for support plus risk adoption being not taken up for Mixed Reality platform services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1ea94b-b404-f850-b60c-4f9a5cc60906
* Version Independent ID: 2b453f8a-45ea-566a-f933-b3c705c535cc
* Content: [Azure Spatial Anchors tutorials - 1. Introduction to the Azure Spatial Anchors tutorials - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-01)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-01.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-01.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng Did these get updated the last time around?

**Comment by msftradford** [comment]
Hi @snakex2000, thanks for the feedback! I've opened an internal issue (#31365908) and we'll get right on it. @hferrone and @mr0ng, feel free to assign to me.
