### ISSUE TITLE
Not clear which version of ASA module assets

### ISSUE THREAD

**Issue by peted70** [MicrosoftDocs/mixed-reality#1427]
If I use v1.2 of the assets package which is the one currently linked (with v1.1.0 of the ASA package) , I get error CS1061: 'AzureSpatialAnchorsDemoWrapper' does not contain a definition for 'OnAnchorCreatedSuccessfully'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec854a93-806e-cef4-1c69-ba551a604724
* Version Independent ID: 0ad6eb8d-3e25-80c4-cc2a-b6774cd5b64f
* Content: [MR Learning ASA module Azure Spatial Anchor on HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1)
* Content Source: [mixed-reality-docs/mrlearning-asa-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-asa-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by sostel** [comment]
+1. With the older version I run into error messages. In the newer version, I get a "Missing script" errors on the "ParentAnchor" - I assume it's the ASAModuleScript.cs that is mentioned in the text, but is not part of the project?
