### ISSUE TITLE
Failed to connect with Azure Storage.

### ISSUE THREAD

**Issue by Tyoons** [MicrosoftDocs/mixed-reality#143]
Hi, 

Im actually running through https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-02

I created a free Azure Account to test Azure solution with Hololens. However I can't write data to the azure table. 
It works fine on unity, but when I deploy it to the Hololens I get this error : 

Failed to connect with Azure Storage.
If you are running with the default emulator configuration, please make sure you have started the sotrage emulator.

ArgumentException: Value does not fall within the expected range. 

How can I fix it to have access to Azure from the Hololens

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15853f4-20ac-bea9-89b0-4cd7da19a5be
* Version Independent ID: 398529a4-fee0-21bb-6cc6-b57b47d25ea1
* Content: [Azure Cloud Tutorials - 2. Integrating Azure storage - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @Tyoons, please file a support ticket at https://sitehelp.microsoft.com/, thanks!
