### ISSUE TITLE
Unable to complete tutorial: ASAmoduleScript.cs missing and other things

### ISSUE THREAD

**Issue by sostel** [MicrosoftDocs/mixed-reality#1433]
I've tried to look up and integrate all of the plugins mentioned above, but unfortunately I'm still blocked. 

- Azure Spatial Anchors: Unclear which version to use. I used a release from end of May, which seemed to fit with the timeframe.
- MR Base module Asset Pack: Broken link / unavailable. Looked it up manually though.
- ASA module Asset Pack: 
   -- In contrast to what the text says, there are more than 2 prefabs in the linked "ASA Module Beta 2", which is confusing and makes me think that I might have a wrong version?
   -- Where can I find the ASAmoduleScript.cs? It's not part of my project. 
- Mixed Reality Toolkit: Once I've integrated it all, I get errors in the MixedRealityToolkit for SlateEnabler.cs and DragEnabler.cs  that they are not implementing some interfaces. I'm not sure what the issue is, since it works fine in another Unity project. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec854a93-806e-cef4-1c69-ba551a604724
* Version Independent ID: 0ad6eb8d-3e25-80c4-cc2a-b6774cd5b64f
* Content: [MR Learning ASA module Azure Spatial Anchor on HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1)
* Content Source: [mixed-reality-docs/mrlearning-asa-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-asa-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by sostel** [comment]
Re: MRTK - Turns out I had to delete the Temp and Library folders and restart Unity and the errors went away. Instead I got 2 errors in AnchorFeedbackScript.cs that OnAnchorCreatedSuccessfully and OnAnchorCreationfailed are not defined.

**Comment by sostel** [comment]
Figured out that the ASAmoduleScript.cs got renamed to AnchorModuleScript. Neverthless, please update the instructions.

**Comment by fermanda** [comment]
I also unable to complete the tutorial.

After build, the attached script (previously ASAModuleScript.cs, now AnchorModuleScript.cs) suddenly missing from the parent anchor. I try to reimport all, and attach the script by myself. Everytime I enable/and disable the script "Disconnecting is no longer implemented" Error showed up on unity console.

This is the version of each module I use:
1. MRTK 2 RC2.0
2. Azure Spatial Anchor 1.1.0
3. ASA Module Assets v1.1
4. MR Base Module Asset v1.2
