### ISSUE TITLE
Eye Tracking Step 3.

### ISSUE THREAD

**Issue by gregoireduttine** [MicrosoftDocs/mixed-reality#1440]
&gt;"The EyeTrackingTutorialDemo script is included as part of this tutorial series repository"

Where can I find the tutorial repository?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f19cfc-88a8-2c19-7270-1c2f06b5987c
* Version Independent ID: 48ede813-0968-4618-a587-370f72db289e
* Content: [MR Learning Base Module - Advanced Input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch5#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@GregoireD75 Sorry for the confusion. The EyeTrackingTutorialDemo script is included with the Unity package named **BaseModuleAssets** downloaded and imported during step 2 of the [Organizing 3D Objects in a Collection](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch4#organizing-3d-objects-in-a-collection) section in the previous lesson:

> 2. Download the Unity package [BaseModuleAssets version 1.2.1](https://github.com/Developer-OI/MixedRealityLearning/releases/download/1.2.1/BaseModuleAssets-1.2.1.unitypackage) and import it using the same instructions to import custom packages outlined in [Lesson1](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1). This package includes 3D models and other useful assets that are used throughout this tutorial.

**Comment by martinwilter** [comment]
@jessemcculloch This issue was addressed with PR #1868, commit https://github.com/MicrosoftDocs/mixed-reality/commit/4868294f69d4a909bba30fc78e1938fe27de9cab.
