### ISSUE TITLE
Typo in german version

### ISSUE THREAD

**Issue by FelixWeichselgartner** [MicrosoftDocs/mixed-reality#146]
Hi, found a typo:

https://docs.microsoft.com/de-de/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#getting-the-qr-package

Erhalten des QR-Pakets
Sie können das nuget-Paket für die QR-Code Erkennung hierherunterladen.

==> hier herunterladen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [Nachverfolgen von QR-Codes - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality-pr.de-de/blob/live/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by FelixWeichselgartner** [comment]
https://docs.microsoft.com/de-de/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#detecting-qr-codes-in-unity

Sie können die QR-Code Erkennungs-API in Unity verwenden, ohne eine Abhängigkeit von mrtk zu treffen. Hierzu müssen Sie das nuget-Paket mithilfe von nuget für Unityinstallieren.

==> Unity installieren.

both after links... maybe this is a recurring theme - or Microsoft cant display html correct...

**Comment by hferrone** [comment]
@cnicco, can you assist?

**Comment by hferrone** [comment]
@FelixWeichselgartner - thanks for bringing this up, we've filed a bug report.
