### ISSUE TITLE
How do I SKIP the "Learn Mixed Reality" tutorial?

### ISSUE THREAD

**Issue by Snacko** [MicrosoftDocs/mixed-reality#147]
Every time I update my nVidia Drivers, I must first uninstall WMR so that nVidia Control Panel won't act crazy and crash.  Once WMR is removed, nVidia Surround will work correctly and I can setup my 3 monitors.  Then I can reinstall WMR and everything works.  

**How do I SKIP the "Learn Mixed Reality" tutorial??????**  It is a pain to have to do that every time I update my graphics drivers.  And I am keeping them up to date.. hoping there will be a fix for this problem someday..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b81a24-ba56-d13e-f31f-b5df1b065112
* Version Independent ID: 6a64872c-32a5-1a72-914c-cc63dce662bd
* Content: [Learn Mixed Reality - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/learn-mixed-reality)
* Content Source: [enthusiast-guide/learn-mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/learn-mixed-reality.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
@tesych @tmlyon Any ideas?

**Comment by hferrone** [comment]
Hi @Snacko, this isn't functionality that we currently support.
