### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/mixed-reality#1481]
How to I revert the runtime back to original?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db68623-3a1e-4502-cd27-f0f7d1369d10
* Version Independent ID: 9fd674c0-5be5-8b56-dbe4-31c03139ba9d
* Content: [OpenXR - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/openxr#feedback)
* Content Source: [mixed-reality-docs/openxr.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/openxr.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by thetuvix** [comment]
Hi @AceHack!

We don't have an easy way to roll your PC back to an older version of our OpenXR runtime - we continue to fix critical correctness and performance bugs and only the latest version of the runtime is available from the Microsoft Store at any time.

Is your OpenXR app no longer working after updating the runtime?

**Comment by AceHack** [comment]
I don't want to roll back OpenXR runtime, I want to completely uninstall it.

**Comment by yl-msft** [comment]
You can uninstall the developer portal app from the settings page.   The API runtime is part of the Mixed Reality experience.  You need to uninstall all Mixed Reality device apps and feature from settings page.

**Comment by AceHack** [comment]
That does not fully uninstall it, it still stays as active runtime.  How do I reset it as active runtime?

**Comment by jessemcculloch** [comment]
@thetuvix - Can you give guidance here?

**Comment by yl-msft** [comment]
Do you mean this regkey value inside Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1\ActiveRuntime?

Currently we don't have a way remove this regkey.  It is co-owned by all Khronos vendors, and we shouldn't remove it if the value is not written by us.  The value can be pointing to Oculus or Vaulve's runtime in future and we shouldn't touch this regkey in our uninstaller.

But I agree with you that we probably should look into an easier workflow to remove this value if the value is indeed pointing to our own runtimes.

In the meantime, please manually remove this regkey.

**Comment by thetuvix** [comment]
Closing this issue now.  Please let us know if there's anything else you're looking for here after removing that registry key.  Thanks!
