### ISSUE TITLE
BoundingBox deprecated

### ISSUE THREAD

**Issue by bgesler1** [MicrosoftDocs/mixed-reality#151]
BoundingBox is deprecated, this page should be updated to use BoundsControl?

![image](https://user-images.githubusercontent.com/69313974/102396696-cbbbba00-3faa-11eb-99f7-364e01a0436a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e0bbe-0f42-1b1d-5875-c2fe81e3a3a3
* Version Independent ID: d499b1bb-7c06-7420-8024-699b70ba608e
* Content: [Getting started tutorials - 7. Interacting with 3D objects - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-07)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @bgesler1, these docs will be updated with MRTK 2.5 in the near future.

**Comment by bgesler1** [comment]
Thanks, good to know!

Just to note, I originally used BoundsControl, and it worked in the Unity Editor. But on the Hololens, the app crashed when enabling it. I went back to using BoundingBox which works on the Hololens. May have been something I missed with setting up BoundsControl, so will wait for this documentation to be updated.

**Comment by JonPaulKing** [comment]
Like bgesler1, the solution, based upon the bounds control, throws an exception when enabled (VS2019, 2019.20.4.f1, 2.53, Hololens 2). Inspired by bgesler's use of the deprecated control, I used it to replace the 'BoundsControl' and it worked.  I am using side loading (via Visual Studio App Package) to install the application on my Hololens 2.
