### ISSUE TITLE
Cursor in MTK Hand Onfocus never trigger 

### ISSUE THREAD

**Issue by shahiltp** [MicrosoftDocs/mixed-reality#152]
Cursor in MTK Hand Onfocus always trigger at any time 
to reproduce it do the settings for leap motion 
show your hand cursor always trigger onfocus even it is not hitting ray casting  anywhere.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69249bf8-d2cd-5efe-ec17-b72078174617
* Version Independent ID: cc1ba99d-5d08-f323-55a4-f4f4ea06974c
* Content: [Cursors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/design/cursors#cursor-in-mrtk-mixed-reality-toolkit-for-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/cursors.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/design/cursors.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by shahiltp** [comment]
I mean It is not entering to rest cursor 
on press is working but on focus is always actiavted even raycast does not hit anywhere

**Comment by hferrone** [comment]
If you're using MRTK, please file this issue in their repo to get support :) https://github.com/microsoft/MixedRealityToolkit-Unity
