### ISSUE TITLE
Shared spatial data for multiple users

### ISSUE THREAD

**Issue by BaraVR** [MicrosoftDocs/mixed-reality#153]
Hi, we are developing a Virtual reality application with Unity 2019, using MRTK and the new XR manager plugin for immersive devices (namely Reverb g1) with the Mixed Reality package active in plugin management. We are creating a networked app that will make use of shared space and the Map manager feature. It is working nicely and the setup was very fast, but we have an issue with the automatic map creation when the Mixed reality portal starts. Now we have to do a lot of steps before being able to use our spatial map. Namely:

1. Turn on Mixed reality, put the HMD on the head, let it create a map, wait until you are in Mixed reality home, remove HMD
2. Open map manager and rewrite the spatial data with the shared ones
3. Open the target app
4. Put the headset on the head again and play

The reason we do this is that when we simply import the maps via map manager and started playing, the headset immediately created a new spatial map that rewrote the one we actually imported.

Can this process be simplified? This is way too complicated for our use case.

Thanks for any help, it is much appreciated!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c70dc70c-23d1-9a39-f846-f97bde5d1975
* Version Independent ID: bb6024f3-4720-3eda-28b2-e8f3bb16ba0b
* Content: [Location Based Entertainment with Windows Mixed Reality - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/discover/location-based-experiences)
* Content Source: [mixed-reality-docs/mr-dev-docs/discover/location-based-experiences.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/discover/location-based-experiences.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **ishitak**

**Comment by hferrone** [comment]
@polar-kev Is this an MRTK issue or something else?

**Comment by davidkline-ms** [comment]
@hferrone, This looks to be an issue outside of MRTK,.

> Now we have to do a lot of steps before being able to use our spatial map.

and

> the headset immediately created a new spatial map that rewrote the one we actually imported.

Lead me to believe it is beneath MRTK.

**Comment by hferrone** [comment]
Roger that! 

@BaraVR, please file a support ticket if you'd like more assistance! (https://sitehelp.microsoft.com/)
