### ISSUE TITLE
Azure Spatial Anchors demo app is not working on HoloLens 2 Emulator

### ISSUE THREAD

**Issue by Flozilla2018** [MicrosoftDocs/mixed-reality#155]
Hello,

i tried to do the "Azure Spatial Anchors" tutorial and test it on the HoloLens 2 Emulator but it does not work.
I always get the error that the "SpatialAnchorManager is improperly configured" because somehow the _spatial perception access_ is not granted.

The _Spatial Perception Capability_ is activated in the Unity Project and it is also set in the generated _Package.appxmanifest_ file of the Visual Studio solution.

Can you please help me how to solve this?
Or is it generally not possible to test this on the HoloLens 2 Emulator?

Regards
Flo

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Tutorials zu Azure Spatial Anchors: 2 Erste Schritte mit Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.de-de/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @Flozilla2018 - this is more of a support question. Please submit a ticket here (https://sitehelp.microsoft.com/).
