### ISSUE TITLE
MRTK Documentation link is broken

### ISSUE THREAD

**Issue by albinhw** [MicrosoftDocs/mixed-reality#1553]
In line To discover more about MRTK profiles and their architecture, visit the MRTK documentation.
MRTK Documentation link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff554d8-c68d-28a2-1331-3177bc8f6d71
* Version Independent ID: a4419d7e-9355-76fd-4ca7-9ea26cb0a5aa
* Content: [Getting started tutorials - 3. Creating user interface and configure Mixed Reality Toolkit - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by jessemcculloch** [comment]
Resolved by PR #1554
