### ISSUE TITLE
Two objects in the hierarchy are named "Indicator", which can cause confusion with the instructions

### ISSUE THREAD

**Issue by alwinv** [MicrosoftDocs/mixed-reality#157]
When setting up the "Indicator" button for the menu, I'd suggest distinguishing between the "Indicator" (chevron) and "Indicator" (button). Otherwise, the instructions are ambiguous. For example, since the button we're modifying is named "Indicator" also, I incorrectly used that object :-) I was pretty sure that was wrong while I was doing it though since toggling activation for the object using the object itself didn't make sense.

Possible fixes:
* Provide a sentence explaining that they're about to set up the first button in the menu to toggle the Indicator chevron between Active/Inactive. That might be enough to help pick the right "Indicator" object.
* Add more context in the instruction to make it clear it's the chevron object you're talking about (e.g. "Assign the Indicator object that looks like a chevron, to the None (Object) field"
* Name the Indicator button object differently than the Indicator chevron object

**This is the first instruction that was ambiguous:**
Rename the first button to Indicator, then in the Inspector window, configure the Button Config Helper (Script) component as follows:

Change the Main Label Text to match the name of the button
Assign the Indicator object to the None (Object) field
From the No Function dropdown, select GameObject > SetActive (bool) to set this function as the action to be executed when the event is triggered
Verify that the argument checkbox is checked
Change the Icon to the 'search' icon

**This was also ambiguous as a result:**
In the Hierarchy window, select the Indicator object, then in the Inspector window:

Uncheck the checkbox next to its name to make it inactive by default
Use the Add Component button to add the Directional Indicator Controller (Script) component
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d5ccf2-6270-b146-f5ca-3da70c886028
* Version Independent ID: 23fdfa60-4d98-86d3-a069-fdd316a3bd23
* Content: [MRTK tutorials - 6. Creating user interfaces - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-06)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng Can you confirm this and make the changes?
