### ISSUE TITLE
Holographic Remoting Steps

### ISSUE THREAD

**Issue by Skyluker4** [MicrosoftDocs/mixed-reality#159]
For enabling Holographic Remoting there should be an extra step for making sure that the Windows Default RHI is DirectX11. With DirectX12 enabled as suggested by Performance recommendations for Unreal by the previous step in the tutorial, holographic remoting will not connect to the Hololens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6317e769-30f1-34f9-cc04-5c57b9fd08d9
* Version Independent ID: 3b2f0aad-b1c4-f4ab-2440-1131a815c92e
* Content: [6. Packaging & deploying to device or emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch6)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch6.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch6.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Hi @Skyluker4 - the tutorial is using Windows Mixed Reality, which means the Default RHI/DirectX11 works as expected. Select DirectX12 is for OpenXR only. 

We've updated the performance and tutorial docs to call this out clearly - thanks for submitting!
