### ISSUE TITLE
Hololens 2 Emulator Install Problems

### ISSUE THREAD

**Issue by samy4sam** [MicrosoftDocs/mixed-reality#1592]
When I try to install the Microsoft HoloLens 2 Emulator, I get the error "The Microsoft HoloLens 2 Emulator requires the Windows 10 October 2018 update or newer." and I can't finish the installation. My Windows 10 Education is up to date, so this error makes no sense. Does anyone have a similar problem and found a workaround?

**Comment by pbarnettms** [comment]
@samy4sam If you open a Command Prompt and type "ver", what is the output of that command?

**Comment by samy4sam** [comment]
@pbarnettms Microsoft Windows [Version 10.0.17134.950]

**Comment by pbarnettms** [comment]
@samy4sam That means you're running the April 2018 update.  The HoloLens 2 Emulator requires the October 2018 update or newer, which means 10.0.17763 or newer.  If Windows Update isn't offering an update, please visit https://www.microsoft.com/en-us/software-download/windows10 to use the Update Assistant.

**Comment by samy4sam** [comment]
@pbarnettms thanks, that solved the problem
