### ISSUE TITLE
Unclear what the refresh rate is for eye tracking data (probably a typo)

### ISSUE THREAD

**Issue by rkevingibson** [MicrosoftDocs/mixed-reality#1607]
Under "Available Eye-Tracking Data", there is the following sentence: "Developers get access to a single eye-gaze ray (gaze origin and direction) at approximately 30 FPS (60 Hz)". 
30 FPS is 30Hz. 60 FPS is 60 Hz. Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd3486e-7247-5145-b705-2feb7495ff02
* Version Independent ID: 8f80dc18-937b-8a6b-e7c3-921507abcda2
* Content: [Eye-gaze - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/eye-tracking#feedback)
* Content Source: [mixed-reality-docs/eye-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/eye-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @sostel
* Microsoft Alias: **sostel**

**Comment by sostel** [comment]
It's a typo. It's corrected in this PR: https://github.com/MicrosoftDocs/mixed-reality/pull/1608.

**Comment by jessemcculloch** [comment]
Merged and should be live on the site in about 5 minutes
