### ISSUE TITLE
Innovation of ultrathin lens

### ISSUE THREAD

**Issue by lidipeng** [MicrosoftDocs/mixed-reality#1627]
Innovation of ultrathin lens
![mmexport1569032913674](https://user-images.githubusercontent.com/48385166/65367144-a2a16200-dc5f-11e9-9e1a-9fe650e3384a.jpg)

![画板 1 副本 5@3x-100](https://user-images.githubusercontent.com/48385166/65367327-26f4e480-dc62-11e9-8cbc-95b32f189048.jpg)
.jpg…]()

**Comment by jessemcculloch** [comment]
This does not appear to be related to our developer documentation
