### ISSUE TITLE
All steps From adding the "Tap to Place" script fail

### ISSUE THREAD

**Issue by SimonDarksideJ** [MicrosoftDocs/mixed-reality#163]
[Enter feedback here]
Following the step to add the "TapToPlace" component, the instructions fail, initially as this step is no longer possible in MRTK 2.5+

> From the Magnetic Surfaces > Element 0 dropdown, uncheck all options expect Spatial Awareness

As the option does not exist.  But also because by adding the TapToPlace script, the editor is flooded with errors and you cannot continue until you remove the script again.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @SimonDarksideJ - The tutorial series overview states that the recommended MRTK version for this tutorial series is MRTK 2.4.0.

We're in the process of updating the content for version 2.5. Thanks for the catch!

**Comment by fjaen** [comment]
I followed the steps and the tap to place part of the tutorial didn't work. Nothing occurs when I click with the left mouse button. The rover does not move. The directional indicator works fine.
Thanks for your help
