### ISSUE TITLE
Quick reference link is dead

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/mixed-reality#1644]
The last link under "See Also" gives a 404; it should point to https://www.khronos.org/registry/OpenXR/specs/1.0/refguide/openxr-10-reference-guide.pdf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db68623-3a1e-4502-cd27-f0f7d1369d10
* Version Independent ID: 9fd674c0-5be5-8b56-dbe4-31c03139ba9d
* Content: [OpenXR - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/openxr#feedback)
* Content Source: [mixed-reality-docs/openxr.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/openxr.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by thetuvix** [comment]
Thanks for the report!  I've fixed this up now.  Let me know if you run into any other issues.
