### ISSUE TITLE
Button Blueprint wont work

### ISSUE THREAD

**Issue by SKBSP** [MicrosoftDocs/mixed-reality#166]
Hi. 

Can't get the button to work. Tried in 4.26 with 0.11.0 first. Everything went fine until I got to the button. It gave me a "Accessed None trying to read property WhiteKing" error. I'm not a programmer but after some googling I surmised that it means it cant find the WhiteKing. I did everything as the tutorial said so after a lot of fiddling today I deleted everything and started from scrach in 4.25 with 0.10.0 and wouldn't you know it, I get to the button and get the same error...

So what is this? I see other people having had problems with the button before. Is the tutorial wrong? Is there a problem with the plugin? 

Hope someone can help

Full error message: 
Blueprint Runtime Error: "Accessed None trying to read property WhiteKing". Blueprint:  ResetButton Function:  Execute Ubergraph Reset Button Graph:  EventGraph Node:  Reset Location

**Comment by sw5813** [comment]
Hi @SKBSP, did you set the WhiteKing property in the Main level? See step 2 of the [Firing the function](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch5#firing-the-function) section.

**Comment by SKBSP** [comment]
Jebus... :P Tnx @sw5813 it's working now:)
