### ISSUE TITLE
SpatialMappingCollider is Obsolete

### ISSUE THREAD

**Issue by unncbglee** [MicrosoftDocs/mixed-reality#167]
I appreciate if the tutorial of object detection with Azure 300 can be updated with latest code and library packages so we can actually run the tutorial and learn from it. It does not make sense and useless to follow up tutorial lessons and eventually the library package is not found.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3e0711-ce63-b64a-2933-4656a33acf68
* Version Independent ID: f368c378-4847-555e-8db5-aa960532a7a9
* Content: [MR and Azure 310 - Object detection - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-azure-310)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-azure-310.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-azure-310.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @DrNeil
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @unncbglee - all our MR and Azure Services tutorials only work on HoloLens (1st gen) and aren't updated for new tech. This area of our tutorials is under active review/development to bring them up to date, but there won't be any new immediate work. 

I appreciate that you need this functionality right now, but all I can do right now is leave this open and update you in the future.

Cheers!

![Screen Shot 2021-02-05 at 3 29 20 PM](https://user-images.githubusercontent.com/8218795/107095972-f6fea080-67c6-11eb-999a-49568651ecb7.png)
