### ISSUE TITLE
DefaultHoloLens2ConfigurationProfile

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/mixed-reality#1675]
The tutorial should use DefaultHoloLens2ConfigurationProfile for HoloLens 2 applications.  It has better defaults specific to HL 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c749260f-d284-74f9-ffff-9afd2069ef81
* Version Independent ID: 04aff1f3-9c67-07f5-4fe2-6b1fd256e9f3
* Content: [Multi-user capabilities tutorials - 2. Getting Unity ready for development - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch2#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by jessemcculloch** [comment]
Resolved
