### ISSUE TITLE
使用 AzureSpatialAnchors SDK  打包成 Xcode 项目的时候编译报错

### ISSUE THREAD

**Issue by CYBoys** [MicrosoftDocs/mixed-reality#168]
使用 AzureSpatialAnchors SDK  打包成 Xcode 项目的时候编译报错
![image](https://user-images.githubusercontent.com/15981638/104698043-b1146680-574b-11eb-90f2-ade172cc3643.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 19d6068a-8891-8072-20f4-e162462140b9
* Version Independent ID: 8bbeeef9-399f-0af2-ba63-30bfe0efc4c3
* Content: [将 Azure 空间定位点集成到共享体验中 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-05.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@keveleigh @mr0ng Can you guys assist?

**Comment by CYBoys** [comment]
I uploaded the entire project to GitHub https://github.com/CYBoys/CompileError.git . The compiled Xcode project is too large to upload. Please switch to the iOS platform to compile and test. You will see the following errors.

![image](https://user-images.githubusercontent.com/15981638/104797015-ef666000-57f5-11eb-95dd-955d248b4d4f.png)

**Comment by varunsiddaraju** [comment]
Hi @CYBoys, thanks for the feedback! We are updating the tutorial and the latest updates will fix the current issues.

**Comment by CYBoys** [comment]
> Hi @CYBoys, thanks for the feedback! We are updating the tutorial and the latest updates will fix the current issues.

Thank you very much, would you please close this isses after updating the tutorial? In that case, Github will let me know.

**Comment by varunsiddaraju** [comment]
> > Hi @CYBoys, thanks for the feedback! We are updating the tutorial and the latest updates will fix the current issues.
> 
> Thank you very much, would you please close this isses after updating the tutorial? In that case, Github will let me know.

Sure, will do.

**Comment by hferrone** [comment]
@varunsiddaraju Can I close this item?
