### ISSUE TITLE
Will not connect to Photon

### ISSUE THREAD

**Issue by Radixtrator** [MicrosoftDocs/mixed-reality#1684]
I followed this tutorial 100%, but it will never actually connect to Photon or even create a room or player. This means that it will never work and sync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd3782f-bda6-fd6a-91d5-f6834d692242
* Version Independent ID: d54407d8-6ec5-51b0-cd7f-e0dcb3888269
* Content: [Multi-user capabilities tutorials - 3. Connecting multiple users - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch3#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch3.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch3.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mr0ng** [comment]
@jessemcculloch @Radixtrator @martinwilter I believe this issue can be closed. @Radixtrator happy to help if you're still having issues with the Photon connection.
