### ISSUE TITLE
Type names have changed?

### ISSUE THREAD

**Issue by MikeChemi** [MicrosoftDocs/mixed-reality#1685]
I just installed Microsoft.MixedReality.SceneUnderstanding.0.5.2024-rc, and it seems like many of the type names have changed. For example, the documentation says to use SceneUnderstanding.QuerySettings, but I've found the type is actually SceneUnderstanding.SceneQuerySettings. Also, the Compute functions appear to be Async right now, not synchronous as the sample code shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ada88-8eb6-0e07-0b90-02b8b87179bf
* Version Independent ID: 9bb41118-53ab-73c6-5908-83f0c2334536
* Content: [Scene understanding SDK - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding-sdk#feedback)
* Content Source: [mixed-reality-docs/scene-understanding-SDK.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/scene-understanding-SDK.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @SzymonS
* Microsoft Alias: **szymons**

**Comment by jessemcculloch** [comment]
Assigned to the doc author to address
