### ISSUE TITLE
Getting Started with MRTK doc redundant

### ISSUE THREAD

**Issue by Troy-Ferrell** [MicrosoftDocs/mixed-reality#1688]
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-getting-started

This doc page should be removed. It's redundant with both the README and Getting Started on MRTK
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

If the UX controls or anything updates, this page needs to be updated too

**Comment by jessemcculloch** [comment]
@grbury - Thoughts?

**Comment by Troy-Ferrell** [comment]
+ @ericob who also self identified issue

**Comment by grbury** [comment]
I don't think we should remove, but agree it could be more robust to eliminate discrepancies and gaps across them

The page is intended to advertise all of the greatness in MRTK for those that don't know to visit the Github directory and docs. 

Perhaps we could remove temporal references, like unity version, etc. And have those mastered in only the MRTK page. 

Regardless, one should be able to start in either portal and easily jump to the other to get added context.

**Comment by Troy-Ferrell** [comment]
@grbury , the main current problem is as MRTK evolves this pages would need to be updated as well.

The **UI and Interaction Building block** and **Feature areas** sections in particular fade out quickly. And have a lot of links that could die etc. Same with **Minimum Requirement for MRTK v2**

The high level principles and reference to the Getting Started at mrtk.io are great and unlikely to change
