### ISSUE TITLE
Find Azure Anchors doesnt work

### ISSUE THREAD

**Issue by Radixtrator** [MicrosoftDocs/mixed-reality#169]
I followed the tutorial exactly and everything works, but the FindAnchor function doesnt work and always returns with the message "Current Azure anchor ID is empty". Everything else works perfectly and the anchors are created. Even the loading works but that one function never works. Any help?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by varunsiddaraju** [comment]
Hi @Radixtrator , thanks for the feedback! We are updating the tutorial and the latest updates will fix the current issues.
