### ISSUE TITLE
It can work on late version of Unity, with some fix.

### ISSUE THREAD

**Issue by mcoy001** [MicrosoftDocs/mixed-reality#1699]
The tutorial is bit out of date, but can still work if anyone new want to try it.
For me the problem is that the console show errors from scripts:   'editoruserbuildsettings' does not contain a definition for 'wsageneratereferenceprojects'. 

There's a solution, just double click the error message, it open the script, then remove all lines related to 'editoruserbuildsettings', also remove it from any if statement.

And it should starts work again, tested on Unity 2019.2.9f1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c49bf7f-19f2-3dae-0a5c-562ef686e4ea
* Version Independent ID: 6bf4877d-e20b-e055-1ee4-ab6d5d6c7976
* Content: [MR Input 210 - Gaze - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-210#feedback)
* Content Source: [mixed-reality-docs/holograms-210.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-210.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by mcoy001** [comment]
Still it would be better if the tutorial can be updated.( or we are going to have different version for HoloLens 2)

**Comment by hferrone** [comment]
Hi folks,

You might try moving to MRTK(https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Overview.html) or implementing gaze in unity (https://docs.microsoft.com/en-us/windows/mixed-reality/gaze-in-unity).

Cheers!
