### ISSUE TITLE
Remote rendering player in Unity and C# rather than DirectX and C++

### ISSUE THREAD

**Issue by ShayneRC** [MicrosoftDocs/mixed-reality#1701]
It would be great if there was a way to do this through Unity and C# rather than DirectX and C++. If there already is a way/examples of this please let me know and maybe place them on this page for others to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b68c509d-6a77-f10c-98fe-3dfbc337d20f
* Version Independent ID: 3b348b73-bf59-ca2a-a3b8-a5ef2b72444c
* Content: [Writing a custom Holographic Remoting player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-create-player)
* Content Source: [mixed-reality-docs/holographic-remoting-create-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holographic-remoting-create-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @NPohl-MSFT
* Microsoft Alias: **nopohl**

**Comment by FlorianBagarMicrosoft** [comment]
Thanks for the suggestion.  Writing your own Holographic Remoting player is a new feature of Holographic Remoting for HoloLens 2, and not possible with Unity at the moment.  We’ll keep your feedback in mind as we plan future releases.
