### ISSUE TITLE
AnchorModuleScript > FindAzureAnchor () or FindAzureAnchor(string)

### ISSUE THREAD

**Issue by young-tae-lim** [MicrosoftDocs/mixed-reality#173]
[여기에 피드백 입력]
I put the spatial anchors account id and account key into ParentAnchor object.
But when I run the tutorial program on hololens 2, 
whenever I choose the FindAzureAnchor, then 'account ID is empty' is appeared on Debugwindow.

What is the problem? Can you help me?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure Spatial Anchors 시작 - Mixed Reality](https://docs.microsoft.com/ko-kr/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.ko-kr/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by varunsiddaraju** [comment]
Hi @young-tae-lim , thanks for the feedback! We are updating the tutorial and the latest updates will fix the current issues.
