### ISSUE TITLE
could not complete tutorial

### ISSUE THREAD

**Issue by carmines** [MicrosoftDocs/mixed-reality#1738]
- privacy step needs updating depending on the version of windows(speech is separate from inking) 
- Azure portal is outdated needs refresh, links don't match anymore. 
- Utterance section needs to be updated
-- could not complete the steps to get the words highlighted. 
-- step4 is where I couldn't figure out the next steps. Where is the link to the Unity sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e92d1-bd95-93c8-7e97-d1df949ed882
* Version Independent ID: bf701f2a-41dc-c37c-d947-28d3a4bcce73
* Content: [Azure Speech Services tutorials - 4. Setting up intent and natural language understanding - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-speechsdk-ch4#feedback)
* Content Source: [mixed-reality-docs/mrlearning-speechSDK-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-speechSDK-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by lowndesc** [comment]
same comments as @carmines
although, steps highlighting is word by word action by user
in my case, LUIS feedback messages are not received or displayed on base screen. hard to debug. could do with a debug window as in the earlier spatial anchors tutorial

**Comment by martinwilter** [comment]
@lowndesc Thanks for reporting this. We will be pushing a complete refresh of this tutorial shortly, which hopefully will resolve the issues you and @carmines.

> in my case, LUIS feedback messages are not received or displayed on base screen.
In the current tutorial, it might not be clear that the Target entity label should be assigned to the words 'hint', 'reset', and 'launch'.

In the code, when the result from LUIS is processed, if it is labeled 'Target' entity it will check for these words and if any of them are found, the corresponding button will be triggered, i.e. the 'HintButton', 'ResetButton', or 'LaunchButton' respectively.

So I suggest that you check if Target entity label has been assigned to the 'hint', 'reset', and 'launch' words only.
