### ISSUE TITLE
Multi-language Speech Recognition

### ISSUE THREAD

**Issue by amrayon2** [MicrosoftDocs/mixed-reality#1751]
I have developed apps in Unity that recognize speech on Hololens 1 but they only recognize English due to software limitations of the Hololens 1. Can Hololens 2 recognize multiple languages? If so, is it using Windows.Speech API? Spanish is what I need to recognize but I'm sure there are others out there hoping for their native language as well. I'm still trying to get Spanish to be recognized on Hololens 1 but it is becoming a futile effort from all the things I have tried.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by NoelCross** [comment]
amrayon2, thanks for your question.  Spanish is indeed supported on HoloLens 2.  Please check the following page for additional languages that are supported on HoloLens 2.

[Supported languages for HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens2-language-support)
