### ISSUE TITLE
Difficult to find help channels on docs

### ISSUE THREAD

**Issue by Troy-Ferrell** [MicrosoftDocs/mixed-reality#1752]
It is a bit difficult to know where to go to ask for help if I can't find something in documentation etc

Something pointing to here or a hololens stackoverflow etc
https://holodevelopersslack.azurewebsites.net

Not exactly sure where would be a good universal place to find this route

**Comment by hferrone** [comment]
Hi @Troy-Ferrell 

We have a community resources here https://docs.microsoft.com/en-us/windows/mixed-reality/community. 

Cheers!
