### ISSUE TITLE
Provide sample serialized scenes for Scene Understanding

### ISSUE THREAD

**Issue by xwipeoutx** [MicrosoftDocs/mixed-reality#1820]
The guide for [the Scene Understanding SDK](https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding-sdk#api-overview) shows very limited device capability for the SceneObserver (basically just HL2), making the whole thing impossible to use without a device.

Can we have a few sample scenes made available and linked to, so we can use the other parts of the SDK (eg. building a visualization from a Scene)

**Comment by jessemcculloch** [comment]
@SzymonSPS - Is this something your team can help with?

**Comment by SzymonSPS** [comment]
Yes. We have a backlog item to publish the SceneUnderstanding app, and include sample scenes as part of this. I don’t have a timeline on this but it’s high on the list and will be available in the near future.

**Comment by jessemcculloch** [comment]
Thanks Simon!

**Comment by SzymonSPS** [comment]
Good news, we have just published our SceneUnderstanding sample. It includes a sample scene which can be used in the sample or on your own with the SDK. We will continue to add more samples/scenes but this should unblock experimentation. It will be linked to the docs soon, but for now you can follow the direct link:

https://github.com/sceneunderstanding-microsoft/unitysample

**Comment by jessemcculloch** [comment]
Also updated in the documentation with PR #1911
