### ISSUE TITLE
Getting Error and can't build

### ISSUE THREAD

**Issue by jared-goering** [MicrosoftDocs/mixed-reality#183]
I keep getting this error from VS when I try to build it even after rebuilding the project. 

Exception thrown at 0x000001F63219DE40 in hololens4.exe: 0xC0000005: Access violation executing location 0x000001F63219DE40.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng Can you or the team assist?

**Comment by varunsiddaraju** [comment]
@hferrone We tried reproducing this issue on our end and it is working fine for us.
We are looking Into other ways to reproduce the issue.

@jared-goering Could you please let me know which version of unity and VS you are using?

**Comment by veeruby-developer** [comment]
@jared-goering please use Unity 2019.4.16f, MRTK 2.5.1, and VS 2019.

**Comment by AvaThalheim** [comment]
Hello, yesterday  i noticed the usage of certain MRTK Prefabs is causing the same issue as well. For example, the Slate Prefab will break the Build, while the NearMenu does not.

**Comment by AvaThalheim** [comment]
@hferrone I removed the DebugWindow Prefab from the scene, now the deploy works.

**Comment by hferrone** [comment]
@AvaThalheim hmmmm, that would fall under an MRTK issue then - could you file one here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues
