### ISSUE TITLE
Small typos in links

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#1849]
URL: undesranding -> understanding
in-document hyperlink: https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping#spatial-mapping-vs-scene-undesranding-worldmesh -> understanding worldmesh

---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62a0220-8d95-be66-37a2-6265a98f0566
* Version Independent ID: 878bfd78-acd8-8605-e6ef-5f0b85f9943c
* Content: [Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping#spatial-mapping-vs-scene-undesranding-worldmesh)
* Content Source: [mixed-reality-docs/spatial-mapping.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-mapping.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Fixed!
