### ISSUE TITLE
Keyboard shortcuts for manipulating hands needs update

### ISSUE THREAD

**Issue by pinkwerks** [MicrosoftDocs/mixed-reality#185]
This link doesn't have correct information for rotating hands.
https://docs.microsoft.com/en-us/windows/mixed-reality/out-of-scope/mrtk-101#how-to-simulate-input-interactions-in-unityeditor

_"Press Q or E(horizontal) / R or F(vertical) to rotate simulated hands"_
I'm not sure what the correct keyboard keys are, but Q & E move the camera. Likewise, pressing ctrl-h in the interaction examples don't mention this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5336e04e-dfe1-2c66-c216-67432cc317b0
* Version Independent ID: 2793cf1a-6a2b-bfb3-26a4-30fdb0d1a199
* Content: [MRTK 101 - Using common spatial interactions - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/out-of-scope/mrtk-101)
* Content Source: [mixed-reality-docs/mr-dev-docs/out-of-scope/mrtk-101.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/out-of-scope/mrtk-101.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
@pinkwerks We've archived this article, but thanks for catching this! If we ever put it back into circulation, we'll be sure to update the input mappings :)
