### ISSUE TITLE
IMU (Inertial Measurement Unit) data sensor streaming

### ISSUE THREAD

**Issue by ishakbhatt** [MicrosoftDocs/mixed-reality#1864]
Is it possible to stream gyro/magnetometer/accel data from the Hololens's internal IMU through the sensor streaming tutorial or will I only get access to the vision sensors like the ToF sensor?

**Comment by jessemcculloch** [comment]
@ishakbhatt - Can you tell me what sensor streaming tutorial you are talking about?  That way I can direct this to the right subject matter expert.

Thanks,
Jesse
