### ISSUE TITLE
Include MR Feature Tool step by step instructions for Beginner HL2 tutorial

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#187]
"Importing Mixed Reality Toolkit" section of "Beginner MRTK Tutorials" > "2. Initializing your project and deploying your first application" should include step by step instructions for importing the MRTK Foundation packages using the [Mixed Reality Feature Tool](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool) in addition to downloading github packages.

The MR Feature Tool should be highlighted as supporting Windows only and that mac support is coming.
Mac users should be directed to use the traditional way of individually downloading/importing MRTK unity packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@varunsiddaraju Did this get fixed in the latest tutorial update PR?

**Comment by varunsiddaraju** [comment]
Yes, @hferrone This is included in the latest tutorial update PR.
