### ISSUE TITLE
Articulation Hand link is broken

### ISSUE THREAD

**Issue by javenu** [MicrosoftDocs/mixed-reality#1882]
First link at the top of this page points to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af10c861-77a3-ae2f-d82c-8ce164afea84
* Version Independent ID: 3148ae2f-0dd3-2863-6068-aaa7b5a94f98
* Content: [Articulated Hand and Eye Tracking in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hand-eye-in-unit#feedback)
* Content Source: [mixed-reality-docs/hand-eye-in-unit.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hand-eye-in-unit.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by jessemcculloch** [comment]
Resolved with PR #1887
