### ISSUE TITLE
Update table headers in "Cross-device input properties" section

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/mixed-reality#1884]
See table in the "Cross-device input properties" section (https://docs.microsoft.com/en-us/windows/mixed-reality/hands-and-motion-controllers-in-directx#cross-device-input-properties)

Update the "HoloLens" header to be "HoloLens Gen 1" to avoid confusion with HoloLens Gen 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bf2ad4-9eaf-fd78-6392-cf30b4c836f9
* Version Independent ID: 6845166c-a5fe-8f30-d28e-a84c966826cd
* Content: [Hands and motion controllers in DirectX - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hands-and-motion-controllers-in-directx#cross-device-input-properties)
* Content Source: [mixed-reality-docs/hands-and-motion-controllers-in-directx.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hands-and-motion-controllers-in-directx.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @caseymeekhof
* Microsoft Alias: **cmeekhof**

**Comment by jessemcculloch** [comment]
Resolved in PR #1887
