### ISSUE TITLE
Missing step in MRTK setup instructions

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#189]
I am using Unity 2019.4.19f1 (fresh install) with MRTK 4.5.1 installed through the MRTK Feature Tool, and having problems with these instructions:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02

There is a step missing in the section "Configuring the Unity project" right before "In the Project Settings window, select Player > XR Settings, click the + icon"

It turns out that in a fresh project, the Player > XR Settings, there is no "+" button available by default because the "Virtual Reality Supported" is not checked by default. That should be documented.

Also, when checking this box for the first time, there's a series of confusing warnings from Unity which should be documented in these instructions. (The warnings are about the XR Plugin Management system not supporting the Windows Mixed Reality packages, and urging the user to uninstall WMR, which I assume should not be done.)

**Comment by varunsiddaraju** [comment]
Thanks for your feedback @julesra, We will look into it and will make the necessary changes.

**Comment by veeruby-developer** [comment]
This Issue has been closed in the latest PR #193
