### ISSUE TITLE
HoloLens 2 gestures 

### ISSUE THREAD

**Issue by sophiasysun** [MicrosoftDocs/mixed-reality#1895]
HoloLens 2 gestures are available here: https://docs.microsoft.com/en-us/hololens/hololens2-basic-usage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac61f71a-4332-f365-7672-9a2aaa8fd3c3
* Version Independent ID: e73579ab-06b2-0615-8725-43c8eebcb915
* Content: [Gestures - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/gestures#feedback)
* Content Source: [mixed-reality-docs/gestures.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/gestures.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @rwinj
* Microsoft Alias: **cmeekhof**

**Comment by rwinj** [comment]
fixed in pull request Fluent style image updates & Gestures redirect #1947
