### ISSUE TITLE
Open app always show empty in Hololens2 emulator

### ISSUE THREAD

**Issue by EmilyChai** [MicrosoftDocs/mixed-reality#1904]
Hi, team

I'm new to Hololens2 development and I create a Hololens2 app according to 
https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1
and
https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2

The show in unity3D is
![WechatIMG1](https://user-images.githubusercontent.com/23117626/69522164-b2a92b00-0f9b-11ea-834a-f2110e0fb9ce.png)
however, when I deploy it to Hololens2 emulator
![WechatIMG2](https://user-images.githubusercontent.com/23117626/69522197-c6549180-0f9b-11ea-97f0-5f8c558ff2bd.png)

It aways show this. Even I try other app, the show is the same.
Could you help to check, what's wrong with it?
I use unity 20-18.4.12f1 and VS community 2017 15.9.17(I also tried in VS2019, the result is the same)

Thanks.
BRs.
Emily

**Comment by pbarnettms** [comment]
Hello Emily,

The fact that it is display a 2D window indicates a problem with your Unity project configuration that is independent of the HoloLens Emulator.  Please verify that you've enabled Windows Mixed Reality support in your Unity project by following the steps at https://docs.microsoft.com/en-us/windows/mixed-reality/configure-unity-project.  If you continue to experience issues, please post your question in the Unity forums for Windows Mixed Reality at https://forum.unity.com/forums/windows-mixed-reality.102/.
