### ISSUE TITLE
Updated Driver

### ISSUE THREAD

**Issue by OCDtraining** [MicrosoftDocs/mixed-reality#1905]
Hello where do I get the updated driver from "This functionality requires an updated driver from Insider Preview Builds with the Map Locking feature"? Please add detailed instructions for this step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f0765a-3f92-5214-4bcd-2f5ad9d93c1a
* Version Independent ID: 7f34bdfd-70ca-1922-4858-3379ed1c9068
* Content: [Mixed Reality Spatial Data Packager Documentation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixedrealityspatialdatapackager)
* Content Source: [mixed-reality-docs/mixedrealityspatialdatapackager.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixedrealityspatialdatapackager.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @alfred-msft
* Microsoft Alias: **alreynol**

**Comment by jessemcculloch** [comment]
That driver has now shipped with Windows SDK 18362.  I have removed the note as you no longer need an insider build SDK.
