### ISSUE TITLE
Please clarify what XR pipeline is being used

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#191]
## Describe the issue

The documentation now contains instructions for two sets of pipelines: the legacy pipeline and the XR sdk pipeline. The documentation needs to be really clear about which of these pipelines is assumed to be present in the user's project. This is because some instructions won't work if the user has the wrong pipeline, and might even cause the project to break. ( Also it would be great to add documentation about what's the difference between these two pipelines, and which MRTK version works with which. )

For example:

These instructions for adding holo-remoting: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#xr-sdk-setup-instructions
are not compatible with these instructions for making a new MRTK project: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02

I followed the 2nd link first (because it seems newer), and then proceeded to do the 1st link because I wanted Holographic remoting. But the first link requires installation of some newer XR packages which seem to conflict with the legacy packages from the 2nd link, and Unity keeps popping up complaints about incompatibility. Now I don't know if my fresh MRTK project is configured correctly. 

It would be helpful if all the instruction documents were really clear about which XR pipeline is assumed to be present in the user's project.
Thanks for fixing.

## Versions I am using
Unity: 2019.4.19f1
MRTK: 2.5.1
XR pipeline: Both ??

**Comment by hferrone** [comment]
@varunsiddaraju Can you put this on the to-do list?

**Comment by varunsiddaraju** [comment]
Yes @hferrone, We will update the documents with the above feedback.
