### ISSUE TITLE
Can't find dropdown list option TogglePlacementHints under Configuring the Placement Hints button

### ISSUE THREAD

**Issue by IzzyGomezThree** [MicrosoftDocs/mixed-reality#1917]
Hello! So I was going through this tutorial, and for step 2 under the "Configuring the Placement Hints button", don't get the dropdown list option "TogglePlacementHints". 

If it helps to know, I am using MRTK 2.1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d715666-5a8f-a497-db0e-152491d52813
* Version Independent ID: be21949e-301f-78cb-ccc2-0fe6eb87c009
* Content: [Getting started tutorials - 7. Creating a Lunar Module sample application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch6#configuring-the-placement-hints-button)
* Content Source: [mixed-reality-docs/mrlearning-base-ch6.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch6.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
Hi @IzzyGomezThree, check if the TogglePlacementHints script component is on the LunarModule gameobject. This should have been done during step 3 in the previous section, Configuring the Lunar Module.

**Comment by IzzyGomezThree** [comment]
Thank you so much @martinwilter , I accidentally put that component on the Rocket Launcher. Cheers!
