### ISSUE TITLE
Change a unity project for hololens to a unity project for holographic remote rendering

### ISSUE THREAD

**Issue by hulnglei1** [MicrosoftDocs/mixed-reality#1934]
How to Change a unity project for hololens to a unity project for holographic remote rendering. Is there a unity project demo for them? Is there a software can show, not just the cube demo.

**Comment by evmill** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/add-holographic-remoting

**Comment by hulnglei1** [comment]
@evmill Hi, thank you for your reply.
Do you have an unity demo for this? And can you advise a product in microsoft store to show this funtion?  I have check holo-light's holo-view demo, Arvizio website. Still can not find a good product.

**Comment by evmill** [comment]
I don't have a project for this unfortunately, not saying it doesn't exist I just don't know of one. I can leave you a few more links here, which I know isn't what you asked for. But realizing now you asked for remote rending they should be more accurate. 

Meanwhile if you make your way to the **HoloDevelopers slack channel** I know there are people there with experience on this that can give you more direction on this. 

https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-player
https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-create-host
https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-create-player
https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-custom-data-channels
https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-secure-connection

**Comment by hulnglei1** [comment]
thanks for your reply. I will keep learn
