### ISSUE TITLE
Windows insider program didn't enable Map Manager feature for 50% of my devices

### ISSUE THREAD

**Issue by OCDtraining** [MicrosoftDocs/mixed-reality#1935]
Hello,
I have currently 4 devices (3 HP backpacks and one desktop PC) on which I enabled Windows insider program to be able to use the Map Manager. However, only 2 (50%) of the devices did actually receive this update. The rest of the devices show the Mixed reality tab as it was before. All devices use the same Microsoft account and all appear to be up to date according to the Windows update tab in settings. I tried pressing the "Check for updates" button multiple times. Over two weeks the situation didn't improve and it is considerably costly for my work. I received some Windows updates in the meantime but the Mixed reality tab allways looks the same. How do I proceed if I want to enable the Map manager feature on all of my devices? How do I proceed if I want to update another device so that this situation doesn't repeat? Thanks in advance for your support. Best Regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb139fd7-2848-e8f4-91bb-ad9f8370ceb2
* Version Independent ID: 37312e53-d3bc-4ad2-5c97-459f252ce3a4
* Content: [Location Based Entertainment with Windows Mixed Reality - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/location-based-experiences)
* Content Source: [mixed-reality-docs/location-based-experiences.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/location-based-experiences.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **ishitak**

**Comment by jessemcculloch** [comment]
Hi @OCDtraining,

Could you please file a support ticket at https://aka.ms/hlsupport

The beginning page should look like this.
![image](https://user-images.githubusercontent.com/11747005/71007069-3b971c00-209b-11ea-9063-20a9197196b2.png)
