### ISSUE TITLE
Missing info on input support for HoloLens 2

### ISSUE THREAD

**Issue by sostel** [MicrosoftDocs/mixed-reality#1948]
I just tried out the Holographic Remoting Player on HoloLens 2 and it seems that support for fully articulated hand tracking and eye tracking is missing. My Unity app just reverted to GGV-style input. Are there specific packages required? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5141cd4-aa05-46fe-9378-a9cc0ef19f76
* Version Independent ID: 1a2e110d-8dae-e52b-f856-34217c6f6e54
* Content: [Holographic Remoting Player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-player)
* Content Source: [mixed-reality-docs/holographic-remoting-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holographic-remoting-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by FlorianBagarMicrosoft** [comment]
Holographic Remoting does support articulated hand tracking and eye tracking. If you want to use these features via Unity you would have to use MRTK (see https://github.com/microsoft/MixedRealityToolkit-Unity).
