### ISSUE TITLE
Azure Anchor Cannot be applied to local position

### ISSUE THREAD

**Issue by d0614** [MicrosoftDocs/mixed-reality#195]
I'm reading this document：
https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02

When I follow the instructions to step 8, the print message gets stuck "Looking for Azure anchor... please wait..."。The previous steps were all correct，The  AzureAnchorID found in step 8 is the same as the AzureAnchorID created in step 3, but the location cannot be positioned to the location in step 3 after the AzureAnchorID is found。

If you do not follow step 4, everything is fine.

I apologize for using machine translation, and thank you in advance for your answer。

**Comment by veeruby-developer** [comment]
@d0614 The azure spatial anchors package used in the tutorial is updated with a fix and tested .
@hferrone Please close this issue.
