### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jfhiggins** [MicrosoftDocs/mixed-reality#1954]
In Hand Tracking Gestures and Interactable buttons, step 4: the text says to set the Y position of the cube at 0.4, but screenshot shows 0.04 which is the right position to match the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff554d8-c68d-28a2-1331-3177bc8f6d71
* Version Independent ID: a4419d7e-9355-76fd-4ca7-9ea26cb0a5aa
* Content: [Getting started tutorials - 3. Creating user interface and configure Mixed Reality Toolkit - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2)
* Content Source: [mixed-reality-docs/mrlearning-base-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by jessemcculloch** [comment]
Resolved in #1953
