### ISSUE TITLE
Unhandled Exception when enabling bounds control

### ISSUE THREAD

**Issue by alexeisenhart** [MicrosoftDocs/mixed-reality#197]
[Enter feedback here]

I'm just getting started with HoloLens 2 development. The tutorial works fine in play mode Unity on my PC and in the HL2 emulator. However, when I deploy to my HoloLens2 (via remote debugging or deploying with Visual Studio), and exception is thrown when I turn on the bounding controls.

Here's the exception that is thrown.

Exception thrown at 0x000001EDC1C38C40 in ArTesting.exe: 0xC0000005: Access violation executing location 0x000001EDC1C38C40.

I've played with it a bit and it seems to be thrown when the Bounds Control is enabled. The Object Manipulator seems to not be the problem. To debug, I modified my scene to have the BoundsControl enabled when the scene starts and the exception is thrown immediately.

Any advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e0bbe-0f42-1b1d-5875-c2fe81e3a3a3
* Version Independent ID: d499b1bb-7c06-7420-8024-699b70ba608e
* Content: [Interacting with 3D objects - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-07)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@alexeisenhart  we were able to successfully build mr-learning-base-07 with Bounds control enabled. with below configuration.

- Unity 2019.4.19f
- MRTK 2.5.3
- VS 2019

**Comment by alexeisenhart** [comment]
@veeruby-developer Thanks for your fast response! I was on:

- Unity 2019.4.16f1
- MRTK 2.5.4
- Microsoft Visual Studio Enterprise 2019, Version 16.8.3

So I upgraded Unity to 2019.4.19f and downgraded MRTK 2.5.3, testing after each. It still crashes in the same way.

Is this version of VS okay to use? Is there anything else I could look into?

**Comment by JonPaulKing** [comment]
The solution, based upon the bounds control, throws an exception when enabled (VS2019, 2019.20.4.f1, 2.53, Hololens 2). Inspired by another thread on this page's feedback, I used a deprecated control (BoundingBox) to replace the 'BoundsControl' for the Gaming Object (Rover Explorer) and this worked. I am using side loading (via Visual Studio App Package) to install the application on my Hololens 2.

**Comment by hferrone** [comment]
@veeruby-developer Can this issue be closed or is there an update that needs to happen?

**Comment by veeruby-developer** [comment]
@hferrone  this issue can be closed.
