### ISSUE TITLE
(Wanted) Indicate how to find MRTK version in the migration instructions

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#198]
It would be great if the documentation about MRTK migration ( https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Updating.html ) would tell me how to find out my current MRTK version in my project. That will help me select the documentation that I need. 
PS: What's the way to do this ?

**Comment by hferrone** [comment]
@polar-kev Can you assist?

**Comment by polar-kev** [comment]
Hey @julesra, follow these instructions to figure out which version of the MRTK you're currently using:
1. Open your MRTK project in Unity
2. Navigate to the "MixedRealityToolkit" folder in your Project window
3. Open the file called "Version"

If the file and folder above do not exist, you are on a newer version of the MRTK. Try the following:
1. Navigate to the Mixed Reality Toolkit Foundation folder
2. Open the "package.json" file in a text editor
3. Look for the line with the word "version:"
