### ISSUE TITLE
Software versions fail to provide sufficient distinction between Hololens 1 & 2 requirements

### ISSUE THREAD

**Issue by BitterDone** [MicrosoftDocs/mixed-reality#1983]
In the Visual Studio section:
"Note about Unity: Unless you're intentionally trying to install a newer (non-LTS) version of Unity for a specific purpose, we recommend not installing the Unity workload as part of Visual Studio installation, and instead install the 2018.4 LTS stream of Unity as noted below."

In the Unity section:
"The current recommendation is to use Unity 2018.4.x, which is the LTS build required for MRTK v2 below."

I'm sure this is accurate for Hololens 2, but only Unity 2017.4.35f1 works for Hololens 1 in my experience. I was blocked from any development for about 6 weeks, trying to get a basic Unity app running (only the camera and a .25 x .25 x .25 cube in front of the camera). I was trying all different versions of Unity 2019 and 2018 LTS, Visual Studio 2017 & 2019, but I would never see the Unity splash screen and would only see blank/black/empty space when the app ran on the Hololens 1.

As soon as I created the basic app in Unity 2017, it worked like a charm.

Today, I tried opening the working 2017 app with Unity 2018 LTS, and saw the same blank/black screen and lack of splash screen. It seems 2018 LTS completely broke the app, because the previously working app now shows the same broken behavior when I open in 2017 LTS.

Please update both sections to clarify:
-Unity 2018 LTS for Hololens 2
-Unity 2017 LTS for Hololens 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6144653-f7f3-0ad2-5c8f-24310633144a
* Version Independent ID: a810412b-2ff0-29d3-3004-af58ce8c24be
* Content: [Install the tools - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools)
* Content Source: [mixed-reality-docs/install-the-tools.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/install-the-tools.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by evmill** [comment]
Have you tried deleting the app from the HL1 and then recreating it from scratch in 2018 LTS instead of upgrading from the 2017 Unity build? 
I can confirm first hand that you can indeed make a demo cube app using Unity 2018 LTS.

**Comment by BitterDone** [comment]
Hi Evan, thanks for the suggestion. I just tried a fresh basic Unity 2018.4.14f4 app on the Hololens 1, following these steps:
https://docs.microsoft.com/en-us/windows/mixed-reality/configure-unity-project

Please also note the issue #1984 I opened regarding the accuracy of these steps. But, they're the best I have to go on at this time.

I first tried deploying via Visual Studio 2017, which errored about not finding the v142 Build Tools. 
I then tried deploying with Visual Studio 2019, which "worked," but I still only see a blank/empty scene when the app launches, and the splash screen is also not seen. 
This is all new projects that haven't existed on the HL1 device.

Repo:
https://github.com/BitterDone/SampleEvmill

Couple pics of the build settings:
https://imgur.com/a/galor3H

HL video of deploying from VS 2019:
https://youtu.be/pcZ3OAWgz00

If Unity 2018 is indeed supposed to work
