### ISSUE TITLE
Azure Spatial Anchors link to Azure Docs takes you out of MR docs

### ISSUE THREAD

**Issue by Yonet** [MicrosoftDocs/mixed-reality#1995]
Azure Spatial Anchors link, below [shared experiences link](https://docs.microsoft.com/windows/mixed-reality/shared-experiences-in-mixed-reality?WT.mc_id=docs-twitter-ayyonet) takes the user to Azure Docs. While it is a great to not repeat the same info, it is confusing user experience. It's not clear how to get back from Azure ASA page, to back to Mixed Reality docs. 

We might solve the issue when we move everything to Azure Docs, for now, I wanted to document.

Thanks!

**Comment by Yonet** [comment]
Is this resolved?

**Comment by hferrone** [comment]
Hi @Yonet, 

This is currently the way the sites/content is structured and split up. Restructuring this would be great and it's definitely on my radar, and will hopefully happen in the future, but right now this one isn't a GitHub issue. Thanks for your feedback on these!

Cheers,
