### ISSUE TITLE
nit: Fix comment in Initialization from Data (aka. the PC Path) sample

### ISSUE THREAD

**Issue by sushraja-msft** [MicrosoftDocs/mixed-reality#2009]
// If we want to use it immediately we can de-serialize the scene ourselves
byte[] newSceneData = new byte[newSceneBuffer.Size];
newSceneBuffer.GetData(newSceneData);
Scene mySceneDeSerialized = Scene.Deserialize(newSceneData);

// Save newSceneBlob for later

In this sample snippet the comment I think should be // Save newSceneData for later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ada88-8eb6-0e07-0b90-02b8b87179bf
* Version Independent ID: 9bb41118-53ab-73c6-5908-83f0c2334536
* Content: [Scene understanding SDK - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding-sdk#feedback)
* Content Source: [mixed-reality-docs/scene-understanding-SDK.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/scene-understanding-SDK.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @SzymonS
* Microsoft Alias: **szymons**

**Comment by hferrone** [comment]
Hi @sushraja-msft 

Thanks for calling this out, the docs have been updated.

Cheers!
