### ISSUE TITLE
Unity project example

### ISSUE THREAD

**Issue by Sam-Nugget** [MicrosoftDocs/mixed-reality#2023]
Is there a more up to date example of a Unity project somewhere? The one found at: https://github.com/chgatla-microsoft/QRTracking/tree/master/SampleQRCodes won't work. I have the correct version of NuGet, Unity and MRTK but can't get it to work. I am fairly new to Unity so an example project would be really useful! Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking#feedback)
* Content Source: [mixed-reality-docs/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by chgatla-microsoft** [comment]
The sample is updated here.
https://github.com/chgatla-microsoft/QRTracking/releases
https://github.com/chgatla-microsoft/QRTracking/tree/master/SampleQRCodes

**Comment by Sam-Nugget** [comment]
Thanks a bunch! Much appreciated 😄
