### ISSUE TITLE
Unable to see spatial mapping mesh

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2036]
Although my app deployed successfully, I was unable to see the spatial mapping mesh as indicated in the 'Congratulations' section of this tutorial. I double checked that I enabled spatial perception (as instructed in 3. Enable spatial perception). I also have both the Unity project configured for MRTK and the MRTK itself configured.

I feel there may be a step missing to enable spatial awareness.  I went back to the project, clicked on the MixedRealityToolkit object in the Hierarchy and clicked on the Spatial Awareness tab. I saw that the box for 'Enable Spatial Awareness System' was unchecked. Once I checked that box, saved the scene, did a new build and deployed the app to my HL2, I was able to see spatial mapping mesh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@aprilspeight Thanks for pointing this out.

You are correct, the DefaultHoloLens2ConfigurationProfile which is the configuration profile used in the tutorial, does not have the Spatial Awareness System enabled by default, so the configuration profile will need to be cloned and the Spatial Awareness System enabled. You can find this missing step in the first section of the next tutorial, [How to configure the Mixed Reality Toolkit Profiles (Change Spatial Awareness Display Option)](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2#how-to-configure-the-mixed-reality-toolkit-profiles-change-spatial-awareness-display-option).

Previously, the tutorial used the DefaultMixedRealityToolkitConfigurationProfile, which does have the Spatial Awareness System enabled by default, so this tutorial series was structured to first show the spatial awareness mesh in this tutorial, and then in the next tutorial cover how to clone and configure the MRTK profiles by showing how to hide the spatial awareness mesh.

We will make the necessary adjustments to the tutorial as soon as possible. Thanks again for making us aware of this issue.

**Comment by aprilspeight** [comment]
Awesome - thanks!
