### ISSUE TITLE
QR Codes Tracking Distance is Limited to About 50cm

### ISSUE THREAD

**Issue by Holo-Fiedel** [MicrosoftDocs/mixed-reality#204]
When tracking a QR code, the user has to get very close to it.
Tracking seems to be successful, when the user is about 50cm or less from the QR code.

This also applies to large QR codes (tested with 20 cm and 30cm side length).

A frequent use case of our customers is to put the QR code on the floor and in order to localize (or re-track) them, they have to crouch, which is a degradation of UX.

Is this behaviour intended?
Or is there a way to extend the tracking distance?

According to the [documentation of MR QR Tracking](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#best-practices-for-qr-code-detection) "The detection distance for size increases linearly.", which is not what we have observed.

As additional information, the floor, which the QR code is placed on, has no pattern and a uniform color, so background noise does not seem to be the reason for this behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#best-practices-for-qr-code-detection)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
@chgatla-microsoft can you assist?

**Comment by chgatla-microsoft** [comment]
The distance depends on QR version ( module size),  the higher the version then the modules are smaller and can only be detected from closer. you can also try micro QR codes if you want the distance of detection to be longer. Also make sure you have enough contrast and proper border.
