### ISSUE TITLE
Higher resolution screenshots 

### ISSUE THREAD

**Issue by sam9116** [MicrosoftDocs/mixed-reality#2042]
the font in the MRTK panel is already really small, lower resolution makes it hard to read the settings 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff554d8-c68d-28a2-1331-3177bc8f6d71
* Version Independent ID: a4419d7e-9355-76fd-4ca7-9ea26cb0a5aa
* Content: [Getting started tutorials - 3. Creating user interface and configure Mixed Reality Toolkit - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch2)
* Content Source: [mixed-reality-docs/mrlearning-base-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@sam9116 Thanks for the feedback.

We've been using the docs contribution guidelines for [adding images](https://docs.microsoft.com/en-us/windows/mixed-reality/contributing#adding-images) and have done a "size up" to 1000 px width, but that probably wasn't enough. 

Our source images are 2560 px width, so we'll look into pushing them out at full resolution.

We will make this update as soon as possible. Thanks again for the feedback, we appreciate it.
