### ISSUE TITLE
Recording the pupil movement through IR camera mounted near the nose bridge in the Hololens 2

### ISSUE THREAD

**Issue by gt-madanb** [MicrosoftDocs/mixed-reality#2046]
Hi all, My research is based on eye-tracking, I need to record the pupil movement through the IR camera based on which will be more helpful for my research. There is no documentation related to the IR camera. I would be so grateful if anybody could look into this issue.

**Comment by jessemcculloch** [comment]
Hi @gt-madanb,

That functionality is not currently supported.  If you would like to request it, the best place to do so is via the Feedback Hub on the devices itself.
