### ISSUE TITLE
Step Missing and Misnomer

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2047]
I have two separate areas of feedback for this tutorial.

1. For Enabling Voice Commands, step 5. Implement the Response event for the speech command, the reader is asked to click the small + button to add a keyword, and then, from the Keyword dropdown, choose the Play Music keyword that was created earlier. By default, the Element 0 section is not expanded and therefore needs to be expanded to see the Keyword dropdown. This may not be intuitive for someone new and it may be best to inform the reader to expand Element 0.

2. For The Pan Gesture, step 5. Add 3D content to be scrolled, the instruction reads: In the Hierarchy window, create four cubes as a child objects of the PanContent and set their Transform Scale to X = 0.15, Y = 0.15, Z = 0.15:

However, PanContent is not the name of the parent object. PanGesture is the parent object. PanContent is the name of the material that was added to the quad object. I believe this may be a typo?

Outside of the feedback above and the other feedback I provided for the prior tutorials, I really like the updates! I think it's clear to follow. I also like that you all provide Tips throughout which link back to prior pages on how to do certain tasks that were discussed in the prior tutorials. The updated screenshots help a lot as well! I'm working through the remaining HL2 tutorials between now and next Friday. I'll continue to submit feedback if anything else comes up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f19cfc-88a8-2c19-7270-1c2f06b5987c
* Version Independent ID: 48ede813-0968-4618-a587-370f72db289e
* Content: [Getting started tutorials - 6. Exploring advanced input options - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch5#enabling-voice-commands)
* Content Source: [mixed-reality-docs/mrlearning-base-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@aprilspeight Thanks again for helpful feedback.

We will implement the suggested additional instructions for expanding Element 0 and correct the PanContent typo in our next update.

We are glad to hear you like the updates and look forward to receiving additional feedback as you work through the rest of the tutorials.

As a heads-up, we have not updated the 3rd and 4th tutorials series yet, which includes the [Azure Speech Services](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-speechsdk-ch1) tutorials and the [Multi-user capabilities](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1) tutorials. We don't have an exact date for when these tutorials will be refreshed, but we are hoping to have them updated within two weeks.

**Comment by aprilspeight** [comment]
Thanks, Martin! I'll keep an eye out for when the 3rd and 4th tutorials are updated and will provide feedback once complete.
