### ISSUE TITLE
HoloLens 2 - Research mode 

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#2054]
"Research mode" has been renamed to "Recording mode" in HL2. 
![image](https://user-images.githubusercontent.com/1419060/74721616-57a46e80-5240-11ea-9c93-b05833501fac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da146661-e620-72d3-95e2-4c0a751245b7
* Version Independent ID: de5c43c1-653b-aa23-948f-108cc63f085e
* Content: [HoloLens Research Mode - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode)
* Content Source: [mixed-reality-docs/research-mode.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/research-mode.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @davidgedye
* Microsoft Alias: **dgedye**

**Comment by nargul90** [comment]
Event with "Recording mode" enable. I get "No sensor streaming groups found", when I deploy the HoloLensforCV app.

**Comment by kell90** [comment]
Does HoloLensForCV work for HoloLens 2?

**Comment by nargul90** [comment]
> 
> 
> Does HoloLensForCV work for HoloLens 2?

"Work" is a bit broad. The sample program compiles and deploys, but the sensor viewer gives "No sensor streaming groups found".

**Comment by cheles** [comment]
This sample doesn't work on HL2. Our development team is working on a replacement but I don't have a time-frame for that for now. The reason why I've opened this issue was to have this mentioned in our public docs.

**Comment by nargul90** [comment]
> 
> 
> This sample doesn't work on HL2. Our development team is working on a replacement but I don't have a time-frame for that for now. The reason why I've opened this issue was to have this mentioned in our public docs.

Thank you for the update!

**Comment by kell90** [comment]
Is there an alternative way to access "Recording Mode" sensor frames from HL2 aside from the APIs provided by HoloLensForCV?

**Comment by cheles** [comment]
For now, no. There is a mention on above doc : Research mode is not intended for applications that will be deployed across an enterprise or made available in the Microsoft Store.

**Comment by nickgreene** [comment]
Thanks for the updates.
Are there any sample recordings of the sensor data streams that will eventually be available in recording mode?

**Comment by jtrinidad6** [comment]
Any update on this matter if this will work with HL 2?

**Comment by hferrone** [comment]
Hi folks, 

There's an updated doc on Research Mode at https://docs.microsoft.com/en-us/windows/mixed-reality/research-mode.

Cheers!
