### ISSUE TITLE
Minor Typos

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2055]
A few minor typos:

1. In step 3. Add and configure the Part Assembly Demo (Script) component, it says: To the Location To Place field, assign the corresponding PlacementHints object, in this case, the RoverEnclosure_PlacementHints object.

The object name is misspelled. It should say 'RoverEnclosure_PlacementHint' not 'RoverEnclosure_PlacementHints'.

2. In Configuring the Lunar Module, it says: Reset the application so the Lunar Module and all the part are placed back to their original position

The word 'part' should be plural. It should say: 'all the parts are placed'

3. In Configuring the Reset button, it says: If you now enter Game mode and press the Reset button you will hear the audio clip being played and see the Lunar Module being launched into space

However, the user is resetting. Why would the lunar module be launched? Given the instructions, when I gave this a try, the only action to occur was my for my scene to reset. Launching occurred in the prior section 'Configuring the Launch button'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d715666-5a8f-a497-db0e-152491d52813
* Version Independent ID: be21949e-301f-78cb-ccc2-0fe6eb87c009
* Content: [Getting started tutorials - 7. Creating a Lunar Module sample application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch6)
* Content Source: [mixed-reality-docs/mrlearning-base-ch6.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch6.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@aprilspeight Thanks very much, we have corrected these typos and will push the fix out with our next update.

Regarding:
>3. In Configuring the Reset button, it says: If you now enter Game mode and press the Reset button you will hear the audio clip being played and see the Lunar Module being launched into space

and: 
>However, the user is resetting. Why would the lunar module be launched? Given the instructions, when I gave this a try, the only action to occur was my for my scene to reset. Launching occurred in the prior section 'Configuring the Launch button'.

That was a copy/paste from the 'Configure the Launch button' section that wasn't updated. It has been corrected now.

Thanks!
