### ISSUE TITLE
Typo and Create Anchor Issue

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2056]
One typo in the 'Trying the basic behaviors of Azure Spatial Anchors' section. It says: Then, enabled the InternetClientServer, PrivateNetworkClientServer, RemovableStorage, and Webcam capabilities.

The word 'enabled' is in the past tense but should instead say 'enable' so that the sentence reads: Then, enable the InternetClientServer, PrivateNetworkClientServer, RemovableStorage, and Webcam capabilities.

The other issue occurs after the deployment to the device. I'll add the steps below as a reference:
1. Move the cube to a different location.
2. Start Azure session.
3. Create Azure Anchor (creates anchor at the location of the cube).
4. Stop Azure session.
5. Remove Local Anchor (allows the user to move the cube).
6. Move the cube somewhere else.
7. Start Azure Session.
8. Find Azure Anchor (positions the cube at the location from step 3).
9. Delete Azure Anchor.
10. Stop Azure session.

I can "successfully" complete steps 1 - 7 with the device. I say that reluctantly because, once I get to step 8, I get a message that says:

AnchorModuleScript.FindAzureAnchor()
Current Azure anchor ID is empty

After I first saw this, I logged into the Azure portal and  saw that there were no updates in the monitoring for Anchors Created. So, I went back through the tutorial again and deployed once again to my HL2. Still had the same issue.

So, I gave something else a try. I completed steps 1-7. Then, for step 8, I moved the cube (instead of clicking Find Azure Anchor), clicked Create Azure Anchor and continued with steps 4 - 10 (i.e. stopped the session, removed the local anchor, moved the cube again, clicked start session and then clicked Find Azure Anchor, etc.). 

Somehow, that worked. I was skeptical so I tried it again 4 more times and it worked each time when I followed that process. Still skeptical, I tried it once more with RocketLauncher_Complete object after deploying to the device. And it worked. I checked the Azure portal again and now I have activity in the monitoring section for Anchors Created, Anchors Deleted and Poses Found.

One thing I noticed is that, if I follow the intended instructions, step 3 - Create Azure Anchor happens REALLY fast. Although it says that the anchor was created successfully, I don't believe it's creating an anchor. However, when I follow the troubleshooting steps I took instead, once I click Create Azure Anchor, the process actually takes a while to load.

Hopefully someone on your end can replicate this with a device. If not, please let me know and I'll use Mixed Reality Capture to get you all a video of what I see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec854a93-806e-cef4-1c69-ba551a604724
* Version Independent ID: 0ad6eb8d-3e25-80c4-cc2a-b6774cd5b64f
* Content: [Azure Spatial Anchors tutorials - 1. Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1)
* Content Source: [mixed-reality-docs/mrlearning-asa-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-asa-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@aprilspeight Thanks for reporting the typo, it has been corrected and we will push the fix out with our next update.

Regarding the issue after deploying to your device, I wasn't able to reproduce it. It sounds like your workaround essentially is doing steps 3-7 twice, correct?

Are you still able to reproduce it? If so:

1. What does the in-app debug log say after you created the anchor in step '3. Create Azure Anchor'? It should say:
```
AnchorModuleScript.CreateAzureAnchor()
Local anchor created
Azure anchor ID '<anchor id>' created successfully
Current Azure anchor ID updated to '<anchor id>'
```
2. Does it still happen if you use far interaction instead of button press? (To avoid the double invocation caused by those functions being hooked up to both the button and interactable script).
