### ISSUE TITLE
Restarting the application

### ISSUE THREAD

**Issue by Phatage** [MicrosoftDocs/mixed-reality#2079]
It should be noted that in order to fully restart the application, the window of the app in the home world needs to be closed (after exiting the app) and a new instance must then be created from the app menu. 

Some of the grammar on the debug messages could use improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed09288-8ef8-73dc-f58a-618f3125fa11
* Version Independent ID: 5f5b2461-ff07-7735-1d60-17a6b2966d77
* Content: [Azure Spatial Anchors tutorials - 2. Saving, retrieving, and sharing Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch2#feedback)
* Content Source: [mixed-reality-docs/mrlearning-asa-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-asa-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@Phatage Thanks for the feedback. We will look into implementing these suggestions in our next update.
