### ISSUE TITLE
Typos in german version

### ISSUE THREAD

**Issue by FelixWeichselgartner** [MicrosoftDocs/mixed-reality#208]
Räumliche Koordinatensysteme
Alle 3D-Grafikanwendungen verwenden kartesische Koordinatensysteme , um die Positionen und Ausrichtungen von virtuellen Objekten zu verwenden. Diese Koordinatensysteme richten drei senkrechte Achsen ein, um Objekte zu positionieren: eine X-, Y-und Z-Achse.
**In gemischter Realitäthaben ihre apps Informationen zu virtuellen und physischen Koordinatensystemen. Windows Ruft ein Koordinatensystem auf, das in der physischen Welt ein räumliches Koordinatensystem hat.**

correct version:
                              insert space      capital letter
**In gemischter Realität haben ihre Apps Informationen zu virtuellen und physischen Koordinatensystemen. Windows Ruft ein Koordinatensystem auf, das in der physischen Welt ein räumliches Koordinatensystem hat.**

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4e9fe050-958c-20e2-e5c6-a87926dc0d95
* Version Independent ID: b60496fb-d44d-aa87-2f49-0e34092f397e
* Content: [Koordinatensysteme - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/design/coordinate-systems)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/coordinate-systems.md](https://github.com/MicrosoftDocs/mixed-reality-pr.de-de/blob/live/mixed-reality-docs/mr-dev-docs/design/coordinate-systems.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by FelixWeichselgartner** [comment]
Also in the first sentence

Im Kern platzieren Mixed Reality-apps holograms in ihrer Welt, **die wie und echte Objekte** aussehen.

Maybe somebody should read the hole paragraph - i suppose there are more erros

**Comment by FelixWeichselgartner** [comment]
Die oben beschriebenen Ober skalamöglichkeiten folgen einem "Schachteln von Puppen"-Modell.

**Comment by FelixWeichselgartner** [comment]
Windows Ruft ein Koordinatensystem auf, das in der physischen Welt ein räumliches Koordinatensystem hat.

Error
Windows Ruft



I will stop now

**Comment by SilasContaifer** [comment]
Hello @FelixWeichselgartner I think would be better for you to create a **Pull Request** fixing the typos - so other person who also understand German can review it and accept later
