### ISSUE TITLE
Not sure what is wrong with this application.

### ISSUE THREAD

**Issue by ronak1997** [MicrosoftDocs/mixed-reality#2081]
As of right now when I click on the elements, nothing shows up whereas it is supposed to show the detailed element information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaed3d8-02a0-f846-2d63-02f981a1b141
* Version Independent ID: 00bb249c-2c9e-6f4a-ff0d-6a50dd3c008e
* Content: [Periodic Table of the Elements - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/periodic-table-of-the-elements#feedback)
* Content Source: [mixed-reality-docs/periodic-table-of-the-elements.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/periodic-table-of-the-elements.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by cre8ivepark** [comment]
@ronak1997 Closing this issue since it is about the application itself, not this documentation.
I'll follow up with the issue on Periodic Table app GitHub. Thanks!
https://github.com/microsoft/MRDL_Unity_PeriodicTable/issues/6
