### ISSUE TITLE
Typo, Toogle -> Toggle

### ISSUE THREAD

**Issue by jonmattgray** [MicrosoftDocs/mixed-reality#2089]
"In the app, you may notice the Diagnostics profiler, you can toggle it's visibility using the speech command Toogle Diagnostics."

Speech command should be Toggle Diagnostics

https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md

**Comment by jessemcculloch** [comment]
This has been fixed and pushed live.
