### ISSUE TITLE
Multi-user capabilities tutorials

### ISSUE THREAD

**Issue by roalchaq** [MicrosoftDocs/mixed-reality#2094]
Thank you for this great set of tutorials. I've go through the Multi-user capabilities tutorials and found some things that can be improved:

1. As you are using PUN, referring the readers to their basic tutorials (https://doc.photonengine.com/en-us/pun/v2/demos-and-tutorials/pun-basics-tutorial/intro) and trying to follow their terminology (Launcher, Game and Player rather than PhotonRoom, PhotonUser, GenericNetworkManager, GenericNetwork Sync, etc.) will make this series easier to follow.
2. The 'Connecting multiple users' section didn't work properly for me. It does instantiate the spheres but they don't move as you move around your head. Instead of using the FixedUpdate method  in GenericNetSync, you could use 'PhotonTransformView'  to synchronize the Position and Rotation of the sphere.
3. There are several objects and methods that are included but are not use at all, two examples are Tableprefab and Moduleprefab GameObjects in PhotonRoom.cs, they are referenced in code using the FindObjectOfType and PhotonNetwork.Instantiate methods instead of these public references.
4. The lunar launcher can not be moved around (just its components). I think this is because the anchor doesn't include the manipulation scripts needed. I used the ParentAnchor from the 'Azure Spatial Anchor' tutorials as a child of the 'MixedRealityPlayspace' and added the TableAnchor script to it instead of manually creating a Tableanchor GameObject and modified the 'TableAnchorAsParent' to get the same position and rotation from the Tutorial.

I included all these suggestions in my own version of these tutorials under Photon.md here: 

https://github.com/roalchaq/HoloLensTutorials.git

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9826a1-27c7-00ee-432d-f63351068fd4
* Version Independent ID: f4866dd4-ee10-29ac-598a-16bc5f1c613b
* Content: [Multi-user capabilities tutorials - 4. Sharing object movements with multiple users - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-sharing(photon)-ch4#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@roalchaq Thanks for the great feedback!

We will soon do a major refresh and cleanup of this tutorial series, similar to the major updates we recently did on the three preceding tutorial series, so we will try to implement your suggestions that align with this tutorial series' longer-term objectives.

>2. The 'Connecting multiple users' section didn't work properly for me. It does instantiate the spheres but they don't move as you move around your head. Instead of using the FixedUpdate method in GenericNetSync, you could use 'PhotonTransformView' to synchronize the Position and Rotation of the sphere.

The reason the spheres don't move in this step is because PhotonRoom.cs sets the sphere as a child of the camera, but then GenericNetSync.cs shares the user's local position instead of the camera's position. If you want to fix it you can, for example, remove the camera parenting in PhotonRoom.cs.

Thanks again for your feedback.
