### ISSUE TITLE
Spatial Sound in Unity Microsoft.SpatialAudio.Spatializer.Unity Requires Dependencies

### ISSUE THREAD

**Issue by kathleenwest** [MicrosoftDocs/mixed-reality#2095]
I think the documentation [here: https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-sound-in-unity] should be updated to include any required dependencies that the user needs to install. I thought this plugin was independent. 

Got this error:
Plugins: Failed to load 'Assets/Packages/Microsoft.SpatialAudio.Spatializer.Unity.1.0.0/Plugins/x86_64/AudioPluginMicrosoftSpatializer.dll' because one or more of its dependencies could not be loaded.

**Comment by jessemcculloch** [comment]
@MikeChemi - Can you look at this please?

**Comment by MikeChemi** [comment]
@jessemcculloch yep! We figured out what was going on over on the [associated github](https://github.com/microsoft/spatialaudio-unity/issues/12). We'll add a blurb about the required VC Runtime version.
