### ISSUE TITLE
Deploying to Hololens 2 might need different settings (when deploying over wifi)

### ISSUE THREAD

**Issue by kkroesl** [MicrosoftDocs/mixed-reality#21]
"Configure Visual Studio for HoloLens by selecting the Master or Release configuration, the ARM64 architecture, and Device as target" <- this only works when your Hololens is connected to your PC via USB AND you are also able to access it via the device portal by opening https://127.0.0.1:10080 in your browser. 
However, this (for some reason) often does not work (I, for example currently get the following error: SSL_ERROR_RX_RECORD_TOO_LONG in firefox).

If your Hololens 2 is paired to your PC AND you can access it via the device portal by opening its real network address in your browser, then you can deploy over wifi, but with different settings. Hence, I suggest adding the following text tot he tutorial:

"To deploy over wifi, configure Visual Studio for HoloLens by selecting the Master or Release configuration, the ARM64 architecture, and Remote Machine as target. Then go to **Project** -> **Properties** -> **Configuration Properties** -> **Debugging**. Make sure Configuration is set to Release and Platform to ARM64. Then, in the dropdown **Debugger to launch:** select **Remote Machine** and add the real network address of your Hololens as **Machine Name**.

I also suggest adding an image like [this one](https://drive.google.com/file/d/10UE_UAOyMcRMx9DL5zPiymAqUTgH5_8V/view?usp=sharing) (feel free to use this).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by evmill** [comment]
@hferrone The suggested text is accurate and informative, can we include it? I also think the image is very helpful.

**Comment by hferrone** [comment]
Absolutely, this is going up in an update tonight!
