### ISSUE TITLE
Confusing Unity requirements

### ISSUE THREAD

**Issue by billti** [MicrosoftDocs/mixed-reality#2104]
This page states "we recommend not installing the Unity workload as part of Visual Studio installation, and instead install the 2018.4 LTS stream of Unity as noted below", but then the first tutorial page I go to at https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1 states "The recommended Unity version for this tutorial series is Unity 2019.2.X."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6144653-f7f3-0ad2-5c8f-24310633144a
* Version Independent ID: a810412b-2ff0-29d3-3004-af58ce8c24be
* Content: [Install the tools - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools?source=docs#feedback)
* Content Source: [mixed-reality-docs/install-the-tools.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/install-the-tools.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
Hi @billti 

The docs have been updated to recommend 2019 LTS.

Cheers!
