### ISSUE TITLE
Article does not include instructions for installing to HoloLens 1

### ISSUE THREAD

**Issue by Shiloh-James-ELC** [MicrosoftDocs/mixed-reality#2111]
The deployment instructions on this page are only correct for deploying a MRTK v2.x application to a HoloLens 2 (an ARM64 device using OS version 10.0.18362.0 at time of writing). The page should also include the proper settings and steps for deploying the app to a HoloLens (x86 device using OS version 10.0.1763.1098 at time of writing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by evmill** [comment]
That tutorial there is the newer one made for HoloLens 2. The older one for HoloLens 1 along with deployment instructions is here: https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100#compile-the-visual-studio-solution .
Perhaps instead of having instructions for both, a link to the older HoloLens 1 guide at the top of the page would be nice?

**Comment by mr0ng** [comment]
@jessemcculloch should we be including HL1 deploy instructions on these tutorials?

**Comment by jessemcculloch** [comment]
@mr0ng - No, those steps are covered under the academy tutorials.
