### ISSUE TITLE
Orbital Script component configiuration

### ISSUE THREAD

**Issue by bblackbourn** [MicrosoftDocs/mixed-reality#2116]
Following the configuration instructions for the orbital script component results in the ButtonCollection object being out of view (below the camera frustum) in play mode and only following head y/yaw rotation, but not x/pitch rotation.
I think the text for the configuration should read as follows where WORLD offset is zero and LOCAL Y offset is -0.04 NOT -0.4:

Configure the Orbital (Script) component:

Verify that Orientation Type is set to Follow Tracked Object
Change LOCAL Offset to X = 0, Y = -0.04, Z = 0.3
Reset WORLD Offset to X = 0, Y = 0, Z = 0

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a77974e-95c6-8d98-08de-53c55ecf8600
* Version Independent ID: d60ba94b-87b2-6be0-1675-f4b2114b7bbd
* Content: [Getting started tutorials - 4. Placing dynamic content and using solvers - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-base-ch3#feedback)
* Content Source: [mixed-reality-docs/mrlearning-base-ch3.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch3.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@bblackbourn Thanks for the feedback.

>Following the configuration instructions for the orbital script component results in the ButtonCollection object being out of view (below the camera frustum) in play mode and only following head y/yaw rotation, but not x/pitch rotation.

This is on purpose so the buttons are not obstructing the user's view. The suggested configuration is to achieve the following:

> In this section, you will enhance the button collection you created in the previous tutorial so it follows the user's gaze direction. Additionally, you will also configure the Solver so the button collection is always:
> * Rotated parallel to the user's reading direction, for natural left to right reading
> * Positioned slightly below the user horizontal gaze direction, so it's not obstructing the other objects you will add later in this tutorial
> * Positioned approximately a half arm's-length from the user, so the buttons can easily be pressed

However, you may configure the solver any way you like.
