### ISSUE TITLE
Incorrect path to folder for audio

### ISSUE THREAD

**Issue by bblackbourn** [MicrosoftDocs/mixed-reality#2117]
In step 4, instruction currently reads:
Navigate to Assets &gt; MixedRealityToolkit.SDK &gt; StandardAssets &gt; Materials to see audio clips provided with the MRTK,...

Should read:
Navigate to Assets &gt; MixedRealityToolkit.SDK &gt; StandardAssets &gt; Audio...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e480f6-30d8-9538-bff1-74ba54dc310e
* Version Independent ID: 1cb31b72-b828-d8d3-74fa-6641a61f3750
* Content: [Getting started tutorials - 5. Interacting with 3D objects - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-base-ch4)
* Content Source: [mixed-reality-docs/mrlearning-base-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@bblackbourn Thanks for reporting this.

We have made the correction and will push the update out shortly.
