### ISSUE TITLE
Holographic Remoting Player causes fatal C++ runtime error in Unity

### ISSUE THREAD

**Issue by Phatage** [MicrosoftDocs/mixed-reality#2124]
This happens right after clicking "connect" if I have it configured to run with my HL2. The HL1 remoting still seems to work fine. It's happened on every Unity version I've tried (2017.4.36f1, 2018.4.4f1, 2018.4.19f1, 2019.3.5f1). MSBuild has been enabled with MRTK 2.3.0. I've made sure I've had the Spector libs installed through VS (even though the error doesn't say anything about libs), running Windows 10 v1803 on a very poor GPU admittedly but still never had issues doing this with the HL1.

I've looked in the log and it doesn't seem to log anything - I was able to test this by trying to run it for HL1 with no IP address specified and it did log "Cannot connect without a remote machine address specified". However then when I ran it with an IP address using HL2, it just crashed with the image below with nothing additional added to the log afterwards. I do want to note that this is using a work computer with some restrictions on it but the error still comes up even while on a personal wifi with no VPN and as I mentioned before, the HL1 connection seems to still work on this same setup.

https://user-images.githubusercontent.com/2589823/77355261-89ff2b00-6d1a-11ea-9a2a-66a5f0471315.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5141cd4-aa05-46fe-9378-a9cc0ef19f76
* Version Independent ID: 1a2e110d-8dae-e52b-f856-34217c6f6e54
* Content: [Holographic Remoting Player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-player)
* Content Source: [mixed-reality-docs/holographic-remoting-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holographic-remoting-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @FlorianBagarMicrosoft
* Microsoft Alias: **flbagar**

**Comment by FlorianBagarMicrosoft** [comment]
Does Holographic Remoting work if you use our remote sample?
You can get the sample from https://github.com/microsoft/MixedReality-HolographicRemoting-Samples. Simply open remote/desktop/SampleRemote.sln in Visual Studio 2019, compile for arm64, specify your HL2 IP address via Project Properties -> Debugging -> Command Arguments, and start on your PC. Once started press space to connect to your HL2. Note, also ensure that the Holographic Remoting Player running on your HL2 is up to date.

**Comment by Phatage** [comment]
Thanks, I actually did try that sample before but didn't really know how to
use it until I saw this message. Also had to compile for x64 to run on my
pc, but seemed to work on my HoloLens 2 without a hitch and I see the
spinning color cube.

I've taken a screencap of the fatal error that still arises in Unity:
https://arup-my.sharepoint.com/:v:/p/travis_rothbloom/EdUKAZzTPT1IsF4a1t2TOl0BpGg3dNuB57rEcHB3FTBqxA?e=shgLUT

**Comment by FlorianBagarMicrosoft** [comment]
Great, so Holographic Remoting works for you and we just need to figure out why Unity does crash.
I installed Unity 2018.4.4f1 today but unfortunately I was not able to reproduce the issue.

I also tried to use different version (1.0.11, 1.0.12, and 1.0.19) for the Windows Mixed Reality package in Unity (via Window -> Package Manager) but works fine with all.
Which package version for Windows Mixed Reality are you using?

Also, have you tried with to use Holographic Remoting in Unity with a freshly created scene/project? I did my tests basically with a default scene which just includes the skybox. Would be great if you could try with a fresh project which does not use any other plugins or packages. My suspicion is that the crash only happens in combination with another package, maybe it's related to MRTK 2.3.0?

**Comment by Phatage** [comment]
Thanks for testing this out. I'm using WMR 1.0.19 and yes this has failed
on fresh projects with no contents, using MRTK 2.3.0. Everything seems to
work fine when setting it to HL1 (and I can confirm that it did work with
my HL1) but the HL2 mode causes the fatal error instantly. It also causes
this issue in Unity 2019.3.5f1.

Is there a big fundamental difference between how it's communicating to the
HL1 vs. the HL2? Obviously it's communicating to an ARM processor instead
of x86 but it worked just fine in your standalone example that didn't use
Unity.

**Comment by FlorianBagarMicrosoft** [comment]
I talked with the developers from Unity who work on WMR. The suggestion is that you upgrade to 2018.4.20f1 or 2019.2.6f1 and use package version 1.0.19. If you still get the issue after that, you should submit your project to Unity through a bug report.

**Comment by Phatage** [comment]
I still got the same exact error on 20184.20f1 using WMR 1.0.19 with a
blank project. Just to be clear, I'm accessing the Holograph Remoting tool
by going to Window > XR > Holographic Remoting, this is the correct way to
access it right?

Would you be able to put me in touch with the Unity WMR developers you've
been speaking to on this or would it be just as efficient submitting a
Unity bug report?

**Comment by FlorianBagarMicrosoft** [comment]
Submitting a Unity bug report ensures that everything is properly tracked. If you want you can post a link to the bug and I will forward it to the Unity developers.

**Comment by Phatage** [comment]
Sounds good, here is the link to the bug:
fogbugz.unity3d.com/default.asp?1235372_amaka0uckg7nrvob

**Comment by ChaseBowman** [comment]
Hello, I wasn't sure how to leave this one level higher -- this is a new topic. 

For Remoting, my HL2 connects perfectly, but on play in unity, when I move my head I see the tracking in the scene window of Unity but I don't see anything in the headset.  So it's connecting, using tracking data, but not showing holograms in the headset.  Any thoughts?
