### ISSUE TITLE
Emulator 2 and DirectX 12

### ISSUE THREAD

**Issue by IvanGitH** [MicrosoftDocs/mixed-reality#2130]
The native DirectX 12 template app (the rotating cube) does not work on the emulator! 
The DirectX 11 version works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158816f1-50b1-c5c2-8a9f-00062116c100
* Version Independent ID: a38cd9ae-c9c6-eb75-cf41-55696330b0d5
* Content: [HoloLens Emulator archive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hololens-emulator-archive)
* Content Source: [mixed-reality-docs/hololens-emulator-archive.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hololens-emulator-archive.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by pbarnettms** [comment]
To work around this issue, please comment-out the following block of code in CameraResources.cpp:

```
 for (auto format : supportedFormats)
    {
        if (format == DirectXPixelFormat::R8G8B8A8UIntNormalized)
        {
            m_holographicCamera.ViewConfiguration().PixelFormat(format);
            supportsRgba = true;
        }
    } 
```

**Comment by IvanGitH** [comment]
Yes, it works now!
https://www.youtube.com/watch?v=fr9ppl2k_3c

**Comment by pbarnettms** [comment]
Glad to hear it.  The issue will be addressed in a future update of either the templates or the emulator.

**Comment by IvanGitH** [comment]
Thank you,

I am developing a 3D engine for HL2 on DX12 (called MixerX) specialized for applications in medicine like integrating CT and MRI images as volumetric and polygonal holograms into real patients and performing diagnostics and navigations in simulations of surgical operations.

Could you provide me with a contact to the DX12 team, since I do not want to use Unity – it is for kids!

Regards,
Ivan Zoraja
