### ISSUE TITLE
DllNotFoundException：AzureSpatialAnchors 

### ISSUE THREAD

**Issue by ylwuhan** [MicrosoftDocs/mixed-reality#214]
I follow the instructions in the tutorial （https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02） to configure the project, but an error is reported after running:DllNotFoundException: AzureSpatialAnchors.
Can anyone help me solve this problem

**Comment by veeruby-developer** [comment]
@ylwuhan  could you please provide more information on this.

If you are getting this **DllNotFoundException: AzureSpatialAnchors** error in Unity Console, then please note that Azure Spatial Anchors can not run in Unity, so to test the Azure Spatial Anchors functionality, you need to build the project and deploy the app to your device.
