### ISSUE TITLE
Images not centered in page

### ISSUE THREAD

**Issue by Yonet** [MicrosoftDocs/mixed-reality#2155]
Some of the images are not centered on page, inlined instead. See images below:
<img width="786" alt="Screen Shot 2020-04-13 at 4 35 44 PM" src="https://user-images.githubusercontent.com/3523671/79170735-1befd600-7da5-11ea-9dec-15236fa7d297.png">
<img width="797" alt="Screen Shot 2020-04-13 at 4 35 50 PM" src="https://user-images.githubusercontent.com/3523671/79170740-1e523000-7da5-11ea-923c-f8a435bb2610.png">

Link to pages: https://docs.microsoft.com/en-us/windows/mixed-reality/using-visual-studio

**Comment by jessemcculloch** [comment]
What page in the docs is this on?
