### ISSUE TITLE
All of this is wrong.

### ISSUE THREAD

**Issue by sealfoss** [MicrosoftDocs/mixed-reality#216]
Basically nothing about accessing video from the HoloLens webcam in this article is correct. Please update w/ relevant info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd07cb8-0169-9eeb-706a-890cd0418d0e
* Version Independent ID: 46b95d28-2e43-1c9d-a338-495210bd9f91
* Content: [Locatable camera in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/locatable-camera-in-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/locatable-camera-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/locatable-camera-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @wguyman
* Microsoft Alias: **wguyman**

**Comment by hferrone** [comment]
@sealfoss Thanks for point this out, we've updated the content!

**Comment by sealfoss** [comment]
Thank you!
