### ISSUE TITLE
Connecting but no holograms in headset 

### ISSUE THREAD

**Issue by ChaseBowman** [MicrosoftDocs/mixed-reality#2160]
My HL2 connects perfectly, but on play in unity, I move my head and see the tracking in the scene window of Unity but I don't see anything in the headset. So it's connecting, using tracking data, but not showing holograms in the headset. Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5141cd4-aa05-46fe-9378-a9cc0ef19f76
* Version Independent ID: 1a2e110d-8dae-e52b-f856-34217c6f6e54
* Content: [Holographic Remoting Player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-player#feedback)
* Content Source: [mixed-reality-docs/holographic-remoting-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holographic-remoting-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @FlorianBagarMicrosoft
* Microsoft Alias: **flbagar**

**Comment by FlorianBagarMicrosoft** [comment]
There have been issues with Holographic Remoting in Unity in older version.
Which Unity version and which Windows Mixed Reality package version in Unity (via Window -> Package Manager) are you using?

**Comment by ChaseBowman** [comment]
Hi @FlorianBagarMicrosoft,
thanks for the reply!
I'm using Unity version 2019.3.7f1. And WMR 4.2.1.  
And yeah so it's definitely connecting -- when I turn my head I see changes in the Unity player.  Just nothing in the headset -- totally blank.

**Comment by ChaseBowman** [comment]
Hi Florian, thanks so much for the support here!  I will try this asap.
