### ISSUE TITLE
Wiring up 4th Button "GetAzureAnchor" copy/paste issue

### ISSUE THREAD

**Issue by DuckAdam** [MicrosoftDocs/mixed-reality#2176]
The step for wiring up the 4th button "GetAzureAnchor" refer to the wrong button:

In the Hierarchy window, select the third child button object named ShareAzureAnchor, then in the Inspector window, locate the Interactable (Script) component and configure the OnClick () event as follows:

To None (Object) field, assign the TableAnchor object
From No Function dropdown, select the SharingModuleScript &gt; GetAzureAnchor () function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439d2561-655e-5168-3504-a50ed1ba9879
* Version Independent ID: e3d7c1bf-82e4-2b30-df08-c5fb340a25c3
* Content: [Multi-user capabilities tutorials - 5. Integrating Azure Spatial Anchors into a shared experience - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch4)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@DuckAdam Thanks for reporting this issue, we will get it corrected right away.
