### ISSUE TITLE
The "waves traveling into HoloLens person" icon is distracting when running.

### ISSUE THREAD

**Issue by pinkwerks** [MicrosoftDocs/mixed-reality#2180]
I use the holographic remoting player "a lot". I love it. I would love it even more if we could do something about that icon in the middle of the screen. The one with the head profile and wi-fi waves going into it - I wish it wasn't there, or at least not dead center and brighter than the surrounding text. Often, I start the viewer, and need to look at unity and hit the play button. But that bright white icon is in the middle of what I need to see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5141cd4-aa05-46fe-9378-a9cc0ef19f76
* Version Independent ID: 1a2e110d-8dae-e52b-f856-34217c6f6e54
* Content: [Holographic Remoting Player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-player#feedback)
* Content Source: [mixed-reality-docs/holographic-remoting-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holographic-remoting-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @FlorianBagarMicrosoft
* Microsoft Alias: **flbagar**

**Comment by FlorianBagarMicrosoft** [comment]
Thanks for the feedback. We will include improvments on that in the next updated of the Holographic Remoting Player.

**Comment by FlorianBagarMicrosoft** [comment]
Pink, version 2.1.3 of the Holographic Remoting player has been released. The icons should not block your view anymore now.

**Comment by pinkwerks** [comment]
OMG so much better thanks for this!
