### ISSUE TITLE
Tutorial - "Tap to Place" setup should include disabling "Use Default Surface Normal Offset"

### ISSUE THREAD

**Issue by paco-ms** [MicrosoftDocs/mixed-reality#219]
The tutorial includes a step to set the surface normal offset to 0 on "Placing Started", but that will be ignored given the fact that the "Use Default Surface Normal Offset" option is on (by default). This can be detected by:
- The fact that a debug assert is raised ("The new value for SurfaceNormalOffset on the Tap to Place object will not be applied because UseDefaultSurfaceNormalOffset is true") when taping.
- The fact that the Rover, when placed, will hover above the box a noticeable distance, rather than sit on it.

These two issues are fixed by disabling that option (thus this step should be included in the tutorial).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@paco-ms its correct. Thanks for the feedback,
tutorials will be updated.
