### ISSUE TITLE
I tried to migrate the project to HoloLens2, but I encountered some problems.

### ISSUE THREAD

**Issue by KysS09** [MicrosoftDocs/mixed-reality#2194]
When I migrated my project to HoloLens2, I found that I had to choose the ARM platform, but the assimp.dll I used did not support the ARM platform. Is there a good solution?

**Comment by hferrone** [comment]
Hi @KysS09,

Can you provide a bit more info:
- What platform are you developing on (Unity, Unreal, etc)
- What tools or plugins are you using (MRTK, HTK, etc)

Cheers!
