### ISSUE TITLE
Hand Models don't have linecasts

### ISSUE THREAD

**Issue by CLaferriereRY** [MicrosoftDocs/mixed-reality#2196]
[Enter feedback here]
I followed all the steps, but the hand models don't have the line casts coming out of them and dont allow for pickup or manipulation of objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e94ee7b-9330-dc8f-cac2-9e677372db91
* Version Independent ID: a3c182a8-1754-8adf-7cbc-51f6ed3f8b2c
* Content: [4. Making your scene interactive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch4)
* Content Source: [mixed-reality-docs/unreal-uxt-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @sw5813
* Microsoft Alias: **suwu**

**Comment by sPoss678** [comment]
Double check the last step of page 3; I somehow skimmed over the DefaultMode setting on the first run through.

"The last step in setting up your project is to tell Unreal to default to MRGameMode. Go to Edit > Projects Settings > Maps & Modes (in the Projects) section. In the Default Modes section, click the dropdown and choose MRGameMode. In the Default Maps section right below, change both the EditorStartupMap and the GameDefaultMap to Main. This way when you close the editor and reopen it, the Main map will be selected by default. Similarly, when you play the game, the Main map will be the level that is started."

**Comment by CLaferriereRY** [comment]
I actually got it working, thanks! now I'm having an issue packaging it for HoloLens. Its saying I dont have the Binaries for the target platform installed. I believe I downloaded everything from the prerequisites. Any idea why this would happen? I'm unfortunately new to Unreal but worked with the HoloLens in Unity for a while.

**Comment by sw5813** [comment]
You'll need to download supporting files from the Epic launcher- see the second step of: https://docs.unrealengine.com/en-US/Platforms/AR/HoloLens2/HowTo/PackageApp/index.html

**Comment by andolph** [comment]
- I have the same problem as the original poster - no line casts coming from the hands - I also have an error message "Attempting to start an AR session but there is no AR plugin configured. To use AR, enable the proper AR Plugin in the Plugin Settings". 

- I have switched on the relevant plugins in both the AR and VR plugin setting sections in Unreal - I have also ensured MRGameMode is switched in as per above. 

Any ideas anyone?

**Comment by sPoss678** [comment]
@andolph  

1. Did you setup the ARSessionConfig blueprint? 
2. If so, did you also add it to the level blueprint? 
3. Also, check the last step on page 3 of the tutorial, to be sure you changed both the DefaultMode and Level settings.

**Comment by andolph** [comment]
Yes - all three 

As mentioned before, I have the hands appearing and I can point, pinch etc but they won't interact with the scene (ie chess piece) and I don't see any casts from them either. The error message implies an AR plugin issue but the relevant ones are all switched on. 

I'm running Unreal 4.25

**Comment by andolph** [comment]
Update:
Fixed ! 

- Ensure All  AR and VR plugins are turned off in Plugin settings except the ones needed by Windows MR and MRTK
- The cast lines to the hands are now visible and there is now correct functionality for picking up objects, etc

**Comment by CLaferriereRY** [comment]
andolph,

So I believe I found a solution, however seeing as I'm new to UE4 in
general I dont know why it works. First, go to the UXTools C++ Classes
folder and search for UxtHandInteractionActor. Drag two of them into your
scene. You should now see the lines coming out of the hands when you press
play. Let me know if this works!

**Comment by andolph** [comment]
hi CLaferriereRY

Many thanks but please my post just above yours
