### ISSUE TITLE
Cannot run when deployed to my HL2

### ISSUE THREAD

**Issue by Phatage** [MicrosoftDocs/mixed-reality#2198]
When I complete all the steps on this page and deploy to my HL2, the app builds and gets deployed successfully, even asking for permissions to use the mic, etc. It then immediately exits to the home screen. Running this while debugging brings up repeated Access Violations, and I've attached a screenshot of this below. Unity is 2019.3.5f1, VS2019 is 16.5.2. 

This happened both when I tried this sample a month ago and with a new project I just created today seeing as things were updated. It's worth noting that playing in the Unity editor seems to work just fine with no issues, except that it obviously cannot see the HL2 joining the session. Am I not enabling all the capabilities needed? I currently have selected InternetClient, InternetClientServer, PrivateNetworkClientServer, RemovableStorage, Microphone, SpatialPerception, PointOfService, and GazeInput.

https://photos.app.goo.gl/hDrs6iubs5WuoESu7 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c749260f-d284-74f9-ffff-9afd2069ef81
* Version Independent ID: 04aff1f3-9c67-07f5-4fe2-6b1fd256e9f3
* Content: [Multi-user capabilities tutorials - 3. Connecting multiple users - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch2#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@Phatage, did you use 2019.3.X both times? There are a lot of changes in Unity 2019.3 and also quite a few [known MRTK issues](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.3.0/Documentation/ReleaseNotes.html#known-issues-in-230) as it relates to this version of Unity.

The [recommended Unity version](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1#prerequisites) for these tutorials is Unity 2019.2.X. I think the quickest way for you to get a successfull deployment would be to redo the project using that Unity version. Once we get the tutorials updated for Unity 2019.3.X, you can revisit the tutorial if you want to do it using the latest Unity version.

Would you be able to start the tutorial over again using Unity 2019.2.21 (latest 2019.2.X patch), no need to redo the [Setting up Photon](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1#setting-up-photon) section, and let us know if you are able to deploy to your HL2 and see the shared movements in real-time?

You can add Unity 2019.2.21 to your Unity Hub from the Unity [Downloads Archive](https://unity3d.com/get-unity/download/archive) page.

**Comment by Phatage** [comment]
Thanks Martin, that did seem to be the issue as I was just able to get it
running successfully on two HL2s using Unity 2019.2.21. Feel free to close
this issue.

**Comment by martinwilter** [comment]
@Phatage, glad to hear you were able to get it working on your HL2s, thanks for letting us know.

@jessemcculloch, this issue can be closed.
