### ISSUE TITLE
Hololens 2 Emulator

### ISSUE THREAD

**Issue by faizan8684** [MicrosoftDocs/mixed-reality#2199]
I am facing through 2 errors, as follows: 
1. Input controls through my keyboard and mouse are not working properly. I get the message of Windows Agreement, and when I press left/right click mouse or Enter key, though there's a sound of clicking, but nothing happens.
2. While deploying to Hololens 2 Emulator through Visual Studio 2019, I am getting the message, "There were deployment errors" and it is not getting deployed. 

I followed the steps on [aka.ms/hololensemulator](). 
I also referred to the previously closed issue [https://github.com/MicrosoftDocs/mixed-reality/issues/1083]() .

Can anyone suggest something else?

**Comment by pbarnettms** [comment]
For #1, are you attempting to interact with the emulator hands or are you expecting to navigate the UI controls by tabbing around?  If the latter, have you turned off the "Use keyboard for simulation" option in the Simulation panel?  If "Use keyboard for simulation" and "Use mouse for simulation" are enabled, a left click of the mouse will rotate the display unless you are holding an Alt key, which will then rotate the hand.  A right-click will perform a tap operation.  If the hand ray is not pointing at a control or other interactive object, you will hear a tap sound but no action will be taken.  I would recommend having a look at the documentation for input control located at https://docs.microsoft.com/en-us/windows/mixed-reality/advanced-hololens-emulator-and-mixed-reality-simulator-input.

2. The "Build" or "Deploy" view of the :"Output" window should have more specific errors.  Can you please share those?  What build of the emulator are you using?  (For example, "10.0.18362.1061")

**Comment by hferrone** [comment]
@faizan8684 Can you share the specific errors and emulator build you're using?

**Comment by hferrone** [comment]
@faizan8684 Hopefully we haven't heard from you because you got the issue resolved. I'm going to close this thread, but if you have further problems please comment and I'll reopen it!
