### ISSUE TITLE
MSBuild for Unity Support 

### ISSUE THREAD

**Issue by Sean-Kerawala** [MicrosoftDocs/mixed-reality#22]
MSBuild for Unity Support is not visible on the users screen in Step 2, but is an option we see in Unity today for the MRTK config settings. Can you please add this so folks have certainty about project initialization? The blurb in the settings pane calls out this as enabling additional HL2 features such as hand joint remoting and depth LSR mode. @martinwilter 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
Hi @Sean-Kerawala,

As stated in the [Introduction](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-01), these tutorials are for Unity 2019.3:

![image](https://user-images.githubusercontent.com/16746283/91236009-b95ffc80-e6eb-11ea-972c-842ce8165a3e.png)
<br><br>

The MRTK Project Configurator [does not show 'Enable MSBuild for Unit'](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/ReleaseNotes.html) option:

![image](https://user-images.githubusercontent.com/16746283/91236280-620e5c00-e6ec-11ea-8a16-3b7823bdfa17.png)
<br><br>

So probably the image shouldn't be updated before the tutorials are updated to Unity 2019.4.

CC @mr0ng
