### ISSUE TITLE
Page Header should read - 4. Making your scene interactive

### ISSUE THREAD

**Issue by bradTTF** [MicrosoftDocs/mixed-reality#2213]
Instead of:
3. Making your scene interactive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e94ee7b-9330-dc8f-cac2-9e677372db91
* Version Independent ID: a3c182a8-1754-8adf-7cbc-51f6ed3f8b2c
* Content: [4. Making your scene interactive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch4#feedback)
* Content Source: [mixed-reality-docs/unreal-uxt-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @sw5813
* Microsoft Alias: **suwu**

**Comment by sw5813** [comment]
Thanks for catching this, just submitted a PR to fix this: https://github.com/MicrosoftDocs/mixed-reality/pull/2218
