### ISSUE TITLE
ResetButton or SimpleButton?

### ISSUE THREAD

**Issue by bradTTF** [MicrosoftDocs/mixed-reality#2214]
The "Add a button" section seems to contain inconsistencies when referring to the name of the button created.

Step 1 states: 
Name this button **“ResetButton”**  and double click to open the Blueprint.

Step 4 states:
Drag the WhiteKing variable from My Blueprint &gt; Variables onto the **Simple Button** Event Graph.

Step 5 states:
Compile and Save the **ResetButton** Blueprint, then return to the Main window.

Step 6 states:
Drag **SimpleButton** into the viewport and set its location to X = 50, Y = -25, Z = 10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @sw5813
* Microsoft Alias: **suwu**

**Comment by sw5813** [comment]
Thanks for catching this, just submitted a PR to fix the inconsistencies: https://github.com/MicrosoftDocs/mixed-reality/pull/2217
