### ISSUE TITLE
Implemented buttons functionalities do not work

### ISSUE THREAD

**Issue by Ciubaka** [MicrosoftDocs/mixed-reality#2216]
I have a problem, I worked according to the guide, but none of the buttons (Hints, Reset, Launch) respond. What could possibly go wrong?

**Comment by martinwilter** [comment]
@Ciubaka Are you currently testing in Unity? If you can share some more details, we might be able to help.

**Comment by Ciubaka** [comment]
Yes, I’m testing in Unity and on physical device. First step working, but
when i press any of buttons nothing happens – lunar not launching,  parts
of Module not being reset to their original position and hints are still
invisible.  I checked the settings a few Times and what’s interesting, when
i presing button audio-related event is working. I don’t know what’s wrong,
but i can’t see any interact beetwen buttons and lunar model.

pt., 15 maj 2020 o 22:33 Martin Wilter <notifications@github.com>
napisał(a):

**Comment by Ciubaka** [comment]
I found a mistake in the guaid, events should be implemented in
Interactable component (OnClick method), not in Pressable Button (Script)
component. When i implemented in Interactable component everything works
.
[image: image.png]

pt., 15 maj 2020 o 23:34 Ildefons Jarzyna <ildefonsjarzyna@gmail.com>
napisał(a):

**Comment by martinwilter** [comment]
@Ciubaka Great to hear you got it to work, well done.

The implementation shown in the tutorial should still work, but you are correct, best practice is to implement the events on the Interactable.OnClick event. We will change to this implementation in future tutorial updates. If you take a look at the RocketLauncher_Complete prefab that came with the tutorial assets, you will see that's how we implemented it on that prefab (which is used in the tutorial series following this one).
