### ISSUE TITLE
Broken links to mrtk-unity docs throughout mixed-reality

### ISSUE THREAD

**Issue by keveleigh** [MicrosoftDocs/mixed-reality#224]
There are quite a few incorrect links to the MRTK docs that are linking to `https://docs.microsoft.com/windows/mixed-reality/mrtk-docs/*` instead of `https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/*`. A good place to see this is the two links at the bottom of this page, in "See also":

![image](https://user-images.githubusercontent.com/3580640/110039407-043f7a00-7cf6-11eb-9613-ad18f5e9fba1.png)

though there are numerous examples of this typo throughout the docs. (The second link also still references "GitHub" in the text, even though it doesn't link to GitHub anymore)

Many of these links also still end in `.md` (for example, the aforementioned "Porting from HoloToolkit/MRTK to MRTK version 2 (GitHub)" link links to https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-docs/updates-deployment/hrtk-to-mrtk-porting-guide.md, which contains both issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95809b24-cc2f-3118-6d05-c504ed734cfc
* Version Independent ID: c9341566-b6b7-25bc-0121-1c6c30a43d49
* Content: [Introducing MRTK for Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/mrtk-getting-started#feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by polar-kev** [comment]
FYI @varunsiddaraju. Are you able to take a look at these?

**Comment by keveleigh** [comment]
Via a rough search, possibly 67 incorrect links with both `mrtk-docs` and `.md`

![image](https://user-images.githubusercontent.com/3580640/110039994-ee7e8480-7cf6-11eb-803b-9a13a45a1a01.png)

and ~103 with `mrtk-docs`

![image](https://user-images.githubusercontent.com/3580640/110040067-0bb35300-7cf7-11eb-91a0-ad86cbda2274.png)

**Comment by varunsiddaraju** [comment]
@polar-kev I'm looking into this issue and we will work on it.

@keveleigh Could you please let me know how to find those 67 incorrect links?

**Comment by keveleigh** [comment]
@varunsiddaraju I opened the repo in VS Code and used their regex search with string `mrtk-docs\/.*\.md`: 
![image](https://user-images.githubusercontent.com/3580640/110042638-eaecfc80-7cfa-11eb-86ff-a2296d920ded.png)

After that, just searching for `mrtk-docs` should reveal any remaining issues

**Comment by varunsiddaraju** [comment]
Hi @polar-kev 

For M/S doc migration, we were using mixed-reality-pr repo but this issue is created from mixed-reality repo so we are not sure whether we are supposed to work on this on this or not. Kindly, please clarify.

**Comment by polar-kev** [comment]
Hey @varunsiddaraju, please use the mixed-reality-pr repo for fixes.

The mixed-reality repo is a public repo that allows anyone looking at our docs to file an issue using the feedback button at the bottom of the page.
![image](https://user-images.githubusercontent.com/30964480/110404688-26a60000-8034-11eb-94dd-09dfe11384f0.png)

The mixed-reality-pr repo is a private repo where we stage updates via our branches, review them, and push them live.

**Comment by hferrone** [comment]
That is correct!

**Comment by hferrone** [comment]
@varunsiddaraju @polar-kev Is this fixed or does this need to remain open?

**Comment by varunsiddaraju** [comment]
@hferrone Thanks for checking up on this, We are still working on it, please keep it open.

**Comment by veeruby-developer** [comment]
@hferrone This Issue can be closed Now.
