### ISSUE TITLE
2019.311f1

### ISSUE THREAD

**Issue by laylagordon-666** [MicrosoftDocs/mixed-reality#2241]
[Enter feedback here]
The app when deployed on Hololens doesn't launch as Hololens app but more like a widows app.
This only happns in unity 2019.3 and not in 2018.
any ideas?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-base-ch1)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@laylagordon-666, because you are using Unity 2019.3, it's possible that Unity disabled legacy VR in your project (in favor of the new XR Plugin Management system) without your knowledge. You can follow the [Configure the Unity project for Windows Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrlearning-base-ch1#configure-the-unity-project-for-windows-mixed-reality) instructions to check.

Issue https://github.com/MicrosoftDocs/mixed-reality/issues/2198#issuecomment-626984298 might also be of help.

**Comment by laylagordon-666** [comment]
I have enabled legacy VR but Unity compains that Built-in VR must be disabled prior to using XR plug-in Management. Also the instructions in that link are for unity 2018?

**Comment by laylagordon-666** [comment]
<img width="650" alt="Capture-unity" src="https://user-images.githubusercontent.com/64796072/82995655-c6415700-9ffb-11ea-9a2a-224b9b9bb67a.PNG">

**Comment by laylagordon-666** [comment]
it says above that legacy XT is incompatibe with XR SDK

**Comment by laylagordon-666** [comment]
> 
> 
> The tutorial should stress that it does NOT work with Unity 2019.3.X.
> It took me hours to find out that using the newest version of Unity was the reason for not getting anything to run on Hololens2.
> Now tried Unity 2019.2.21f1 and it works.

I'm glad you say that. Mine works perfcetly on 2019.2 too but NOT on 2019.3
can you please conofirm this is official line?
its wasted me so much time trying to get it working

**Comment by martinwilter** [comment]
@laylagordon-666 and @kkroesl, sorry for the wasted time.
__
<br><br>


> I have enabled legacy VR but Unity compains that Built-in VR must be disabled prior to using XR plug-in Management. Also the instructions in that link are for unity 2018?

Those are for Unity 2019.2 and should generally also work for Unity 2018 LTS, but will not work with Unity 2019.3 if you accept Unity's  'Built in VR Detected' and 'Built in VR Enabled' prompts as that will disable built-in/legacy VR and remove Windows Mixed Reality SDK.

If instead you close those two popups you should be able to deploy to HoloLens using built-in/legacy VR.

If you want to try Unity's new XR Plugin Management system, you can refer to the [Getting started with MRTK and XR SDK](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html).
__
<br><br>

> it says above that legacy XR is incompatibe with XR SDK

You can't use built-in/legacy VR with the new XR Plugin Management system. To re-enable built-in/legacy VR you can try to run the MRTK Project Configurator again, if that doesn't work, you probably need to first uninstall the XR Plugin Management package (using Package Manager).
__
<br><br>


> The tutorial should stress that it does NOT work with Unity 2019.3.X.
> It took me hours to find out that using the newest version of Unity was the reason for not getting anything to run on Hololens2.
> Now tried Unity 2019.2.21f1 and it works.

Thanks for the feedback. There is an 'Important' note in the [Prerequisite](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1#prerequisites) section of this tutorial series:

![image](https://user-images.githubusercontent.com/16746283/83045564-98a7de00-9ffa-11ea-9d5c-70ca994c11d5.png)

but we will consider making it more explicit.
__
<br><br>




> > The tutorial should stress that it does NOT work with Unity 2019.3.X.
> > It took me hours to find out that using the newest version of Unity was the reason for not getting anything to run on Hololens2.
> > Now tried Unity 2019.2.21f1 and it works.
> 
> I'm glad you say that. Mine works perfcetly on 2019.2 too but NOT on 2019.3
> can you please conofirm this is official line?
> its wasted me so much time trying to get it working

The tutorials officially supports Unity 2019.2, not Unity 2019.3, however, it is possible to deploy to HoloLens using Unity 2019.3 with built-in/legacy VR or the new XR Plugin Management system as outlined above.

**Comment by laylagordon-666** [comment]
I like to get the new XR SDK working with 2019.3 and deploy tp HL2.
I've tried using that link you just posted before and I get an error. But I just gave it another go.
I have set the profile to the defaultXRSDK one and I'm skipping the steps for "To migrate an existing profile to XR SDK, the following services and data providers should be updated" as I'm not porting an existing profile?
I've attached the screenshot of the error I get just by pressing play in unity on the scene
<img width="953" alt="Capture-unity-2" src="https://user-images.githubusercontent.com/64796072/83051174-8606c680-a045-11ea-96e8-88aab6960177.PNG">
<img width="953" alt="Capture-unity-3" src="https://user-images.githubusercontent.com/64796072/83051245-a3d42b80-a045-11ea-9c0e-716f6c5c3d42.PNG">

**Comment by martinwilter** [comment]
@laylagordon-666, first thing I would do is to upgrade/use the latest Unity 2019.3 patch version which is 2019.3.14 as the XR packages will be updated as well.

**Comment by laylagordon-666** [comment]
also I#m not getting thr the diagnostic widget and  hand joint service. Even before I pause the scene (which is when I get the error) nothing happens in the scene where as with the one on the left you get a bigger list
<img width="953" alt="Capture-unity-4" src="https://user-images.githubusercontent.com/64796072/83052505-52c53700-a047-11ea-8cbd-04e0de4d143b.PNG">

**Comment by laylagordon-666** [comment]
I updated the XRSDK to the latest version in my 2019.3.11f1 but just following your suggestion I'm now downloading 2019.3.14f1

**Comment by martinwilter** [comment]
@laylagordon-666, thought you might wanted to know that [MRTK 2.4.0](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/tag/v2.4.0) was just released, so if you want to use the new XR Pluging Management system, you might have better luck with that version of MRTK. But please note that the tutorials are made for MRTK 2.3.0 and Unity 2019.2.

**Comment by laylagordon-666** [comment]
Thanks, will give that a go :)

**Comment by laylagordon-666** [comment]
so the app launches inside a window with unity logo and i can see my blank scene but it doesn't behave like a Hololens app with the optimizer, spatial perception and the hand cause the widgets ddon't exist under the defaultXRSDKconfiguration profile. do I need to add those seperatly? I'm guessing I can't use the Hololens ones or the other mixedreality default one.

**Comment by laylagordon-666** [comment]
ok, so progress is that the app npw launches fine and I have my hands as a holographic objects being tracked and spatial mesh in the room. Just need to add the profiler I guess. I'm using defaultXRSDK. And ARM64 at the time of deployment. The profiler seemed to be part of the DefaultMixedRealityToolkitConfigurationProfile, can I add it seperately? (the one that shows the FPS info)

**Comment by laylagordon-666** [comment]
actually just figured out the diagnostic tool was disabled in that profile. I think its all working now

**Comment by laylagordon-666** [comment]
could you just point me towards  when in play mode in unity with the other default profiles, you see the two hands with touch pointer, how can I add those to the defaultXRSDK one?

**Comment by laylagordon-666** [comment]
fixed above with using ARM64.
Still getting these warnings as attached, however I cant see where the depth buffer sharing is set to 24 as I've setthe one in the XR plugin managemnt to 16.
the menu item its suggesting I use to change it, doesn't exist.
<img width="672" alt="Capture-unity-5" src="https://user-images.githubusercontent.com/64796072/83194137-13bee080-a130-11ea-9111-0ef511e753e3.PNG">

**Comment by laylagordon-666** [comment]
fixed the warnings by installing tools. but still getting yhat error after I pause the play button

**Comment by martinwilter** [comment]
@hferrone, FYI, this issue is not related to the tutorials because the tutorials clearly states they are for Unity 2019.2 as earlier mentioned in this thread, i.e. the tutorials do not support Unity 2019.3.X nor Unity's new XR pipeline.

**Comment by hferrone** [comment]
Thanks @martinwilter I'm going to close this one.
