### ISSUE TITLE
when testing, It shows "no connection with database"

### ISSUE THREAD

**Issue by zyb-cn** [MicrosoftDocs/mixed-reality#225]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b4bf8e38-57dc-77f6-22e8-9c157900daa3
* Version Independent ID: 1b4c66e9-49fb-5a35-992f-4352506b20ac
* Content: [集成 Azure 自定义视觉 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-03)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-03.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-03.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@zyb-cn  Please verify that entered connection string of the Azure storage account is correct and valid.

**Comment by hferrone** [comment]
@zyb-cn Is this resolved for you?
