### ISSUE TITLE
Object Detection Manager

### ISSUE THREAD

**Issue by zyb-cn** [MicrosoftDocs/mixed-reality#226]
how to set the Api key,

**Comment by veeruby-developer** [comment]
@zyb-cn  As per the tutorial, please find and locate the Custom Vision Resource of type Cognitive Services(its name followed by -Prediction), There click Keys and Endpoint to retrieve the key and replace the API key present in ObjectDetectionManager (script) where custom vision key is already assigned. if your model has been trained previously now you can detect the Object.
