### ISSUE TITLE
Feature icons have low contrast and aliased borders on Dark theme

### ISSUE THREAD

**Issue by robertos** [MicrosoftDocs/mixed-reality#228]
When viewing the index page for MRTK on the Dark theme, the "Feature areas" icons look aliased and have low contrast. 

To repro:
1. Open https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/
2. Scroll all the way to the bottom
3. On the left part of the footer, select Theme > Dark

Suggestion: make the icons opaque (not transparent), adding a white background in the image.

![image](https://user-images.githubusercontent.com/621574/110248225-b1c1c000-7f78-11eb-8eb8-18494e68c3fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8688c8ff-81f9-705a-24eb-c255e31c54f8
* Version Independent ID: 915f7e31-a006-a871-de27-14f9f87c3244
* Content: [MRTK-Unity Developer Documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/)
* Content Source: [mrtk-unity/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/index.md)
* Product: **mixed-reality**
* GitHub Login: @polar-kev
* Microsoft Alias: **kesemple**

**Comment by hferrone** [comment]
@cre8ivepark Can you help with this?

**Comment by cre8ivepark** [comment]
@hferrone I'll update them. Thanks!
