### ISSUE TITLE
needs "Is Eye Tracked Enabled" on the Pointers Profile!

### ISSUE THREAD

**Issue by kkroesl** [MicrosoftDocs/mixed-reality#2291]
I spent a long time trying to figure out why the eye tracking in my application did not work, even though I exactly followed the tutorials.
Turns out, if you clone all the profiles like described in the tutorials, the default value for "Is Eye Tracked Enabled" on the pointers profile is false.

The following text should be added to the tutorial:

In the Hierarchy window, select the MixedRealityToolkit object, then in the Inspector window, select the Input tab, expand the Pointers section and clone the DefaultMixedRealityInputPointerProfile to replace it with your own customizable Input Pointer Profile.
In the Gaze Settings section, check the Is Eye Tracked Enabled checkbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f19cfc-88a8-2c19-7270-1c2f06b5987c
* Version Independent ID: 48ede813-0968-4618-a587-370f72db289e
* Content: [Getting started tutorials - 6. Exploring advanced input options - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch5)
* Content Source: [mixed-reality-docs/mrlearning-base-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
@kkroesl @hferrone please note that the current tutorials are for MRTK 2.3.0, not MRTK 2.4.0 where this change was introduced.

Ref [Import the Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#import-the-mixed-reality-toolkit):
__
![image](https://user-images.githubusercontent.com/16746283/85478966-174c5880-b572-11ea-9419-57068221696f.png)
__

Tutorials will be updated for MRTK 2.4.0 in the near future.
