### ISSUE TITLE
Please add hand rays voice commands to documentation

### ISSUE THREAD

**Issue by dudziakl** [MicrosoftDocs/mixed-reality#2299]
Please add two missing voice commands in documentation: "show hand rays" and "hide hand rays". They are very useful when working with keyboard/laptop to prevent accidental hand interactions. Near interactions are still available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by evmill** [comment]
@hferrone Some starting hand ray info here. 
https://docs.microsoft.com/hololens/hololens-cortana#built-in-voice-commands
