### ISSUE TITLE
Quad Examples

### ISSUE THREAD

**Issue by LucasSwitz** [MicrosoftDocs/mixed-reality#2303]
I've been working through the native scene understanding documentation and I am missing clarity on how to appropriately use FindCentermostPlacement(). I'm working with a floor quad and have a location within the Quad provided by FindCentermostPlacement(). The coordinates provided appear to be within the Quad plane, but not relative to the center of the Quad plane - rather relative to some corner-anchored origin.

I am unable to find documentation about how to properly orient the Quad plane's axis. The provided page says: "For more detailed information please see our samples on quads which show specific implementations". I cannot find these examples. If these exist, I think it would be helpful to include them in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ada88-8eb6-0e07-0b90-02b8b87179bf
* Version Independent ID: 9bb41118-53ab-73c6-5908-83f0c2334536
* Content: [Scene understanding SDK - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/scene-understanding-sdk)
* Content Source: [mixed-reality-docs/scene-understanding-SDK.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/scene-understanding-SDK.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @SzymonS
* Microsoft Alias: **szymons**

**Comment by SzymonSPS** [comment]
Thanks for the question, we should document this better. 

Yes! The coordinates of the output are relative to the quad in "quad space" with the top left corner being 0,0 (just as it would be with other windows Rect types.) We don't have a usage pattern for this API in our sample (yet) but you can see how quads are generated in the sample "GenerateUnityMeshForSceneObjectQuad" function.

While I obviously can't help debug the code, if the alignment is off, it's most likely just an origin shift from center to top left.

We will be adding a sample of placement in an upcoming revision, so you should get a better reference.
