### ISSUE TITLE
build errrors

### ISSUE THREAD

**Issue by loleklel** [MicrosoftDocs/mixed-reality#231]
[Enter feedback here]
I tried to build the project and deploy to hololens 2 but I got 16 error such as:
How can I deal with these errors?

Reference rewriter: Error: type `System.Web.HttpUtility` doesn't exist in target framework. It is referenced from RestSharp.dll at System.String RestSharp.Extensions.StringExtensions::UrlDecode(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1219)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:209)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Reference rewriter: Error: method `System.String System.Web.HttpUtility::UrlEncode(System.String,System.Text.Encoding)` doesn't exist in target framework. It is referenced from RestSharp.dll at System.String RestSharp.Extensions.StringExtensions::UrlEncode(System.String,System.Text.Encoding).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1219)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:209)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by loleklel** [comment]
Hi,

1. I am using Unity 2019.4.18f1
2. ASA SDK is the 2.7.2
3. I followed the tutorial on docs.


st 10. 3. 2021 v 17:25 odesílatel pamistel <notifications@github.com>
napsal:

**Comment by pamistel** [comment]
Thanks for the response. Since there are multiple tutorials i want to make sure I'm looking at the correct one. Can you link me to the page of the tutorial you followed

**Comment by loleklel** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02

čt 11. 3. 2021 v 15:51 odesílatel pamistel ***@***.***>
napsal:

**Comment by pamistel** [comment]
Hi @loleklel 

Thank you for the clarification. This tutorial is from the MRTK team. We will reach out and ask them to update it.
In the meantime, could I ask you to try the [tutorial ](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal) from the ASA Documentation

**Comment by hferrone** [comment]
Please file a support request to follow up, thanks!
