### ISSUE TITLE
Unity switched to XR Plugin System

### ISSUE THREAD

**Issue by rlbogue** [MicrosoftDocs/mixed-reality#2325]
The documentation for enabling XR is out of date.  mixed-reality-docs/mrlearning-base-ch1.md

**Comment by hferrone** [comment]
@martinwilter Is this addressed?

**Comment by martinwilter** [comment]
@rlbogue @hferrone 

MRTK's support for Unity's new XR pipeline is experimental:

![image](https://user-images.githubusercontent.com/16746283/86956074-63200580-c10d-11ea-8937-1cdc04cd5893.png)

Consequently, we recommend using the legacy system, but if you want to try the XR pipeline, you can refer to the [Getting started with MRTK and XR SDK](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/GettingStartedWithMRTKAndXRSDK.html) guide.

**Comment by rlbogue** [comment]
There is inconsistency here.  Unity is indicating that the currently used system is legacy and will be retired.  However, MRTK has it as experimental.  More importantly, if you use their new framework and try to deploy it to an HL2 it throws an exception (more specifically it hits a developer breakpoint).  Clarity that the new system cannot be used yet would be good.

**Comment by martinwilter** [comment]
I agree, this:

>Clarity that the new system cannot be used yet would be good.

could be made more clear in the MRTK docs and the MRTK release notes.

Not sure it makes sense to mention it in these tutorials though. Readers doing these tutorials, should follow the instructions exactly as provided, as great effort has been put into making it the smoothest possible experience for people just starting out with MRTK and Unity. Providing information about not using the new XR system, might indicate that they don't necessarily need to follow the instructions.

**Comment by hferrone** [comment]
@rlbogue Can you share details on the exception/developer breakpoint?

**Comment by rlbogue** [comment]
I tried to see if I could get a quick repro and I couldn't.  (Don't ask me what's different -- I don't know. I do know the device was being weird -- in and out of the app at the same time (home screen w/o home and yet the profiler.)  Before I literally hit two __debug statements in dissasembly of the unity core.  (I added their symbol servers.)  I must had nudged things just enough to not trigger those same breakpoints again.  I've abandoned using the new XR system for now so I'll likely not hit it again but if I do I'll get a capture.

**Comment by rlbogue** [comment]
@martinwilter  I think that you SHOULD mention it during the tutorial because the reader is likely to believe they should do what the UX tells them to do -- and now it's saying not to use it.  When you couple the out of date screen shots and the product telling you to do something differnet, you're likely to follow it.  Of course, updating screen shots would help.

**Comment by martinwilter** [comment]
Thanks for the feedback, @rlbogue. We are currently not contracted to maintain these tutorials, so my comment was just meant as my two cents :)

The screenshots are not outdated because these tutorials are for unity 2019.2:

![image](https://user-images.githubusercontent.com/16746283/86983448-c4ad9780-c140-11ea-93d1-46df83c0983d.png)

We made this clear distinction because of all the changes in Unity 2019.3 such as new XR pipeline, new editor skin, etc.

We tried to make this clear by using the IMPORTANT tag, but it appears to be missed or ignored quite frequently, so a more suitable tag might be the CAUTION or WARNING tag, @hferrone.

**Comment by hferrone** [comment]
At this point I think we can change the tag to CAUTION @martinwilter.

**Comment by martinwilter** [comment]
@hferrone , are you asking me to make that change for the the four live Unity MRTK tutorials:

- https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base
- https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1
- https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-speechsdk-ch1
- https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1

 and make a PR?

I'm happy to help out with that, on my own time, no problem at all!

But please note, as I mentioned in my last comment on this thread, we - the contracted company - are not currently contracted to maintain or support these tutorials. Regardless, feel free to ping me (as an individual) on any issue that comes up, I'm always happy to help the community if I can!

**Comment by rlbogue** [comment]
@martinwilter Regarding the important tag -- Here's the problem with reading that block.  I interpreted it that you didn't recommend older versions -- not newer versions.  I think that the key point that there is a newer approach that hasn't been fully tested is not transparent.  If we want to block a behavior of someone because we've not tested it, that's something that we want to generally be very clear about.  With regard to the demos, they actually need more than a simple face lift.  The actual steps to get a working demo are now much shorter because MRTK code does most of the configuration for you.  I'm happy to help with the necessary updates as well.

**Comment by martinwilter** [comment]
@rlbogue  You are right, it would benefit the reader to inform them not to use the new XR pipeline.

Yes, the steps for configuring Unity is outdated in the live tutorials, and can easily cause confusion. We have completely redone the Getting Started tutorials and they are ready for release, just needs to be merged in https://github.com/MicrosoftDocs/mixed-reality/pull/2324.

You can access our version here https://github.com/onginnovations/mixed-reality/blob/overhaul-develop/mixed-reality-docs/mr-learning-base-01.md

**Comment by rlbogue** [comment]
@martinwilter Respectfully, they're still not great.  There are steps that shouldn't be included.  for instance TMPPro components -- these will install on the fly when needed.  A new scene doesn't need to be created.  Bit depth doesn't have to be set.  This really needs to be "lean and mean" followed by optimizations and additional recommendations.

**Comment by martinwilter** [comment]
Hi @rlbogue, I appreciate the feedback and discussion around how we can make the steps as smooth as possible for people new to Unity.

One thing to keep in mind is that many other tutorials link to this tutorial so the structure needs to keep that in mind.
<br>

>There are steps that shouldn't be included. for instance TMPPro components -- these will install on the fly when needed.

We believe that for beginners, it's best to give them proactive steps rather than reactive. I.e., we know we are going to use TMP, so let's import it when we import other packages, instead of having Unity prompt us to do it when we happen to add a TMP object to the scene and then having to instruct the readers on how to handle it at that point in the tutorial.

This is particularly important since many other tutorials link to this tutorial. If we don't have the TMP section in this tutorial, every tutorial that link to this tutorial for initial project configuration will have to include instruction re TMP in their tutorials.

We also added the TIP to inform readers that it's not a required step.
<br>

>A new scene doesn't need to be created.

This is also because a lot of tutorials link to this tutorial, so we need the students to make a new scene. We don't know where they are linked from and can't assume they happen to have a new Unity project with the default SampleScene loaded.
<br>

>Bit depth doesn't have to be set.

Do you mean it should be optional or moved to an optimization section?

**Comment by rlbogue** [comment]
@martinwilter 

RE: Proactive/Reactive - the research on adult learning doesn't support your perspective.  Both limiting cognitive load and the fact that people learn only when they need to points to the fact you should only instruct when it's potentially going to bite them.  In the case of TMPPro it's a matter of hitting (figuratively) the "OK" button when you add your first component.  It doesn't break anything else.

Re: Tip for TMPPro - It's in the wrong place.  You say do this then "you might not have to."  It's moot because you really shouldn't be doing this.

Re: Linking from other tutorials - This is bad form.  You should be showing them how to add to the current scene.  Inbound links should create the scene first (but in practicality no one will link to this except as the first step because you're doing the things that have to be done first.)

Re: Bit depth - I mean it should be moved to optimization.

More broadly... think about this as "fastest way to functional" What do you do to get people working?  then add to that "What will bite them if they don't do it?"  It would be GREAT if you could add what happens if you skip the step so that this also can function as a FAQ/debugging document.  For instance, if you don't add Windows Mixed Reality to the XR section you get a 2D window when you build and run it instead of an immersive experience.  Calling out what happens if you skip a step makes it easier for people to debug their work.  (Because I've been building lots of little projects I've missed this particular step a few times.)

Also, be aware that there are two steps that this doesn't cover.  1) Paring your device.  It is a prereq to get VS to deploy but it's not called out well (again, a great place for a reference / reminder / tip).  2) Adding the Unity symbol servers to VS.  Maybe I'm the only one that manages to find unique and interesting ways to crash the player but it's happened multiple times in multiple different ways.  More broadly... setting up the development environment is more than installing VS and downloading MRTK.  what are the other steps to BE READY FOR your first project?

**Comment by mr0ng** [comment]
@rlbogue - Correct. Unity is pushing the new XR system heavily. As Martin mentioned, the new XR system still doesn't work well with HoloLens/MRTK, but things are changing rapidly - so we are monitoring closely. We'll be sure to add a note on the new tutorial updates that adds a little more context for the readers.

Regarding your thoughts on the new tutorials - thanks so much for your review. It's honest feedback like yours that will help improve these tutorials for all users. We will be sure to consider your feedback and integrate/implement. 

Specifically regarding TMP - the tutorials originally didn't have this step. Importing TMP assets on the fly caused a bug in the MRTK where the text would appear too large until the scene was reloaded. I believe this issue may still be outstanding, but I'll double check. Please keep the feedback coming!

**Comment by rlbogue** [comment]
@mr0ng 

Re: New XR system -- Totally get it.  It's worth a simple note that gets pulled from the docs when the technical issues are resolved.  

Re: Thoughts on tutorials - I'm happy to help more directly.  Just need to know how to plug into the process in a way that's helpful vs. creating more forks that cause more work.

Re: TMP on the fly -- This should be a note so that it can be updated when the technical issue is resolved.  Now it's simply not clear why this is necessary (or advisable.)
