### ISSUE TITLE
The king positions might be -260, -40, 0 instead of -26, -4, 0 

### ISSUE THREAD

**Issue by SharkiBoom** [MicrosoftDocs/mixed-reality#2327]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 522f021d-e4ac-5efe-22e6-9a8959b78c16
* Version Independent ID: 422f61eb-0594-e6ea-6566-717ae48e128e
* Content: [2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch2)
* Content Source: [mixed-reality-docs/unreal-uxt-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-haferr**

**Comment by sw5813** [comment]
Hi @SharkiBoom, did you resize the board and King piece properly? I'd be interested to see a screenshot showing where the King ends up on your board with (-260, -40, 0) instead of (-26, 4, 0)
