### ISSUE TITLE
Unity version should be updated to 2019.4.x LTS versus pointing to Unity 2019.2.x version now.

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#2329]
https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1#prerequisites

Unity version should be updated to 2019.4.x LTS versus pointing to Unity 2019.2.x version now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1)
* Content Source: [mixed-reality-docs/mrlearning-base-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-base-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@martinwilter Is this addressed?

**Comment by martinwilter** [comment]
@snakex2000 @hferrone 

These tutorials are for Unity 2019.2 and MRTK 2.3, as stated in the prerequisites:

![image](https://user-images.githubusercontent.com/16746283/86957487-a3808300-c10f-11ea-9c05-2c43b64311bc.png)

and the import MRTK section:

![image](https://user-images.githubusercontent.com/16746283/86957520-b3986280-c10f-11ea-8acd-ca4aba637720.png)

@hferrone, the [new tutorials](https://github.com/MicrosoftDocs/mixed-reality/pull/2324) support Unity 2019.3 and MRTK 2.4.
