### ISSUE TITLE
Missing animation file format version 1.1 specs?

### ISSUE THREAD

**Issue by theolizard** [MicrosoftDocs/mixed-reality#233]
Hello,

MRTK 2.6 claims the motion capture format has changed to version 1.1 and links to this page but this page only details the version 1.0 structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01d77645-a814-700f-c79a-b86e925505ab
* Version Independent ID: a97205c5-1272-3146-8773-6e33238bf28a
* Content: [InputAnimationFileFormat](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input-simulation/input-animation-file-format)
* Content Source: [mrtk-unity/features/input-simulation/input-animation-file-format.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/input-simulation/input-animation-file-format.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by polar-kev** [comment]
@hferrone, here are the version 1.1 updates that should be appended to input-animation-file-format.md.

Section | Type | Notes
-- | -- | --
Has Camera Pose | [Boolean] |  
Has Hand Data | [Boolean] |  
Has Eye Gaze | [Boolean] |  
Camera | Pose Curves | Only if Has Camera Pose is true
Hand Tracked Left | Boolean Curve | Only if Has Hand Data is true
Hand Tracked Right | Boolean Curve | Only if Has Hand Data is true
Hand Pinching Left | Boolean Curve | Only if Has Hand Data is true
Hand Pinching Right | Boolean Curve | Only if Has Hand Data is true
Hand Joints Left | Joint Pose Curves | Only if Has Hand Data is true
Hand Joints Right | Joint Pose Curves | Only if Has Hand Data is true
Eye Gaze | Ray Curves | Only if Has Eye Gaze is true

**Comment by polar-kev** [comment]
@hferrone, I'm not sure why this file wasn't carried over in the migration. The version in the old repo has the 1.1 data,
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/InputSimulation/InputAnimationFileFormat.md
