### ISSUE TITLE
Unable to connect to server with error message on HoloLen 2

### ISSUE THREAD

**Issue by VinsonLeDahu** [MicrosoftDocs/mixed-reality#2336]
Hello,

After completing the chapter 2 in the tutorial [Connecting multiple users](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch2.md) and deploying my app to HoloLens 2, this message was displayed on HoloLens 2 when I launched the app.

Failed to connect to server after testing each known IP.

> I follow the resolution of this issue #2212. But I have still the message.

My development environment is as follows.

Unity 2019.2.17f1
Visual Studio 2019 ( Version 16.6.2 )

How can I solve it ?
 

 
Some features of my project to help you

- I have MSBuild enabled because I can not disabled it : I uncheck the box and I apply the setting, then I open a second time the MRTK configurator ans the Ms build is still checked.

- I do not have the following message when I play my app in Unity :

> PhotonLobby.OnJoinRoom()
> Current room name: RoomNNNN
> Other players in room: 0
> Total players in room: 1

- I have errors in the unity console cause  of the class HttpUtility :

Reference rewriter: Error: type `System.Web.HttpUtility` doesn't exist in target framework. It is referenced from RestSharp.dll at 
> System.String RestSharp.Extensions.StringExtensions::HtmlDecode(System.String).
> UnityEngine.Debug:LogError(Object)

**Comment by hferrone** [comment]
@martinwilter Can you assist here?

**Comment by martinwilter** [comment]
Hi @VinsonLeDahu,

I believe you might be able to resolve this issue by removing Windows 10 SDK build 19041 from your dev environment. 

To do this, launch Visual Studio Installer, click the Modify button, and then, under the **Individual components** tab, search for 'windows 10 sdk' and make sure **only build 18362** is selected:

![image](https://user-images.githubusercontent.com/16746283/86964760-6fab5a80-c11b-11ea-8520-deccfe025ac0.png)

then click the Modify button (in the bottom right corner) to apply the changes.

Regarding your other comments:
<br>

From what you write here:

> * I have MSBuild enabled because I can not disabled it : I uncheck the box and I apply the setting, then I open a second time the MRTK configurator ans the Ms build is still checked.

it sounds like MS Build is not enabled. If you are able to uncheck the option, it's not enabled. If the option is greyed out and you are not able to uncheck it, it's enabled.
<br>

>* I do not have the following message when I play my app in Unity :
>
>>PhotonLobby.OnJoinRoom()
>>Current room name: RoomNNNN
>>Other players in room: 0
>>Total players in room: 1

What message do you see instead? Please provide this information if the above suggestion did not resolve the issue.
<br>

> * I have errors in the unity console cause of the class HttpUtility

You can ignore these errors as long as Unity displays the "Build completed with a result of 'Succeeded' in X seconds" after completing the build process.
<br>

CC @hferrone

**Comment by VinsonLeDahu** [comment]
Hi @martinwilter 
Thank you for your response,

I try to modify Windows 10 SDK visual studio, but Windows 10 SDK 10.0.18362 was already the only SDK selected :
![visual](https://user-images.githubusercontent.com/68011974/87028613-26bcda00-c1df-11ea-9044-a4836f31fb24.PNG)

when I play my app on Unity I have no message displayed

![message mis](https://user-images.githubusercontent.com/68011974/87040324-d484b480-c1f0-11ea-87c7-21d4f2b5f57d.PNG)

For MSBuilt, I try to disabled it on the configurator

![uncheck](https://user-images.githubusercontent.com/68011974/87028986-bc586980-c1df-11ea-8863-9c0eb0520401.PNG)

then I press apply and unity want to reload the scene

![confirmation](https://user-images.githubusercontent.com/68011974/87029001-c24e4a80-c1df-11ea-9dee-dc3864fa8ae4.PNG)

But when I check the configurator it is still checked.

![deuxieme](https://user-images.githubusercontent.com/68011974/87029012-c8dcc200-c1df-11ea-8d48-2b071ffae7f3.PNG)

But when I do this a second there is not the windows to reload the scene.
Futhermore, I let the "enable MSBuild for Unity" box checked and I aplly the settings, there is a loading windows and at the end of this one, there is a MSBuild tool in the Unity menu.

**Comment by martinwilter** [comment]
Hi @VinsonLeDahu,

Thanks for checking the Windows SDK build version and for providing this additional information. I'm not familiar with the 'Kit' part of your Windows SDK, but assume this might just be some location specific naming, do you know?

Regardless, let's first see if we can get Unity to connect to Photon. For that, we shouldn't need to consider MS Build or the Windows SDK.

I should have mentioned this in my previous message, but can you share screenshot of your Console, just in case something has happened to your DebugWindow object so you simply can't see the message. Something like this would be great:

![image](https://user-images.githubusercontent.com/16746283/87098191-9214a500-c1fb-11ea-940e-1a9dd3f1ec7e.png)

__

Here are a few more things you can do to help us debug this:

1. Run your project in Unity with the PUN App ID: `184dd3eb-7b34-496c-a803-a4b64d4f32f3`, and let me know if that makes any difference? This is the ID we are using for testing, so we know it works.

2. Clone our repo and check out tag [multi-user-capabilities-v2.3.0.0](https://github.com/microsoft/MixedRealityLearning/tree/multi-user-capabilities-v2.3.0.0), then run the project in Unity using the App ID mentioned above, and let me know if you are able to connect to Photon from that project?

3. If you are able to share your Unity project with me, preferably via GitHub, I can take a quick look and see if I spot something unusual in your project.

4. Run the PUN demo to see if you can connect to Photon. You can access the demos from the Unity menu Window > Photon Unity Networking > Configure Demos (build setup), then enter game mode and load the Basic Tutorial. If successful, your Unity should look similar to this:

![image](https://user-images.githubusercontent.com/16746283/87099432-93939c80-c1fe-11ea-8a61-4e75ddc5aef6.png)

**Comment by VinsonLeDahu** [comment]
Hi @martinwilter

First I tried to uninstall and install Windows 10 SDK again, and it was the same name.

So this is the screenshot of my console when I use your PUN appID. I have the same console with my appID :

![console](https://user-images.githubusercontent.com/68011974/87157098-fc8e1980-c2bd-11ea-99a1-3c5886463734.PNG)

then I try to run your project, and I get this :

![son projet](https://user-images.githubusercontent.com/68011974/87156853-a1f4bd80-c2bd-11ea-8382-223527cbf973.PNG)

Finally I did not succeed to connect with the pun demo :

![4](https://user-images.githubusercontent.com/68011974/87156930-be90f580-c2bd-11ea-9ddb-584a39dd0e61.PNG)

**Comment by martinwilter** [comment]
Hi @VinsonLeDahu, you don't really need to build now, since PUN itself is not working, I recommend first focusing on getting PUN to work in the Unity editor.

The screenshot of our project running looks correct except that PUN isn't called at all.

Can you show me the complete log for the two errors you receive when running the demo?

Since this issue (at least the first one that needs to be resolved), is a Photon PUN issue, I also recommend reaching out to their team for support https://forum.photonengine.com.

**Comment by VinsonLeDahu** [comment]
Hi @martinwilter

I found a talk where it says to uninstall all Windows 10 SDK except build 18362. So I did it and I have no more the console message :
`Failed to connect to server after testing each known IP.`

And I have the correct message on the HoloLens :
```
PhotonLobby.OnJoinRoom()
Current room name: RoomNNNN
Other players in room: 0
Total players in room: 1
```

But I still have any message on the game window of unity and the pun demo does not work with the console message :

![pun](https://user-images.githubusercontent.com/68011974/87593810-53e01f80-c6ec-11ea-9220-5ae4f71b3a71.PNG)

I left a message on pun forum but I think it comes from my network : it is a secure one on my PC and I access the internet through my phone on hololens side. I will be able to test the app with two HoloLens soon so I could tell you.

**Comment by martinwilter** [comment]
Hi @VinsonLeDahu, thanks for the update. Glad to hear you were able to get it working on your HoloLens 2.

> I access the internet through my phone on hololens side

Maybe you can try to connect your PC to your phone's hotspot?

I came across this thread where several different solutions for similar issue are suggested: https://forum.photonengine.com/discussion/12341/connecting-to-master-server-works-in-build-but-not-editor, maybe one of them will work for you.

**Comment by hferrone** [comment]
@martinwilter Can this one be closed, or does it need more support?

**Comment by martinwilter** [comment]
@hferrone, if we can keep the issue open for a few more days, that would be great.

Although this seems to be a Photon/local network issue, I think it will benefit the community if VinsonLeDahu reports his findings re getting Photon to work on his computer.

**Comment by hferrone** [comment]
@martinwilter Roger that, no problem :)

**Comment by hferrone** [comment]
@VinsonLeDahu Did this help fix your issue? I'm going to close this for now, but if you have any more problems please comment them and I'll reopen!
