### ISSUE TITLE
Minor fixes to this documentation page

### ISSUE THREAD

**Issue by Nuno-Monteiro** [MicrosoftDocs/mixed-reality#2337]
On the Reprojection chapter, where it says:
Depth Reprojection: The application submits their depth buffer to the system for every rendered frame. On Unity, this is done with the "Enable Depth Buffer Sharing" option in the Player Settings pane. DirectX apps call CommitDirect3D11DepthBuffer. The application should not call SetFocusPoint.

=> the option is actually called "Shared Depth Buffer" and it's not on the player settings pane but instead on Windows Mixed Reality Settings pane under XR Plugin Management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874d6e8e-dd9a-f355-5025-b7a1804ffcbe
* Version Independent ID: d3d8b319-459e-357d-52c2-823daeadda6d
* Content: [Hologram stability - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hologram-stability#reprojection)
* Content Source: [mixed-reality-docs/hologram-stability.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hologram-stability.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
Thanks @Nuno-Monteiro for the heads up!
