### ISSUE TITLE
Scene Understanding SDK link is broken

### ISSUE THREAD

**Issue by jdm** [MicrosoftDocs/mixed-reality#2340]
https://github.com/MicrosoftDocs/mixed-reality/blob/openxr-102/mixed-reality-docs/openxr.md#roadmap contains a link to https://github.com/MicrosoftDocs/mixed-reality/blob/openxr-102/mixed-reality-docs/scene-understanding-sdk.md, but that link is a 404.

**Comment by hferrone** [comment]
@jdm The links you provided are still a draft and have not been published yet.
