### ISSUE TITLE
Holographic Remoting connecting via Unreal Editor but not receiving frames on Hololens 2

### ISSUE THREAD

**Issue by lmistades** [MicrosoftDocs/mixed-reality#2346]
Hi,

I'm trying to get Holographic Remoting to work in Unreal 4.25 and for some reason the Hololens 2 establishes a connection and is able to control the running game with movement and is transmitting audio but is not rendering or mirroring any frames to the device itself. enabling diagnostics shows a running frame rate but with 0 frames being received.

Both desktop and hololens 2 is updated to the latest version and are both able to connect to each other via device portal.

![20200708_232116_HoloLens](https://user-images.githubusercontent.com/50820284/87010592-5aa4f900-c1f9-11ea-936c-5f0007cd9b0f.jpg)

Thanks

**Comment by hferrone** [comment]
@martinwilter Have you run into this issue with the Holographic Remoting tutorial updates?

**Comment by martinwilter** [comment]
Hi @hferrone, I haven't worked on or tried the Holographic Remoting tutorials. Also, I haven't worked with Unreal for several years now.

Maybe @varunsiddaraju has some suggestions? Although, I don't believe he works with Unreal either.

**Comment by varunsiddaraju** [comment]
Hi @hferrone: We worked on Unity Holographic Remoting and haven't tried it on Unreal.

**Comment by fieldsJacksonG** [comment]
@lmistades Do you see any warnings or errors in your Output Log while remoting?

Can you filter the Output Log by LogWmrHmd and copy here?

**Comment by mr0ng** [comment]
@lmistades - this is fairly common and I've experienced this with remoting, regardless of Unity/Unreal. I've noticed it on laptops and any computers that doesn't use a good GPU. For example, on my Surface Book, I need to ensure that the app is running off the dedicated GPU and not the internal GPU for it to work. Do you know what hardware you're running?

**Comment by mr0ng** [comment]
Not sure if this is helpful, but I've heard this come up as a suggestion: "Make sure you have HEVC encoder installed on Windows."

**Comment by lmistades** [comment]
I'll try the suggestions out. I'll try providing an output log from the device portal and checking if HEVC encoder is installed.

As for my hardware, I'm using the following specifications:

CPU: Ryzen 7 1700, 8 cores 16 threads
GPU: Sapphire Radeon RX 580 Nitro Plus Limed Edition 1450MHz 8GB GDDR5

**Comment by lmistades** [comment]
I've checked my output log while connected via Holographic Remoting and got the following results when filtering with logwmrhmd:

![image](https://user-images.githubusercontent.com/50820284/87165500-d0de5400-c2fc-11ea-9329-0786d654a9e2.png)

![image](https://user-images.githubusercontent.com/50820284/87165543-e0f63380-c2fc-11ea-80d7-d13264717bc1.png)

**Comment by lmistades** [comment]
Just closing this issue as I've received help from Microsoft via another channel. I was able to resolve the issue by doing a complete uninstall and reinstall of all AMD drivers. Receiving remoting frames now both via builds and the Unreal editor

Thanks

![Test](https://user-images.githubusercontent.com/50820284/87411408-43e81300-c5fa-11ea-8c02-c5a403bb00b6.jpg)
