### ISSUE TITLE
Reverb G2

### ISSUE THREAD

**Issue by bongistka** [MicrosoftDocs/mixed-reality#2351]
[Enter feedback here]
Hi,
will this still work if we use Reverb g2 and omit the Mixed Reality Portal altogether, using its built-in SteamVR compatibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f0765a-3f92-5214-4bcd-2f5ad9d93c1a
* Version Independent ID: 7f34bdfd-70ca-1922-4858-3379ed1c9068
* Content: [Mixed Reality Spatial Data Packager Documentation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixedrealityspatialdatapackager)
* Content Source: [mixed-reality-docs/mixedrealityspatialdatapackager.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixedrealityspatialdatapackager.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @alfred-msft
* Microsoft Alias: **yuripek**

**Comment by hferrone** [comment]
@yuripek Can you shed some light on this question?

**Comment by bongistka** [comment]
We have Location-Based virtual reality product where we need our users to see each other virtually in their actual position. We use Mixed Reality Spatial Data Packager and the Windows insider builds' map manager feature to share spatial data between the currently sold HP Reverb headsets which use Mixed Reality Portal. Our app is SteamVR-based so in addition to that we use SteamVR and Mixed Reality for SteamVR. It is said, that the next generation of HP Reverb headsets is to be SteamVR compatible, and we plan to use this feature in order to simplify our currently too vulnerable setup which is depending on too many 3rd party components. Our question is: will we be still able to share spatial data between our new Reverb devices if we start using the newly obtained SteamVR compatibility once we switch to Reverb Gen2?

**Comment by yuripek** [comment]
Hello @bongistka , I was incorrectly tagged as an owner of this feature. I am following up through internal channels trying to locate the correct owner...

**Comment by jessemcculloch** [comment]
Hi @bongistka,

I checked with the program manager in charge of our VR platform, and they informed me that the HP G2 does not bypass the Mixed Reality Portal. Upgrading to the G2 headsets will not change the setup that you are currently using.

**Comment by snakex2000** [comment]
@bongistka   Question for you,  is there is a reason still using the old Mixed Reality Spatial Data Packager tool?   

The new Mixed Reality Portal is public now  and released with Windows 10  2004 release with the map manager.  Just checking since the tool was "as-is"  and now should be able to stop using the tool.

**Comment by bongistka** [comment]
Thank you, we already took notice of that. So just to be clear; map manager
should be now sufficient tool to share spatial data between devices? No
Spatial data packager needed? What about the map file, do we need to create
a new one?

Thanks a lot!

št 16. 7. 2020 o 18:54 snakex2000 <notifications@github.com> napísal(a):

**Comment by bongistka** [comment]
Just to clarify my answer a bit more, we did try the map manager without
the spatial data packager tool but that yielded poor results. The only way
to make it work for us was to combine both of the tools. But now the map
manager feature is finally out of insider preview so we might as well give
it another try.

št 16. 7. 2020 o 22:41 Barbora Darmová <darmova@gmail.com> napísal(a):

**Comment by snakex2000** [comment]
Thanks Barbora!  Would definitely test with the new Windows 10 2004 released UI now.   We have had success with LBE operator who is just using the portal now without the tool now.   If do hit something, feel free to ping me (Nathan or Carlos) in support to look at further.

**Comment by bongistka** [comment]
Hi,

we did test the portal and the "Export System Map & Anchors" function
worked just fine (exactly as in the insider build), so did the Importing of
map and anchor files saved on the device. But the "Export System Map &
Spatial Mapping Database" did throw the following error:
[image: Výstřižek.JPG]
this is exactly the same error we used to get when we were in insider.
Needless to say, the headset was not sleeping. Do you know how to get past
this error? Or is system map & anchors sufficient for shared space
tracking? In our experience, the shared space tracking using only a system
map & anchors was relatively good in the center but as users moved towards
the edges of our space, their maps became less and less synchronized (which
was fixed by using the spatial data packager).

Best,
Barbora


po 20. 7. 2020 o 21:31 snakex2000 <notifications@github.com> napísal(a):

**Comment by yuripek** [comment]
@bongistka , unfortunately I cannot see the error message image. Can you please type it as text?

**Comment by bongistka** [comment]
Hi the message is:



*localhost:50080 says*
*Failed to export the spatial mapping database and system map, check if*
* the device is sleeping*

Best,
Barbora

ut 21. 7. 2020 o 19:57 Yuri Pekelny <notifications@github.com> napísal(a):

**Comment by yuripek** [comment]
Thank you for the error message! The "Export System Map & Spatial Mapping Database" functionality is supported only by Microsoft HoloLens devices. For Microsoft Mixed Reality, please use the Export and Upload functionality for System Map and Anchors only.

**Comment by bongistka** [comment]
Hi,
Thank you that was very helpful information. Is the map manager from the
portal documented? We tried what you suggested and it worked. The result is
a bit less precise but very stable and easier to set up overall we are very
satisfied with it. One last thing, is it possible to prevent mixed reality
from creating a new map on the startup, sort of a "lock map" feature like
it was in the spatial data packager? Thanks a lot!

Best regards,
Barbora

st 22. 7. 2020 o 3:00 Yuri Pekelny <notifications@github.com> napísal(a):

**Comment by yuripek** [comment]
There is no official documentation for Mixed Reality MapManager yet. You should be able to use the LockMap feature of MRSpatialPackagerHelperScript.ps1 to lock your map if you comment out the script line that calls Start-Process MixedRealitySpatialDataPackager.exe.
