### ISSUE TITLE
Need to replace titles from "MixedRealityPackager.exe" to "MixedRealitySpatialDataPackager.exe"

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#2360]
Need to replace titles in the docs from "MixedRealityPackager.exe" to "MixedRealitySpatialDataPackager.exe" to match the tool name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f0765a-3f92-5214-4bcd-2f5ad9d93c1a
* Version Independent ID: 7f34bdfd-70ca-1922-4858-3379ed1c9068
* Content: [Mixed Reality Spatial Data Packager Documentation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixedrealityspatialdatapackager)
* Content Source: [mixed-reality-docs/mixedrealityspatialdatapackager.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixedrealityspatialdatapackager.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @alfred-msft
* Microsoft Alias: **yuripek**

**Comment by jessemcculloch** [comment]
Github is having an issue with merging right now, but as soon as I can merge the linked PR, this will be resolved.
