### ISSUE TITLE
Link to Text Prefab in MRTK is broken

### ISSUE THREAD

**Issue by rlbogue** [MicrosoftDocs/mixed-reality#2366]
the link to Text Prefab in MRTK (bottom of article) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9f9ed3-b6cd-2a1c-c106-fd719dbfb624
* Version Independent ID: 507bf69d-3d81-4ac1-5106-c677e29ce7f0
* Content: [Text in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity)
* Content Source: [mixed-reality-docs/text-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/text-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
Thanks @rlbogue!
