### ISSUE TITLE
Voice commands language

### ISSUE THREAD

**Issue by jpevolutis** [MicrosoftDocs/mixed-reality#2371]
Hello,

You say that "speech commands will always run in the system's display language".
Does it mean that if my app is in English with English voice commands, but the user has changed its Hololens settings to Spanish, my voice commands won't work at all ?

This is kind of unpredictable.
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by hferrone** [comment]
Hi @jpevolutis , that's correct. The OS settings are key. More specifically, if an app tries to create a Spanish speech recognizer while the OS is set to English, it will fail.
