### ISSUE TITLE
Project builds and deploys to HoloLens 2 Does Not Work as Expected

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#2377]
I followed the directions with current (7/17/2020) Unity and mixed reality tool kit. I do not get any hand indicators or any type of mesh. All I get is the scene and a dot in the center of the view field. This is my second attempt. In the first attempt I continued through the tutorials building the menu, which did appear but without any hand or other input, nothing works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
Hi @laultman,

Can you check that you are using the DefaultMixedRealityToolkitConfigurationProfile:

![image](https://docs.microsoft.com/en-us/windows/mixed-reality/images/mr-learning-base/base-02-section6-step1-3.png)

**Comment by hferrone** [comment]
@laultman Did this fix your issue?

**Comment by hferrone** [comment]
@laultman Hopefully we haven't heard from you because this fixed your issue. I'm closing the issue, but if you have any more problems please comment them on the thread and i'll reopen it!
