### ISSUE TITLE
Hololens 1 doens't connect to database

### ISSUE THREAD

**Issue by NedumaranDuriraju** [MicrosoftDocs/mixed-reality#2378]
Hi,

Here i follow this tutorial https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-azure-02 and deployed into hololens 1.
In unity, I am able to connect to azure storage using connection string.  However in hololens, it keep showing "no connection to database".  on Debug windows, it showed "Fail to connect azure storage, and stated about storage emulator default setting"
on hololens, i go to microsoft edge, it do have internet connected, but not in app.

Any step that i missed and cause it doesn't connect to azure storage?

Unity Setting, Internetclient, internetclient server all checked. 

your help is much appreciated! thank you

**Comment by hferrone** [comment]
@martinwilter Was this one of the updated docs?

**Comment by martinwilter** [comment]
@hferrone, this is the new (not updated) Azure Cloud Services tutorials.

I believe @varunsiddaraju, is already looking into this issue.

**Comment by davidlyw89** [comment]
hi @martinwilter @hferrone 

So do I need to wait for updated documentation for this issue? Not connected to database

**Comment by hferrone** [comment]
@davidlyw89 Yes, were looking into the issue and will update the documentation if needed.

**Comment by rubit0** [comment]
Does your connection string point to an Azure storage Emulator instance that runs on your local PC? If so, then your HoloLens can't connect to that and you must create an Azure storage account in Azure.

**Comment by davidlyw89** [comment]
Hi, 

For latest update.  
It solved by updating Hololens software.
https://support.microsoft.com/en-au/help/12379/windows-10-mobile-device-recovery-tool-faq

Currently Hololens Version
Version Windows Holographic
OS Build:  10.0.17763.1339
Firmware: 0005.05.S.1801091036R

**Comment by hferrone** [comment]
@varunsiddaraju @martinwilter Is there an update on this or can it be closed?

**Comment by varunsiddaraju** [comment]
@hferrone Yes, this can be closed.
