### ISSUE TITLE
Incorrect panel name

### ISSUE THREAD

**Issue by HiromuKato** [MicrosoftDocs/mixed-reality#2398]
The text below is 'My Blueprint panel', not 'Details panel'.(And I don't think you need to scroll.)

> Scroll to the Variables section in the Details panel, click the + button and name the variable WhiteKing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-haferr**

**Comment by HiromuKato** [comment]
![MyBlueprint](https://user-images.githubusercontent.com/5102264/88592972-d0ceaa00-d099-11ea-881f-09bcc93ad8ca.png)

I think 'My Blueprint panel', not 'Details panel'. Is it wrong?

**Comment by hferrone** [comment]
Not at all @HiromuKato , the docs will be updated today.

**Comment by HiromuKato** [comment]
I saw the following commit, but it didn't seem to change from the Details panel.
https://github.com/hferrone/mixed-reality/commit/1dad52f34caee6032d3d62c552745465d354806a

**Comment by hferrone** [comment]
@sw5813 Is this correct?

**Comment by sw5813** [comment]
Yes, it looks like @HiromuKato is correct. Thanks for catching this! This line should read: "In the **My Blueprint** panel, navigate to the **Variables** section , click the + button and name the variable WhiteKing."

Then the first bullet should be preceded with "In the Details panel, ..."
