### ISSUE TITLE
Unable to click the 'search bar' to type.

### ISSUE THREAD

**Issue by aprilspeight** [MicrosoftDocs/mixed-reality#2401]
The instructions for **Writing and reading data from Azure Table storage** state that to click on the **search bar** and type in a name. I cannot 'click' on the search bar when viewed with a HL2. I took a picture which shows my finger going through the holographic search bar. No keyboard appears for me to type. I'm unable to attach the image to this issue but can share on Teams with whoever triages this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15853f4-20ac-bea9-89b0-4cd7da19a5be
* Version Independent ID: 398529a4-fee0-21bb-6cc6-b57b47d25ea1
* Content: [Azure Cloud Tutorials - 2. Integrating Azure storage - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-azure-02)
* Content Source: [mixed-reality-docs/mr-learning-azure-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-learning-azure-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@martinwilter Can you assist?

**Comment by varunsiddaraju** [comment]
The "search bar" currently doesn't support the near interaction, we should use far interaction and use the pointer to select the "search bar" and use the keyboard to enter the text. We will add a note about this in the tutorial so that it will be more clear.

**Comment by hferrone** [comment]
Thanks @varunsiddaraju - please comment "Closes #2401" when you commit the changes so this is tracked.

**Comment by aprilspeight** [comment]
Thanks @varunsiddaraju !
Does this mean that the functionality is already in place as-is? Or should I wait until the tutorial is updated to try again?

**Comment by aprilspeight** [comment]
@varunsiddaraju disregard my last comment - I see what you mean. Just tried it out as a far interaction with the pointer and it works. Thanks again!
