### ISSUE TITLE
HoloLens 2 Tutorials Do Not Work Using Current Tooling (VS 2019 and Unity)

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#2402]
I have followed the "Getting started tutorials" starting over from the beginning several times to ensure that I follow every step explicitly. The Mixed Reality Toolkit does not work as expected or described. There are many issues with the tool/documentation. On this step for instance the major functionality Tap to Place does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a77974e-95c6-8d98-08de-53c55ecf8600
* Version Independent ID: d60ba94b-87b2-6be0-1675-f4b2114b7bbd
* Content: [Getting started tutorials - 5. Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @laultman, 

Can you provide the exact Unity version you're using?
