### ISSUE TITLE
The diagram in "Project Settings" doesn't match the text.

### ISSUE THREAD

**Issue by HiromuKato** [MicrosoftDocs/mixed-reality#2406]
The text is written as follows, but in the figure the red square is not drawn for the item "Mobile/Tablet".

> Set C++, Scalable 3D or 2D, Mobile/Tablet, and No Starter Content as your Project Settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 522f021d-e4ac-5efe-22e6-9a8959b78c16
* Version Independent ID: 422f61eb-0594-e6ea-6566-717ae48e128e
* Content: [2. Initializing your project and first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch2)
* Content Source: [mixed-reality-docs/unreal-uxt-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/unreal-uxt-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-haferr**

**Comment by hferrone** [comment]
@HiromuKato Thanks for catching this!
