### ISSUE TITLE
There's no mention in documentation of how to use TeleportHotSpots

### ISSUE THREAD

**Issue by vrobel** [MicrosoftDocs/mixed-reality#241]
Hi, I can't seem to find any info about how to properly implement TeleportHotSpot. How I approached it was to place an object with a collider on it and to add TeleportHotSpot component. Implementation suggests it only accepts TeleportPointers but ParabolicTeleportPointer seems to ignore my hot spots and the pointer hides when I'm over my hotspot area.

EDIT: Noticed that I needed to update my setup. I'm using Oculus Quest 2 with Hand Tracking (Articulated Hand Controller). Also noticed it works fine and as expected with controllers. I should file a separate bug report as the hotspot gets recognized for a frame and immediately it gets unfocused next frame. I'm using MRTK 2.5.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab379974-9f28-0380-3b0a-b8ee5f83948c
* Version Independent ID: f7dfa238-a18a-3019-2f1d-7b7de6964199
* Content: [TeleportSystemOverview](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/teleport-system/teleport-system)
* Content Source: [mrtk-unity/features/teleport-system/teleport-system.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/teleport-system/teleport-system.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by polar-kev** [comment]
@RogPodge, is this a docs gaps or are there instructions we can point to?

**Comment by RogPodge** [comment]
@polar-kev yeah we're currently missing documentation (and unit testing!) on this feature. I think it was included when the teleport system was still in experimental, and when it was graduated, we never properly vetted the teleport hotspot feature.

I'm somewhat booked at the moment but I can handle graduating this particular aspect of the Teleport system in a future release!
