### ISSUE TITLE
Does not specify supported/required hardware for this feature

### ISSUE THREAD

**Issue by Betterlife-exe** [MicrosoftDocs/mixed-reality#243]
This page does not say if this works with all WMR compatible base stations and WMR headsets with Inside-Out tracking, or which devices that specifically support this feature. Unity's openXR "Microsoft Hand Interaction Profile" interaction feature only lists Microsoft HoloLens 2, and this page says nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cce8b2-209f-abe2-f91a-ca7dfd93a2e8
* Version Independent ID: f6706015-a42a-2090-7625-7045ea115597
* Content: [Hands and motion controllers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/design/hands-and-tools)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/hands-and-tools.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/design/hands-and-tools.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @shengkait
* Microsoft Alias: **shentan**

**Comment by hferrone** [comment]
@keveleigh Any ideas here?

**Comment by yl-msft** [comment]
@Betterlife-exe , thanks for the feedback.  We are in progress to write a new version of this page in near future to address questions like this.  For your specific question, the "openxr hand interaction profile" will support on WMR controllers on PC VR as well, if you limit to just the "air-tap and aim pose" for far objects, and "grasp and grip pose" for direct manipulation.
