### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/mixed-reality#244]
Reading the very first HoloLens tutorial and find gaps in the documentation.

This picture shows what should be done:
![image](https://user-images.githubusercontent.com/1756871/111878003-55ae6100-89a6-11eb-8c94-1243834eacd9.png)

This picture shows what can be done:
![image](https://user-images.githubusercontent.com/1756871/111878019-75de2000-89a6-11eb-9f46-858af2e1e413.png)s
Points 4 and 5 do not make a sense.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [HoloLens (1st gen) Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/holograms-100)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/holograms-100.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
Hi @ddobric - thanks for posting. Per the note at the beginning of the tutorial, these articles are not updated. Please see the HoloLens 2 content :)
![Uploading Screen Shot 2021-03-22 at 9.42.14 AM.png…]()

**Comment by ddobric** [comment]
@hferrone  I think this a misunderstanding. The tutorials are NOT as they have been before. Years ago, it was possible to build applications with these tutorials I agree they can remain, but I think all tutorials MUST deliver useful information.
The comment above is ok, if it would be right. But, you didn't leave tutorials as they have been before. They are changed in a way that nobody needs. Right now, tutorial(s) is simply wrong. They refer to the wrong version of Unity, describing UI elements that not exist etc.

For the case of misunderstanding, could you please point to a tutorial that describes how to work with HL1 and the tutorial for HL2.

My suggestion is, somebody from the doc team should simply start doing demos step by step as they are described.

**Comment by hferrone** [comment]
Hi @ddobric, I completely agree. However, these HL1 tutorials are made with Unity 2018, which means they are correct for that older version. We're in the process of working through these to determine their accuracy and value. At the moment, we have these HL2 tutorials available that are up-to-date: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials#hololens-2

**Comment by keveleigh** [comment]
>However, these HL1 tutorials are made with Unity 2018

Even older for some of them! Much of the 200-level courses were originally made with Unity 5.4 and were only updated through Unity 2017.2.1p2.

**Comment by ddobric** [comment]
@keveleigh, I only recommend somebody should step through tutorials and check if it works :)
I have posted the issue here after I received a lot of complaints. Then I tried it step by step, It does not work. There so no clear separation between HL1 and HL2 tutorials especially regarding the Unity version.
In my opinion, this has to correct. There are lot of people out there who invested in HL1, which is not the cheapest device on the market. 
When somebody starts playing with HL (in this case HL1) there is no second chance for the first impression.

**Comment by keveleigh** [comment]
>I only recommend somebody should step through tutorials and check if it works

Are you saying they don't work with the version of Unity they're built for?

>There so no clear separation between HL1 and HL2 tutorials especially regarding the Unity version.

That's true, there's no clear message about the newest version of Unity they're compatible with. @hferrone maybe we should add a tag like "this tutorial was designed for Unity 2017. Newer versions may not be compatible".

**Comment by ddobric** [comment]
> Are you saying they don't work with the version of Unity they're built for?

Yes, by following tutorials the wrong version of Unity is installed. The new one has also some compiling issues related ti mixed reality SDK. The tutorial describes something that cannot be found in the Unity (at least in that version).
It is totally wired. Forums are full of questions related to that issue.

> That's true, there's no clear message about the newest version of Unity they're compatible with. @hferrone maybe we should add a tag like "this tutorial was designed for Unity 2017. Newer versions may not be compatible".

I have no recommendation what is the best way, because I do not know what is supported by newer Unity.
But, there is a simple expectation.
The newer version of tutorials and all related tools should usually support older version. This was always been "the Microsoft feature". If this is not the case then please make this understandable before reader start doing the tutorial.  
If HL1 is not supported by new tools, then bring back the old tutorial as it was years ago. That one was good one. If HL1 is supported to some sort then please describe how.
