### ISSUE TITLE
Pulse mat black color

### ISSUE THREAD

**Issue by haraldsamson** [MicrosoftDocs/mixed-reality#245]
Hello,

First issue, in the demo scene the default color of MRTK_Pulse_SpatialMeshBlue.mat is opaque black, is there a way to turn this base color to transparent ?

Second issue, In the following text from the web page, the names of the textures are inverted between spatial mesh and hand mesh  :

> **Prerequisites**
> For the spatial mesh example, ensure that MRTK_Pulse_ArticulatedHandMeshBlue.mat or MRTK_Pulse_ArticulatedHandMeshPurple.mat is assigned under MRTK Settings -> Spatial Awareness -> Display Settings -> Visible Material.
> 
> For the hand mesh example, ensure that MRTK_Pulse_SpatialMeshBlue.mat or MRTK_Pulse_SpatialMeshPurple.mat is assigned in ArticulatedHandMesh.prefab, which itself should be assigned in MRTK Settings -> Input -> Hand Tracking -> Hand Mesh Prefab.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: de0712a2-2861-f717-a3af-925faa17b5ba
* Version Independent ID: c9a3af22-6b69-ef44-4bab-21bf7b50a459
* Content: [PulseShader](https://docs.microsoft.com/fr-fr/windows/mixed-reality/mrtk-unity/features/rendering/pulse-shader)
* Content Source: [mrtk-unity/features/rendering/pulse-shader.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/rendering/pulse-shader.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by hferrone** [comment]
@CDiaz-MS Any updates here?

**Comment by haraldsamson** [comment]
Issue is still running

**Comment by hferrone** [comment]
@CDiaz-MS Is this fix still coming?

**Comment by CDiaz-MS** [comment]
@hferrone Yes the fix for the docs is coming soon and @haraldsamson I am currently investigating the SR_Triangles shader to see if we could surface a way to change that default color.
