### ISSUE TITLE
Build errors when attempting multiplayer

### ISSUE THREAD

**Issue by SheehanC1** [MicrosoftDocs/mixed-reality#246]
While following the multiplayer for HoloLens 2 tutorial, I got to the part where you test if you can see the "PhotonUsers", one in the headset, the other in Unity (the very bottom of 3.Connecting multiple users). I tried to make the build for the headset in order to test but ran into 15 errors. They don't stop the build from being made, but running the build on the HL2 always results in an immediate crash of the app.

![image](https://user-images.githubusercontent.com/45801579/112027237-60cfd100-8b0d-11eb-82fe-40f706ebdf3c.png)

After experimenting, I deleted the MRTK.Tutorials.AzureSpatialAnchors folder and tried again and the build succeeded without errors, so I think the issue may lie somewhere in there. The build would run in the headset but running it in the headset and Unity does not result in them connecting and being able to see each other(This may be a separate issue but still wanted to include just in case).

I also realized this is extremely similar to this [issue with azure](https://github.com/MicrosoftDocs/mixed-reality/issues/231). 

Tested/Experienced with:
Unity 2019.3.13 and 2019.4.0
MRTK 2.5.1 and 2.6
Azure Spatial Anchors SDK "Core" and "for Windows" 2.7.1
AR Foundation,  3.1.3
AR KIt XR Plugin 3.1.3
AR Core XR Plugin 3.1.3
Windows Mixed Reality 4.2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06547a84-546e-2da3-3715-1df2bd40d206
* Version Independent ID: 56001e11-25bd-b4cc-5ad0-62cac6e01081
* Content: [Connecting multiple users - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-03)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-03.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-03.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by oafolabi-msft** [comment]
Hi @SheehanC1, I would like to get some more information about the problem. Since you mentioned that it is similar to the issue with azure (#231), I would like to know I you were able to successfully run that tutorial?

**Comment by SheehanC1** [comment]
Hi @oafolabi-msft, after following the [Getting Started with Azure Spatial Anchors](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02) tutorial I got what looks to be near identical errors logged with my original build errors and quite similar with the [231](https://github.com/MicrosoftDocs/mixed-reality/issues/231) issue

![image](https://user-images.githubusercontent.com/45801579/112204425-08223600-8bea-11eb-8cc6-db06bd88cfb8.png)

**Comment by hferrone** [comment]
@varunsiddaraju is this an issue with the tutorial or something else? @mr0ng for visibility

**Comment by varunsiddaraju** [comment]
@hferrone Looks like it's an issue related to an asset package that was shared with the tutorials.
We will look more into it.

**Comment by mr0ng** [comment]
Thanks @varunsiddaraju

**Comment by hferrone** [comment]
Any updates here @varunsiddaraju @mr0ng

**Comment by varunsiddaraju** [comment]
We are working on replace Resharp.dll with unity web request API’s.

We will be sharing the updated tutorial packages soon.

**Comment by hferrone** [comment]
@varunsiddaraju Any updates on this?

**Comment by veeruby-developer** [comment]
Hello Harrison,

We are still working on replacing Restsharp.dll with Unity WEB Request for Uploading files.


Will keep you updated.

Regards,
Varun Siddaraju

**Comment by polar-kev** [comment]
This is now fixed.
