### ISSUE TITLE
Device Portal Simulation Tab

### ISSUE THREAD

**Issue by mfdursun** [MicrosoftDocs/mixed-reality#250]
Hello,

According to the document in simulation tab there are 4 different choises on the tab. However there are only upload recording and control mode options. **What is the data type for that recording? How may I record such thing?**  How to get recording and use it on the device?

![Capture](https://user-images.githubusercontent.com/81554132/112802445-dd692f00-907a-11eb-9516-b83e0e58a74e.PNG)

Thank you,

#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/tr-tr/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by hferrone** [comment]
Hi @mfdursun - You can record using the HoloLens device and then use that in the Emulator. The format is xref. Thanks!
