### ISSUE TITLE
The MixedRealityToolkit has no children and does not report an error

### ISSUE THREAD

**Issue by iluvian** [MicrosoftDocs/mixed-reality#251]
[在此处输入反馈]
![image](https://user-images.githubusercontent.com/39895100/112806714-ac542300-90a9-11eb-8551-0c597358e60a.png)

Follow the steps of the document, no error is shown, cannot be resolved

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [初始化项目并部署第一个应用程序 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@iluvian MixedRealityToolkit with no child Objects is correct.

**Comment by hferrone** [comment]
@veeruby-developer Can you update the screenshots or send me correct ones?

**Comment by iluvian** [comment]
> @iluvian MixedRealityToolkit with no child Objects is correct.
> the Screenshots with child object for MixedRealityToolkit is from the older MRTK versions.
The version numbers I used were MRTK2.5.3，Unity 2019.4.8，Is this an older one？

**Comment by veeruby-developer** [comment]
@iluvian  MRTK 2.5.3 is the right version for this tutorial you can proceed with it.
