### ISSUE TITLE
Pressable button script executes twice

### ISSUE THREAD

**Issue by koudic** [MicrosoftDocs/mixed-reality#252]
I'm using a custom gameobject with the pressable button script from the mrtk 2.6. My button executes a press twice, from the front and the back, the interactable arrow (white arrow) shows towards the user, how can i change this behavior so it only executes from when pressing the button from the front?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20c7396-a42e-bbbf-11ac-2af1d559d142
* Version Independent ID: 1c21a109-c706-3bca-2331-abab43233423
* Content: [Butons](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button)
* Content Source: [mrtk-unity/features/ux-building-blocks/button.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/ux-building-blocks/button.md)
* Product: **mixed-reality**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by CDiaz-MS** [comment]
To enforce a front push only, make sure the `Enforce Front Push` property is active. 

![image](https://user-images.githubusercontent.com/53493796/113052126-9ef77100-915b-11eb-85f0-9f7b36afa723.png)

If switching this property does not resolve the issue, then it would be helpful for you to attach a screen shot of the game object with Pressable Button attached.  The screen shot will show where the planes that represent the push distances are positioned.

**Comment by koudic** [comment]
Thanks for your reply, the "Enforce Front Push" is activated, see screenshot below:

![image](https://user-images.githubusercontent.com/50170855/113053047-28349500-91a8-11eb-87c0-2ded5221f475.png)

![image](https://user-images.githubusercontent.com/50170855/113053181-4ac6ae00-91a8-11eb-9022-4c0c079f0f66.png)

**Comment by CDiaz-MS** [comment]
It looks like the Start Push Distance plane is placed in front of the Near Interaction Touchable plane (indicated by the blue plane placed in front of the origin of the white arrow).

I recommend changing the Start Push Distance to align exactly on the front surface of the object.  The easiest way to complete this is to set the Start Push Distance to -0.5 while the Distance Space Mode is in Local Space.  Then switch the Distance Space Mode to World space.

Here is a gif showing these steps from scratch, hope this helps:
![PressableButton](https://user-images.githubusercontent.com/53493796/113170058-0dd7d700-91fb-11eb-8b21-209e20df7c31.gif)
