### ISSUE TITLE
Tap to place generating error

### ISSUE THREAD

**Issue by vijitrahi** [MicrosoftDocs/mixed-reality#253]
'Tap to place' component generating error NullReferenceException

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorGUILayout.IsChildrenIncluded (UnityEditor.SerializedProperty prop) (at <8d21067e8d9c494db25a2b2485216e63>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUILayoutOption[] options) (at <8d21067e8d9c494db25a2b2485216e63>:0)
Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.RenderAdvancedProperties () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d2406e0dc3e0-1616679876246/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:118)
Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.RenderCustomInspector () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d2406e0dc3e0-1616679876246/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:99)
Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers.TapToPlaceInspector.OnInspectorGUI () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@d2406e0dc3e0-1616679876246/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs:72)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <8d21067e8d9c494db25a2b2485216e63>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@vijitrahi could you please provide us more information at what stage you are getting this error.

**Comment by hferrone** [comment]
@vijitrahi We'd love to help, but we need more info as mentioned above or let us know if you resolved the issue :)

**Comment by dfcarpenter** [comment]
I am getting this as well. For me this happens when I click to expand the Advanced Properties of the Tap to Place (Script). 

- Unity 2020.2.6f1
- OpenXR
- MRTK 2.6.1

![image](https://user-images.githubusercontent.com/4450286/114961077-cd8c7180-9e14-11eb-816f-c1b0b806f30b.png)

**Comment by hferrone** [comment]
@veeruby-developer Does this provide more clarity on the issue?

**Comment by veeruby-developer** [comment]
@dfcarpente These tutorials are not tested for MRTK 2.6.1.
please use MRTK 2.5.3

**Comment by dfcarpenter** [comment]
It says right in the documentation that 2.6 should work. 
![image](https://user-images.githubusercontent.com/4450286/115274806-eab38f80-a0f5-11eb-9965-8e5cad4df30c.png)

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-01#prerequisites

**Comment by hferrone** [comment]
@veeruby-developer Can you take another look?

**Comment by WLSmith9386** [comment]
I am getting the same issue as above, when Opening the Advanced Properties tab Unity starts to generate a NullReferenceException.

I downloaded the toolkit from the Mixed Reality Feature Tool.

I commented out line 118 of TaptoPlaceInspector.CS and the error went away allowing for the rest of the advanced properties to be shown. `EditorGUILayout.PropertyField(maintainScaleProperty);`

**Comment by hferrone** [comment]
@veeruby-developer This still seems to be an issue?

**Comment by MaxWang-MS** [comment]
This is a bug in MRTK 2.6.x and has been fixed in the newly released 2.7 version (microsoft/MixedRealityToolkit-Unity#9645).
