### ISSUE TITLE
I have a question about "Local anchor transfers in Unity"

### ISSUE THREAD

**Issue by parsley777** [MicrosoftDocs/mixed-reality#254]
[여기에 피드백 입력]
The Web page below states that when I export anchor data, you run the "TransferDataToClient" function.
https://docs.microsoft.com/ko-kr/windows/mixed-reality/out-of-scope/local-anchor-transfers-in-unity

Do I need to implement a function(TransferDataToClient) that sends the data to other devices over the network?
Or can I just send the data to another device with the content on that webpage?
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b01e03ae-bf91-fa69-3085-3a565e88c5ee
* Version Independent ID: 42518045-dd41-6405-5a0b-a7e6b5fedb96
* Content: [Unity의 로컬 앵커 전송 - Mixed Reality](https://docs.microsoft.com/ko-kr/windows/mixed-reality/out-of-scope/local-anchor-transfers-in-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/out-of-scope/local-anchor-transfers-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality-pr.ko-kr/blob/live/mixed-reality-docs/mr-dev-docs/out-of-scope/local-anchor-transfers-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @fieldsJacksonG
* Microsoft Alias: **jacksonf**

**Comment by keveleigh** [comment]
`TransferDataToClient` is a function you'd need to implement yourself. That page describes obtaining the data to send but not the exact method of sending the data.

**Comment by parsley777** [comment]
Nice to meet you, Mr/Ms. MaxWang.
Thank you for your kind reply.
Your advise was very helpful to me.

May I ask you a few questions?
Is there a way to see the anchor data file in the hololens on the PC after
connecting the hololens and the PC?
I want to see the capacity of the anchor data file.
And I want to copy the anchor data file to my PC and input it into another
hololens.

Have a nice day.
Thank you.

Best regards,
Thomas.

2021년 4월 15일 (목) 오전 1:31, Harrison Ferrone ***@***.***>님이 작성:

**Comment by parsley777** [comment]
Nice to meet you, Mr/Ms. Harrison Ferrone.
Thank you for your kind reply.
Your advise was very helpful to me.

May I ask you a few questions?
Is there a way to see the anchor data file in the hololens on the PC after
connecting the hololens and the PC?
I want to see the capacity of the anchor data file.
And I want to copy the anchor data file to my PC and input it into another
hololens.

Have a nice day.
Thank you.

Best regards,
Thomas.

2021년 4월 15일 (목) 오전 1:31, Harrison Ferrone ***@***.***>님이 작성:

**Comment by parsley777** [comment]
Nice to meet you, Mr/Ms. Kurtis.
Thank you for your kind reply.
Your advise was very helpful to me.

May I ask you a few questions?
Is there a way to see the anchor data file in the hololens on the PC after
connecting the hololens and the PC?
I want to see the capacity of the anchor data file.
And I want to copy the anchor data file to my PC and input it into another
hololens.

Have a nice day.
Thank you.

Best regards,
Thomas.

2021년 4월 13일 (화) 오전 3:17, Kurtis ***@***.***>님이 작성:
