### ISSUE TITLE
Default image when sharing is MS logo, instead of a more specific and compelling image.

### ISSUE THREAD

**Issue by m-the-hoff** [MicrosoftDocs/mixed-reality#256]
When sharing this page such as in a LinkedIn post by pressing the Share icon -> LinkedIn icon, the default image is the plain Microsoft logo. Ideally, it would be MRTK specific like the first photo on the page, to make it more compelling and more informative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95809b24-cc2f-3118-6d05-c504ed734cfc
* Version Independent ID: c9341566-b6b7-25bc-0121-1c6c30a43d49
* Content: [Introducing MRTK for Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/mrtk-getting-started)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
Agreed, but this isn't a supported feature at this time. Thanks for the callout!
