### ISSUE TITLE
Samsung HMD Odyssey

### ISSUE THREAD

**Issue by eLvitra** [MicrosoftDocs/mixed-reality#257]
My controllers are constantly ether turning off or loosing connection to my headsett. This happens when both controllers are infront of my headset. fresh batteries doesnt do anything. What the hell is wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/give-us-feedback#feedback)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Service: **unspecified**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
Hey @eLvitra, the developer documentation is specifically to instruct developers, so I won't be much help. For help with troubleshooting your controllers there are a couple good options:

- there's a thorough Troubleshooting article that is kept up-to-date by our support team and engineers at https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/troubleshooting-windows-mixed-reality. Start with that guide. If that doesn't help, you can comment on that article.
- another great option is posting in our support forums, where our support team and engineers are constantly checking and answering questions: https://forums.hololens.com/categories/troubleshooting.
- the other option is getting live support through support.microsoft.com.

Matt
