### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by xlmv521** [MicrosoftDocs/mixed-reality#259]
[在此处输入反馈]
这个页面的说明文档，有些截图和解释是不匹配的，在解释发布的那一栏，命名是导入包，确用来解释发布。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [初始化项目并部署第一个应用程序 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02#importing-the-mixed-reality-toolkit)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@xlmv521 please provide us the information where the Explanation does not match to the Screenshots.
so that we could update the tutorials if it is relevant.

**Comment by xlmv521** [comment]
这里的文字解释的是发布项目文件，但是图片是导入包，图文不一致。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MicrosoftDocs/mixed-reality"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上8:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MicrosoftDocs/mixed-reality] Error feedback (#259)





 
@xlmv521 please provide us the information where the Explanation does not match to the Screenshots.
 so that we could update the tutorials if it is relevant.

**Comment by xlmv521** [comment]
刚才给你截图的那个位置的图片应该是这里的导入包的过程，图文排版有问题。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MicrosoftDocs/mixed-reality"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上8:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MicrosoftDocs/mixed-reality] Error feedback (#259)





 
@xlmv521 please provide us the information where the Explanation does not match to the Screenshots.
 so that we could update the tutorials if it is relevant.

**Comment by veeruby-developer** [comment]
@xlmv521 Thanks for the replay, due the language barrier it is been difficult for us to understand for which screenshot you are referring to. could you please help us and provide us the information along with the highlighted screenshot.

**Comment by hferrone** [comment]
@xlmv521 We'd love to help, but we need more info as mentioned above or let us know if you resolved the issue :)
