### ISSUE TITLE
provided link to the paper isn't working

### ISSUE THREAD

**Issue by AMX07** [MicrosoftDocs/mixed-reality#26]
[Enter feedback here]
the link provided at line# 314 of the webpage under[https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality](url) <p> tag which is :- 
`<a href="https://etclab.mie.utoronto.ca/people/paul_dir/IEICE94/ieice.html" data-linktype="external">A Taxonomy of Mixed Reality Visual Displays</a>`  links to the web page (https://etclab.mie.utoronto.ca/people/paul_dir/IEICE94/ieice.html) isn't functioning anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ab05be-d139-8231-b567-815998113666
* Version Independent ID: 66ebb69f-5df4-b8a2-a3dd-deffeeedcc06
* Content: [What is Mixed Reality? - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality)
* Content Source: [mixed-reality-docs/mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mixed-reality.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @BrandonBray
* Microsoft Alias: **branbray**

**Comment by hferrone** [comment]
@BrandonBray @cre8ivepark @jessemcculloch Any ideas on how we can get the correct link?

**Comment by AMX07** [comment]
I found this online `https://search.ieice.org/bin/summary.php?id=e77-d_12_1321`

**Comment by hferrone** [comment]
Thanks for finding this!
