### ISSUE TITLE
duplicated API reference for core WDP APIs

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/mixed-reality#260]
This page contains duplicated documentation for core Windows Device Portal APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09aeb4f-c11d-108b-cab0-b2fc07adf72d
* Version Independent ID: 83c0eab2-daf3-14c4-0857-2a40cdac6964
* Content: [Device portal API reference - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/device-portal-api-reference#holographic-os)
* Content Source: [mixed-reality-docs/device-portal-api-reference.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/device-portal-api-reference.md)
* Service: **unspecified**
* GitHub Login: @JonMLyons
* Microsoft Alias: **JLyons**

**Comment by mattzmsft** [comment]
Hey @StephenHodgson, can you provide more information on the specific issue and your proposed resolution? I don't see any duplicated content within this article, but maybe i'm missing it or maybe you're saying it's a duplication of content that exists on another page? Looking for more context :-)

Thanks!
Matt

**Comment by StephenHodgson** [comment]
The duplicated information is located in the core windows device portal docs found [here](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)

Also related to https://github.com/MicrosoftDocs/windows-uwp/issues/367

**Comment by PatrickFarley** [comment]
Hi @StephenHodgson,
There is some overlap between the core Device Portal docs you linked to and the HoloLens-specific Device Portal docs on this page, but the two sets of APIs are not 1:1 identical, and they are intended for different use cases.
