### ISSUE TITLE
c# tutorial for the qr scanner

### ISSUE THREAD

**Issue by paulesn** [MicrosoftDocs/mixed-reality#264]
Is there a C# Version of the main part of the tutorial? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [Nachverfolgen von QR-Codes - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality-pr.de-de/blob/live/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
Hi @paulesn - We are currently working on creating a C# QR code tutorial, but in the meantime please refer to the API reference at the bottom of the article (if you haven't already :)): https://docs.microsoft.com/de-de/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#qr-api-reference
