### ISSUE TITLE
Where are the "Standalone settings"

### ISSUE THREAD

**Issue by pamistel** [MicrosoftDocs/mixed-reality#265]
There is a step " Go to the Standalone settings". What and where can this be found in unity?
A screenshot might be helpful.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae640b1-6e0f-bd94-133f-ae39af0d390c
* Version Independent ID: 47d796b6-f4fe-a711-0feb-dde3987ee62f
* Content: [GettingStartedWithMRTKAndXRSDK](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk)
* Content Source: [mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
Thanks, this has been updated!
