### ISSUE TITLE
MRTK Deployment onto Emulator

### ISSUE THREAD

**Issue by Romoth** [MicrosoftDocs/mixed-reality#269]
Instructions were decent overall.  Some minor things have changed in the current tool releases.  Instead of deploying to an actual Hololens device, I want to run the basic cube app on the Hololens emulator.  The instructions didn't mention how to deploy to the emulator.  Perhaps there is written up elsewhere.  Provide a link if it is.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@Romoth you could find instructions for Deploying apps to the HoloLens Emulator on this [Page](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-hololens-emulator)

**Comment by Romoth** [comment]
I had looked at that page many times.  What I was missing was the Debug
Target setting in Project Properties.  I had to be running the emulator
before it could be found.

[image: Snap1.png]
