### ISSUE TITLE
Documentation inconsistent with HL1 emulator requirements

### ISSUE THREAD

**Issue by MSDNAndi** [MicrosoftDocs/mixed-reality#27]
The installer of the HL1 emulator currently requires VS2017 to successfully complete if you do a complete install or want to install the templates. The documentation does not mention this and only requires VS2019.
Please either fix the installer or update the documentation to clarify that to install the HL1 emulator with Visual Studio 2019 you need to deselect the VS templates and manually add them later on, or you need VS 2017 installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6144653-f7f3-0ad2-5c8f-24310633144a
* Version Independent ID: a810412b-2ff0-29d3-3004-af58ce8c24be
* Content: [Install the tools - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools?tabs=native)
* Content Source: [mixed-reality-docs/install-the-tools.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/install-the-tools.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
@thetuvix @polar-kev Can you confirm and assist?

**Comment by hferrone** [comment]
@thetuvix @polar-kev Checking in on this one
