### ISSUE TITLE
Sergoe UI Font not included with Figma Mixed Reality Toolkit

### ISSUE THREAD

**Issue by cgimber** [MicrosoftDocs/mixed-reality#272]
Hi! My team is looking for the Sergoe UI Fonts used in the figma components. Where are these available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62712b23-e5db-ab31-7cce-eb31e2e6baad
* Version Independent ID: 14d3b6ff-951a-1e92-8508-8d2b2ba608fa
* Content: [Figma Toolkit - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/design/figma-toolkit)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/figma-toolkit.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/design/figma-toolkit.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @DongPark
* Microsoft Alias: **dongpark**

**Comment by cre8ivepark** [comment]
@cgimber I guess you are using this on Mac? (Windows should have Segoe UI fonts in the system by default)
You can download Segoe UI fonts from this page:
https://docs.microsoft.com/en-us/windows/uwp/design/downloads/
Thanks!
