### ISSUE TITLE
Bind the HoloLens scene camera to the ARCamera

### ISSUE THREAD

**Issue by 1996010320** [MicrosoftDocs/mixed-reality#273]
In the latest release of Unity (2017 2.2p2), where is the option Central Anchor Point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c4dede-5f71-8f1e-41de-0a79174af5ae
* Version Independent ID: d143fd99-178b-e924-5a6c-08729f2d81d0
* Content: [Using Vuforia with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/vuforia-development-overview)
* Content Source: [mixed-reality-docs/vuforia-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/vuforia-development-overview.md)
* Service: **unspecified**
* GitHub Login: @ChimeraScorn
* Microsoft Alias: **cwhite**

**Comment by mattzmsft** [comment]
@ChimeraScorn can you take a look at this? It's possible our Vuforia documentation is out-of-date relative to recent Unity updates.

**Comment by olirehacek** [comment]
Same problem here. Need this fixed asap

**Comment by olirehacek** [comment]
Found solution : Just get rid of the ARcamera and add "Vuforia Behavior" directly to your Mixed Reality Camera.

**Comment by mattzmsft** [comment]
@1996010320 @MadMax93 did this work for you as well? @olirehacek Thanks for the recommendation!

**Comment by 1996010320** [comment]
Yes the only way I found is removing Hololens camera and tag ARCamera as the main camera. Just want to check is this the official way to make it work, so technically there won't be "binding" anymore?

**Comment by vitaliyOSTAPCHUK** [comment]
Still got some shift in the CamereSpace after removieng the ARcamera and binding it to the MixedRealityCamera. What Unity Version are you using?

**Comment by olirehacek** [comment]
2017.3.1p and with no issue.

**Comment by jessemcculloch** [comment]
I don't know if this issue is still occuring.  Will close next week if no further comments/issues

**Comment by vitaliy-ostapchuk93** [comment]
Version of Vuforia and Unity are out of date so feel free to close this.

**Comment by jessemcculloch** [comment]
Thanks
