### ISSUE TITLE
Changing Spatial Awareness Display Option at runtime is unclear

### ISSUE THREAD

**Issue by justinpando** [MicrosoftDocs/mixed-reality#274]
This tip is unclear:

> If you want to see the Spatial Awareness Mesh when testing the Tap To Place functionality on your HoloLens, you can temporarily set the Spatial Mesh Observer's Display Option to Visible. For a reminder on how to change the Display Option, you can refer to the Changing the Spatial Awareness Display Option instructions.

The linked page shows you how to create a new custom profile and manually change the spatial awareness display option, but doesn't include instructions about procedurally changing the display option at runtime. I'm not sure how to handle that, in following the tutorial I might have expected to drag something into the TapToPlace component's OnPlacingStarted and OnPlacingStopped events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@RogPodge Can you assist?

**Comment by MaxWang-MS** [comment]
The question has been answered [here](https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/9673), @hferrone please close the issue.

**Comment by cre8ivepark** [comment]
@justinpando You can also check out this video (43:53)
https://channel9.msdn.com/Shows/Mixed-Reality/MRTKs-UX-Building-Blocks
