### ISSUE TITLE
Documentation for migrating from manual install to feature tool

### ISSUE THREAD

**Issue by yhong3** [MicrosoftDocs/mixed-reality#275]
Hi, is there any documentation about how to migrate from manual install to the feature tool? I tried the manually installed/upgraded MRTK 2.5.1 and 2.5.4, following the [Updating guide](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/updates-deployment/updating) but the feature tool was not able to detect the MRTK installed in the unity project. I feel like it should be on this page if exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0405e5-aef5-5ed3-d9a1-960b4065300b
* Version Independent ID: dd9cd8d6-caea-6146-fd71-c5b3605435c4
* Content: [Welcome to the Mixed Reality Feature Tool - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @davidkline-ms
* Microsoft Alias: **v-hferrone**

**Comment by davidkline-ms** [comment]
At this time, the feature tool cannot detect an installation of  MRTK that was performed via a .unitypackage import.

I will work with the team to draft formal migration instructions. While we write them, the following should help you migrate:

Follow steps 1-5 from https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/updates-deployment/updating#unity-asset-unitypackage-files and then use the [Feature Tool](https://aka.mss/mrfeaturetooldocs) to install the desired packages.
