### ISSUE TITLE
Reset Button - Rover Assembly doesn't have a PartAssemblyController

### ISSUE THREAD

**Issue by justinpando** [MicrosoftDocs/mixed-reality#277]
[Enter feedback here]

In following the tutorial, I reached this instruction:

> In the Hierarchy window, select the RoverExplorer > Buttons > Reset button object, then in the Inspector window, configure the Interactable OnClick () event as follows:
> 
> Assign the RoverAssembly object to the None (Object) field
> From the No Function dropdown, select PartAssemblyController > ResetPlacement () to set this function as the action to be executed when the event is triggered

However, the RoverAssembly object doesn't have a PartAssemblyController. Instead, I dragged the PartAssemblyController from each of the five parts to the Reset button's OnClick event and it works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e0bbe-0f42-1b1d-5875-c2fe81e3a3a3
* Version Independent ID: d499b1bb-7c06-7420-8024-699b70ba608e
* Content: [Interacting with 3D objects - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-07)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-07.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@justinpando you should attach the PartAssemblyController Script to the RoverAssembly as per the tutorial,
![image](https://user-images.githubusercontent.com/61759322/115023674-bca73300-9edc-11eb-8ac2-accc42b1db7b.png)

please let us know does this solve your issue?
