### ISSUE TITLE
Bad typo

### ISSUE THREAD

**Issue by MatteoLuccio** [MicrosoftDocs/mixed-reality#277]
In the first sentence, "just as if they are real objects" should be "just as if they were real objects." "As is" demands the subjunctive! Cheers, Matteo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cba65e3-618a-b55a-d428-1e649b94a916
* Version Independent ID: 58c15d23-5e33-5672-b76e-2811880c6109
* Content: [What is a hologram? - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hologram#feedback)
* Content Source: [mixed-reality-docs/hologram.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hologram.md)
* Service: **unspecified**
* GitHub Login: @beaufolsom
* Microsoft Alias: **befolsom**

**Comment by mattzmsft** [comment]
Ah, good catch. As a fellow grammar nerd, it feels good to squash that one :-) Thanks @MatteoLuccio

**Comment by MatteoLuccio** [comment]
Glad to be of service.
