### ISSUE TITLE
Texts and images do not match.

### ISSUE THREAD

**Issue by Ryosuke-Ymd** [MicrosoftDocs/mixed-reality#278]
[

[Docs]>[Windows]>[Mixed Reality]>[Development]>[Unity]>[HoloLens2 Tutorials]>Getting Started tutorial series>[2. Initializing your project and deploying your first application](URL : [https://docs.microsoft.com/ja-jp/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02])

Texts and images of this web page after "Building your application to your HoloLens 2" do not match. So I want you to correct this page.

And, I have this images about a cube written "Hello World" on my mind. Could you tell me a web page using the images?

Sorry, I don't write English well. 
Thank you for reading.

]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [プロジェクトの初期化と最初のアプリケーションの配置 - Mixed Reality](https://docs.microsoft.com/ja-jp/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02#feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.ja-jp/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@veeruby-developer Can you assist?

**Comment by veeruby-developer** [comment]
@Ryosuke-Ymd thanks for the feedback, please help us and provide more details along with screenshots where the Texts and Images does not match so that we could update the tutorials..

**Comment by Ryosuke-Ymd** [comment]
@veeruby-developer 
I have attached screenshots to this message. And, I will paste the link to the website just in case.
Would you please confirm the screenshots.

・Screenshots
![screenshot_1](https://user-images.githubusercontent.com/77087414/115253466-5f72e200-a167-11eb-9dc9-1c51464c2e3c.png)
![screenshot_2](https://user-images.githubusercontent.com/77087414/115253474-613ca580-a167-11eb-9e22-c1a172d7e2a4.png)
![screenshot_3](https://user-images.githubusercontent.com/77087414/115253476-61d53c00-a167-11eb-9a70-6aba999caf2e.png)
![screenshot_4](https://user-images.githubusercontent.com/77087414/115253478-626dd280-a167-11eb-978c-56c016d4bc3e.png)
![screenshot_5](https://user-images.githubusercontent.com/77087414/115253482-63066900-a167-11eb-8afb-d28420e0fe9a.png)
![screenshot_0](https://user-images.githubusercontent.com/77087414/115253485-64379600-a167-11eb-8d4b-e6054ab4990a.png)

・Website
[https://docs.microsoft.com/ja-jp/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02#building-your-application-to-your-hololens-2]

**Comment by veeruby-developer** [comment]
@Ryosuke-Ymd all the screenshots are correct please refer below some of the examples,

![image](https://user-images.githubusercontent.com/61759322/115358043-e3b27d00-a1da-11eb-95bf-f6ff84ddac6d.png)
![image](https://user-images.githubusercontent.com/61759322/115358129-f927a700-a1da-11eb-8378-46d916c24f11.png)
![image](https://user-images.githubusercontent.com/61759322/115358180-05136900-a1db-11eb-8b13-678045e79cc4.png)
![image](https://user-images.githubusercontent.com/61759322/115358215-0d6ba400-a1db-11eb-8df5-f7e1b91c5a2a.png)
![image](https://user-images.githubusercontent.com/61759322/115358253-16f50c00-a1db-11eb-836f-14e4ece905e8.png)

please try again by clearing browsing data(cache memory)

**Comment by Ryosuke-Ymd** [comment]
@veeruby-developer 
It hasn't been fixed yet.

**Comment by hferrone** [comment]
I'm showing that these are correct on my browser as well. @Ryosuke-Ymd this is likely a caching error.

**Comment by Ryosuke-Ymd** [comment]
@hferrone 
I tried to access the website from my another google account, another person's google account and another web browsers. But I can't.
Does the problem have anything to do with a place to access?
I think the problem is the same as this [feedback.](https://github.com/MicrosoftDocs/mixed-reality/issues/259)

**Comment by kirurobo** [comment]
The [Japanese version](https://docs.microsoft.com/ja-jp/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02) of the published document has outdated text and mismatched images compared to the [English version](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02).

![Screenshot of the Japanese version](https://user-images.githubusercontent.com/1019117/116964816-63fed500-ace7-11eb-83e5-3d26909eb2a6.png)

![Screenshot of the English version](https://user-images.githubusercontent.com/1019117/116964797-55182280-ace7-11eb-96b2-06653781d735.png)
