### ISSUE TITLE
PinchSlider start/end points missing, start and end distance fields non-functional

### ISSUE THREAD

**Issue by justinpando** [MicrosoftDocs/mixed-reality#279]
I'm trying to modify a PinchSlider for my UI layout, and referenced this documentation page:

> You can directly move the starting and end points of the slider by moving the handles in the Scene:
> 
> ![image](https://user-images.githubusercontent.com/3631080/115103876-1bcf6c80-9f0a-11eb-9d0e-eb9dc267d073.png)
> 
> You can also specify the axis (in local space) of the slider via the Slider Axis field
> 
> If you cannot use the handles, you can instead specify the start and end points of the slider via the Slider Start Distance and Slider End Distance fields. These specify start / end position of slider as a distance from the slider's center, in local coordinates. This means that once you set the slider start and end distances as you want them, you can scale the slider to be smaller or larger without needing to update the start and end distances.

There don't seem to be any start and end points for the slider as shown in the image. Modifying the Start Distance and End Distance fields also don't seem to change the slider's start and end positions in space in any way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94494374-dada-4b2e-9177-133836bceb77
* Version Independent ID: b7ee6187-130b-c2b8-5fff-a8686844c0b2
* Content: [Slider](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/sliders)
* Content Source: [mrtk-unity/features/ux-building-blocks/sliders.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/ux-building-blocks/sliders.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by Cameron-Micka** [comment]
Hi @justinpando, thank you for opening this issue. Looking at the slider locally grabbing the start/end points appear to adjust the slider's range, but the visuals don't update (just the slider thumb's range). 

![image](https://user-images.githubusercontent.com/13305729/115284049-05d7cc80-a101-11eb-935d-825a9c73316a.png)


@cre8ivepark should the visuals update as well? If not I wonder if we should add support for that or update the docs?

**Comment by justinpando** [comment]
How are you getting the start and end handles to appear? I'm not seeing them at all unfortunately.

**Comment by Cameron-Micka** [comment]
@justinpando oh interesting. The start and end handles are rendered using OnSceneGUI so I would make sure gizmos for the script are enabled (circled in red), the slider gameobject is selected, and the script is expanded/visible in the inspector (circled in red).

![image](https://user-images.githubusercontent.com/13305729/115461936-ddbe9b00-a1de-11eb-9918-cc2d1599184a.png)
