### ISSUE TITLE
Failed to connect with Azure Storage.

### ISSUE THREAD

**Issue by XiangGuo1992** [MicrosoftDocs/mixed-reality#28]
Hi,

When I tried to run the example in this page at 'Writing and reading data from Azure Table storage', I can run the app in the Unity with the Connection String (Azure storage can update the objects). However, when I deployed the app to HoloLens 2, there is an error, 'Failed to connect with Azure Storage. If you are running with the default storage emulator configuration, please make sure you have started the storage emulator.'. Could you explain the reason for me? Thank you!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15853f4-20ac-bea9-89b0-4cd7da19a5be
* Version Independent ID: 398529a4-fee0-21bb-6cc6-b57b47d25ea1
* Content: [Azure Cloud Tutorials - 2. Integrating Azure Storage - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-azure-02#feedback)
* Content Source: [mixed-reality-docs/mr-learning-azure-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-azure-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@jessemcculloch Who can we point this to?

**Comment by hferrone** [comment]
@martinwilter Have you run into this before?

**Comment by martinwilter** [comment]
Hi @hferrone,

Unfortunately, I'm not familiar with this tutorial series... would love to go through the tutorials, but time is an issue :) For future reference, I'm familiar with the following tutorial series:

- [Getting started tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-01)
- [Azure Spatial Anchors tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-asa-01)
- [Multi-user capablilities tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-sharing-01)
- [Azure Speech Services tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-speechsdk-ch1)

I'll check if someone in my networks knows how to handle the 'Failed to connect with Azure Storage' issue, and update here if any luck.

**Comment by nra20** [comment]
Hello everyone,

Was anyone able to figure out why this error was occurring when deploying the app unto the Hololens2 device, but not when testing within the Unity Editor? 

Best,
Nick

**Comment by XiangGuo1992** [comment]
> Hello everyone,
> 
> Was anyone able to figure out why this error was occurring when deploying the app unto the Hololens2 device, but not when testing within the Unity Editor?
> 
> Best,
> Nick

**Comment by hferrone** [comment]
@martinwilter Could you tag whoever overhauled this tutorial series in your org?

**Comment by martinwilter** [comment]
Sure @hferrone, I'll check if they are available.

**Comment by rubit0** [comment]
Thee Azure Storage Emulator is only accessible to your _local dev machine_, this is why you get this error message on your HoloLens 2. To fix this you need to create an _Azure Storage account_ on Azure (this may require a credit card).

If for some reason your are in a situation where you can't create an Azure Storage account, you could alternatively expose the ports of your local machine to make the Azure Storage Emulator accessible in your local network, but scenario is not officially supported.

**Comment by hferrone** [comment]
Thanks @rubit0! @XiangGuo1992 I'm going to close this, but if this problem persists or another one comes up feel free to comment in the thread and I'll reopen :)
