### ISSUE TITLE
Scene Understanding Example does not work in MRTK 2.61 or Higher

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#280]
Scene Understanding Example in MRTK does not work when deployed to HoloLens 2. The menu is out of sight when executed and the scene is head locked. After adjusting the menu setting to get the menu in view, it too is head locked and completely unresponsive. The Demo Spatial Awareness Example scene is also head locked and does nothing. I would guess it is not configured correctly but have NO idea where to begin to troubleshoot this project configuration. I would expect a working OOB experience for a primary example. The SDK documentation is out of date, useless.

Using Unity 2019.4.23 and MRTK 2.6.1 and MRTK 2.7 preview with VS 2019.16.9.4
Followed the basic Unity project setup for MRTK from this [link ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr) 
Followed these instructions to configure the demo example a this [link](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding)

I have been working with MRTK and Unity for HoloLens now for nearly a year with extremely poor experiences across the entire spectrum. It seems that HoloLens is "nice to have" for MRTK. If that is the case, why not just say so. At least then we developers trying to use it can lower our expectations of the MRTK and Microsoft in general. If you do expect to support HoloLens then do so. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8aa2e52-391c-7963-0496-7c735c0bc596
* Version Independent ID: bd0e1c49-b23b-91d7-31aa-a1a09fe4e387
* Content: [SceneUnderstanding](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding)
* Content Source: [mrtk-unity/features/spatial-awareness/scene-understanding.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/spatial-awareness/scene-understanding.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by laultman** [comment]
I found a [workaround](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/choosing-unity-version). If you are recommending users use the Unity Legacy XR, then do not demonstrated in a setup guide the use of some other XR plug-in as is done in the Beginners tutorial for HoloLens. In fact this warning should be on EVERY tutorial or sample of any kind. We would not be forced to waste many hours locating the correct combinations of tools and configurations.

tags to help somebody else: OpenXR compatible example

**Comment by hferrone** [comment]
Hi @laultman - we've got some changes in the works that will make sample scenes work across multiple XR setups. Thanks for the callout!

**Comment by lucamorando95** [comment]
Hi have the same problem of @laultman.
Completely unresponsive app when deployed on hololens.
The app runs because when I ask to toggle menu it works but is three days that I try to acquire data from the real environment for the scene understanding task.
I try every possible  setup configuration but NOTHING.
I’m working with unity 2019 but I tried also with the latest unity 2020.4 and mrtk 2.7.3.
The sample example must work, and the documentation about to run it must be perfect!
On the editor everything works fine.


Using Unity 2019.4.11f1 and MRTK 2.5.4 with visual studio 2020 and MRTK 2.7.3  with VS 2020
Followed the basic Unity project setup for MRTK from the same link of @laultman

**Comment by MaxWang-MS** [comment]
Hi @lucamorando95, can you send us a repro project and/or the log of the deployed app on HoloLens?

**Comment by lucamorando95** [comment]
Hi MaxWang-MS:

Thank you for your attention. Actually i have resolved the bug. There were some inconsistencies between the version of unity, Visual Studio and the XR plugin Management.
In Every new build Unity generated a IL2CPP error in the executable itself. It was not visible also during the upload of the executable on the HoloLens via Visual Studio.
To find the error i have launch the deploy of the application in Debug Mode, until discover the problem.
The correct configuration that permits to the Scene Understanding Project to work is:
Unity v 2020.3.23f1
MRTK Foundation 2.7.3
MRTK WinRT Projections 0.5.1052
MR Scene Understanding 0.6.0
XR Plugin Management
Visual Studio 2019 16.11.8
With the Following Configuration :
Microsoft Visual Studio Community 2019 (2)
Versione 16.11.8
VisualStudio.16.Release/16.11.8+32002.261
Microsoft .NET Framework
Versione 4.8.03761

Edizione installata: Community

Visual C++ 2019   00435-60000-00000-AA906
Microsoft Visual C++ 2019

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Strumenti C#   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti di Visual Basic   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Visual Studio Tools per Unity   4.11.4.0
Visual Studio Tools per Unity

Thank You for your Help
Luca


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
