### ISSUE TITLE
the MRTK is not working.

### ISSUE THREAD

**Issue by CyanW0202** [MicrosoftDocs/mixed-reality#281]
I have downloaded the .NET ver 5.0, trying to open the MRTK package.
But the error of couldn't find the .NET framework keeps poping up.
![image](https://user-images.githubusercontent.com/47878471/115609370-4c156300-a29c-11eb-999e-2989198056bf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ac37f3-5dc8-8076-da7c-4c6d877eac49
* Version Independent ID: b58b8052-ddca-5941-3981-867baef990a5
* Content: [Unity development for HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-development-overview?tabs=arr%2Chl2#have-feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/unity-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/unity-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **kurtie**

**Comment by davidkline-ms** [comment]
This appears to be a situation where .net5 is not properly installed on the system, resulting in the Mixed Reality Feature Tool not being able to run.

The errors in Unity's console window imply that MRTK packages have not been imported onto the project.

**Comment by davidkline-ms** [comment]
Please download the desktop version of .net5 from https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore and run the installer. This will enable the Mixed Reality Feature Tool to run and import features into your Unity project,.
