### ISSUE TITLE
Missing profile cloning instruction

### ISSUE THREAD

**Issue by mikey-mdk** [MicrosoftDocs/mixed-reality#282]
I believe there is an instructional step missing for cloning the MixedRealityInputSystemProfile. One of the first steps is to add a new data provider under the input tab but you are only able to do so once you have cloned your own version of this profile, which I don't believe the tutorial has instructed you to do up to this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73165980-1885-b806-7200-65d2bff9ac87
* Version Independent ID: 4ce5f95c-de8d-b246-6f06-e00f5dc2d211
* Content: [Using eye-tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-08?tabs=winxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mikey-mdk** [comment]
It appears that the step for cloning a new profile occurs later in the tutorial. But the first steps mentioned in this issue are still in conflict.

**Comment by veeruby-developer** [comment]
@mikey-mdk Thanks for the feedback, instructions to clone MixedRealityInputSystemProfile will be updated.
