### ISSUE TITLE
Input Data Providers missing the instructed type

### ISSUE THREAD

**Issue by mikey-mdk** [MicrosoftDocs/mixed-reality#283]
When attempting to add a new Data Provider for the Input Data Providers, the instructions say to assign the new provider to the type of Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input > WindowsMixedRealityEyeGazeProvider, yet that namespace is not provided as one of the options

![image](https://user-images.githubusercontent.com/83050479/115810882-8fa6c480-a3a3-11eb-8100-97b3cc970bcb.png)

The only type that has a subtype of "EyeGazeProvider is the OpenXREyeGazeDataProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73165980-1885-b806-7200-65d2bff9ac87
* Version Independent ID: 4ce5f95c-de8d-b246-6f06-e00f5dc2d211
* Content: [Using eye-tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-08?tabs=winxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by mikey-mdk** [comment]
It appears that the very next section supersedes the section above it which this issue is referencing

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-08?tabs=winxr#enabling-eye-based-gaze-in-the-gaze-provider

**Comment by veeruby-developer** [comment]
@mikey-mdk please let us know what is the MRTK version you are using

**Comment by mikey-mdk** [comment]
I am currently using the latest version MRTK version 2.6.1

**Comment by veeruby-developer** [comment]
@mikey-mdk  just verified with Unity Version 2019.4.22 and MRTK 2.6.1, "WindowsMixedRealityEyeGazeProvider" Type is available, also attached a screenshot for reference
![image](https://user-images.githubusercontent.com/61759322/115947662-c89b8200-a4e6-11eb-8f67-f89ae36684ad.png)

**Comment by mikey-mdk** [comment]
I am using Unity version 2020.3.5f1

**Comment by veeruby-developer** [comment]
@mikey-mdk  these tutorials are not yet tested for Unity Version 2020. please Use Unity 2019.4.x.
