### ISSUE TITLE
Missing Speech Namespace

### ISSUE THREAD

**Issue by mikey-mdk** [MicrosoftDocs/mixed-reality#284]
I believe the first section of this page is deprecated or no longer accurate.

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-09?tabs=winxr#ensuring-microphone-capability-and-adding-speech-input-data-provider

That namespace is no longer one of the selectable types. The very next section of the page shows that the HoloLens2InputSystemProfile already has a Windows Speech Input data provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e526277-fa7f-9d2a-faed-aed2d7555c93
* Version Independent ID: ee349afa-a729-60fd-0570-dfc3458e4cc5
* Content: [Using speech commands - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-09?tabs=winxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-09.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-09.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@mikey-mdk please let us know what is the MRTK version you are using

**Comment by mikey-mdk** [comment]
I am using MRTK version 2.6.1

**Comment by veeruby-developer** [comment]
@mikey-mdk just verified with Unity Version 2019.4.22 and MRTK 2.6.1, "WindowsSpeechInputProvider" Type is available
![image](https://user-images.githubusercontent.com/61759322/115947747-5b3c2100-a4e7-11eb-8358-449ffd81c1d3.png)

**Comment by mikey-mdk** [comment]
I am using Unity version 2020.3.5f1

**Comment by veeruby-developer** [comment]
@mikey-mdk  these tutorials are not yet tested for Unity Version 2020. please Use Unity 2019.4.x.
