### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by gsmuthusamy** [MicrosoftDocs/mixed-reality#285]
Hey! I walked through this tutorials. There were few unassigned values for Quad object and SpatializeOnOff Script --> Button Text Object. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d7c33b7-9950-5bb6-977c-7b4cd316e0ad
* Version Independent ID: 008e809f-a7c8-78c3-3356-bdf8d724469a
* Content: [Spatial audio tutorials - 5. Using reverb to add distance to spatial audio - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch5)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @kegodin
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
@mr0ng @veeruby-developer Can you assist?

**Comment by veeruby-developer** [comment]
@gsmuthusamy could you please provide us more information which are the unassigned values for Quad object and SpatializeOnOff Script. so that we could update the tutorials if it is relevant.

**Comment by gsmuthusamy** [comment]
![SpatialaudioError](https://user-images.githubusercontent.com/34948887/116042602-e136a400-a66e-11eb-9048-3923707b0b15.PNG)
![spatialon and off](https://user-images.githubusercontent.com/34948887/116042619-e562c180-a66e-11eb-8b7a-2ccf87cfbc94.PNG)

**Comment by veeruby-developer** [comment]
@gsmuthusamy in the screenshot I see that you have added "**PressableButonHoloLens2**" for "ButtonTextObject". but in the 4th [tutoria](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch4) it is mentioned to add the **TextMeshPro** Component of the PressableButtonHoloLens2. refer below screenshot.
