### ISSUE TITLE
Outdated images/info

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#29]
[Enter feedback here]
We should take more info and images from this [doc](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal#performance-tracing) or just retire this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by hferrone** [comment]
@cre8ivepark Can you assist?

**Comment by hferrone** [comment]
@cheles These have all been updated, thanks for calling this out!
