### ISSUE TITLE
How to find XR Settings

### ISSUE THREAD

**Issue by xtellurian** [MicrosoftDocs/mixed-reality#291]
In Chapter 3 - Target Windows 10 SDK, it is unclear how to find the Virtual Reality SDKs list under XR Settings.

Please add a line saying something similar to "Under Edit > Project Settings > Player find the XR settings under the Windows Tab"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [Holograms 100 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Service: **unspecified**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by smattiso** [comment]
XR Settings was a bit confusing. I had to click on "Other Settings" to see something similar.
Then again, I'm having a different issue with these instructions myself, so maybe it's different for people who aren't having the same issue.
