### ISSUE TITLE
obsolete methods used in this page

### ISSUE THREAD

**Issue by HesterMeng** [MicrosoftDocs/mixed-reality#292]
On this page, the method WorldAnchorStore.GetAsync(store) is obsolete for Unity 2019.4. Thus I wonder if this page can be updated to use up-to-date methods for instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d3daf6-e9f9-d400-1941-ab76efed39ef
* Version Independent ID: f8a2ed75-804a-18f2-4d97-eb7737b0de75
* Content: [Persistence in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/persistence-in-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/persistence-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/persistence-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
Thanks for bringing this up - we have a new doc that has updated content: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-anchors-in-unity?tabs=worldanchor#persistent-world-locking

**Comment by HesterMeng** [comment]
Thank you!
