### ISSUE TITLE
Cannot assign Microsoft.MixedReality.ToolKit.WindowsMixedReality.Input as Type for Input Provider

### ISSUE THREAD

**Issue by Hattexmc** [MicrosoftDocs/mixed-reality#293]
Hello,
i am currently working through the "Beginner MRTK tutorials" for  unity. For using eye tracking, i should add a new Input Data Provider and 
"Assign Microsoft.MixedReality.ToolKit.WindowsMixedReality.Input > WindowsMixedRealityEyeGazeProvider to the Type field of the new Data Provider."
The "Type" - dropdown menu does not show this as an option.

Unity 2020.3.5f1
MRTK Foundation V2.6.1 &
MRTK Standard Assets V2.6.1 installed via Mixed Reality Feature Tool. No other packages are loaded

![image](https://user-images.githubusercontent.com/81165301/116671563-5ec91f80-a9a1-11eb-8a41-59fba01c58fb.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73165980-1885-b806-7200-65d2bff9ac87
* Version Independent ID: 4ce5f95c-de8d-b246-6f06-e00f5dc2d211
* Content: [Using eye-tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-08?tabs=winxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-08.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by Hattexmc** [comment]
Edit: created and configured new project with Unity 2019.4.25f1 and MRTK Foundation/Standard Assets V2.6.0.  (via MR Feature Tool)
In this project it works as described.
Updated MRTK packages to V2.6.1 and still runs as aspected, so problem is the unity version.

**Comment by veeruby-developer** [comment]
@Hattexmc  these tutorials are not yet been tested for Unity 2020.  Please use Unity 2019
