### ISSUE TITLE
Graphics Driver WDDM1.3

### ISSUE THREAD

**Issue by CyanW0202** [MicrosoftDocs/mixed-reality#294]
I follow the instruction and searching for a possible way to update my WDDM1.3 to WDDM2.0. Realizing that it may related to the compatibility of my intel HD 4000 graphic card. Visit the website of intel HD4000 and reviewing the support of WDDM1.3 I still couldn't understand what should I do to update my graphics driver...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f464b6-99ef-6d78-c30a-4066e9e7a411
* Version Independent ID: 88e27323-63f3-5113-5038-6ee50a606491
* Content: [Get help with PC compatibility - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/get-help-with-pc-compatibility#WarnGraphicsDriver)
* Content Source: [enthusiast-guide/get-help-with-pc-compatibility.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/get-help-with-pc-compatibility.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Hi @CyanW0202 - this is more of a support issue than docs I think. Please file a support ticket with Microsoft or with the graphics driver manufacturer. All the best!
