### ISSUE TITLE
definition of mixed reality

### ISSUE THREAD

**Issue by jennycolegrove** [MicrosoftDocs/mixed-reality#295]
[This is Jennifer Colegrove, an industry analyst from Touch Display Research Inc. I'm updating my report "Sensors for AR VR and AI", the first report was published in 2016. Now in 2021, I'll add in Mixed Reality, and XR definition in it. I read the Microsoft article about "What is Mixed Reality" in August 2020. I understand you use MR as a spectrum which include AR and VR and anything in between. (Just like Electromagnetic wave spectrum include visible light, UV, IR, etc.)  I'm thinking to say MR is an umbrella term which include both AR and VR. This definition is simpler, easier to understand. Just like Electromagnetic wave spectrum is an umbrella term including visible light, UV, IR, etc. (XR can also be an umbrella term including AR, VR, MR. but some say extended reality is a higher level).   What's your thought? You can email me directly jc@touchdisplayresearch.com or call my cell phone 408-341-5065. Thanks.   Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea162663-1580-2d23-4c07-fbd09f1bee9b
* Version Independent ID: a49e7344-f7f6-1dcc-c885-70037966617b
* Content: [What is Mixed Reality? - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/discover/mixed-reality)
* Content Source: [mixed-reality-docs/mr-dev-docs/discover/mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/discover/mixed-reality.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @BrandonBray
* Microsoft Alias: **branbray**

**Comment by hferrone** [comment]
Hi @jennycolegrove - thanks for the callout here, we'll take this into consideration for our next docs update :)
