### ISSUE TITLE
ASA Tutorial: SpatialAnchorManager script can not be loaded

### ISSUE THREAD

**Issue by jstiefel** [MicrosoftDocs/mixed-reality#297]
Following the ASA tutorial I have an issue with the SpatialAnchorManager and AnchorModuleScript in the second part at "Configuring the buttons to operate the scene". I have no function `AnchorModuleScript->StartAzureSession()` available in the dropdown. When I check the `ParentAnchor` in the Inspector, I see that both SpatialAnchorManager and AnchorModuleScript have a warning:

```
The associated script can not be loaded. Please fix any compile errors and assign a valid script.
```

I think this is caused by some version mismatch despite following the tutorial very carefully. The tutorial does not seem to be completely consistent with versions. For example it tells you to install ASA SDK 2.7.1:

```
Add AzurespatialAnchors SDK V2.7.1 into your unity project, to add the packages please follow this tutorial
```

The linked page then says:

```
The Azure Spatial Anchors SDK versions 2.8 or earlier do not support the Unity XR Plug-in Framework and should be configured in Unity 2019.4 (LTS) using the following packages:
```

However, the first part of the tutorial clearly tells you to install Unity 2019.4 and the XR Plug-in.

I'm installing the following package versions since it's not mentioned which versions are required:

AR Foundation 2.1.18
Windows XR Plugin 2.5.2
ARKit XR Plugin 2.1.18

Using the Mixed Reality Feature Tool I'm installing:

ASA SDK Core 2.7.1
ASA SDK for iOS 2.7.1
ASA SDK for Windows 2.7.1

Other versions:

Windows 10 SDK, Version 1903 (10.0.18362.1)
Unity 2019.4.19f1
Mixed Reality Toolkit Foundations 2.6.0

I'm also getting a lot of errors of missing methods from the Windows XR Plugin in the Console:

![grafik](https://user-images.githubusercontent.com/44534970/117337126-45dad580-ae9d-11eb-9e2e-fec421c9f2fe.png)

Can someone tell me how to proceed without trial and error of each possible version combination? I'm running into version mismatches quite often in these tutorials and I'm puzzled by all these compatibility issues. I'm usually working on Linux and never had such a mess with version incompatibility in any other software.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@jstiefel this tutorial does not support ASA for XR plugin Management yet. so if you are using ASA Version 2.7.1 and Unity 2019 LTS version, you need to setup the unity to work with Legacy XR. in the first part of the tutorial there are 3 tabs present one for XR plugin(XRSDK), Open XR and Legacy XR. please follow the Tab with Legacy WSY as in below screenshot. that should work,
![image](https://user-images.githubusercontent.com/61759322/117408351-723e3280-af2d-11eb-927e-094b4a357ec5.png)

**Comment by jstiefel** [comment]
@veeruby-developer Thanks for your response. I was just doing the first tutorial series using Unity 2019 LTS and Windows XR Plugin and was expecting that the ASA tutorial builds on this one. But it is mentioned in no place that the ASA tutorial does not support XR plugin management.

**Comment by jstiefel** [comment]
I switched from the XR Plugin to Legacy WSA and was able to build and deploy. However, I'm still getting errors in Unity and on the Hololens I just see the software window and nothing else.

![grafik](https://user-images.githubusercontent.com/44534970/117479706-f067fc80-af60-11eb-88ae-6bce44bbc1df.png)

**Comment by veeruby-developer** [comment]
@jstiefel  if you are using Legacy WSA the tutorial should work.
Build Errors in unity is due to the restsharp.dll in the project, this will be fixed in the next update.
however these build errors will not affect the tutorial process flow.

is it possible for you to share the screenshot of the "software window" you are referring to..?

**Comment by jstiefel** [comment]
> 
> 
> @jstiefel please ensure that you have enable Virtual Reality Supported and added Windows Mixed Reality
> ![image](https://user-images.githubusercontent.com/61759322/117641202-82f7de00-b1a3-11eb-818f-912669aceeed.png)
> and also ensure that you have selected the right configuration profile for Legacy WSA, it should be "DefaultHoloLens2ConfigurationProfile:"

I had it enabled. But it seems like things got messed up when I switched from XR Plugin to Legacy WSA. Created a new project and it works now. Thanks!

**Comment by jstiefel** [comment]
Need to quickly re-open this issue. I followed the next parts of the ASA tutorial, now at Part 5, building for iPhone: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-05#installing-inbuilt-unity-packages

When I installed the package ARKit XR plugin 3.1.3 for iOS, it messes things up again activating the XR Plugin Management. When I tried to remove the XR Plugin, I get the following message:

![grafik](https://user-images.githubusercontent.com/44534970/117672728-6317e880-b1aa-11eb-9750-963316a77483.png)

**Comment by veeruby-developer** [comment]
@jstiefel keep the XR plugin Installed, but make sure that non of the option there is checked,
![image](https://user-images.githubusercontent.com/61759322/118227732-ac1bb580-b4a6-11eb-890c-4ac2e3793f4a.png)

and in XR Settings (Legacy XR), ensure that only Virtual Reality Supported checkbox is checked and please remove Windows Mixed Reality SDK, that should work.
