### ISSUE TITLE
Build Fails for ARM64 with HoloLens2

### ISSUE THREAD

**Issue by veeruby-developer** [MicrosoftDocs/mixed-reality#298]
If you build the project as ARM64 and deploy to HL2, it will silently fail.   The reason is, because the Unity project isn’t setup to publish the Azure Speech plugins for ARM64:

![image](https://user-images.githubusercontent.com/61759322/117445819-ce6a7c00-af58-11eb-90d3-3186cda9e530.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bd308a-2d2c-87b4-bb20-f58805a2a813
* Version Independent ID: f2f80227-5c89-d3d4-93a7-c3df8cca8de1
* Content: [Azure Speech Services tutorials - 1. Integrating and using speech recognition and transcription - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch1)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@veeruby-developer @mr0ng Can you please make this update?

**Comment by veeruby-developer** [comment]
@hferrone we are working on this. will update you at the earliest.

**Comment by veeruby-developer** [comment]
@hferrone  this has been fixed in the latest PR #325
