### ISSUE TITLE
Conflicting Default Profiles In Instructions

### ISSUE THREAD

**Issue by mikey-mdk** [MicrosoftDocs/mixed-reality#299]
When following the spatial anchors tutorial located here...

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02

When you get to the following section the copy indicates that you will be cloning the DefaultHoloLens2ConfigurationProfile

![image](https://user-images.githubusercontent.com/83050479/117528563-b827e480-af87-11eb-8aa5-6bd7af7f65f1.png)

However when you click on the link to go to that section of the tutorial located here...

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-03?tabs=winxr#changing-the-spatial-awareness-display-option

The instructions tell you to clone the DefaultXRSDKConfigurationProfile:

![image](https://user-images.githubusercontent.com/83050479/117528611-e60d2900-af87-11eb-866f-8aef602f5e55.png)

For a novice it is difficult not knowing if there is a significant difference between these two profiles and what the downstream ramifications may be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@mikey-mdk  There are 3 Tabs present, you are referring to the XR plugin tab, so it says XRSDK profile.
if you switch to the Legacy WSA tab that will work.
Apart from the Getting started tutorials other tutorial series not yet Support Windows XR Plugin. so in the instructions it says to switch to DefaultHoloLens2ConfigurationProfile.
