### ISSUE TITLE
Unable to find Azure anchor

### ISSUE THREAD

**Issue by iluvian** [MicrosoftDocs/mixed-reality#302]
Step 8:Follow this tutorial to package the app. Unable to find Azure anchor after deleting local anchor.
debug window shows "Looking for azure anchor...please wait...
I spent seven minutes looking, but there was no new message on the window.
unity 2019.4.8
azure spatial anchor SDK :2.4

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure 空间定位点入门 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@iluvian This ASA tutorial is supported for ASA 2.7 Version refer below screenshot
![image](https://user-images.githubusercontent.com/61759322/117604191-5bd4e880-b172-11eb-947a-36abad13ea95.png)
please use ASA version 2.7.1 or 2.7.2.
