### ISSUE TITLE
unity hololens2 MRTK Folder have no SDK Folder

### ISSUE THREAD

**Issue by yexunwenjinghong** [MicrosoftDocs/mixed-reality#305]
[在此处输入反馈]
Unity Assets Folder have only shaders Folder,have no anythingelse .

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [使用求解器创建动态内容 - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality-pr.zh-cn/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@veeruby-developer Can you confirm that all Unity assets are present for this tutorial?

**Comment by veeruby-developer** [comment]
@yexunwenjinghong  if you have imported the MRTK through "MR Feature tool" you will not find anything in the Assets folder, you can find everything in Package window Packages > Mixed Reality Toolkit Foundation > SDK > Features >.
![image](https://user-images.githubusercontent.com/61759322/118075024-d8fb9a00-b3cc-11eb-9fa5-0e9432f0bcf4.png)

**Comment by yexunwenjinghong** [comment]
I'm sorry to reply late, my problem has been solved, thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 凌晨5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MicrosoftDocs/mixed-reality] unity hololens2 MRTK Folder have no SDK Folder (#305)





 
@veeruby-developer Can you confirm that all Unity assets are present for this tutorial?
