### ISSUE TITLE
Can't connect WDP from USB

### ISSUE THREAD

**Issue by GabrielFranklin** [MicrosoftDocs/mixed-reality#307]
Please help me, I followed instructions to run WDP from USB but I cant...I checked on my PC, task IpOverUsbSvc is running, and I can access via WIFI...

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Usar o Portal de Dispositivos do Windows - Mixed Reality](https://docs.microsoft.com/pt-br/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal#troubleshooting)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality-pr.pt-br/blob/live/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by hferrone** [comment]
Hi @GabrielFranklin - browsers have started to block port 10080, so we recommend using Wifi to connect, then read the IP address of the usbncm and us that for USB access to the portal. Please let me know if this works for you!
