### ISSUE TITLE
Example code in c++

### ISSUE THREAD

**Issue by StarWardo** [MicrosoftDocs/mixed-reality#31]
Could we get an example of how to scan a QR code and get the info from the code in C#? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking)
* Content Source: [mixed-reality-docs/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
@jessemcculloch Who could we bring in for this?

**Comment by hferrone** [comment]
Hi @StarWardo, give this a shot :) 

https://github.com/chgatla-microsoft/QRTracking/tree/master/SampleQRCodes
