### ISSUE TITLE
Bad listi formatting

### ISSUE THREAD

**Issue by fnunnari** [MicrosoftDocs/mixed-reality#312]
Confused listing at "Checking this box allows you to:".
The consequences of checking the box cannot be understood.
Listing is badly formatted and confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240922bb-42ba-7082-8605-50f40223ce9a
* Version Independent ID: 749d9a63-b1bd-9dce-ca82-32a6fa0006d0
* Content: [Exporting and building a Unity Visual Studio solution - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/exporting-and-building-a-unity-visual-studio-solution)
* Content Source: [mixed-reality-docs/exporting-and-building-a-unity-visual-studio-solution.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/exporting-and-building-a-unity-visual-studio-solution.md)
* Service: **unspecified**
* GitHub Login: @BrandonBray
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
Thanks @fnunnari! It looks like the formatting broke when we exported the page from the old site. It should look a lot better now :-)
