### ISSUE TITLE
Doc Update Warnings!!!

### ISSUE THREAD

**Issue by cjosewski** [MicrosoftDocs/mixed-reality#315]
I know you guys are trying to stay ahead of all of us...   but it would be nice to get consistent updates to the documentation.

As it is you're rolling them out AD HOK and it's hard to keep up.

Perhaps a versioning system to the Docs that correspond to software version releases?

Please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483d15fb-7035-b66b-a9a5-854ee1f80594
* Version Independent ID: 16328f2c-4c86-91d9-83c1-a3ade9de3dcb
* Content: [Mixed Reality Configuration Guide - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/mixed-reality-configuration-guide#feedback)
* Content Source: [mrtk-unity/configuration/mixed-reality-configuration-guide.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/configuration/mixed-reality-configuration-guide.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by hferrone** [comment]
Hi @cjosewski - We have a versioning system for these docs, it's currently only on 2.6 because we just migrated the content. New versions will be added with each new release - thanks for the callout!
