### ISSUE TITLE
there is no English-to-Mandarin translation

### ISSUE THREAD

**Issue by harrytete** [MicrosoftDocs/mixed-reality#316]
[在此处输入反馈]
Dear official,
when I change language from English to Chinese, the words on this website didn't translate, and AI translation Robot didn't work, please check this problem.
[https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/?view=mrtkunity-2021-01](url)

Thank you.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8688c8ff-81f9-705a-24eb-c255e31c54f8
* Version Independent ID: 915f7e31-a006-a871-de27-14f9f87c3244
* Content: [MRTK-Unity Developer Documentation - Mixed Reality Toolkit](https://docs.microsoft.com/zh-cn/windows/mixed-reality/mrtk-unity/?view=mrtkunity-2021-01)
* Content Source: [mrtk-unity/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/index.md)
* Product: **mixed-reality**
* GitHub Login: @polar-kev
* Microsoft Alias: **kesemple**

**Comment by hferrone** [comment]
Hi @harrytete - we're working on this issue, thanks for bringing it to our attention.
