### ISSUE TITLE
Broken Unity Mixed Reality forums link 

### ISSUE THREAD

**Issue by mreimer01** [MicrosoftDocs/mixed-reality#318]
The Unity Mixed Reality forums link has issues. It goes to a screen that states "You do not have permission to view this page or perform this action."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ac37f3-5dc8-8076-da7c-4c6d877eac49
* Version Independent ID: b58b8052-ddca-5941-3981-867baef990a5
* Content: [Unity development for HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-development-overview?tabs=arr%2Chl2#feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/unity-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/unity-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
Hi @mreimer01 - Did you sign in to Unity when prompted?

**Comment by mreimer01** [comment]
I was not prompted to sign in. Im already signed into the Unity forums and cannot access the forum section. Is it invite only?

**Comment by hferrone** [comment]
There are no invites, it's completely public. This seems like a bug on Unity's side, so you'll need to file a bug report with them (https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-#:~:text=Click%20on%20Help%20and%20select,to%20submit%20your%20bug%20report).
