### ISSUE TITLE
The first two sessions don't seem to be in the schedule at Build 2021

### ISSUE THREAD

**Issue by danielatdigital** [MicrosoftDocs/mixed-reality#320]
The first two sessions don't seem to be in the schedule at Build 2021 - I can't find them using the search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1de8e78-6bae-2163-2f8c-a9dee641a17e
* Version Independent ID: 028211e2-63af-bfe2-271e-74eae04a728a
* Content: [Microsoft Build 2021 - Mixed Reality Sessions - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/whats-new/mr-build)
* Content Source: [mixed-reality-docs/mr-dev-docs/whats-new/mr-build.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/whats-new/mr-build.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by hferrone** [comment]
Hi @danielatdigital - those are small 15 minute presentations that were part of the main build session, but not actual sessions in themselves. These don't have links yet, but we'll update as soon as we have them. Thanks!
