### ISSUE TITLE
Typo in "Target object" section

### ISSUE THREAD

**Issue by HenryGuo2003** [MicrosoftDocs/mixed-reality#321]
This property specifies which object will get transformed by the bounds control manipulation. If no object is setit defaults to the owner object.
--> 
This property specifies which object will get transformed by the bounds control manipulation. If no object is set, it defaults to the owner object.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 88931aed-f7dd-9d97-36c6-9838acdf96f6
* Version Independent ID: 0b0f869c-60aa-e077-1a00-bb04f8253e78
* Content: [BoundsControl - Mixed Reality Toolkit](https://docs.microsoft.com/zh-tw/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/bounds-control?view=mrtkunity-2021-01)
* Content Source: [mrtk-unity/features/ux-building-blocks/bounds-control.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/ux-building-blocks/bounds-control.md)
* Product: **mixed-reality**
* GitHub Login: @thalbern
* Microsoft Alias: **bethalha**

**Comment by hferrone** [comment]
Thanks for the catch!
