### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by kirillp** [MicrosoftDocs/mixed-reality#322]
Hi, we tried and got an error: CreateForWindow failed with E_INVALIDARGS and with valid HWND which is perfectly works for normal D3D11 rendering. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745996b6-93b9-0039-78e4-1dc76ac2d16e
* Version Independent ID: eb998dc5-14b5-8869-87d1-c3cbf923019c
* Content: [Getting a HolographicSpace - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/getting-a-holographicspace)
* Content Source: [mixed-reality-docs/getting-a-holographicspace.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/getting-a-holographicspace.md)
* Service: **unspecified**
* GitHub Login: @MikeRiches
* Microsoft Alias: **mriches**

**Comment by mattzmsft** [comment]
Hi @kirillp, are you saying something is wrong with the documentation? Or are you just trying to get help solving a problem with your app? If the former, please suggest a change to the docs via pull request; if the latter, you should ask for help in forums.hololens.com. We don't have anyone to troubleshoot issues through the documentation site.

**Comment by kirillp** [comment]
Thx
