### ISSUE TITLE
Closing the QRCodesManager properly

### ISSUE THREAD

**Issue by clintOngInnovations** [MicrosoftDocs/mixed-reality#326]
The QRCodesManager really needs the following if you are trying to debug in Unity.  Without it, Unity crashes when trying to start on the next run.  I was using Unity 2019.4

private void OnApplicationQuit()
        {
            StopQRTracking();
            qrTracker = null;
            capabilityTask.Dispose();
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
@chgatla-microsoft Can you confirm?

**Comment by chgatla-microsoft** [comment]
@clintOngInnovations is this when you are running it in editor? Remoting? It is not clear how closing should affect it.  when the app runs again it is a new process anyway that said it is also safe to stopQRTracking on close though. Can you clarify the details of the crash? any logs?

**Comment by clintOngInnovations** [comment]
I am using holographic remoting in Unity 2019.4.14, and it will run and I can view QR codes info (minus being able to get positions since it isn't UWP).  After running and stopping running in the editor the first time, as soon as I try to run it a second time, Unity immediately crashes.  I assumed that it was something to do with the QRTracker process still running somewhere, and disposing of it seemed to have fixed it. I am going to play with it again in the coming days and will see if I can get some log files of when it crashes without the OnApplicationQuit() code.
