### ISSUE TITLE
Issues related to Holographic Remoting for OpenXR

### ISSUE THREAD

**Issue by veeruby-developer** [MicrosoftDocs/mixed-reality#327]
Built the Desktop App for OpenXR to test Holographic Remoting from sample project  [OpenXR Mixed Reality samples repo](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples) and was able the establish connection with HoloLens, but have below issues in it.

1.  was not able to click on any of the Button on the Menu(no Pointers).
2.  on the Desktop app there is no preview being shown once it is connected to HoloLens.
![image](https://user-images.githubusercontent.com/61759322/119772890-7d0d3700-bedd-11eb-96bb-7d580b37a7aa.png)

getting this error on the console:

"OpenXR reprojection settings are not supported; missing openXR extension XR_MSFT_composition_reprojection_preview"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491e1f34-574b-1cb2-60e1-cc3a7f948610
* Version Independent ID: a2e67067-6084-58f9-4078-45a3d4d1b584
* Content: [Holographic Remoting in desktop app - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/holographic-remoting-desktop)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/holographic-remoting-desktop.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/holographic-remoting-desktop.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **alexturn**

**Comment by keveleigh** [comment]
Did you build the PC app as UWP or Windows Standalone? There's a known Unity issue on UWP, but it should work on Standalone.

**Comment by veeruby-developer** [comment]
@keveleigh Thanks for your response,
I had built PC app as UWP and had above issues.
now that you mentioned, built the PC App as Windows Standalone and was able to connect to holoLens2. but had the same issue **"was not able to click on any of the Button on the Menu(no Pointers)"** and in the console still getting this error "OpenXR reprojection settings are not supported; missing openXR extension XR_MSFT_composition_reprojection_preview".
however now preview is being shown once the App is connected to HoloLens.

Further to that, we are in progress with Updating  [PC Holographic Remoting Tutorial](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-pc-holographic-remoting-01) to support OpenXR. this tutorial includes a demonstration of 3D model manipulation, model clipping, and eye-tracking features. all of these features works perfectly with Legacy WSA.

but With OpenXR had below problems.

- **When PC App built as UWP**:  Hand interactions does not work and on the Desktop app there is no preview being shown once it is connected to HoloLens(like the sample app).

- **When PC App built as Windows Standalone** : able to see the preview on PC App and able to click the buttons only with Near interaction. rest like "far interactions", "grabbing an object with tracked hands", "eye tracking" are not working.

can you please confirm does Holographic Remoting for OpenXR supports "far interactions", "grab an object with tracked hands", "eye tracking" features ?

Thank you.

**Comment by keveleigh** [comment]
@veeruby-developer Which MRTK and Mixed Reality OpenXR package versions are you using? I'd definitely recommend updating to the latest.
Also, which profiles are you using for MRTK?

> can you please confirm does Holographic Remoting for OpenXR supports "far interactions", "grab an object with tracked hands", "eye tracking" features ?

Yep! All of these should work over Holographic Remoting for OpenXR.

**Comment by veeruby-developer** [comment]
@keveleigh  we are using **MRTK 2.7.0** and **Mixed Reality OpenXR plugin 0.9.5.**
and for MRTK profile we are using **DefaultHoloLens2ConfigurationProfile**

**Comment by keveleigh** [comment]
I'd double check that you have the Microsoft HoloLens feature set enabled and make sure you have Microsoft Hand Interaction added to the interaction profiles list

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-getting-started#configuring-xr-plugin-management-for-openxr

![image](https://user-images.githubusercontent.com/3580640/122306960-3e581480-cebe-11eb-8e68-115b604f9e36.png)
