### ISSUE TITLE
Broken link to examples.

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#33]
Broken link: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Examples/Demos/Solvers/Scenes/SurfaceMagnetismSpatialAwarenessExample.unity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8600c8a4-e7b8-288d-9481-7ab90dae39d4
* Version Independent ID: 25a6ae27-ac69-b292-3994-6c9126ab54bc
* Content: [Surface magnetism - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/surface-magnetism)
* Content Source: [mixed-reality-docs/surface-magnetism.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/surface-magnetism.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
Thanks for catching this @laultman - here is the link: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/Examples/Demos/Solvers/Scenes/SurfaceMagnetismSpatialAwarenessExample.unity. 

The docs will be updated later today.
