### ISSUE TITLE
Documentation Spelling Error

### ISSUE THREAD

**Issue by JShull** [MicrosoftDocs/mixed-reality#334]
[Spelling Error -->Audio demos are missing an asmdef file (UPM **pacakge**)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75031480-862f-2164-f57d-9dbcba2563ca
* Version Independent ID: 82f6b67a-4a68-ed40-126f-bf6ef999df8a
* Content: [MRTK 2.7 Release Notes - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-27-release-notes?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/release-notes/mrtk-27-release-notes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/release-notes/mrtk-27-release-notes.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by MaxWang-MS** [comment]
The error is now fixed. Thanks for pointing it out!
