### ISSUE TITLE
TrackedGeometry or TrackedImage

### ISSUE THREAD

**Issue by peted70** [MicrosoftDocs/mixed-reality#335]
This page flips between using OnUpdateTrackedGeometry and OnUpdateTrackedImage such that it's not clear which one should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db9ec0f-8219-f292-1ac5-6ca607125b33
* Version Independent ID: a04e35e0-a4a8-2af9-88a7-a5d44f90901b
* Content: [QR codes in Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-qr-codes?tabs=426&source=docs)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
@sw5813 Can you assist?

**Comment by typride** [comment]
Tracked geometry is used for 4.26 and image used for < 4.26.
