### ISSUE TITLE
Something is wrong with documentation for Progress Indicator

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#339]
I don't have time to detail the problems with your documentation. A well seasoned developer should reasonably be able to use the documentation as a starting point. The purpose of documentation and MRTK in particular is to decrease the friction. After three hours I still have not deciphered your absolutely the most frustrating ____ .

Write a simple example that explains how it works. 
Better one that actually works.
[Enter feedback here]

MRTK 2.7.0 preview 5 which I have to use to fix other bugs you have in the spatial mesh.
---
#### Document Details
If you take this criticism personally then you have a bigger problem. I don't care if you delete this post but fix the documentation with something that work!

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7a2016-5e4e-0393-263a-ed9a518f2af4
* Version Independent ID: 53eaf4a9-7863-0dec-57d5-dea046ce16fc
* Content: [ProgressIndicator - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/progress-indicator?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/ux-building-blocks/progress-indicator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/ux-building-blocks/progress-indicator.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by hferrone** [comment]
Thanks for the callout @laultman - we're working on it!

**Comment by hferrone** [comment]
@polar-kev Has this been updated?

**Comment by polar-kev** [comment]
@laultman can you be more descriptive about what the problem you encountered is? Are you not able to find the Progress Indicator example scene? What part of the documentation are you stuck on?

**Comment by polar-kev** [comment]
There is currently a PR open to improve the progress indicator example scene by providing more real world examples such as scene loading, async tasks, and animations.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9971

**Comment by Sean-Kerawala** [comment]
Please refer to the PR or comment on this issue if the above PR doesnt solve for the need. Thank you!
