### ISSUE TITLE
Expose C# class variables for easy tuning

### ISSUE THREAD

**Issue by dbqt** [MicrosoftDocs/mixed-reality#342]
"Make C# class variables public to expose them in the editor UI." This is not always the best way to do it, as it exposes the variables programmatically too. If we want the variables to be editable via the inspector, but not be public programmatically, it's better to keep the variable private, but give it the attribute [SerializeField]. 

Usage example:

[SerializeField] private int someValue;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f00922d-8f87-0c40-4b9c-9994be4f8f7f
* Version Independent ID: 75796fe2-31b2-734d-101d-9bf235222344
* Content: [Best practices for working with Unity and Visual Studio - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/best-practices-for-working-with-unity-and-visual-studio)
* Content Source: [mixed-reality-docs/best-practices-for-working-with-unity-and-visual-studio.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/best-practices-for-working-with-unity-and-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Guidance updated, closing issue
