### ISSUE TITLE
Windows Device Manager Error with /api/filesystem/...   (ERR_HTTP2_PROTOCOL_ERROR)

### ISSUE THREAD

**Issue by Hattexmc** [MicrosoftDocs/mixed-reality#346]
I am developing for HoloLens 2 and i need to load files into the device via Windows device manager.

**History:**
It worked properly until about the time when the new windows update version 2004 got loaded. Before that, i used to connect with my device via USB and  https://127.0.0.1:10080 which worked fine. 
After the update, this stopped working, so after some research [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal)  i found that IpoverUSB is not recommended and switched to UsbNcm. Now i can connect with the Portal again and most services seem to work, but i am not able to load files from or on to the device. 
I need to connect via USB because my Notebook is part of the company-network and my HoloLens 2 is registered to a private Account.

**Errors:**
When i try to upload a File, i am able to select a file from my drive, but after clicking on "upload", it loads for a few minutes and fails with the following output in the console:

![image](https://user-images.githubusercontent.com/81165301/122046255-f8784f00-cdde-11eb-9e4e-3996109cc89d.png)

When i try to download a file, i click on the disk- symbol and it loads again for a few minutes. After that, the following appears:
![SeiteNichtErreichbar](https://user-images.githubusercontent.com/81165301/122047323-4c376800-cde0-11eb-819e-3488060477ac.png)

Text (Translated): 
Hmmm...this page is unfortunately unavailable It looks like the website at https://xxx.xxx.xxx.xxx/api/filesystem/apps/file?knownfolderid=LocalAppData&filename=playerprefs.dat.bak&packagefullname=AOAMRTKApp_1.1.0.0_arm64__ph1m9x8skttmg&path=%5C%5CLocalState is having problems or it may have been permanently moved to a new web address. ERR_HTTP2_PROTOCOL_ERROR

The files are less than 3kB in size so this should not be the problem.
Connection works perfectly fine with Visual Studio for deployment. I double-checked developer mode, device portal enabled on HL2, and i reset the device.

**Comment by hferrone** [comment]
@jessemcculloch Can you point me in the direction of someone who might know what's happening here?

**Comment by Hattexmc** [comment]
It seems to be a problem with the browser.

Firefox works fine, but Edge and Chrome fail to do the job. 
It seems that it has nothing to do with the Windows update as previously guessed, as i noticed my company device and my private device (second laptop to try) were on different states and on both devices, 1/3 Browsers work.

Issue started in the first week of June 2021

**Comment by bphillips09** [comment]
@Hattexmc is this issue still prevalent?

**Comment by Hattexmc** [comment]
I always use Firefox where it works fine. (Currently Version 90.0.2 (32-Bit))
I just tried it with Chrome Version 92.0.4515.131 (Official Build) (64-Bit) and Edge 92.0.902.67 (Official Build) (64-Bit), it works again on both Browsers. Unfortunately i cannot tell what exactly caused or fixed the issue.
