### ISSUE TITLE
Tutorial Missing Step for RoverParts?

### ISSUE THREAD

**Issue by sourada13** [MicrosoftDocs/mixed-reality#349]
The tutorial seems to be missing a section. You are asked to create an empty object, RoverParts, and then duplicate the parts, but there are no parts underneath the object to clone. The image shows Camera, Generator, Lights, etc but there is no step to add those items to the RoverParts object. I'm not sure where to find and add those. Otherwise, these have been very helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340a4a6c-bcfc-9c46-699b-b8d3a61f5fc2
* Version Independent ID: 90437a82-b687-e409-c8ee-da4e4d1fee2f
* Content: [MRTK tutorials - 4. Positioning objects in the scene - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-04)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-04.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-04.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
you can find all the RoverParts at ** RoverExplorer > RoverAssembly > RoverModel > Parts** pleae refer the screenshot from the unity package.
![image](https://user-images.githubusercontent.com/61759322/122336881-1bc80900-cf5b-11eb-9e4f-0956cd22878a.png)
also there is instructions in tutorial to duplicate the Parts and move it to RoverParts Game Object please refer below screenshot.
![image](https://user-images.githubusercontent.com/61759322/122336717-e6bbb680-cf5a-11eb-928e-36bfc46b5396.png)

let us know this solves your issue.

**Comment by sourada13** [comment]
Thank you! Yes I found it in the end. I appreciate you responding and
clarifying too!
