### ISSUE TITLE
Voice Command not recognized

### ISSUE THREAD

**Issue by fabs-git** [MicrosoftDocs/mixed-reality#351]
None of the assigned (response) functions is reacting to speech commands from the tutorial file. I have tried speech input in other files too and still no response. Is there a way to assess whether is it only happening on my machine? How to open the MRTK black box for some feedback? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545d8e93-218e-ab72-3ce2-0f905c400b04
* Version Independent ID: b8f61664-578f-1d0b-caeb-8bdd30889e39
* Content: [Speech - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/speech?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/input/speech.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/input/speech.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@polar-kev Can you assist?

**Comment by fabs-git** [comment]
@hferrone  @polar-kev: I have been stuck with this for days. Please send any tip or suggestion I could look up! Also, are there any settings (minimum platform version, target SDK version...) that I have to adjust in my unity project? 
I can successfully use the Hololens' default commands while running my unity app (start recording, select, stop recording, etc.), but not the custom commands I set in the Unity MRTK_Input_Speech.

**Comment by m-the-hoff** [comment]
Have you checked the following: 

On HoloLens, go to Settings->Privacy->Speech and turn on speech recognition.

Under Settings->Privacy->App Permissions->Microphone, ensure enabled
Under Settings->Privacy->App Permissions->Voice Activation, ensure enabled

In Unity->Player Settings->UWP tab->Publishing Settings->Capabilities->Microphone (checked)

Does "Hey Cortana" work on the device?  Like: "Hey Cortana, what's my IP?"
