### ISSUE TITLE
SpatialAnchorManager is improperly configured

### ISSUE THREAD

**Issue by ttkrpink** [MicrosoftDocs/mixed-reality#353]
As indicated in the tutorial, adding the following components is required.
ARSessionOrigin (Script)
ARAnchorManager (Script)

However, after adding these two, the "SpatialAnchorManager is improperly configured" error message is still there. If I forced to start a session and create an anchor, the app will crash on Hololens. The following is my setup.

Unity 2020.3.11
MRTK 2.6.2
OpenXR 0.9.5
ASA SDK 2.9.0
DefaultOpenSRConfigurationFile is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by gllebede** [comment]
Do you see any other messages in the output like "Need an enabled ARCameraManager in the scene" or "The anchor prefab for ARAnchorManager must be set to null."? 

If there isn't anything like this then most likely Spatial Perception Access is not granted. You can enable it on the Windows Store Build Settings select Publishing Settings by adding the “SpatialPerception” capability:

![image](https://user-images.githubusercontent.com/36988895/122949595-b2d5fc00-d373-11eb-8589-f061d9ae45dc.png)

**Comment by ttkrpink** [comment]
Here is my setup. The output has "Need an enabled ARCameraManager in the scene"  message. and the "SpatialAnchorManager is improperly configured". Are there other things I can do to find the problem?

![image](https://user-images.githubusercontent.com/2522889/123367789-26af1900-d5ad-11eb-9fac-03d5bca4e58a.png)
![image](https://user-images.githubusercontent.com/2522889/123367870-50684000-d5ad-11eb-9ed5-b8265f42d5f5.png)

**Comment by ttkrpink** [comment]
I got to the tutorial's 4th step by the following change:
1. using the Azure Spatial Anchor tutorial's "AnchorModuleScript". The multi-user tutorial script has two error messages.
2. using the Windows Mixed Reality in the XR Plug-in Management. Using OpenXR will have error messages.
3. following the [post](https://www.reddit.com/r/HoloLens/comments/mni5q0/mrtk_azure_spatial_anchors_unity_tutorials/), watzizname gave out a sultion.

So far, the tutorial works till step 4. Step 5 does not work.

**Comment by hferrone** [comment]
@ttkrpink Do you have any full logs for us to take a look at?

**Comment by ttkrpink** [comment]
I used ASA 2.10.0 for other projects, Those projects seem fine. I guess have to reimport everything for this messy project. Closing this issue, thanks for all your help.
