### ISSUE TITLE
Unity App in C#

### ISSUE THREAD

**Issue by whohlfeld** [MicrosoftDocs/mixed-reality#353]
As many Hololens Apps are built with unity and also the tutorial from Microsoft is based on creating projects with Unity it would be nice to adapt this description to fit to such an app which is written in C# and not C++ as well. Help would be much appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a192e3ab-0496-d94d-f535-a79147e4a71d
* Version Independent ID: d13d1082-0574-e470-6230-978d683a9e1a
* Content: [Add holographic remoting - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/add-holographic-remoting)
* Content Source: [mixed-reality-docs/add-holographic-remoting.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/add-holographic-remoting.md)
* Service: **unspecified**
* GitHub Login: @MikeRiches
* Microsoft Alias: **mriches**

**Comment by jessemcculloch** [comment]
Going through old issues, is this one still relevant and need to keep open?

**Comment by yugen12** [comment]
Yes please
