### ISSUE TITLE
Is the collider information correct?

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/mixed-reality#354]
The documentation states if you want to use the Near Interaction Grabbable that a Collider should be added, but it then informs the reader that it's not needed because it has already being added to the prefab. HOWEVER, the Near Interaction Grabbable only calls GetComponents not GetComponentsInChildren so it doesn't find the collider and complains at run time;
'NearInteractionGrabbable requires a BoxCollider, SphereCollider, CapsuleCollider or a convex MeshCollider on an object.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
Hey @paulio tutorial does not say to add the Collider component, it states that **"Collider" component is required on an Object to use Near Interaction Grabbable and Object  Manipulator**, and in the note it is not mentioned that Collider is not needed it is mentioned that **"Collider" has already been added to the object so no need to add again**.

> HOWEVER, the Near Interaction Grabbable only calls GetComponents not GetComponentsInChildren so it doesn't find the collider and complains at run time;

thanks for pointing this mistake, we will update the Cube prefab and add the box collider to the parent object, that should fix this error.
