### ISSUE TITLE
The information for play mode remoting is not latest after MR openxr plugin 1.0 released

### ISSUE THREAD

**Issue by yl-msft** [MicrosoftDocs/mixed-reality#356]
The information on this page is not latest, such as the "menu" screenshot, or the dialog titles.

The feature now is named as "Holographic Remoting for Play Mode".

@yl-msft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96964557-d6ea-4d0f-e3b8-2a4976860590
* Version Independent ID: ace2aa93-4c83-bbfa-a063-e5550f60e8be
* Content: [Unity Play Mode - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-play-mode?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/unity-play-mode.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/unity-play-mode.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@thetuvix Were these addressed in your latest update, or was that just the text?

**Comment by keveleigh** [comment]
@hferrone they still look out of date. I'll open a PR!
