### ISSUE TITLE
After deploy app error

### ISSUE THREAD

**Issue by BalazsAti** [MicrosoftDocs/mixed-reality#357]
After deploying the app to Hololens 2 device, the app does not open, or work. The app create a window, and do no run.

I use unity 2019.4.28f1, visual studio 2019 Version 16.10.2, Windows 10 19043.1052. I made every step that microsoft docs write, with legacy xr.

**Comment by hferrone** [comment]
Hi @BalazsAti - can you give me some more information on what kind of app you're deploying, and what specific article you're following?

**Comment by BalazsAti** [comment]
Hi! I am building the test app. https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=wsa

**Comment by hferrone** [comment]
@veeruby-developer Can you help?

**Comment by veeruby-developer** [comment]
Hey @BalazsAti please ensure below points:

- Ensure that Under Player XR Settings Ensure that ** Virtual Reality Supported** is Enabled and **Windows Mixed Reality** SDK is added
![image](https://user-images.githubusercontent.com/61759322/124062834-17b5e400-da4f-11eb-8127-6936adf1aedf.png)
- Ensure that right configuration profile is selected
![image](https://user-images.githubusercontent.com/61759322/124062934-59468f00-da4f-11eb-9cf6-26e742ece92b.png)
