### ISSUE TITLE
Failed to connect to Azure storage on Hololens2 device

### ISSUE THREAD

**Issue by nra20** [MicrosoftDocs/mixed-reality#36]
[Enter feedback here]
Good afternoon,

I was following the Azure storage tutorial and was able to run the app in the Unity Editor just fine, but when I deployed it to the app and attempted to set an object I was met with this error:
'Failed to connect with Azure Storage. If you are running with the default storage emulator configuration, please make sure you have started the storage emulator.'

Is there a solution or work around for this?

Thank you,
Nick 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15853f4-20ac-bea9-89b0-4cd7da19a5be
* Version Independent ID: 398529a4-fee0-21bb-6cc6-b57b47d25ea1
* Content: [Azure Cloud Tutorials - 2. Integrating Azure Storage - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-azure-02#writing-and-reading-data-from-azure-table-storage)
* Content Source: [mixed-reality-docs/mr-learning-azure-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-azure-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by nra20** [comment]
> Hi @nra20 , we're working on finding the fix for this on another open ticket: #28. I'll update you when we have something!

**Comment by nra20** [comment]
> > Hi @nra20 , we're working on finding the fix for this on another open ticket: #28. I'll update you when we have something!

Hi @hferrone  thank you for the reply. Was anyone able to figure out why this error occurs?

Best,
Nick

**Comment by hferrone** [comment]
Hi @nra20, check out the suggested fix here https://github.com/MicrosoftDocs/mixed-reality/issues/28
