### ISSUE TITLE
Not moveable in Hololens2

### ISSUE THREAD

**Issue by SeanBrennan8** [MicrosoftDocs/mixed-reality#360]
The cube is moveable in unity by using the mouse. It is not moveable when using the hololens, i can see the "Hello World" box but cant move it. Am i supposed to be able to move it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@veeruby-developer Can you assist?

**Comment by veeruby-developer** [comment]
@SeanBrennan8  yes you should be able to move the cube on HoloLens2. can you provide us more details,
like Unity version, MRTK version, and are you using openXR or XRSDK or LegacyWSA and also which is the MRTK profile you used?

**Comment by SeanBrennan8** [comment]
@veeruby-developer i am using unity version 2020.3.12f1. I am using the MRTK.HoloLens2.Unity.Tutorials.Assets.GettingStarted.2.5.0.1.unitypackage. I am using openXR and sorry i am not sure what MRTK profile.

**Comment by veeruby-developer** [comment]
@SeanBrennan8 I think **Microsoft Hand Interaction profile** in the Interaction profile feature set has been removed by mistake, 
![image](https://user-images.githubusercontent.com/61759322/123743209-8289e280-d8ca-11eb-82e0-defb0d6b7198.png)
please add the **Microsoft Hand Interaction profile** by clicking on + icon. 
That should fix your issue.
and also ensure that you have selected the **DefaultMixedRealityConfigrationProfie**.
![image](https://user-images.githubusercontent.com/61759322/123743380-c846ab00-d8ca-11eb-87c7-5543b15c7651.png)
