### ISSUE TITLE
Configuring the buttons to operate the scene Clarifaction

### ISSUE THREAD

**Issue by jjantzer** [MicrosoftDocs/mixed-reality#364]
Under the header "Configuring the buttons to operate the scene", The tasks for each button could use more clarity

- Assign the ParentAnchor object _(under the scene tab)_ to the None (Object) field
- From the No Function dropdown, select AnchorModuleScript > StartAzureSession () to set this function as the action to be executed when the event is triggered

The ParentAnchor Object must be selected from the "scene" tab and not the default "assets" tab. Selection from the assets tab will result in a successful build,. however a NullReferenceException when deployed in the app as the object referenced is the prefab asset, and not Game Object in the scene. When rebuilt with the reference to the scene object, the app worked as intended. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
Hey @jjantzer why do you feel that ParentAnchor Object must be selected from the Assets folder, because it is nowhere mentioned in the tutorial to drag the ParentAnchor Object from the Assets folder. 
we add the Objects present in Assets folder into the Hierarchy at the start of the tutorial to work on these objects in the scene.

also you could see in the screenshot that ParentAnchor Object in the scene is drag and dropped.
![image](https://user-images.githubusercontent.com/61759322/123616329-cf66ae00-d823-11eb-8b29-e0a375b795d3.png)

**Comment by jjantzer** [comment]
The issue I had is under the On Click () component, when selecting the object to assign the function, searching for ParentAnchor yields the prefab unless the scene tab is selected at the top of the search frame. If the prefab is selected, a script can still be assigned, in this case StartAzureSession, but the object (prefab) is not in the scene, and it gives a NullReferenceException when deployed in the HoloLens.

The guide does not state that the ParentAnchor should be dragged and dropped into None (Object) field, just simple says assign which by clicking the target next to the field opens a search box which is the most intuitive method of assigning an object. I'm new to Unity and have a lot to learn, but the I still feel the tutorial could be more clear in this aspect. 

![Screenshot 2021-06-28 103124](https://user-images.githubusercontent.com/78400264/123654374-045f0a80-d7fc-11eb-8909-5a0e0caf6439.png)
