### ISSUE TITLE
DataManager prefab error

### ISSUE THREAD

**Issue by kroodl21** [MicrosoftDocs/mixed-reality#365]
![image](https://user-images.githubusercontent.com/34234312/123584723-b6fc8200-d796-11eb-8793-335e491df729.png)
Cannot manipulate DataManager prefab due to an error that says "Please remove the CanvasRendere component from the GameObject as this component is no longer necessary"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45a901a-51fd-81b7-c2b9-22e78a7afeed
* Version Independent ID: 32b6e26d-280a-6239-a9bc-6f3bbe68c868
* Content: [Azure Cloud Services for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-01)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by veeruby-developer** [comment]
@kroodl21  if you are using OpenXR and XRSDK please note that these tutorials are not yet been updated.
please provide us more info at what stage you are getting this error.

**Comment by bphillips09** [comment]
@kroodl21 Can you provide more information?

**Comment by typride** [comment]
Closing as there's no response, can reopen if necessary.
