### ISSUE TITLE
Suspending mesh observation: CoreServices does not exist in the current context

### ISSUE THREAD

**Issue by jstiefel** [MicrosoftDocs/mixed-reality#366]
I'm trying to suspend and restart mesh observations according to this example with MRTK 2.6 in Unity 2019.4.26: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/usage-guide?view=mrtkunity-2021-05#starting-and-stopping-all-mesh-observation

```
// Resume Mesh Observation from all Observers
CoreServices.SpatialAwarenessSystem.ResumeObservers();

// Suspend Mesh Observation from all Observers
CoreServices.SpatialAwarenessSystem.SuspendObservers();
```

However, I get the error message

```
The name 'CoreServices' does not exist in the current context
```

What I'm trying to do is to turn off any occlusions of holograms due to the environment for a specific GameObject. I would like to place a hologram at the real place of an object an be able to see it. The easiest solution I could think of is to completely stop all mesh observation. But can anyone tell me why `CoreServices` are not found?

Any other ideas how this can be achieved for a single GameObject and not the complete scene?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fdd7544-8c4e-ea7c-6d2f-00053360ec62
* Version Independent ID: 699e448a-c996-bdc7-ea48-94493109ccf7
* Content: [UsingGuide - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/usage-guide?view=mrtkunity-2021-05#starting-and-stopping-all-mesh-observation)
* Content Source: [mrtk-unity/features/spatial-awareness/usage-guide.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/spatial-awareness/usage-guide.md)
* Product: **mixed-reality**
* GitHub Login: @davidkline-ms
* Microsoft Alias: **davidkl**

**Comment by davidkline-ms** [comment]
This is a static class that should be always available, so this feels like there may be a missing namespace. Does your file have
using Microsoft.MixedReality.Toolkit; ?

If so, would you be willing to share your script so that we could try to reproduce the issue locally?

**Comment by jstiefel** [comment]
> 
> 
> This is a static class that should be always available, so this feels like there may be a missing namespace. Does your file have
> using Microsoft.MixedReality.Toolkit; ?
> 
> If so, would you be willing to share your script so that we could try to reproduce the issue locally?

Thanks, this was it. I was missing the information about the namespace. Couldn't find this in the corresponding documentation.

**Comment by BitterDone** [comment]
Thank you @davidkline-ms, I had these other using statements but not Microsoft.MixedReality.Toolkit. 

Interestingly, the MRTK Scene Understanding sample works fine in Unity and on my HoloLens, but it doesn't have that using Microsoft.MixedReality.Toolkit statement in either the DemoSceneUnderstandingController or DemoSpatialMeshHandler class.
