### ISSUE TITLE
Multi-user Capabilities Tutorials requires update

### ISSUE THREAD

**Issue by CharlesWilliamW** [MicrosoftDocs/mixed-reality#368]
[Enter feedback here]
I tried to follow https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-02
However, the links about creating and preparing the Unity project have been updated to use new versions of Unity and MRTK.
I get compile errors [MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.4.0.unitypackage](https://github.com/microsoft/MixedRealityLearning/releases/download/multi-user-capabilities-v2.4.0/MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.4.0.unitypackage)
Could you update this tutorial or provide the Unity and MRTK versions to run the tutorial?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06844159-dbd8-246c-5265-9757ef956d25
* Version Independent ID: 92f139c0-1b0f-4652-c8d2-7463aa3c44d9
* Content: [Setting up Photon Unity Networking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-02#feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
We're actively working on updating these, stay tuned!
