### ISSUE TITLE
QR codes with Logos documentation

### ISSUE THREAD

**Issue by camnewnham** [MicrosoftDocs/mixed-reality#37]
Not sure if this is sufficient enough information to add to the docs, but the current documentation states _"QR codes with logos have not been tested and are currently unsupported."_ 

I have tested this feature with QR codes partially obscured i.e. a normal code with a logo, other image, or general obstruction placed over the center. The feature was tested with the sample project from @chgatla-microsoft at https://github.com/chgatla-microsoft/QRTracking/tree/master/SampleQRCodes

This works as expected. The QR code is detected and oriented correctly as long as the code is correctly generated with an error correction level that supports the amount of obscurity: https://en.wikipedia.org/wiki/QR_code#Error_correction. The caveat is the usual one for error corrected QR codes, that the code becomes more complex (more bits are included) and may be more difficult to detect than a non-obscured non-error-tolerant code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking)
* Content Source: [mixed-reality-docs/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
@chgatla-microsoft Can you confirm?

**Comment by chgatla-microsoft** [comment]
Even though certain logos work not all logos might work. Currently the platform does not support the logo QR codes. But nothing is preventing users to try out and see what works for them but they are not officially surported.
