### ISSUE TITLE
Typo, Intel "Xenon" 

### ISSUE THREAD

**Issue by eroldan** [MicrosoftDocs/mixed-reality#370]
In paragraph "High Resolution Headset Requirements" says "Intel Xenon"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e694a30a-96e3-995a-19db-037e7e8747ed
* Version Independent ID: 05d92353-ad6c-58a3-d863-b9ad60c04447
* Content: [Windows Mixed Reality PC compatibility guidelines - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/windows-mixed-reality-minimum-pc-hardware-compatibility-guidelines#compatibility-guidelines)
* Content Source: [enthusiast-guide/windows-mixed-reality-minimum-pc-hardware-compatibility-guidelines.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/windows-mixed-reality-minimum-pc-hardware-compatibility-guidelines.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
@tesych Can you confirm?
