### ISSUE TITLE
The Step: Click the left mouse button to start the tap-to-place process.  Doesn't work.

### ISSUE THREAD

**Issue by Secret-Lin** [MicrosoftDocs/mixed-reality#372]
[Enter feedback here]
The Step: Click the left mouse button to start the tap-to-place process.  Doesn't work. (Solved)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a441bd4f-7fb9-780a-696c-6b07fee8c179
* Version Independent ID: 76453e28-721e-92ee-122c-f1f5ca571377
* Content: [Creating dynamic content using Solvers - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-05)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by Secret-Lin** [comment]
Besides, Press-and-hold the mouse and drag the mouse do not change the camera view, it ony change the view in Scene.

**Comment by Secret-Lin** [comment]
Well, there is an error happen while in play mode:
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.MixedRealitySceneContent.InitializeSceneContent () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f9119e214301-1624605940213/Core/Utilities/SceneContent/MixedRealitySceneContent.cs:115)
Microsoft.MixedReality.Toolkit.MixedRealitySceneContent+<InitializeSceneContentWithDelay>d__8.MoveNext () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f9119e214301-1624605940213/Core/Utilities/SceneContent/MixedRealitySceneContent.cs:75)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72beca6012c7404d8521ba134a35bf68>:0)

It says the MixedRealitySceneContent has an object reference and it is set to non-object. But I can't find that reference and I can't  solve it.

**Comment by veeruby-developer** [comment]
these errors does not seem to be from the tutorial implementation, can you provide us more details,
like Unity version, MRTK version, and are you using openXR or XRSDK or LegacyWSA and also which is the MRTK profile you used?

**Comment by hferrone** [comment]
@Secret-Lin Can you send us some full logs and detailed implementation instructions on how you're setup?

**Comment by Secret-Lin** [comment]
> these errors does not seem to be from the tutorial implementation, can you provide us more details,
> like Unity version, MRTK version, and are you using openXR or XRSDK or LegacyWSA and also which is the MRTK profile you used?

For Unity, it is 2019.4.28f1c1.
For MRTK, it is latest version, which is 2.7.2 for Foundation.



> @Secret-Lin Can you send us some full logs and detailed implementation instructions on how you're setup?

I think I strictly follow the toturial and what logs do you want? l am a freshman in this area.  -v-

**Comment by Secret-Lin** [comment]
Well! Problem Solved!
In the first and second step of toturial. I followed the ch-veision. Then, I reallize it has some problem then I switch to en-veision.  But I do not redo the first two steps.
Today, I redo the first two steps, the problem is solved.
Anyway, Thanks for your reply and help!! -v-
