### ISSUE TITLE
Subject is about Performance Optimization - Gives On Instruction of Download

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#376]
A nice discussion on optimization. There seems to be some tooling to do this. No link is provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3da8de1e-b87c-425f-8074-ea48143223fc
* Version Independent ID: 3d5f3f97-daf6-ee5c-6302-3e54976e77d2
* Content: [Optimize window - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/tools/optimize-window?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/tools/optimize-window.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/tools/optimize-window.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@polar-kev Do you have a link for the mentioned tooling?

**Comment by laultman** [comment]
Performance Getting Started - Mixed Reality Toolkit | Microsoft Docs<https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/performance/perf-getting-started?view=mrtkunity-2021-05> (Sorry, I clicked the GitHub link in the page, assumed it gave the page link.)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by polar-kev** [comment]
@laultman, the Optmization Window can be brought up by navigating to Mixed Reality>Utilities>Optimize Window" from the top bar menu in Unity,
![image](https://user-images.githubusercontent.com/30964480/125685621-a8c5e69e-937f-49c0-9d87-e8eece53c0c9.png)

@hferrone, can you add the above to the docs page?
