### ISSUE TITLE
Feature request: OpenXR Editor Remoting ability to check connectivity of remote device

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#378]
Hello,

Sometimes the OpenXR Editor Remoting won't be able to connect to a remote device (ex: when the device fell asleep, or IP address is wrong, etc)

It would be nice if there was a way inside the Editor Remoting tab to check if a device is connectable or not. Like a "Check Connection" button that the user pushes to see if the connection is successful or not. That way the user doesn't have to push Play and has to wait / restart, just to determine that there's a network problem.

Versions: MRTK 2.7.2; Holographic Remoting 2.6.0.0; Unity 2020.3; OpenXR 1.2.3

---
Tagged people: @yl-msft thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96964557-d6ea-4d0f-e3b8-2a4976860590
* Version Independent ID: ace2aa93-4c83-bbfa-a063-e5550f60e8be
* Content: [Unity Play Mode - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-play-mode?tabs=openxr#holographic-remoting-setup)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/unity-play-mode.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/unity-play-mode.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by typride** [comment]
Closing as seems to be acknowledged and older now.
