### ISSUE TITLE
MRTK is missing but it is in my project?

### ISSUE THREAD

**Issue by Secret-Lin** [MicrosoftDocs/mixed-reality#379]
![捕获](https://user-images.githubusercontent.com/49646932/125879511-a427e519-653a-4c78-a5c8-512cc503fc74.PNG)
I was trying to modify the Onclick() in the Events in the intractable section. It raise up an error "MRTK is missing". But MRTK is in my project and I try to click "MRTK > Add to Scene and Configure", it only highlights the MRTK in my Hierachy.

The probelm is solved by redo everything. -v-
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d5ccf2-6270-b146-f5ca-3da70c886028
* Version Independent ID: 23fdfa60-4d98-86d3-a069-fdd316a3bd23
* Content: [Creating user interfaces - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-06)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment]
HI @Secret-Lin, can you let me know which version of Unity and the MRTK you're using? Thanks!

**Comment by typride** [comment]
Closing due to no response to question posed by @bphillips09 . Can reopen if need be.
