### ISSUE TITLE
Emulator Device Registration - Install MRTK Examples Hub

### ISSUE THREAD

**Issue by 784651** [MicrosoftDocs/mixed-reality#383]
I am attempting to install the MRTK Examples Hub on my Hololens Emulator. I have logged into the device using my Microsoft Account. In the Portal, account.microsoft.com/devices, I can see the Hololens emulator as a device. When attempting to install the MRTK Examples hub using this URL, https://www.microsoft.com/en-us/p/mrtk-examples-hub/9mv8c39l2sj4?activetab=pivot:overviewtab I get an error stating, "It looks like you don’t have any applicable device(s) linked to your Microsoft account. To install, sign in on a device with your Microsoft account."

I've waited about 10 hours to see if it's a cache issue, but am still not able to install. Also logged out, private window, cleared cookies, etc. 

When using the emulator, **Should I be able to install Hololens Apps to my emulator in this manner**? If not, I would like this called out more explicitly, and if so, instructions/directions how to properly register the device. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by pbarnettms** [comment]
@784651 The product page you link shows that the system requirements for the app are an ARM architecture.  The emulator, as documented, requires apps to be built for x86 or x64.  Therefore, that particular app will not work and the error you are receiving is correct.

That said, going through sign in in the emulator just to install this app is the long way to do it.  You can get the MRTK x86 build by going to the github project (https://github.com/Microsoft/MixedRealityToolkit-Unity), scroll down to 'Build Status', click on the Azure Pipeline link and then download the x86 artifact, which will give you the appx.  You can then use the in-device app installer or Device Portal to sideload the appx.

**Comment by 784651** [comment]
This is awesome! Thank you!
