### ISSUE TITLE
the app is stuck  at loading on my hololens 2

### ISSUE THREAD

**Issue by ahmed-saber-gomaa** [MicrosoftDocs/mixed-reality#384]
I have followed the tutorial "Getting started with azure spatial anchors" step by step. Nevertheless, when the app is deployed on the hololens 2, all I can see is the loading screen (the 4 spheres). 

side note: I loaded ASA SDK from the Mixed Reality Feature Tool.

I hope someone cold help, Thanks :D

**Comment by bphillips09** [comment]
HI @ahmed-saber-gomaa, can you let me know the version info for the tools you are using?
- Unity Version
- ASA Version
- MRTK Version
- If you are using OpenXR

**Comment by ahmed-saber-gomaa** [comment]
hi @bphillips09 , thanks for the response. The fault was from my side. I was using an outdated windows XR plugin.
