### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by Psoffie009** [MicrosoftDocs/mixed-reality#386]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7da38f-67f0-9558-e3ec-d1ca87a782e0
* Version Independent ID: 0dc68b17-ee6d-0ae3-31da-792bf0b5deab
* Content: [Getting started with OpenXR - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started#using-preview-extensions)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/native/openxr-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/native/openxr-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by bphillips09** [comment]
@Psoffie009 Can you provide more information?
