### ISSUE TITLE
Cannot find Azure Spatial Anchors

### ISSUE THREAD

**Issue by satokazu1957** [MicrosoftDocs/mixed-reality#387]
[Enter feedback here]
I made a application along with the first part of the chapter 2.
Start azure session and finished the azure anchors successful.
But cannot fid azure anchor.

The debug window shows that the app finding azure spatial anchor.
Azure dashboard show that the anchor was created.
HoloLens2 tracking data show that the anchor is placed.

I tried the tutorial so many times with several different unity version and mrtk, ASA SDK, according to the tutorial.
This time, I tried with
• Unity 2020.3.12f1
• MRTK 2.7.2
• ASA SDK 2.10.1

How or what shall I check to clear this trouble?

![20210721_101232_HoloLens](https://user-images.githubusercontent.com/36905108/127086595-6a97591b-ec43-42cd-a3df-e63bfe3643df.jpg)
![azure](https://user-images.githubusercontent.com/36905108/127086690-bb1e2232-81f9-457a-8a5b-66bf86ded65f.jpg)
![spatial anchors](https://user-images.githubusercontent.com/36905108/127086810-0c732419-cda6-44eb-809e-8ab8d054a335.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment]
Hi @satokazu1957, we are currently working on updating our ASA tutorial docs - can you try importing this [updated GettingStarted package](https://github.com/microsoft/MixedRealityLearning/releases/download/getting-started-v2.7.2/MRTK.HoloLens2.Unity.Tutorials.Assets.GettingStarted.2.7.2.unitypackage) and seeing if that resolves your issue?

**Comment by satokazu1957** [comment]
Hi @bphillips09 , I tried the updated GettingStartedPackage.
I made two projects, one is "Open XR" and one is "Windows XR plugin".
But both are work not good.
Open XR project is stopped at creating Azure anchor.
Windows XR plugin project is stopped at finding Azure anchor.

<Open XR project>
Unity 2020.3.12f1
MRTK Foundation / Standard Assets2.72
Azure Spatial Anchors SDK core / Windows 2.10.2
Mixed Reality OpenXR Plugin 1.0.1
Getting Started Package 2.7.2 (you announced me)
MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.XRplugginManagement.2.5.3.unitypackage
AR Foundation 4.1.7
HoloLens2 (21H1  OS build 20348.1010

![20210729_134312_HoloLens](https://user-images.githubusercontent.com/36905108/127437750-eb010047-1ba4-4b7b-b7a3-4f97ba9e1cae.jpg)


<Windows XR Plugin project>
Unity 2020.3.12f1
MRTK Foundation / Standard Assets2.72
Azure Spatial Anchors SDK core / Windows 2.10.2
Getting Started Package 2.7.2 (you announced me)
MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.XRplugginManagement.2.5.3.unitypackage
AR Foundation 4.0.12
HoloLens2 (21H1  OS build 20348.1010

![20210729_141256_HoloLens](https://user-images.githubusercontent.com/36905108/127437742-3db6ba38-aba4-432d-b827-f30656de7cbd.jpg)

**Comment by satokazu1957** [comment]
But I progress the tutorial to the "3. Saving, retrieving, and sharing Azure Spatial Anchors", Azure Spatial Anchor is shared by two HoloLens, one is HoloLens1 and other is HoloLens2.
The project is dependent on the WindowsXR Plugin tutorial.

**Comment by ahmed-saber-gomaa** [comment]
@satokazu1957 I didn't get your last comment. Do you mean that you were able to share an Anchor with two hololens devices?

**Comment by satokazu1957** [comment]
@ahojnnes  I could have shared the Azure Spatial Anchors between two HoloLens.
But the instruction "Trying the basic behaviors of Azure Spatial Anchors", of next url was not work good.
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02?tabs=winxr

1. Move the cube to a different location
2. Start Azure Session
3. Create Azure Anchor (creates an anchor at the location of the cube).
4. Stop Azure Session
5. Remove Local Anchor (allows the user to move the cube)
6. Move the cube somewhere else
7. Start Azure Session
8. Find Azure Anchor (positions the cube at the location from step 3)
9. Delete Azure Anchor
10. Stop Azure session

From 1 to 7 work no problem, but when try "8", hololens waiting to find azure anchor and never go ahead.
When pass the "5", "8" work good.

So I go ahead the tutorial to "4. Displaying feedback from Azure Spatial Anchors", the Azure spatial anchors could be shared by two hololens.

**Comment by oafolabi-msft** [comment]
@satokazu1957, is this still an issue for you, or did the suggestion resolve the problem?

**Comment by satokazu1957** [comment]
I tried the "Multi-user capabilities tutorial".
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-01
I proceeded with the tutorial. And I have checked the results every chapter.
"Connecting multiple user" and "Sharing object movements with multiple users" chapter have no trouble.
At this point I tried the check with HoloLens 2 and PC.
But final result was not work good.

I have two troubles.

One.
After stating azure session, when click "Create Azure Anchor button", the table anchor go away.
I guess the origin of the table anchor may be where the origin of the HoloLens was at the stating the app.

Two
And second HoloLens start app, starting azure session, when click "Get Azure Anchor button", the table anchor went near (or same ) table anchor of the first HoloLens but coordination is not different. It seems 90 degree rotated.

=================
My environment is bellow,

• Unity 2020.3.12f1
• MRTK 2.7.2
• ASA SDK 2.10.2
• MRTK.HoloLens2.Unity.Tutorials.Assets.GettingStarted.2.7.2.unitypackage
• MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.2.7.2.unitypackage
• MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.7.2.unitypackage

**Comment by satokazu1957** [comment]
> @satokazu1957, is this still an issue for you, or did the suggestion resolve the problem?

I have still troubles on the tutorial, "Multi-user capabilities tutorial".
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-01

**Comment by shrutipistolwala-tech** [comment]
This worked for me you can try : Update ASA Core and for ASA for Windows SDK to 2.10.2 (latest version) using Mixed Reality Feature Tool. If you cant see new versions click refresh in the lower left corner.

**Comment by satokazu1957** [comment]
> This worked for me you can try : Update ASA Core and for ASA for Windows SDK to 2.10.2 (latest version) using Mixed Reality Feature Tool. If you cant see new versions click refresh in the lower left corner.

@shrutipistolwala-tech thanks,
But now I checked the version of ASA core and ASA windows SDK, both were 2.10.2 already, Mixed Reality Feature Tool say.
Azure Spatial Anchors could be created correctly and share on  my Azure by the 1st HoloLens, and the 2nd HoloLens get the Azure Spatial Anchor from my Azure but cannot placed the anchor object to the correct place.
The debug window of the 2nd HoloLens showed that get the Azure Spatial Anchor successful, and place the anchor successful, but the anchor of the 2nd HoloLens is different from the 1st one.

What shall I check on this project?

At all I want create the HoloLens app. which support Azure Spatial Anchors and Photon at the same time. 
It will help me to create the useful UX test platform which can be used both in the same room and in the globally different  place  at the same time.

**Comment by shrutipistolwala-tech** [comment]
@satokazu1957 I would suggest that if this doesn't work redo the tutorial as if you miss any step it will not work otherwise it works fine for me atleast.

**Comment by satokazu1957** [comment]
> @satokazu1957 thanks for all of this info. It seems like the first issue that you mention ("the token service encountered an error") is related to credentials, I would check that they are correct in the SpatialAnchorManager object in your Unity scene. The second issue that you mention where you are never returned anchors is concerning. Are you able to reproduce the same issue with our [ASA Unity sample](https://github.com/Azure/azure-spatial-anchors-samples/tree/master/Unity) or the [MROpenXR+ASA Unity sample](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/AzureSpatialAnchorsSample)? Thanks!

So I have no time to update my project, I will rebuild my project with new samples in the near furrure!
Thanks!

**Comment by typride** [comment]
Closing issue, can reopen if not resolved.

**Comment by SunTBurst** [comment]
> Hi @bphillips09 , I tried the updated GettingStartedPackage. I made two projects, one is "Open XR" and one is "Windows XR plugin". But both are work not good. Open XR project is stopped at creating Azure anchor. Windows XR plugin project is stopped at finding Azure anchor.
> 
> Unity 2020.3.12f1 MRTK Foundation / Standard Assets2.72 Azure Spatial Anchors SDK core / Windows 2.10.2 Mixed Reality OpenXR Plugin 1.0.1 Getting Started Package 2.7.2 (you announced me) MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.XRplugginManagement.2.5.3.unitypackage AR Foundation 4.1.7 HoloLens2 (21H1 OS build 20348.1010
> ![20210729_134312_HoloLens](https://user-images.githubusercontent.com/36905108/127437750-eb010047-1ba4-4b7b-b7a3-4f97ba9e1cae.jpg)
> 
> Unity 2020.3.12f1 MRTK Foundation / Standard Assets2.72 Azure Spatial Anchors SDK core / Windows 2.10.2 Getting Started Package 2.7.2 (you announced me) MRTK.HoloLens2.Unity.Tutorials.Assets.AzureSpatialAnchors.XRplugginManagement.2.5.3.unitypackage AR Foundation 4.0.12 HoloLens2 (21H1 OS build 20348.1010
> ![20210729_141256_HoloLens](https://user-images.githubusercontent.com/36905108/127437742-3db6ba38-aba4-432d-b827-f30656de7cbd.jpg)

I met a similar problem(Create Azure Anchor (creates an anchor at the location of the cube). Could you tell me how you solved it?
