### ISSUE TITLE
Hardware update

### ISSUE THREAD

**Issue by durante** [MicrosoftDocs/mixed-reality#387]
The biggest downside to the Spectator view mount is that is all screwed together. For such a price, not too many people would have one dedicated to Spectator view. 

I decided to upgrade the Spectator view for easier use. Based on the original design, because I did not want to invest too much time into completely redesigning it.

The upgrade is, Quick release spring load hooks, to provide fast removal. Also mounting surface for extra accessories e.g light, speaker, mic etc

Everything can be printed off with a 3d printer except the springs, pins and hot shoe mount.

Design is on thingiverse 

https://www.thingiverse.com/thing:2871324

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c80c33-09c9-2f47-7486-d6c406a9a1a4
* Version Independent ID: f8ae5662-23e0-141b-efcc-8e5fb3361193
* Content: [Spectator view - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view#feedback)
* Content Source: [mixed-reality-docs/spectator-view.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spectator-view.md)
* Service: **windows**
* GitHub Login: @fieldsJacksonG
* Microsoft Alias: **jacksonf**

**Comment by chrisfromwork** [comment]
@durante, have you needed to run back through the calibration process after dismantling and reassembling this camera + HoloLens rig?
