### ISSUE TITLE
Altspace Uploader is missing from MRFT

### ISSUE THREAD

**Issue by RecycleMichael** [MicrosoftDocs/mixed-reality#388]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1069484-7225-532e-be75-7cf6814ef355
* Version Independent ID: 7c9a8a28-7091-c8b5-f0a9-b4a9c86c6088
* Content: [Discovering and acquiring features - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/discovering-features)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/discovering-features.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/discovering-features.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @davidkline-ms
* Microsoft Alias: **v-hferrone**

**Comment by bphillips09** [comment]
Hi @RecycleMichael, I just checked and it is there for me. I think it depends on the version of Unity your project is using, as it won't appear if the project is using a version lower than Unity 2020. Can you let me know which version of Unity your project is detected as using when you select it with the MRFT? Also, can you let me know the version of the Mixed Reality Feature Tool you are using? Thanks!

**Comment by RecycleMichael** [comment]
I updated and it fixed. Thanks!
