### ISSUE TITLE
Missing React-Native development frameworks

### ISSUE THREAD

**Issue by kpiascik** [MicrosoftDocs/mixed-reality#39]
The document can include http://components.magicscript.org/ which is a React-Native based framework which runs on ARKit and ARCore.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df6195f5-7d86-8bf3-a472-116c74f435d5
* Version Independent ID: 9355d0d1-71dd-75b8-ea8e-181d5f0133c4
* Content: [JavaScript Development Overview - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/javascript-development-overview)
* Content Source: [mixed-reality-docs/javascript-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/javascript-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Yonet
* Microsoft Alias: **ayyonet**

**Comment by hferrone** [comment]
@thetuvix Can you confirm and let me know where this would go?

**Comment by Yonet** [comment]
@hferrone I can add that under JavaScript. @kpiascik do you have any specific tutorial that you would like to share?

**Comment by Yonet** [comment]
@kpiascik link is not displaying black. 
![magicscript](https://user-images.githubusercontent.com/3523671/93573682-48a7ab00-f94c-11ea-8b4b-0bf77f8b9f87.png)

**Comment by kpiascik** [comment]
@Yonet  If you navigate to the magicscript.org domain and then click through, the link displays correctly.  For some reason if you try to access it directly it doesn't.  We had this issue with the site before.  I'll need to fix it.  Can you try instead providing components.magicscript.org ?

**Comment by kpiascik** [comment]
@Yonet these are react-native examples for iOS/Android, not Windows or Web though.

**Comment by Yonet** [comment]
@kpiascik thank you for confirming. I'll leave it up to @hferrone to decide if it fits in to windows mixed reality docs in that case. Thank you for submitting.

**Comment by hferrone** [comment]
@thetuvix Should we include these iOS/Android React frameworks?

**Comment by hferrone** [comment]
@thetuvix I could really use some guidance here :)

**Comment by hferrone** [comment]
@Yonet Is this still something we should be including in the upcoming JS updatePR?

**Comment by Yonet** [comment]
Hi @kpiascik, we need to have either Universal Windows Platform(UWP) or WebXR platform support documentation to add MagicScript to the documentation. I do not see either on your documentation. See an example deployment doc on [BabylonReactNative](https://github.com/BabylonJS/BabylonReactNative#universal-windows-platform-uwp).
If you do support Browser or UWP, please share docs. Thanks!

**Comment by kpiascik** [comment]
We have support for ARCore, ARKit and Magic Leap. We don't have WebXR at the moment. If that changes I'll create a new issue to have it added. On Mar. 31, 2021 1:22 a.m., Yönet ***@***.***> wrote:
Hi @kpiascik, we need to have either Universal Windows Platform(UWP) or WebXR platform support documentation to add MagicScript to the documentation. I do not see either on your documentation. See an example deployment doc on BabylonReactNative.
If you do support Browser or UWP, please share docs. Thanks!

**Comment by Yonet** [comment]
Sounds great @kpiascik. I will close this for now but feel free to reopen or send a PR when there is WebXR support, if not Windows. 😎
Thanks!
