### ISSUE TITLE
Documentation images in high resolution?

### ISSUE THREAD

**Issue by derdimi** [MicrosoftDocs/mixed-reality#391]
I am quite disappointed that you downsized all documentation images in the course of your Github migration. Is there any chance to get them back somehow?

**Comment by mattzmsft** [comment]
Hi @derdimi, we actually didn't "downsize" any images, the Docs platform unfortunately just doesn't have the ability to host images larger than they appear in-line (which the old platform did - you could click on a "small" inline image to see it full-size in a pop-up). Unfortunately, that platform capability isn't something I can address, but I will pass on the feedback to the platform team. Are there specific images you're having trouble with?

**Comment by derdimi** [comment]
Thank you very much for passing on my feedback.

Some pages have very small images now. They are practically useless. Here is an [EXAMPLE](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools#installation-checklist-for-immersive-headsets).

I was hoping to get some great images for my master thesis. Fortunately, I was able to download most of them from [archive.org](https://archive.org/) which was a bit of a challenge, because some URLs have changed in course of the migration. What I still would like to have are the following three images in a higher resolution:
- [colorseparationofroundwhitecursor-300px.png](https://docs.microsoft.com/en-us/windows/mixed-reality/images/colorseparationofroundwhitecursor-300px.png) (found at [Hologram stability](https://docs.microsoft.com/en-us/windows/mixed-reality/hologram-stability))
- [surfacereconstruction.jpg](https://docs.microsoft.com/en-us/windows/mixed-reality/images/surfacereconstruction.jpg) (found at [Spatial mapping](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping))
- [inputs.jpg](https://docs.microsoft.com/en-us/windows/mixed-reality/images/inputs.jpg) (found at [Case study - My first year on the HoloLens design team](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-my-first-year-on-the-hololens-design-team))

I don't know if there ever was a full-size version of those last two but it would be great to have them.


I am not sure why it is not possible to have resized images in GitHub markdown but it seems to be possible to use HTML. Right now, you are using this piece of code:

`![alt](images/colorseparationofroundwhitecursor-300px.png)`

But you could use this one instead (just some example shrinking value to see the difference):

`<img alt="alt" src="images/colorseparationofroundwhitecursor-300px.png" width="48">`

It works on GitHub (tested by editing it [HERE)](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hologram-stability.md) and it probably would work on microsoft.com as well. Anyway, thanks again for passing on the feedback. I really appreciate it.

**Comment by mattzmsft** [comment]
![colorseparationofroundwhitecursor](https://user-images.githubusercontent.com/33294058/40944542-07c4a2c6-680a-11e8-8882-70b650e7ad70.png)
![surfacereconstruction](https://user-images.githubusercontent.com/33294058/40944566-1d83f044-680a-11e8-8726-2de7bfdd12cb.jpg)
![inputs](https://user-images.githubusercontent.com/33294058/40944579-299f3af0-680a-11e8-9663-58638a96b1af.jpg)

I hope this isn't too late to be useful! Here are the three images you asked for. I'll give the HTML thing a try moving forward, but it would be a lot of work to go back through all 200 articles we migrated to find images that are under-sized. As I come across examples while editing articles, I'll replace them, assuming this works as expected! Thanks!

**Comment by mattzmsft** [comment]
And I agree that screenshots that used to expand are where this affects us the most!

**Comment by mattzmsft** [comment]
Hmm I tried what you suggested for the screenshots from "Install the tools" you referenced, but it still doesn't work the way you'd want it to when published. In the repo you can at least click the image to see a larger size (and download to get full size) but on docs.microsoft.com, there's no click-to-expand or see full size option... you'd have to right-click and open image to see it full size, which isn't intuitive :-/

**Comment by derdimi** [comment]
Hey, thanks very much for the reply and for the images. It's not too late :)

> you'd have to right-click and open image to see it full size, which isn't intuitive :-/

I agree that it's not ideal for most users. But to be honest, for me personally, it does make a huge difference and at least it could be a workaround for future articles. However, thank you for trying my suggestion and investing time in this.

Congrats on the GitHub acquisition btw :cake:

**Comment by mattzmsft** [comment]
Thanks! Moving forward, I'll try to make sure any images with small text or details get uploaded at full-size to at least enable the right-click option, and then we'll try to get a click-to-expand feature added to Docs in future platform updates. Going to close this issue in the meantime.
