### ISSUE TITLE
Error CS0234: when building for IOS.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/mixed-reality#391]
Trying to build for IOS in Unity but not working.

The errors are below:

Assets/MRTK.Tutorials.AzureSpeechServices/Scripts/LunarcomIntentRecognizer.cs(7,19): error CS0234: The type or namespace name 'Windows' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

Assets/MRTK.Tutorials.AzureSpeechServices/Scripts/LunarcomIntentRecognizer.cs(98,80): error CS0246: The type or namespace name 'ConfidenceLevel' could not be found (are you missing a using directive or an assembly reference?)

Assets/MRTK.Tutorials.AzureSpeechServices/Scripts/LunarcomIntentRecognizer.cs(20,5): error CS0246: The type or namespace name 'DictationRecognizer' could not be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bd308a-2d2c-87b4-bb20-f58805a2a813
* Version Independent ID: f2f80227-5c89-d3d4-93a7-c3df8cca8de1
* Content: [Azure Speech Services tutorials - 1. Integrating and using speech recognition and transcription - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch1)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment]
Hi @JoshJarc, can you provide for me the following information please:
- Unity version
- Xcode version
- Azure Speech Services version

**Comment by typride** [comment]
No response from GH user. Closing. Can reopen if necessary.
