### ISSUE TITLE
Great Guide.

### ISSUE THREAD

**Issue by KickinItInSD** [MicrosoftDocs/mixed-reality#393]
Love the guide! I'm building a Collaborative project, and this was a great stepping stone. I think it would be good to have a small section that steps through how to implement this onto your own model/project as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a79cabb-52f4-1cd5-d473-174391c73de3
* Version Independent ID: fa30affe-a552-a265-6626-855b2326bf02
* Content: [Holograms 240 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-240)
* Content Source: [mixed-reality-docs/holograms-240.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-240.md)
* Service: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by mattzmsft** [comment]
@keveleigh @davidkline-ms do you know if there's anything we could do to update the course with tips on how you can sample the source code to apply it to your own project? Or does MRTK have snippets you can use outside of the full app codebase?

**Comment by Redge-Ballard** [comment]
I would also be interested in something like this. I'm trying to tweak parts of the tutorial to fit my project's needs and it's turning out to be a lot more difficult than I had anticipated.

**Comment by sostel** [comment]
+1 :D

**Comment by hferrone** [comment]
Closing this one as HoloToolkit is deprecated, but if anyone has follow-ups please post and we'll reopen. Thanks!
