### ISSUE TITLE
How can i get the position of Room Floor after SpatialMapping.

### ISSUE THREAD

**Issue by Xudarker** [MicrosoftDocs/mixed-reality#394]
[Enter feedback here]

How can i get the position of Room Floor after SpatialMapping? is there have any APIs to do that?  thanks, hope to get response soon. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8aa2e52-391c-7963-0496-7c735c0bc596
* Version Independent ID: bd0e1c49-b23b-91d7-31aa-a1a09fe4e387
* Content: [Scene understanding observer - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/spatial-awareness/scene-understanding.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/spatial-awareness/scene-understanding.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by MaxWang-MS** [comment]
You can open the SceneUnderstandingExample.unity sample scene as mentioned in the doc, and then create your own script calling the DemoSceneUnderstandingController.GetSceneObjectsOfType(SpatialAwarenessSurfaceTypes) Method.

**Comment by Xudarker** [comment]
@MaxWang-MS  i have found the example about scene understanding, not really sure this is the one which i can get my answer about this question, but still thanks.

**Comment by MaxWang-MS** [comment]
@Xudarker Please close the issue if the issue has been resolved or otherwise let me know what question you have, thanks!
