### ISSUE TITLE
Azure spatial anchor_Remove Local Anchor

### ISSUE THREAD

**Issue by young-tae-lim** [MicrosoftDocs/mixed-reality#395]
I'm doing Azure Spatial Anchor tutorial.
When running on HoloLens 2, the cube object disappears when running Remove Local Anchor in the fifth step 'Allows the user to move the cube'.

For Basic Events in ButtonParent > RemoveLocalAnchor > Button Config helper, it appears that the cube is removed by assigning ParentAnchor.
I wonder how the cube in the instruction manual is created again.
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure Spatial Anchors 시작 - Mixed Reality](https://docs.microsoft.com/ko-kr/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality-pr.ko-kr/blob/live/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment]
Hi @young-tae-lim, can you provide for me some version information?
- Unity version
- MRTK version
- ASA version

**Comment by young-tae-lim** [comment]
> @young-tae-lim 안녕하세요 , 버전 정보를 알려주실 수 있나요?
> 
> * 유니티 버전 2020.3.15f2
> * MRTK 버전  2.7.2
> * ASA 버전 2.10.2
