### ISSUE TITLE
Fully qualify the namespace for Path

### ISSUE THREAD

**Issue by peted70** [MicrosoftDocs/mixed-reality#397]
Use System.IO.Path in the snippets to avoid a build error and trying to work out where Path is. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74770102-2289-8f0a-cabc-a5e15b5a4a88
* Version Independent ID: 61fa1f2b-f423-81f3-d42f-9fe9867950c8
* Content: [WinRT in Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-winrt?tabs=426)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-winRT.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-winRT.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **jacksonf**

**Comment by bphillips09** [comment]
@DCtheGeek Should this be implemented here?

**Comment by bphillips09** [comment]
@fieldsJacksonG Should this be implemented?

**Comment by typride** [comment]
@fieldsJacksonG closing this as there was no response or solution provided. Can reopen if useful or necssary!
