### ISSUE TITLE
Missing Capability Check

### ISSUE THREAD

**Issue by ckskylight** [MicrosoftDocs/mixed-reality#40]
Hi! I followed these instructions and they were great, but sadly they did not work because of missing capabilities, which resulted in several hours of debugging. Users following these instructions should know that they need to set

1. Internet (Client and Server)
2. Private Networks (Client and Server)

Also another issue is that when I set these in Unity under Player settings, they didn't not transfer to the appxmanifest in VS, which was very confusing. They have to be set directly in the built project's Package.appxmanifest :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0213cb7-2364-a9f3-6bbf-6b3d9501531d
* Version Independent ID: faba539d-c785-bc56-d5f3-9ec2997b19e9
* Content: [PC Holographic Remoting tutorials - 2. Create a Holographic Remoting PC application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-pc-holographic-remoting-02)
* Content Source: [mixed-reality-docs/mr-learning-pc-holographic-remoting-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-pc-holographic-remoting-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@martinwilter This seems like an issue with the tutorials, can you confirm?

**Comment by martinwilter** [comment]
Hi @hferrone,

I'm not familiar with this tutorial, but my guess is:

- Internet (Client and Server) capabilities are not needed, probably the desktop app connects to HL app over wifi?
- Private Networks (Client and Server) capabilities are not related to the the tutorial, but depends on local environment:

>Private Networks (Client & Server): Provides inbound and outbound access to Intranet networks that have an authenticated domain controller, or that the user has designated as either home or work networks. Inbound access to critical ports is always blocked.

Personally, I've never seen those capabilities not being transferred to VS, I remember eye tracking not falling into that, but that was changed in latest MRTK releases, I could be wrong, but as far as I know, all capabilities settings are now transferred to VS.

**Comment by ckskylight** [comment]
@martinwilter 

The tutorial is explicitly for connecting to HL over wifi to stream frames so internet capabilities are 100% needed. This is what it says on the tutorial: "_In this section, you will configure your project to stream your Mixed Reality experience to your HoloLens 2 device from your PC in real-time over a Wi-Fi connection_" 

I was doing this on my home network, which I guess falls under "private networks".

If this helps, I'm using Unity 2019.4.9f1 and MRTK 2.4.0. It may be possible that the capabilities get transferred the first time the solution is generated but not the succeeding times it is built. However, I tried to build several times to test whether the settings get transferred and they did not. Setting them explicitly in the VS solution was the only step I needed to take to make everything work.

**Comment by martinwilter** [comment]
Thanks for the additional information, @ckskylight. I've notified the tutorial creators so they can take a look at this.

**Comment by varunsiddaraju** [comment]
Hi @hferrone,

We have checked this issue and we need to add the below details on "Build details" sections of the tutorial.

"In the Project Settings window, expand the Publishing Settings, scroll down to the Capabilities section and check the below-shown capability checkbox in addition to the existing capabilities:
•	Internet Clint server
•	Private Network Client Server
"

**Comment by hferrone** [comment]
@varunsiddaraju Can you be clearer on where this content needs to go and clarify this part of the sentence: "check the below-shown capability checkbox in addition to the existing capabilities:"

**Comment by martinwilter** [comment]
Hi @hferrone, I'll be stepping in to help with this and some of the other issues.

I see someone on Varun's team had made the update to the old docs fork when they looked into this a while back, they made these two commits:

https://github.com/onginnovations/mixed-reality-old/commit/6ecb21f798d43075fdf86cb43c1b63f3667340d0 
https://github.com/onginnovations/mixed-reality-old/commit/3be9f2f472bd3e710734066e22e2de65144cd7e3

In the md https://github.com/onginnovations/mixed-reality-old/blob/pc-holographic-remoting/mixed-reality-docs/mr-learning-pc-holographic-remoting-02.md:

![image](https://user-images.githubusercontent.com/16746283/94730815-a78bfd80-0318-11eb-9e9a-1b02b621ce69.png)

This is the same concept as described here https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-02#enabling-additional-capabilities.

Hope this helps. Let me know if you need anything else.

**Comment by martinwilter** [comment]
@hferrone, were those lines added to the docs repo? (The md I linked in my previous post was from our fork of the old docs repo). Let me know if want me to make a quick PR.
