### ISSUE TITLE
Project Name vs. Short Name vs. Display Name vs. Package Name

### ISSUE THREAD

**Issue by KenanBektas** [MicrosoftDocs/mixed-reality#403]
Hi, 

I deployed two different apps (the content, Project Name, and Display Names are different) I have noticed that the 2nd one replaces the 1st one i.e., after deployment (VS2019) the 2nd one overwrites the 1st deployment. I think this issue is related to using the same package name in two different projects as explained [here](https://stackoverflow.com/questions/62994573/deploy-multiple-application-to-hololens-2). 

A manual update of the AppxManifest resolves the problem but having 3 different names for a single App is a bit confusing. 
Perhaps you can clarify this issue?

Kind regards
Kenan

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by pbarnettms** [comment]
This is a standard part of the Windows UWP application model, not HoloLens-specific.  For more information about the various elements in the manifest, please refer to https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appx-package-manifest.
