### ISSUE TITLE
Adding the requirement for the animation doesn't work

### ISSUE THREAD

**Issue by Morgan-6Freedom** [MicrosoftDocs/mixed-reality#404]
I have followed Adding the triggers and it doesn't work. 
![image](https://user-images.githubusercontent.com/49686866/129214538-0e073ad9-7c35-4333-8c66-bbe3c29ab456.png)
![image](https://user-images.githubusercontent.com/49686866/129214562-dc96713c-27f1-4a2f-8659-1b496d60a7e4.png)

Try with the GLB attached
👉 [cube_anim3.zip](https://github.com/MicrosoftDocs/mixed-reality/files/6976161/cube_anim3.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae9e8b5-04c1-4326-ea3a-2428d1b5f569
* Version Independent ID: 793ed24a-e530-17b5-f0b8-d6d4adfb0d61
* Content: [Create 3D models for use in the home - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/distribute/creating-3d-models-for-use-in-the-windows-mixed-reality-home#asset-requirements-overview)
* Content Source: [mixed-reality-docs/mr-dev-docs/distribute/creating-3d-models-for-use-in-the-windows-mixed-reality-home.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/distribute/creating-3d-models-for-use-in-the-windows-mixed-reality-home.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thmignon
* Microsoft Alias: **thmignon**

**Comment by bphillips09** [comment]
@Morgan-6Freedom Are there any specific errors you are getting?

**Comment by Morgan-6Freedom** [comment]
@bphillips09 no. The cube does appear in my room, but it is not animated.

**Comment by bphillips09** [comment]
@thmignon Is this documentation still accurate?

**Comment by typride** [comment]
Closing, can reopen if unresolved.

**Comment by Fangh** [comment]
> Closing, can reopen if unresolved.

Do you have any link to a PR that shows that the issue has been resolved ?
