### ISSUE TITLE
Code Snippets need Updating.

### ISSUE THREAD

**Issue by WLSmith9386** [MicrosoftDocs/mixed-reality#405]
```
private PhotoCapture photoCaptureObject = null;

void OnPhotoCaptureCreated(PhotoCapture captureObject)
{
    photoCaptureObject = captureObject;

    Resolution cameraResolution = PhotoCapture.SupportedResolutions.OrderByDescending((res) => res.width * res.height).First();

    CameraParameters c = new CameraParameters();
    c.hologramOpacity = 0.0f;
    c.cameraResolutionWidth = cameraResolution.width;
    c.cameraResolutionHeight = cameraResolution.height;
    c.pixelFormat = CapturePixelFormat.BGRA32;

    captureObject.StartPhotoModeAsync(c, false, OnPhotoModeStarted);
}
```
StartPhotoModeAsync only takes two arguments as per https://docs.unity3d.com/ScriptReference/Windows.WebCam.PhotoCapture.StartPhotoModeAsync.html

`PhotoCapture.SupportedResolutions.OrderByDescending((res) => res.width * res.height).First();`

Is dependent on using the System.Linq namespace this should be mentioned so it doesn't show up as an error message inside of Unity.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd07cb8-0169-9eeb-706a-890cd0418d0e
* Version Independent ID: 46b95d28-2e43-1c9d-a338-495210bd9f91
* Content: [Photo Video camera in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/locatable-camera-in-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/locatable-camera-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/locatable-camera-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **v-hferrone**

**Comment by bphillips09** [comment]
@WLSmith9386 Good catch - I can't even find a previous revision of `PhotoCapture` that supported 3 arguments.
