### ISSUE TITLE
Issue with 'Initializing your project and deploying your first application'

### ISSUE THREAD

**Issue by RyanJang111** [MicrosoftDocs/mixed-reality#406]
![Application Issue](https://user-images.githubusercontent.com/86286992/129291882-0d8b5861-90b2-4894-ab13-8b6f07ff87e5.png)

I have tried to build and deploy the application through visual studio with Unity and HoloLens 2. I have gone through all the steps here (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr), but the installed application doesn’t open properly what it should show (I should be able to see 3D cube box), showing static window screen only as attached. Have you gone through this? Can you tell me how I should solve this issue?
   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment]
Hi @RyanJang111, can you let me know which version of Unity you are using as well as which MRTK version?

I have run through this tutorial myself a few times with HL2 and it has worked for me.

**Comment by RyanJang111** [comment]
Hi @bphillips09 , I am using Unity (2020.3.13f1) and MRTK (1.0.2104.4-Beta). Do you think I need to use different versions? Can you let me know which version did you install as well?

**Comment by bphillips09** [comment]
@RyanJang111 I recall using similar versions as you - I will try to replicate your issue and get back to you.

**Comment by typride** [comment]
Closing issue. Can reopen if not resolved.
