### ISSUE TITLE
Unable to complete on Hololens

### ISSUE THREAD

**Issue by jmackenzie68** [MicrosoftDocs/mixed-reality#417]
nm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d17c7d8-64b2-d72c-da83-9dc8ba1f5089
* Version Independent ID: cf571c53-ddb1-dd44-b608-9fd96efd644a
* Content: [MR and Azure 305 - Functions and storage - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-305)
* Content Source: [mixed-reality-docs/mr-azure-305.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-305.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by DrNeil** [comment]
Hi,

Thanks for trying the lab. You will have created an Azure function which determines the shapes. This function should be triggered when you gaze at the object in the scene (cube)
You can test the function in the Azure portal to check it working
Only once you have started spawning shapes with the function is the storage file created
Then the second time you run the app it will find the storage file and replay the shapes you spawned in the first run

All the best
(Dr).Neil

---
Neil
Director
nsquared
m: (+61) 414 064 517
w: (+61) 2 9262 3386
Suite 303, 75 King Street
Sydney NSW 2000
digitable.co | Check out the nsquared vision
The information contained in this email is confidential.
If you are not the intended recipient, you may not disclose or use the information in this email in any way.
nsquared does not guarantee the integrity of any emails or attached files.
The views or opinions expressed are the author's own and may not reflect the views or opinions of nsquared.
________________________________

**Comment by jmackenzie68** [comment]
Thanks for the reply, I managed to get it working, but couldnt figure out how to delete this ticket. haha   been a long week
