### ISSUE TITLE
I`m Animator

### ISSUE THREAD

**Issue by Asadkhujaev** [MicrosoftDocs/mixed-reality#419]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f464b6-99ef-6d78-c30a-4066e9e7a411
* Version Independent ID: 88e27323-63f3-5113-5038-6ee50a606491
* Content: [Get help with PC compatibility - Enthusiast Guide](https://docs.microsoft.com/en-gb/windows/mixed-reality/enthusiast-guide/get-help-with-pc-compatibility#WarnBluetooth)
* Content Source: [enthusiast-guide/get-help-with-pc-compatibility.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/get-help-with-pc-compatibility.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by qianw211** [comment]
Hi @Asadkhujaev , what's your question here?
