### ISSUE TITLE
HTTP download link, advised to "Run anyway"

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/mixed-reality#419]
It doesn't seem like a great idea to teach people to just click "run anyway" on exe's they get from the web; and this link goes to HTTP (despite working over HTTPS and this page being HTTPS).

The link should be updated to HTTPS and really the wording of the text could be improved so it's not conditioning people to just skip past important security warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d039f73-3530-e97d-c1be-c2e2b9c87953
* Version Independent ID: c041e4f7-fa4a-a1d2-ce4a-db985c9f3633
* Content: [Add custom home environments - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/add-custom-home-environments)
* Content Source: [mixed-reality-docs/add-custom-home-environments.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/add-custom-home-environments.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @mattzmsft

**Comment by mattzmsft** [comment]
@DanTup I don't think the wording at all suggests that you should just accept any foreign .exe from the web. It's very careful contained as a note to how you install the file above, which _will_ require someone to perform those steps when the prompt comes up. That being said, there's no harm in reminding people that they should only do that for files they trust, so I have no issue adding that :-) By the way, I'm not having the download issue you are, and no one else is reporting it. Clicking the link immediately begins the download for me, and the http auto resolves to https. But we can tweak that too, no harm in that.

**Comment by DanTup** [comment]
@mattzmsft 

> I'm not having the download issue you are, and no one else is reporting it.

I'm not having any issue, the download works fine - my concern was just that the link is HTTP (it doesn't matter if it redirects to HTTPS, as the HTTP request can be intercepted and then not redirected to the real location) and there is advice to click "run anyway". With an HTTP link there's no guarantee that the file the user got was the one on the MS site. My PR fixes that though, so the risk reduced :-)

The updated text reads much better IMO 👍 Closing this as both of my concerns have been addresse; thanks for the quick response!
