### ISSUE TITLE
this documentation is bad. 

### ISSUE THREAD

**Issue by iambetterthanyou** [MicrosoftDocs/mixed-reality#42]
[Enter feedback here]

So frankly, this sucks. 

You have strung along 30 different code strings, tiny applications and a crap ton of documentation for people to sift through to make thier $3000 AR headset work. This culture of github sucks and frankly a s a business professional, the last thing i want to go do is sit on a forum. Make this work with one package. These instructions are very vague and require me to have 70 different tabs open all cross referencing each other. Get your act together MRTK. You have had numerous revisions and a few years to work it out. Get it done and stop making us chase accross the internet to make something work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ac37f3-5dc8-8076-da7c-4c6d877eac49
* Version Independent ID: b58b8052-ddca-5941-3981-867baef990a5
* Content: [Unity development overview - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unity-development-overview?tabs=mrtk%2Carr%2Chl2)
* Content Source: [mixed-reality-docs/unity-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/unity-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
Hi @iambetterthanyou, we are actively working to improve our documentation and developer experience. Since this is a broad scope of work, I'm going to close this issue. Thanks for your input.
