### ISSUE TITLE
We might want to add a note about the shared depth buffer.

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/mixed-reality#423]
See https://docs.microsoft.com/en-us/windows/mixed-reality/hologram-stability#stabilization-plane

And: https://docs.unity3d.com/2018.1/Documentation/Manual/wmr_input_types.html

>When Enable Depth Buffer Sharing is enabled, ensure applications do not explicitly call the SetFocusPoint method, which overrides per-pixel depth reprojection with plane-based reprojection.
>
>Enable Depth Buffer Sharing on HoloLens has no benefit unless you have updated the device’s OS to Windows 10 Redstone 4 (RS4). If the device is running RS4, then it determines the stabilization plane automatically from the range of values found in the depth buffer. Reprojection still happens using a stabilization plane, but the application does not need to explicitly call SetFocusPoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a94ef06-a591-458c-58a4-75112a0a8a42
* Version Independent ID: fec94425-e12a-7250-814a-6da52a6031d0
* Content: [Focus point in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/focus-point-in-unity)
* Content Source: [mixed-reality-docs/focus-point-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/focus-point-in-unity.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by mattzmsft** [comment]
@StephenHodgson if you think it should be in there, wanna just update the articles with a PR, and i'll merge it in? I'm trusting you on this one as this goes beyond my technical expertise. :-)

**Comment by StephenHodgson** [comment]
At least references to the other bits of documentation.

**Comment by mattzmsft** [comment]
Just asking if you'll submit a PR for the changes you want to make since I don't understand exactly what you're requesting. Thanks!

**Comment by StephenHodgson** [comment]
Will do

**Comment by StephenHodgson** [comment]
Could you assign this to me so I remember?

**Comment by mattzmsft** [comment]
@StephenHodgson sure, as a bug in VSO?

**Comment by StephenHodgson** [comment]
I meant right here on github. Right column near the top.

**Comment by thetuvix** [comment]
Thanks for the poke - I'd been meaning to fix this up!  I just submitted a pull request here as #439.

**Comment by mattzmsft** [comment]
Thanks @thetuvix! And thanks @StephenHodgson for teaching me about GitHub issues :-)
