### ISSUE TITLE
New tutorial is missing Azure part

### ISSUE THREAD

**Issue by ahmed-saber-gomaa** [MicrosoftDocs/mixed-reality#424]
I think in your modified tutorial "Getting Started With Azure Spatial Anchors", you skipped the part where you add the ASA packages. It was there in the past. I can't build the project without them.

**Comment by msftradford** [comment]
@ahmed-saber-gomaa, thanks for reaching out! You can follow [these instructions](https://docs.microsoft.com/en-us/azure/spatial-anchors/how-tos/setup-unity-project?tabs=unity-package-web-ui) to configure your Unity project with ASA.
