### ISSUE TITLE
Calibration Issues

### ISSUE THREAD

**Issue by MasayaTodoroki** [MicrosoftDocs/mixed-reality#425]
Hi there,
I've been following through these steps and am currently stuck on calibration. When I run the calibration solution the .exe window opens but then makes windows go straight to blue screen. This only happens when my capture card is connected to the computer. I'm using a black magic capture card which seems to be working perfectly through the blackmagic software. How can I go about troubleshooting this?

**Comment by mattzmsft** [comment]
hi @MasayaTodoroki, for some reason, the way you captured this issue doesn't tell me which steps you're trying to follow or which article you're referencing. Can you provide that info so I can try to get you help? Thanks.

**Comment by jessemcculloch** [comment]
Closed due to time and lack of details
