### ISSUE TITLE
Training fails

### ISSUE THREAD

**Issue by SabinMGeorge** [MicrosoftDocs/mixed-reality#426]
It seems the sample project's training part work anymore with 6 images. 
I get this error from the training post query 
$"{resourceBaseEndpoint}/customvision/v3.0/training/projects/{projectId}/train"
{
    "code": "BadRequestDetectionTrainingValidationFailed",
    "message": "Not enough images for training"
}

Could you please verify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bf8e38-57dc-77f6-22e8-9c157900daa3
* Version Independent ID: 1b4c66e9-49fb-5a35-992f-4352506b20ac
* Content: [Integrating Azure Custom Vision - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-03)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-03.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-03.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by typride** [comment]
Is this still an issue?

**Comment by typride** [comment]
Closing, can reopen if still relevant.
