### ISSUE TITLE
says nothing about running the app. 

### ISSUE THREAD

**Issue by iambetterthanyou** [MicrosoftDocs/mixed-reality#43]
[So, this document outlines NOTHING about how to run the app you just produced. It does not say, the app pops up in front of you or that you have to open it, or anything like that.  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d386bb-3f93-d434-e7b3-28c58ea673e9
* Version Independent ID: a1a9b02f-66a0-feb0-7a08-9a8d2cf398d1
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Thanks @iambetterthanyou, we're in the midst of addressing this in several of our other issues, specifically #59. I'm going to close this as we don't want to duplicate these.
