### ISSUE TITLE
HTTP 404 Error for multiple pages - Integrating Azure Custom Vision - Mixed Reality

### ISSUE THREAD

**Issue by rgeorge0706** [MicrosoftDocs/mixed-reality#431]
Hi,

I was trying to follow the guides for integrating Azure Custom Vision Services with Hololens 2 but now the pages display a 404 error.  The pages I tried to access are below:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-01
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-02
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-03

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02

**Comment by Crazyhenry123** [comment]
Same problem here. I am learning through these tutorials for our project, these are the best reference which are missing now..

**Comment by vtieto** [comment]
Those tutorials have been converted to Learn modules. Links have been corrected.

@rgeorge0706 
@Crazyhenry123 
@Sean-Kerawala

**Comment by typride** [comment]
Links fixed, issue resolved.
