### ISSUE TITLE
Missing assets in Chapter 2

### ISSUE THREAD

**Issue by JairoGLoz** [MicrosoftDocs/mixed-reality#431]
Holograms-211 - Chapter 2 - Navigation
Errata: 2. In the Holograms folder, find the ScrollFeedback asset.

- But there's no ScrollFeedback asset in the provided Unity package

**Comment by mattzmsft** [comment]
@cre8ivepark @keveleigh @davidkline-ms can you guys please take a look at this? thanks!

**Comment by keveleigh** [comment]
Which Unity package are you referring to? Only Holograms 210 provides a package, while Holograms 211 and 212 contain starting projects, which both contain slightly different contents than the 210 package.

The 211 starting project does contain ScrollFeedback in the Holograms folder: https://github.com/Microsoft/HolographicAcademy/blob/Holograms-211-Gesture/Starting/ModelExplorer/Assets/Holograms/ScrollFeedback.prefab
