### ISSUE TITLE
Black Screen: Toggle Desktop Accelerated Graphics

### ISSUE THREAD

**Issue by jfoshee** [MicrosoftDocs/mixed-reality#433]
If the Hololens Emulator is only showing a black screen (other than possibly the gaze cursor) try toggling **Use desktop accelerated graphics** under **Additional Tools** => **Optional Settings**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by mattzmsft** [comment]
Still trying to confirm this with emulator owner. Thanks for flagging it!

**Comment by pbarnettms** [comment]
In the event of the emulator not rendering any content, turning off "Use desktop accelerated graphics" is a valid option.  However, if the gaze cursor is visible the problem may be that the app being launched is not completing activation.  If pressing F2 to bloom brings up the pins panel, the issue might be the app and not GPU.
