### ISSUE TITLE
Release notes are not update to date

### ISSUE THREAD

**Issue by WikkidEdd** [MicrosoftDocs/mixed-reality#437]
The latest Mixed Reality Open XR package via the Mixed Reality Feature Tool is 1.0.3 and this page's release notes haven't been updated since 1.0.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 080a7cf8-61d0-c43d-dec1-8c7e64655687
* Version Independent ID: 87bda3a8-1c05-4a7d-fbc8-180d84276f57
* Content: [Mixed Reality OpenXR plugin release notes - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-release-notes)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/openxr-release-notes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/openxr-release-notes.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by vtieto** [comment]
Release notes are now up to v. 1.1.1 (10/15/21)
