### ISSUE TITLE
 in unity 2018.1.2f1

### ISSUE THREAD

**Issue by chrisfromwork** [MicrosoftDocs/mixed-reality#437]
"Fastest" no longer appears to be an option for Edit -&gt; Project Settings -&gt; Quality. An "Ultra" options now exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e220dac9-c551-9639-3af0-39e0e7687fd0
* Version Independent ID: 6186d98f-44d0-53a5-8d54-4f77a7d07ef5
* Content: [MR Spatial 230 - Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230)
* Content Source: [mixed-reality-docs/holograms-230.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-230.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by keveleigh** [comment]
Ahh, interesting. We don't [officially recommend 2018.1 yet](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools), but I'll be sure to address this in the ongoing Academy refresh.

**Comment by chrisfromwork** [comment]
sounds good
