### ISSUE TITLE
Unclear where to locate HoloToolkit-SpatialMapping-230\SpatialMapping\Prefabs

### ISSUE THREAD

**Issue by chrisfromwork** [MicrosoftDocs/mixed-reality#438]
Is there an appropriate hyperlink that could be added to this page to help locate the called out HoloToolkit-SpatialMapping-230\SpatialMapping\Prefabs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e220dac9-c551-9639-3af0-39e0e7687fd0
* Version Independent ID: 6186d98f-44d0-53a5-8d54-4f77a7d07ef5
* Content: [MR Spatial 230 - Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230)
* Content Source: [mixed-reality-docs/holograms-230.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-230.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by keveleigh** [comment]
I'm not sure a useful hyperlink is possible here. On GitHub, the starting files are in a binary package. The completed hyperlink [would be here](https://github.com/Microsoft/HolographicAcademy/blob/Holograms-230-SpatialMapping/Completed/Planetarium/Assets/HoloToolkit-SpatialMapping-230/SpatialMapping/Prefabs/SpatialMapping.prefab), but that's not particularly useful.
Otherwise, I don't know of a way to hyperlink into a Unity instance. Finding it in the Project panel or searching for it are the only ways I know.

**Comment by mattzmsft** [comment]
Thanks @keveleigh. @chrisfromwork, i'm going to mark this as closed, but if you have any further thoughts, please let us know.

**Comment by chrisfromwork** [comment]
I guess I'm just a bit curious where these holographic academy projects are referenced in these tutorials. When I was searching for spatial mapping I ended up directly on this page with no context/no awareness of where this repo was located. After spending a few minutes back tracking to find this git hub project, it still wasn't obvious where to grab the repo.

**Comment by keveleigh** [comment]
Under [Before You Start / Project Files](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230#project-files), near the top of the tutorial, there's a link to download the files.

![image](https://user-images.githubusercontent.com/3580640/41063847-b8932016-698e-11e8-9737-8782eff9810d.png)

The link goes to https://github.com/Microsoft/HolographicAcademy/archive/Holograms-230-SpatialMapping.zip, which downloads a zip file of the repo's files.

I can add a link to make the repo more obvious though.
