### ISSUE TITLE
XR Legacy Input Helpers 2.1.4 instead of Legacy Input Helpers 2.1.4

### ISSUE THREAD

**Issue by enniobolondi** [MicrosoftDocs/mixed-reality#44]
Dear MicrosoftDocs,
at the begin of the page you ask to install "Legacy Input Helpers 2.1.4" but actually I can only see listed another one called "XR Legacy Input Helpers 2.1.4".
I guess this is the valid name.
Thanks for the attention.
Regards
Ennio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582e33a2-4681-efd2-2ce3-6d87f5c408c8
* Version Independent ID: 262d47df-2b3a-c123-94cd-ac439d966903
* Content: [Azure Spatial Anchors tutorials - 5. Azure Spatial Anchors for Android and iOS - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-learning-asa-05)
* Content Source: [mixed-reality-docs/mr-learning-asa-05.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-learning-asa-05.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@polar-kev @thetuvix Can you confirm?

**Comment by martinwilter** [comment]
Hi @enniobolondi, yes, the correct name is **XR Legacy Input Helpers**, thanks for pointing out this typo.

CC @hferrone
