### ISSUE TITLE
Add details about how to enable Kiosk mode for the 17134 (RS4) April Update

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/mixed-reality#443]
Please update/add documentation about how to enable this feature on the latest OS update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#kiosk-mode)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by mattzmsft** [comment]
Enabling commercial features is actually documented in the HoloLens IT Pro documentation (https://docs.microsoft.com/en-us/hololens/hololens-kiosk), though since the content is duplicated here, you're right that it needs to be updated. I'll update it to cross-link.
