### ISSUE TITLE
IN RS4-Our application hangs a little and then quits when clicking the Decline button on EULA page

### ISSUE THREAD

**Issue by swathiJaya** [MicrosoftDocs/mixed-reality#444]
Hi,
On testing our app Trimble Connect  on RS4-10.0.17134.80, we observed that on clicking the Decline button on the EULA PAGE and on exiting the app, app hangs a little and then quits.

Kindly let us know if there is something if we will have to handle in the app life cycle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/give-us-feedback#feedback-for-hololens)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
@swathiJaya Hi! You work for Trimble? I think you may want to leverage your existing dev connections into Microsoft. This issue reporting feature is to report issues you find within documentation (this is the developer documentation repo), and not for app help.
