### ISSUE TITLE
IN RS4-there is a time delay in the display of toast messages triggered using voice command 

### ISSUE THREAD

**Issue by swathiJaya** [MicrosoftDocs/mixed-reality#445]
Hi,
On testing our app Trimble Connect  on RS4-10.0.17134.80, we observed that There is a time delay noticed in the display of toast message triggered using voice command 

Kindly let us know if there is something if we will have to handle with respect to voice commands.

Thanks,

**Comment by mattzmsft** [comment]
Same comment as the other issue you reported :)
