### ISSUE TITLE
Missing links -> "Be sure to check out the following links for more details on what's under the hood."

### ISSUE THREAD

**Issue by cyr0zn** [MicrosoftDocs/mixed-reality#447]
[Enter feedback here]
No said links are present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db9ec0f-8219-f292-1ac5-6ca607125b33
* Version Independent ID: a04e35e0-a4a8-2af9-88a7-a5d44f90901b
* Content: [QR codes in Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-qr-codes?tabs=426)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by vtieto** [comment]
I updated this document to be more clear about where additional QR code information can be found.

@cyr0zn 
@Sean-Kerawala
