### ISSUE TITLE
Post Issues

### ISSUE THREAD

**Issue by daniel-martinezm** [MicrosoftDocs/mixed-reality#449]
In the section of the explanation of the queries, there's a mistake on what goes inside the code snnippet. Currently the explanation of the code is inside the snnippet while the code itself is outside without formatting.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d59acc0-cd69-18a6-7e1d-cc1374687942
* Version Independent ID: d5d76031-143d-a520-dee4-a7a2a11df3b7
* Content: [Case study - Expanding the spatial mapping capabilities of HoloLens - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/case-study-expanding-the-spatial-mapping-capabilities-of-hololens)
* Content Source: [mixed-reality-docs/case-study-expanding-the-spatial-mapping-capabilities-of-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/case-study-expanding-the-spatial-mapping-capabilities-of-hololens.md)
* Product: **windows**
* GitHub Login: @jevertt
* Microsoft Alias: **jevertt**

**Comment by mattzmsft** [comment]
thanks @daniel-martinezm. can you open a pull request to correct the issue you're flagging please?

**Comment by benjaminboxler** [comment]
Closed by #494
