### ISSUE TITLE
Missing information about Source Code Editor could lead to Error while packaging.

### ISSUE THREAD

**Issue by Dimoki** [MicrosoftDocs/mixed-reality#45]
Hey!

Keep in mind that you have to select Visual Studio 2019 for your Source Code Editor, if you have UE already installed with another Editor.

Otherwise there will be an error while packaging!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c8f2c0-77cc-9ae9-562d-16d163dff85f
* Version Independent ID: 3e0c6539-52e5-a851-7f2f-03fa2f7b3789
* Content: [6. Packaging & deploying to device or emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-uxt-ch6)
* Content Source: [mixed-reality-docs/unreal-uxt-ch6.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/unreal-uxt-ch6.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-haferr**

**Comment by hferrone** [comment]
Good call, this will be udpated today!
