### ISSUE TITLE
There is no "Places" icon on my start menu.

### ISSUE THREAD

**Issue by resdim** [MicrosoftDocs/mixed-reality#452]
The documentation does not specify the "fix" for a missing Places icon, nor is there any documentation I can locate (either on Bing or Google.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d039f73-3530-e97d-c1be-c2e2b9c87953
* Version Independent ID: c041e4f7-fa4a-a1d2-ce4a-db985c9f3633
* Content: [Add custom home environments - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/add-custom-home-environments#trying-a-sample-environment)
* Content Source: [mixed-reality-docs/add-custom-home-environments.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/add-custom-home-environments.md)
* Product: **windows**
* GitHub Login: @mattzmsft

**Comment by mattzmsft** [comment]
Hi @resdim. That feature should show up with the public release of RS4 (the Windows 10 April 2018 Update) on the desktop, for connected Windows Mixed Reality immersive (VR) headsets. So I just want to confirm:

1. What version of Windows 10 is your PC running (you can search 'winver' from the Start search on your desktop and run the command)?
2. You're using one of our VR headsets right (not HoloLens)?

**Comment by resdim** [comment]
Windows 10 - Version 1709 (OS Build 16299.431)

It is Windows Home edition, although I bought the computer for this purpose
and saw nothing about Pro being required for custom environments (the whole
reason I got the headset was to practice building environments)

I appreciate the response, I would love to devote my future career to this
kind of technology but sometimes I run into mental blocks like this.

**Comment by mattzmsft** [comment]
hey @resdim, sorry for any confusion, but you shouldn't need the Pro version of Windows 10 for any of this. It just looks like you're on the last version of Windows 10 (aka RS3) and to switch "Places" and use custom environments, you need to update to the [Windows 10 April 2018 Update (aka RS4)](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes). This is a free update that you should be able to find just by opening **Settings > Update & Security** and selecting the **Check for updates** button.
