### ISSUE TITLE
Planefinding api returns real world floor with some offset.

### ISSUE THREAD

**Issue by Shubham7694** [MicrosoftDocs/mixed-reality#453]
Issue: I am using SurfaceMeshesToPlane class from Holotoolkit to get the real world floor. I have noticed that floor is always returned with some offset: i.e. when i draw a cursor on detected floor or select a point, it always shows at some height above floor or some depth below the real floor. 

Expected: Real world floor and HL detected floor should be as close as possible [5-10 cm offset acceptable].

Query: Do we need to adjust some parameter. [Urgent]

**Comment by mattzmsft** [comment]
@keveleigh @davidkline-ms can you guys address this please?

**Comment by mattzmsft** [comment]
or maybe @cre8ivepark?

**Comment by keveleigh** [comment]
Will address in https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2285
