### ISSUE TITLE
MR Spatial 220: Spatial sound Chap 1, 2, 5 Errata

### ISSUE THREAD

**Issue by jcarter9** [MicrosoftDocs/mixed-reality#455]
MR Spatial 220: Spatial sound - Chapter 1 Unity Setup

--- Errata: ---
MR Spatial 220: Spatial sound - Chapter 1 Unity Setup
Instructions
Start Unity.
Select Open.
Navigate to your Desktop and find the folder you previously unarchived.
Click on the Starting folder and then press the Select Folder button.
**Errata:** needed to select: Starting\Decibel before I got the Select Folder button!

In the Hierarchy panel, select HolographicCollection > POLY.
**Errata:** In the Hierarchy panel, select HologramCollection > POLY.

In the Platform list, select Windows Store and click Switch Platform.
**Errata:** In the Platform list, select Universal Windows Platform and click Switch Platform.

After: Check Unity C# Projects to enable IntelliSense.
**Errata:** should have: Target Device: HoloLens

below:
Unity begin compiling scripts and creating a Visual Studio solution. When complete, a File Explorer window will appear.
**Errata:** did you wish to tell user to open Visual Studio via double-clicking App\Decibel.sln  (?)
Then one has a Visual Studio instance opened so one can change the settings in VS.
Then Debug -> Start without Debugging
--- Errata: ---

MR Spatial 220: Spatial sound - 
Chapter 2 - Spatial Sound and Interaction

--- Errata: ---
In the Hierarchy panel, expand HolographicCollection and select POLY.
**Errata:** In the Hierarchy panel, expand HologramCollection and select POLY.

Build and Deploy

In Unity select File > Build Settings.
Ensure that the selected folder is App.
Click Build.
**Errata:** Should be Click Build 1st!
--- Errata: ---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd968d4e-e950-862a-4eb5-388874f8886b
* Version Independent ID: bdb773ef-80f6-281e-ec3a-95c9be4d8a17
* Content: [MR Spatial 220 - Spatial sound - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-220#)
* Content Source: [mixed-reality-docs/holograms-220.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-220.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by jcarter9** [comment]
Also, if this note is for Chapter 2, I didn't notice any command panel, much less it following me.

"Note: There is a text panel that will tag-along with you. This will contain the available voice commands that you can use throughout this course."

**Comment by jcarter9** [comment]
It wasn't until Chapter 5 build, that I saw the floating voice command menu.

Re: "Approach within 1 meter of the underworld hologram and start talking."
It kinda worked..  often nothing, but then some very loud noise, and only sometimes when speaking would it echo my voice.

Tested with physical HoloLens.

**Comment by mattzmsft** [comment]
@keveleigh flagging this for you!

**Comment by mattzmsft** [comment]
Looks like @keveleigh updated the files, so I'm going to mark this as closed! Thanks!
