### ISSUE TITLE
Chaper 5 - Microphone Manager does not clean up the dicationRecognizer properly

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/mixed-reality#459]
dicationRecognizer should be disposed in the OnDestroy unity event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69612b4a-28d3-984c-10e3-14c095628821
* Version Independent ID: aff1727f-4384-ed06-c263-adb27495deba
* Content: [MR and Azure 303 - Natural language understanding (LUIS) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-303#chapter-3--set-up-the-unity-project)
* Content Source: [mixed-reality-docs/mr-azure-303.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-303.md)
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by mattzmsft** [comment]
@Drneil @StefanoDeflorio @elliotmoule flagging this for you all as well!
