### ISSUE TITLE
Video not available anymore

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#461]
Youtube video shows as "not available anymore".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9fe050-958c-20e2-e5c6-a87926dc0d95
* Version Independent ID: b60496fb-d44d-aa87-2f49-0e34092f397e
* Content: [Coordinate systems - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/design/coordinate-systems)
* Content Source: [mixed-reality-docs/mr-dev-docs/design/coordinate-systems.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/design/coordinate-systems.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by Sean-Kerawala** [comment]
We have resolved this issue. Thank you for filing!
