### ISSUE TITLE
App deployment via web page

### ISSUE THREAD

**Issue by janholo** [MicrosoftDocs/mixed-reality#464]
https://docs.microsoft.com/en-us/windows/uwp/packaging/installing-uwp-apps-web

Is this also possible on the HoloLens because I did not get it to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36fb16b-1b4a-0fad-514d-7f304d034212
* Version Independent ID: 5cf326ca-2d25-afcc-48ee-a5d8ffc4ae6f
* Content: [Get apps for HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/get-apps-for-hololens)
* Content Source: [mixed-reality-docs/get-apps-for-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/get-apps-for-hololens.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
what kind of app are you trying to install through this process, and how is it being distributed? I'm not aware of many UWP apps being distributed through the web...

**Comment by janholo** [comment]
The app is a private app for our customer. First install would be done manually. After that the app should update itself via the process mentioned above. The app packages would be hosted in the private network of the customer.

**Comment by mattzmsft** [comment]
Thanks for the info. I'll look into this.

**Comment by jessemcculloch** [comment]
Was there ever a resolution to this?
