### ISSUE TITLE
Generic/unknown HTTP error when deploying to Hololes

### ISSUE THREAD

**Issue by Boellis** [MicrosoftDocs/mixed-reality#466]
I managed to get everything setup and working in Unity, but when I deploy and run the app on my Hololens, I get a Generic/unknown HTTP error in my console and 'Argument ExceptionMethod:' for my translation text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273a2a92-c9ce-da55-5c65-db227228febc
* Version Independent ID: 0f5e9631-d624-6707-e299-7d841e751f47
* Content: [MR and Azure 301 - Language translation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-301)
* Content Source: [mixed-reality-docs/mr-azure-301.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-301.md)
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by DrNeil** [comment]
Which version of Unity are you using? There are known issues with many Unity versions. Please check it is the 2017.4. LTS version.

**Comment by Boellis** [comment]
That fixed the issue. Thank you again DrNeil

**Comment by mattzmsft** [comment]
Thanks @DrNeil! Gonna mark this one as closed!
