### ISSUE TITLE
Holographic remoting diagnostics logs

### ISSUE THREAD

**Issue by hololensuser** [MicrosoftDocs/mixed-reality#468]
Hi, 

Can you please clarify if there is anyway to collect the latency information provided in diagnostics ? I am looking for a way to study the impact of network bandwidth, congestion on the end-to-end latency. 

Thanks.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465515d0-e7cb-b8f4-192c-27684afaaef6
* Version Independent ID: 465515d0-e7cb-b8f4-192c-27684afaaef6
* Content: [Holographic Remoting Player - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/holographic-remoting-player)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/holographic-remoting-player.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/holographic-remoting-player.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @FlorianBagarMicrosoft
* Microsoft Alias: **v-vtieto**

**Comment by FlorianBagarMicrosoft** [comment]
Yes there is.
If you write a custom player (see https://docs.microsoft.com/windows/mixed-reality/develop/native/holographic-remoting-create-player) there is a method called LastFrameStatistics which you can call on m_playerContext. This is what is used by the player from the Microsoft store to collect the data for the diagnostics.

**Comment by typride** [comment]
Closing this issue as @FlorianBagarMicrosoft has responded. Can reopen if not resolved.
