### ISSUE TITLE
Deploying an app to the HoloLens 2 Emulator

### ISSUE THREAD

**Issue by ArthurEmcon** [MicrosoftDocs/mixed-reality#472]
Hi,

I am having trouble to deploy my Unity project to the Hololens 2 Emulator. When I try to follow the step below:

![image](https://user-images.githubusercontent.com/77690649/142446851-74ed4d3c-65b3-4af3-815d-508ae7e70174.png)

What I actually get from the dropdown follows:

![image](https://user-images.githubusercontent.com/77690649/142447337-d501285f-9030-41d2-a61b-8f26bf8b8d7b.png)

The project was built from unity with the following parameters:

![image](https://user-images.githubusercontent.com/77690649/142447609-76502c5c-ad37-4a57-a09f-e82a829dae4f.png)

What is possibly wrong there?

Arthur

**Comment by pbarnettms** [comment]
You need to set your UWP project as your startup project.  An Il2Cpp project is only a library and you cannot deploy and debug a library.  Right-click on your Universal Windows project and choose "Set as Startup Project"

**Comment by ArthurEmcon** [comment]
It worked, thank you. But now that the emulator is started, it only shows the apps panel, nothing from the project. Here's a picture:

![image](https://user-images.githubusercontent.com/77690649/143082888-fa41b0b7-4e92-4653-a99c-9e1e33644be0.png)

I have tested if it is an issue with the unity project by executing a default Holographic DirectX 11 App. Most of the time the same thing happens, but it happened once the appearance of a spinning cube, meaning that I can't conclude if it is an issue with the Unity project or with the deployment process.

**Comment by ArthurEmcon** [comment]
Ok, after waiting some more, it seems that the implementation is slow and the screen above is while it is loading. Now, after waiting for the implementation, the Holographic DirectX 11 App is working, but the Unity Project exits with errors

**Comment by pbarnettms** [comment]
Please follow up separately on your Unity project errors.  This is not a function of the HoloLens 2 Emulator or Visual Studio, which both appear to be working properly.  The Unity forums and HoloDevelopers on Slack are a couple of resources available to you.

**Comment by ArthurEmcon** [comment]
Ok I think the issue here is closed then
