### ISSUE TITLE
copy edit needed

### ISSUE THREAD

**Issue by larsville** [MicrosoftDocs/mixed-reality#473]
> On the end of the spectrum, we have the physical reality that we as humans exist.

Should be:

> On **one** end of the spectrum, we have the physical reality that we as humans exist **in**.

or some such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea162663-1580-2d23-4c07-fbd09f1bee9b
* Version Independent ID: a49e7344-f7f6-1dcc-c885-70037966617b
* Content: [What is Mixed Reality? - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/discover/mixed-reality)
* Content Source: [mixed-reality-docs/mr-dev-docs/discover/mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/discover/mixed-reality.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by vtieto** [comment]
Fixed.
