### ISSUE TITLE
The user interface for the hololens simulator can be improved

### ISSUE THREAD

**Issue by fvbakel** [MicrosoftDocs/mixed-reality#477]
The user interface for the hololens simulator can be improved

I have installed the hololens 2 and tried to use this page to see how you can controll the emultor. The user interface for the emulator is not intuative and difficult/imposible to use. For example. When I start the emulator I first get a screen to accept the terms. There seems to be no posiblity to select the accept button. The emulator tries to hard to emulate the usage controlls. 

Is it possible to just allow a mouse click on the buttons in the emulator?

Edits:
- Improved text.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c84d41-476f-d14d-814c-241283d8aaf4
* Version Independent ID: 28c84d41-476f-d14d-814c-241283d8aaf4
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/advanced-concepts/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by pbarnettms** [comment]
By default the emulator does not make you accept the license agreement.  This happens only if you've explicitly chosen to enable sign-in with a Microsoft Account, which is not the default configuration.  That said, you can turn that option off in the emulator settings o=and use the keyboard to navigate this interface and complete the experience.  Beyond that, this feedback is not constructive and not actionable.

**Comment by fvbakel** [comment]
Sorry for my wording, I changed it. I added a recording of the steps. 

You mention that the license agreement is not the default behaviour. It could be that on my first attempt used a wrong button because it was so hard to navigate the user interface of the emulator.

[record.zip](https://github.com/MicrosoftDocs/mixed-reality/files/7625034/record.zip)

Is it possible to make the navigation of the emulator more easy? Is it possble to allow for simple mouse clicks in the emulator?

**Comment by pbarnettms** [comment]
Mouse input is not supported in the emulator.

To proceed you should either turn off "Sign in with a Microsoft Account" or temporarily turn off "Use keyboard for Simulation" and use the keyboard to navigate and complete the sign-in experience.
