### ISSUE TITLE
How can I export and import anchor in WMR？

### ISSUE THREAD

**Issue by BCEF** [MicrosoftDocs/mixed-reality#478]
When I use the following function, I got a error(denied access to WorldAnchor serialization)
WorldAnchorTransferBatch.ExportAsync(transferBatch, OnExportDataAvailable, OnExportComplete);

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 98ca56aa-2a43-30f5-78e4-c3e679dbdcc2
* Version Independent ID: d961cd72-b132-bdbb-709b-b3fe588ab7cb
* Content: [Shared experiences in Unity - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/shared-experiences-in-unity)
* Content Source: [mixed-reality-docs/shared-experiences-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/shared-experiences-in-unity.md)
* Product: **windows**
* GitHub Login: @fieldsJacksonG
* Microsoft Alias: **jacksonf**

**Comment by mattzmsft** [comment]
Hey @BCEF, the dev suggested that you may have missed step #3 in [this section of the article](https://docs.microsoft.com/zh-cn/windows/mixed-reality/shared-experiences-in-unity#setting-the-spatialperception-capability). Can you confirm you successfully set the _SpatialPerception_ capability?

**Comment by BCEF** [comment]
I do set the SpatialPerception capability. 
I use the Immersive HMD.

**Comment by jessemcculloch** [comment]
World anchors are not supported on immersive headsets.
