### ISSUE TITLE
In my Hololens 2, Developer Mode option is grayed out and I am not able to turn it on. Will need more clarification.

### ISSUE THREAD

**Issue by Samvid95** [MicrosoftDocs/mixed-reality#48]
So I have received Hololens 2 from a friend and I noticed my Developer Mode option is grayed out and I am unable to turn it on. I stumbled upon this documentation but unfortunately there isn't useful information available for that case. We will need to add appropriate steps to solve the issue. 

Best,
Samvid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by evmill** [comment]
Hello Samvid,
Sometimes when using a work account / work device you'll receive device management policies. If you see some words along the lines of "some settings are managed by your organization" then they have likely disabled Developer Mode for security reasons.

There's also a chance you may need to be the "device owner" to enable Developer Mode. I'm not sure. In either case you can always [reflash the device](https://docs.microsoft.com/en-us/hololens/hololens-recovery#clean-reflash-the-device) and set it up with a new account.

**Comment by Samvid95** [comment]
Thanks it worked.
