### ISSUE TITLE
"Feedback Hub" doesn't exist in Windows 11

### ISSUE THREAD

**Issue by BitterDone** [MicrosoftDocs/mixed-reality#482]
Unless I did something to disable / uninstall, I have no apps related to "feedback" on my Windows 11 machine. 
![image](https://user-images.githubusercontent.com/4481910/144336957-d488e517-b2d5-466b-94fd-a5e84fe4d17b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbb3b0c5-b2d1-a650-8c86-4b21ec8b4d34
* Version Independent ID: 007a9670-2c14-ed44-3716-ba5894ab7144
* Content: [Filing bugs and feedback - Enthusiast Guide](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/filing-feedback)
* Content Source: [enthusiast-guide/filing-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/filing-feedback.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by BitterDone** [comment]
I'm trying to submit a bug regarding the MRTK Feature Tool, where the program just doesn't open. I see the spinning mouse icon for a split second, and then nothing.

**Comment by BitterDone** [comment]
Also it's the current latest version, MixedRealityFeatureTool-1.0.2111.0-Preview

**Comment by BitterDone** [comment]
Just kidding, either it was originally installed and I removed it, or you have to download it yourself anyway from the Windows Store

Link for other lazies:
https://www.microsoft.com/en-us/p/feedback-hub/9nblggh4r32n

Please update the page to include this link in case others face the same problem

**Comment by qianw211** [comment]
Thank you for your feedback! We have added a link to the Windows Store for downloading and install the app.
