### ISSUE TITLE
Holographic remoting

### ISSUE THREAD

**Issue by Eytos** [MicrosoftDocs/mixed-reality#483]
Hello everyone,
I'm trying to connect my Hololens 2 remotly with my unity project in order to test my software. I have some issues with that.
First of all I don't understant this part :
![image](https://user-images.githubusercontent.com/91499576/144903566-59f4b53d-0d06-4f52-a016-32219b3b4e87.png)
I don't know if the problem is in my openXr configuration but I don't find precisely the submenu "OpenXr Editor Remoting", I only have this :
![image](https://user-images.githubusercontent.com/91499576/144903901-1b03cfb7-1d07-4f68-a702-ca4c06a19838.png)
The even if I try to pass that and click on "Holographic Remoting for Play Mode" I have lot of error coming on.
For exemple if I try to enable "Holographic Remoting for Play Mode" I have this :
![image](https://user-images.githubusercontent.com/91499576/144904226-a7331442-b8b8-40fa-a5c7-a96e5975af19.png)
And if I click on "Fix" then new errors but in the Project Setting Open Xr :
![image](https://user-images.githubusercontent.com/91499576/144904323-1ad8d743-3a28-4a41-8714-d96d30858122.png)
![image](https://user-images.githubusercontent.com/91499576/144904372-0fa6ceaf-2cb5-4e24-be3c-bedf3cc6e808.png)
![image](https://user-images.githubusercontent.com/91499576/144904443-bfb2ce76-8296-4000-b1c8-48e5deeaf2be.png)
And if I fix it, I start again with the first issue..

If someone already succeed, I will be thanksful for your help.

PS : I'm french, sorry for the approximate english, I try my best.

**Comment by srinjoym** [comment]
@Sean-Kerawala We hit these same issues internally trying to setup remoting with a partner. This is the only configuration that worked:

1. The "Holographic Remoting remote app feature group" checkbox should be disabled (not enabled as the docs say)
2. The "Holographic Remoting for Play Mode" feature in the OpenXR tab should be enabled (not in the docs)
