### ISSUE TITLE
This needs to be updated to account for simulating controllers. 

### ISSUE THREAD

**Issue by ChimeraScorn** [MicrosoftDocs/mixed-reality#485]
Controllers are accessed through ISimulatedHuman2, so once you have the Human object, cast to ISimulatedHuman2 to get the LeftController or RightController properties. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f9dd-e42e-0eba-6f81-c11cec7475b2
* Version Independent ID: e927a495-7bee-bb29-8e8c-b1df2686a5e3
* Content: [Perception simulation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/perception-simulation)
* Content Source: [mixed-reality-docs/perception-simulation.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/perception-simulation.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by mattzmsft** [comment]
@ChimeraScorn can you create a PR for the changes you want to make?

**Comment by pbarnettms** [comment]
Controllers are included in the latest version of the documentation.
