### ISSUE TITLE
 holosketch does not recognize the files from unity

### ISSUE THREAD

**Issue by SweetDD** [MicrosoftDocs/mixed-reality#486]
It doesnt work. OneDrive in holosketch does not recognize the files from unity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f1e4a4-be34-3c5b-b30c-7676edaece62
* Version Independent ID: cff3f692-5d66-84f9-7a50-b842a57b2eeb
* Content: [Case study - Building HoloSketch, a spatial layout and UX sketching app for HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-building-holosketch%2C-a-spatial-layout-and-ux-sketching-app-for-hololens)
* Content Source: [mixed-reality-docs/case-study-building-holosketch,-a-spatial-layout-and-ux-sketching-app-for-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/case-study-building-holosketch,-a-spatial-layout-and-ux-sketching-app-for-hololens.md)
* Product: **windows**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark, paseb**

**Comment by SweetDD** [comment]
And what do you mean with "Prepare an image which model Prefab. "?

**Comment by cre8ivepark** [comment]
Sorry for the typo. It means "Prepare a thumbnail image for the model object". Are you using Unity version 5.4.5f1? Since Asset bundle format has changed, it won't work with other Unity version. Tested with Unity 5.4.5f1 and it works well.

**Comment by jessemcculloch** [comment]
Is this issue still needing to be open? @SweetDD?
