### ISSUE TITLE
My Hololens just updated (by itself), as always a shitstorm has come

### ISSUE THREAD

**Issue by manjia** [MicrosoftDocs/mixed-reality#489]
My Hololens just updated by itself, the result? None of my computer vision apps is working anymore. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ede87e9-b4de-472a-df45-dd197f82d911
* Version Independent ID: 67f5e7d2-49b5-d469-4f4a-6cb756034f70
* Content: [Release notes - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes)
* Content Source: [mixed-reality-docs/release-notes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/release-notes.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
This is not the place to report this.  Please use feedback hub.

**Comment by manjia** [comment]
As quick as always I see, FUCK YOU Jesse.

**Comment by jessemcculloch** [comment]
Well, I recently took over this repo and am going thru the issues and trying to resolve or close them.  But thanks for your feedback
