### ISSUE TITLE
.NET Scripting Backend deprecated

### ISSUE THREAD

**Issue by Hefaistus** [MicrosoftDocs/mixed-reality#490]
Unity is apparently deprecating the .NET Scripting Backend, as per this page: https://docs.unity3d.com/2018.2/Documentation/Manual/windowsstore-dotnet.html

This means that the section on the Scripting Backend will soon be out-of-date, especially if the newer releases of Unity are recommended. As it stands, the .NET Scripting Backend also doesn't properly support .NET Standard 2.0, which is giving me a lot of issues.

What is the best course of action on this? I tried searching what Microsoft recommends, but aside a singular reference in the porting guide (which says to switch to IL2CPP), I couldn't find any information related to the deprecation. Is Microsoft working on their own solution to the deprecation, or do I have to simply suck it up and switch to IL2CPP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by manjia** [comment]
That sounds funny, Microsoft has always deprecated (or better removed) stuff not caring about 3rd part projects maintainability and now they are getting kicked out from the Unity environment, without which the Hololens is a pretty useless device.. 
thats how karma works i think

**Comment by keveleigh** [comment]
We'll need to revisit some of our documentation as we move into 2018.2. The deprecation of the .NET scripting backend is planned alongside some of its benefits finally making their way to IL2CPP, such as [managed code debugging](https://blogs.unity3d.com/2018/07/11/scripting-runtime-improvements-in-unity-2018-2/). If you run into any issues with IL2CPP and our course content, please raise an issue on it! I've run a few courses without issue.

**Comment by himanshuajmera** [comment]
Hi,
I'm following this tutorial to learn Basic Hololens development with Unity. In my console, I'm seeing this warning (Virtual Reality SDK Windows Mixed Reality failed to initialize. Will attempt to enable None instead) and my cube (from Chapter 4) is not appearing in the device. Can anyone help?

**Comment by ShadowsOftheBeast** [comment]
@keveleigh, Raising the issue now -> I cant deploy to my hololens, i have cited what is going on on the thread above with the label : unable to deploy, there seems to be lots of pdb files that are not being resolved once you build in unity and open in visual studio, can you please give us a step by step deployment that does not give errors and also does not reference pdb files that cannot be found? for a $3,000 device, i would expect that there would be more activities on the forum, in trying to resolve this from Microsoft??
