### ISSUE TITLE
Documentation request: Please discuss PointersMediator

### ISSUE THREAD

**Issue by julesra** [MicrosoftDocs/mixed-reality#494]
It would be great if this page discussed how PointersMediator ties to pointers (mediation isn't mentioned in this page). Also, when/why should PointerUtils be used for disabling pointers, instead of using a custom PointersMediator ? Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42a9027-955f-e309-b005-00094d8bb4af
* Version Independent ID: 25f57041-a926-97a2-03ba-01d7f758c35d
* Content: [Pointers - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/pointers?view=mrtkunity-2021-05#pointer-event-interfaces)
* Content Source: [mrtk-unity/features/input/pointers.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/input/pointers.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by typride** [comment]
Hello @julesra thanks for your feedback! 

Does this document do what you're describing?
https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/architecture/controllers-pointers-and-focus.md

It better describes pointer remediation and how it relates to pointer disabling. 

As far as I can tell, pointer remediation is best used to automatically activate/deactivate which pointer is in use when there are two components that could be interacted with. So, it would automatically select the closer component to the user, for example. To override this, you could adjust the PointerBehavior (https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/architecture/controllers-pointers-and-focus.md#how-to-disable-pointers).

Please let me know if this isn't satisfactory and I'll work to add this input to the docs. I have reached out to the relevant SME to get more info for you, as well.

**Comment by typride** [comment]
Following up: As of now, this is probably the best answer we can give. Though, thanks to your suggestion, I'll update he doc to better highlight the pointer architecture document to help elucidate how PointerRemediator relates to Pointers and when to use them each respectively for activating/deactivating pointers. 

Note also that new updates to MRTK will hopefully resolve some of this unnecessary complexity with pointer configuration/control. Thanks!
