### ISSUE TITLE
MRTK + Quest2 Does Not Work

### ISSUE THREAD

**Issue by keli95566** [MicrosoftDocs/mixed-reality#495]
I followed everything in the documentation to setup MRTK for Quest2, however, the controller freezes no matter what I do. Controller tracking and hand tracking works fine for other applications.

I tried both Unity 2019.4+ and 2020.3LTS. I am using Oculus integration 35 and the latest MRTK versions. Would be great if you could update the documentations soon!

 
![BugMRTK 1](https://user-images.githubusercontent.com/29271960/148200974-0a9f79aa-71fb-4759-9ef4-50f5d24733b9.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f368fda-6413-ca5e-86d6-cafbc1bc3573
* Version Independent ID: 0bb7f455-d610-23a1-880d-9d95cb37c0be
* Content: [Deploying to Oculus Quest - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/supported-devices/oculus-quest-mrtk?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/supported-devices/oculus-quest-mrtk.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/supported-devices/oculus-quest-mrtk.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by RogPodge** [comment]
Thanks for filing the issue! Can you provide the console logs and video of the controller freeze in action? 

An exception has probably been thrown somewhere, causing the controllers to never gain tracking. We haven't seen this behavior before, so to update the documentation, we need to know which step went wrong/which settings we have made assumptions about.

Listing the MRTK version would also be helpful! The latest release we tested for was MRTk 2.7.3

**Comment by keli95566** [comment]
Hi there, thank you for getting back so quickly! Yes, I am using MRTK 2.7.3, the example for hand tracking. 
Unfortunately, there was neither no errors, log, warnings thrown went built, nor when running the app. 
I also installed [this](https://sidequestvr.com/app/5100/mrtk-samples-with-passthrough-api) app from side quest, the exact same issue happened..

**Comment by RogPodge** [comment]
Sorry for the late response. We're not quite sure what can be happening.

Can you tell us which profiles you are using? In addition, Can you show us your XRI and other deployment settings?

**Comment by typride** [comment]
@keli95566 Any updates from you that we can use to help you?

**Comment by typride** [comment]
Closing for now. Can reopen later if response is given.
