### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by a11303** [MicrosoftDocs/mixed-reality#497]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Version Independent ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Content: [HoloLens Emulator archive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/hololens-emulator-archive)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

HoloLens 2 Emulator build 10.0.19041.1174--------------link error

**Comment by typride** [comment]
Link fixed
