### ISSUE TITLE
Perception Simulation API examples are out of date

### ISSUE THREAD

**Issue by elbuhofantasma** [MicrosoftDocs/mixed-reality#498]
The Perception Simulation API is out of date and contains information for HoloLens 1 and not for HoloLens 2. The code examples are only good for the HoloLens 1 as well, and they should be updated for HoloLens 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aec8bc9f-8879-7158-99e8-5ae1eeacfd88
* Version Independent ID: aec8bc9f-8879-7158-99e8-5ae1eeacfd88
* Content: [Perception simulation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/perception-simulation-overview#control-the-simulated-human)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/perception-simulation-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/perception-simulation-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment]
The examples are still current for HoloLens 2 and were updated when HoloLens 2 was released.  Please cite specifics if you believe this not to be the case.

**Comment by elbuhofantasma** [comment]
Some of the comments in the extended code sample mention the bloom gesture from HoloLens 1. The picture below shows where these comments are at in the sample. Thank you for responding quickly!
![image](https://user-images.githubusercontent.com/65038391/149601710-d54fc7a4-d384-45f1-8c44-0c5e0a3a7a9a.png)

**Comment by pbarnettms** [comment]
Thank you.  However, the mention of 'Bloom' in a code comment has no effect on functionality.  The API call is the same for HoloLens 1 and HoloLens 2 and the example remains current.

**Comment by pbarnettms** [comment]
Thank you.  However, the mention of 'Bloom' in a code comment has no effect on functionality.  The API call is the same for HoloLens 1 and HoloLens 2 and the example remains current.

**Comment by typride** [comment]
@pbarnettms closing this issue. Can reopen if still relevant.
