### ISSUE TITLE
OpenXR Basic Sample video gives http 404 error

### ISSUE THREAD

**Issue by elbuhofantasma** [MicrosoftDocs/mixed-reality#499]
The OpenXR Basic Sample video overview is showing an http 404 error instead of page with the video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7da38f-67f0-9558-e3ec-d1ca87a782e0
* Version Independent ID: 0dc68b17-ee6d-0ae3-31da-792bf0b5deab
* Content: [Getting started with OpenXR - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/native/openxr-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/native/openxr-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **vinnietieto**

**Comment by typride** [comment]
Thank you for the feedback! I've removed the link since the video is embedded in the doc and the link just brought you to the github repo unnecessarily.

**Comment by typride** [comment]
Thank you for the feedback! I've removed the link since the video is embedded in the doc and the link just brought you to the github repo unnecessarily.
