### ISSUE TITLE
No available 3DView API

### ISSUE THREAD

**Issue by MarcellKlepper** [MicrosoftDocs/mixed-reality#500]
The 3DView page of the hololens device portal does not have a documented API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09aeb4f-c11d-108b-cab0-b2fc07adf72d
* Version Independent ID: 83c0eab2-daf3-14c4-0857-2a40cdac6964
* Content: [Device portal API reference - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/device-portal-api-reference#see-also)
* Content Source: [mixed-reality-docs/device-portal-api-reference.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/device-portal-api-reference.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **JLyons**

**Comment by JonMLyons** [comment]
The 3DView page uses the Holographic Perception WebSocket mentioned above:

/api/holographic/perception/client (GET/WebSocket)
Accepts websocket upgrades and runs a perception client that sends updates at 30 fps.
