### ISSUE TITLE
Forgotten portal password?

### ISSUE THREAD

**Issue by dimitrijevic** [MicrosoftDocs/mixed-reality#501]
What to do if you forget what username and password was setup for the portal on the Hololens? It can't be that you have to reset the device and loose all the apps and settings so you have to redo it all... I can see the pin for pairing visible but visiting even after unpair all gives the username/password request again.

**EDIT: Nevermind, found /devicepair.htm**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by JonMLyons** [comment]
Check out the section "Creating a Username and Password" in this document.  It shows the link you can use to reset your password:

"If you wish to change this username or password at any time, you can repeat this process by visiting the device security page by either clicking the Security link along the top right, or navigating to: https://<YOUR_HOLOLENS_IP_ADDRESS>/devicesecurity.htm"
