### ISSUE TITLE
Information is too ambigious

### ISSUE THREAD

**Issue by jelmer3000** [MicrosoftDocs/mixed-reality#501]
In the section [Persistence ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-anchors-in-unity?tabs=wlt#persistent-world-locking)under the tab "world locking tools" it says that the WorldLockingContext component saves "local spatial anchors". It is unclear what component you mean here. "local spatial anchors" do not exist as a component or any archetype in a Unity/MRTK context.  

So, what component should be added to a gameobject for it to be considered and saved "automagically" by the WorldLockingContext component? Thanks for clarifying! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce23a257-72cf-9324-8661-a28c880442bf
* Version Independent ID: 03785876-3645-86bb-ec36-1be4b17759f6
* Content: [World locking and spatial anchors in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-anchors-in-unity?tabs=worldanchor#persistent-world-locking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/spatial-anchors-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/spatial-anchors-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by vtieto** [comment]
Thanks for your feedback! WLT saves and restores the entire global coordinate space relative to the physical world. To restore an object's position in the physical world from a previous session, simply restore the object's pose, just like in non-AR Unity apps and games. Your app doesn't need to interface with spatial anchors or special components at all.

Thanks again for your feedback, the documentation has been updated to better convey this.
