### ISSUE TITLE
Some Unity doc links aren't up to date

### ISSUE THREAD

**Issue by BottomTrap** [MicrosoftDocs/mixed-reality#502]
Just a little remark so that other people won't waste time looking for the current docs.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: fcba0969-c41e-3177-0b1b-a75167bbe753
* Version Independent ID: 88232eae-3a56-e764-b6b5-d87a02d50061
* Content: [Spatial mapping in Unity - Mixed Reality](https://docs.microsoft.com/fr-fr/windows/mixed-reality/spatial-mapping-in-unity)
* Content Source: [mixed-reality-docs/spatial-mapping-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-mapping-in-unity.md)
* Product: **windows**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by jessemcculloch** [comment]
Fixed
