### ISSUE TITLE
Enforced Sign-In on device

### ISSUE THREAD

**Issue by Nakle** [MicrosoftDocs/mixed-reality#503]
Is there a way to **not** require sign-in after sleep/restart/OS Update on the Hololens? 
The Account is managed through Azure Active Directory with provision package installed for commercial edt.

**Comment by Nakle** [comment]
I even have 'DevicePasswordEnabled' **Not Enabled** in the provision package installed on the Hololens..
![image](https://user-images.githubusercontent.com/3876702/42747809-26563dc2-88de-11e8-8acf-11f8b3895ac5.png)

**Comment by jessemcculloch** [comment]
Can you tell me what documentation page this is in reference to?
