### ISSUE TITLE
Teleporting w/ RaiseTeleportRequest

### ISSUE THREAD

**Issue by istvanContXtual** [MicrosoftDocs/mixed-reality#503]
Hi,

Is there a way to teleport or move the camera without the parabolic teleport pointer?

I am trying to create a map or toolbelt based system, where i can just press a button in a ui panel and move the camera top a pre defined location in the world.

Tried CoreServices.TeleportSystem.RaiseTeleportRequest(pointer, teleportHotspot); but does not seem to be working.

Any help/suggestion is much appreciated!

**Comment by typride** [comment]
Hello! Thanks for reaching out! 

Which version of unity are you using? Can you also provide any other relevant info that could help us solve this for you?

**Comment by typride** [comment]
Closing issue as of now.. @istvanContXtual please feel free to comment or reopen issue if not resolved.
