### ISSUE TITLE
Working with WebXR with custom optics.

### ISSUE THREAD

**Issue by mrhegemon** [MicrosoftDocs/mixed-reality#506]
Hey there, I am trying to build a common WebXR framework for the Hololens, Mira, Meta, HoloKit, Smoke AR, Vufine Cardboard, Daquri, and Epson.

The hope is to have common framework for all WebXR build on Three.js and Aframe. Our current project is lifescope.io. It has a bit of a custom render system. 

Are there any public measurements of Hololens and other WMR device optics?

(I’m also trying to get the same measurements for other headsets)

Parameters include:

Interlens Distance
Screen to lens distance
Vertical distance to lens center
Distortion Coefficients (K1, K2)
Max FOV (Inner, Outer, Top, Bottom)
Stereo Separation

Figured I would ask before trying to figure it out myself. 

I would also love to talk more about using your platform. Love your hardware!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29fa1597-758b-7549-69fb-38f4c7d0353f
* Version Independent ID: ae91ad80-866d-952d-d484-948e730d4299
* Content: [Using WebVR in Microsoft Edge with Windows Mixed Reality - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-webvr-in-edge-with-windows-mixed-reality)
* Content Source: [mixed-reality-docs/using-webvr-in-edge-with-windows-mixed-reality.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-webvr-in-edge-with-windows-mixed-reality.md)
* Product: **windows**
* GitHub Login: @YashMaster
* Microsoft Alias: **yabahman**

**Comment by hferrone** [comment]
Hi @mrhegemon,

You can find device specifications we have available for HoloLens 2 at https://docs.microsoft.com/en-us/hololens/hololens2-hardware and HoloLens 1st Gen at https://docs.microsoft.com/en-us/hololens/hololens1-hardware.

Cheers!
