### ISSUE TITLE
LUIS app creation UI has changed, instructions do not match UI

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#51]
The luis.ai webpage UI has changed and there are now options that don't match with what the user is instructed to do. 

Old UI for app creation
![image](https://user-images.githubusercontent.com/30964480/93411973-21b87e80-f851-11ea-9dc6-15762c12365b.png)

New UI for app creation
![image](https://user-images.githubusercontent.com/30964480/93411829-d8682f00-f850-11ea-8700-ce00798ddc37.png)

Old UI for entity creation. The tutorial instructs the user to select a Simple Entity but **this option is not available.** 
![image](https://user-images.githubusercontent.com/30964480/93411865-e918a500-f850-11ea-961b-e888d0f1b4ca.png)

New UI for entity creation
![image](https://user-images.githubusercontent.com/30964480/93411881-ef0e8600-f850-11ea-87b0-ec9b9b5b1286.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e92d1-bd95-93c8-7e97-d1df949ed882
* Version Independent ID: bf701f2a-41dc-c37c-d947-28d3a4bcce73
* Content: [Azure Speech Services tutorials - 4. Setting up intent and natural language understanding - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mrlearning-speechsdk-ch4)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch4.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mrlearning-speechSDK-ch4.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@martinwilter Is this a tutorial you or your team updated? If so, can you add these new screenshots and some language to address these new options?

**Comment by martinwilter** [comment]
@hferrone, our team created this in 2019, but we didn't update it in 2020.

**Comment by martinwilter** [comment]
@hferrone, I was just informed that our team is likely to be able to update this tutorial in the near future.

**Comment by hferrone** [comment]
@martinwilter Ok thanks, please close this issue when it gets an update!

**Comment by martinwilter** [comment]
@hferrone, just a heads-up, I'm no longer on the team that handles the tutorials so I won't know if/when this tutorial series is updated. 

(You can still tag me on future issues if my assistance is needed).

**Comment by hferrone** [comment]
Closing this one because we have duplicates for tracking the issue :)
