### ISSUE TITLE
Custom Skybox?

### ISSUE THREAD

**Issue by ctkjedi** [MicrosoftDocs/mixed-reality#514]
All the information here is helpful, but lacking one small bit. The skybox is mentioned, but there doesn't seem to be anything outlining how to customize that, so only the default "blue sky with sun" is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d039f73-3530-e97d-c1be-c2e2b9c87953
* Version Independent ID: c041e4f7-fa4a-a1d2-ce4a-db985c9f3633
* Content: [Add custom home environments - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/add-custom-home-environments#trying-a-sample-environment)
* Content Source: [mixed-reality-docs/add-custom-home-environments.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/add-custom-home-environments.md)
* Product: **windows**
* GitHub Login: @mattzmsft

**Comment by yamroz** [comment]
There is currently problem with importing your sample environment to Blender 2.8, their import script does not support MSFT_texture_dds
Is there any possibility to provide this project without using this extension? This way we could use it as a template of sorts.

Thank you!
