### ISSUE TITLE
Can not deploy to Hololens

### ISSUE THREAD

**Issue by aliaga-d** [MicrosoftDocs/mixed-reality#515]
A member of our team received a mail from email@engage.microsofthololens.com to update the OS of our hololens. After that I can not deploy any of my applications, or even Academy Basics 100 to the hololens (either paired or through USB).
Any application builds but I get the error:

> Error		DEP6720: Failed to deploy package 'Native Debugger' (EB22551A-7F66-465F-B53F-E5ABA0C0574E). DEP6959: Error removing the file from the remote device: 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\VSRemoteTools\x86\1041\DiagnosticsHubMsg.dll. 指定されたファイルが見つかりません。(File not found)  (HRESULT からの例外:0x80070002)'.	(Exception thrown) 			

This update in Hololens has stopped all our development so I would like to ask your help on dealing with this issue. Very much appreciated

**Comment by jessemcculloch** [comment]
Closing do to age.  If this is still an issue, please reach out to support.microsoft.com
