### ISSUE TITLE
\

### ISSUE THREAD

**Issue by turkeyl** [MicrosoftDocs/mixed-reality#517]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 542e0b57-5be5-a436-de94-d64865f0a6a2
* Version Independent ID: 06a6194c-d1d8-bc23-ba24-73cea88f78d9
* Content: [Windows Mixed Reality headset health and safety - Enthusiast Guide](https://docs.microsoft.com/ar-sa/windows/mixed-reality/enthusiast-guide/wmr-health-safety-comfort)
* Content Source: [enthusiast-guide/wmr-health-safety-comfort.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/wmr-health-safety-comfort.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by turkeyl** [comment]
.././.

**Comment by turkeyl** [comment]
517

**Comment by turkeyl** [comment]
.'''''

**Comment by turkeyl** [comment]
'

**Comment by turkeyl** [comment]
turkey1

**Comment by typride** [comment]
Comments are gibberish. Possible injection attempt.
