### ISSUE TITLE
IOL'[

### ISSUE THREAD

**Issue by turkeyl** [MicrosoftDocs/mixed-reality#519]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 77f464b6-99ef-6d78-c30a-4066e9e7a411
* Version Independent ID: 88e27323-63f3-5113-5038-6ee50a606491
* Content: [Get help with PC compatibility - Enthusiast Guide](https://docs.microsoft.com/ar-sa/windows/mixed-reality/enthusiast-guide/get-help-with-pc-compatibility#WarnBluetooth)
* Content Source: [enthusiast-guide/get-help-with-pc-compatibility.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/get-help-with-pc-compatibility.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @qianw211
* Microsoft Alias: **v-qianwen**

**Comment by typride** [comment]
It looks like there was no note entered in this. The Arabic text above says: [اكتب ملاحظاتك هنا] -> [Write your notes here].
