### ISSUE TITLE
Mixed Reality Feature Tool is not launching when I click the exe 

### ISSUE THREAD

**Issue by mhussar** [MicrosoftDocs/mixed-reality#521]
The Mixed Reality Feature Tool is not launching when I click the exe 
I installed all the prerequisite files (.net 5 runtime etc) 
There should be troubleshooting information on this page for issues like this.
Please help.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0405e5-aef5-5ed3-d9a1-960b4065300b
* Version Independent ID: dd9cd8d6-caea-6146-fd71-c5b3605435c4
* Content: [Welcome to the Mixed Reality Feature Tool - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @davidkline-ms
* Microsoft Alias: **v-hferrone**

**Comment by typride** [comment]
@mhussar thanks for your feedback! I just ran through the directions (installed .NET, and ensured I am running updated Windows 10). It worked on my computer.

Can you confirm that you: 

- Are running Windows 10?
- Installed the right version of .NET for your system (Windows   Arm64 | x64 | x86)
- Extracted the folder for the Mixed Reality Feature Tool (unzipped)

Thanks for confirming these things! Will look forward to hearing back from you about this.
