### ISSUE TITLE
10.0.17134.111 Device Portal Live Preview Crashing

### ISSUE THREAD

**Issue by jbwhite93** [MicrosoftDocs/mixed-reality#522]
After a forced Hololens update the Live Preview within the Device Portal crashes after just a few short seconds. This issue is also prevalent through the Hololens companion app, we have tested it on multiple laptops and desktops and were met with the same issue. We only have one Hololens at our company and this effects how we can show off demos. Not sure if it is the hardware not taking the update correctly or if others are experiencing this issue on this Rev 4 version we do not have a way of testing a different Hololens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ede87e9-b4de-472a-df45-dd197f82d911
* Version Independent ID: 67f5e7d2-49b5-d469-4f4a-6cb756034f70
* Content: [Release notes - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes)
* Content Source: [mixed-reality-docs/release-notes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/release-notes.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Closing issue due to age.  If still an issue, please reach out to support.microsoft.com
