### ISSUE TITLE
Guide using old version of Unity

### ISSUE THREAD

**Issue by drstark** [MicrosoftDocs/mixed-reality#523]
This guide uses an old version of Unity and many of the menu options have been changed. For example, the build options in Unity is now UWP, not Windows Store, and there is no to set the SDK to Universal 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ropinheiro** [comment]
Also, option to allow VR is now in a different (specific) sub-section of Player -> Settings.

**Comment by keveleigh** [comment]
Updated a few of these in https://github.com/MicrosoftDocs/mixed-reality/pull/2314
