### ISSUE TITLE
This document is out of date

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/mixed-reality#524]
There were changes in the 2018 Spring update to spaces.  This document still refers to the old version of spaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a387bd0-0edb-1ffb-dc7a-b1c207e6cecb
* Version Independent ID: 7e09e2ee-f114-ab87-f7fd-9075431e912b
* Content: [Environment considerations for HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/environment-considerations-for-hololens)
* Content Source: [mixed-reality-docs/environment-considerations-for-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/environment-considerations-for-hololens.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Doc updated
