### ISSUE TITLE
Page not being updated

### ISSUE THREAD

**Issue by egvandell** [MicrosoftDocs/mixed-reality#525]
This page doesn't seem to be getting updated, it references an "upcoming" event that is in the past.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8249a505-fcfc-b123-b391-46365e0f1c34
* Version Independent ID: 8249a505-fcfc-b123-b391-46365e0f1c34
* Content: [Journey into Mixed Reality development (for beginners) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/whats-new/journey-to-mr-series)
* Content Source: [mixed-reality-docs/mr-dev-docs/whats-new/journey-to-mr-series.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/whats-new/journey-to-mr-series.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by typride** [comment]
The doc has been updated and is continuing to be updated as events pass! Thank you for your feedback.
