### ISSUE TITLE
Problems running on Hololens

### ISSUE THREAD

**Issue by njss** [MicrosoftDocs/mixed-reality#528]
When I test the application on the PC everything runs, a photo is taken and MS Azure service replies with correct person identification.
However, when running on Hololens, an error message is displayed  on the Hololens regarding the mixed reality toolkit version. Also a message states that either the camera cannot be activated or the photo cannot be stored/found on the Hololens device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672ee7be-91f6-7602-1a3b-8cb5db8c3592
* Version Independent ID: 268f1b1b-1e51-9737-5d5a-e44d96aa849a
* Content: [MR and Azure 304 - Face recognition - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-304#bonus-exercises)
* Content Source: [mixed-reality-docs/mr-azure-304.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-304.md)
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by DrNeil** [comment]
Lab 304 does not use the MR toolkit, I wonder if you have added the reference by mistake ?
Regarding the camera usage, make sure you have the assembly capabilities set correctly in your Visual Studio project.

**Comment by njss** [comment]
I have re-followed the tutoria. Now the only problem is that it is never possible to take a photo using hololens (latest update). It always gives a msg stating that it was not possible to take a photo? Any hints or a running updated example?

**Comment by njss** [comment]
Thank you for your answers

**Comment by DrNeil** [comment]
Have you made sure the UWP capabilities are set to allow the app to access the camera? When you deploy the app to the HoloLens and run the app the first time, it should ask for permission to use the camera.

**Comment by njss** [comment]
Yes sure. And hololens asks for permission to use the camera. I select yes, the app starts and as soon as I do the gesture to Capture the photo the error occurs. I then try to debug it while running on hololens and the message states that it was not possible to take a photo

**Comment by njss** [comment]
It is never possible to use the camera on the Unity 2018.2f1 hololens app

**Comment by DrNeil** [comment]
In the prerequisites you will notice this lab specifies Unity 2017.4. 
It has not been tested with Unity 2018.2f1

**Comment by njss** [comment]
Well I guess that soon Unity 2018 will then be working again properly with Hololens?

**Comment by njss** [comment]
I wonder why everything that I tested worked perfectly (inputs interaction, vuforia, remote emulator)with the new Unity 2018 except for  the camera? But I understand that this tests will take some time. I will continue the app development using Unity 2018 and patiently wait for mixed reality toolkit updates and for an approved version of Unity and then work again on context-aware features using the camera. Thanks for the fast support
