### ISSUE TITLE
CustomVisionObjectsのusingが必要？

### ISSUE THREAD

**Issue by haveagit** [MicrosoftDocs/mixed-reality#529]
本手順通りに進めたつもりですが、Chapter 11まで進めても
CustomVisionTrainer.csとCustomVisionAnalyser.csにコンパイルエラーが残りました。
両クラスにusing static CustomVisionObjects;を追加し、さらにCustomVisionObjects.csのMultipartObjectをpublicに変更したところ正常にコンパイルできたのですが、この方法でよかったのでしょうか？
それとも私の実装手順が誤っていますでしょうか？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889db7e9-a0ea-abb3-9b25-f9db5527655c
* Version Independent ID: 6fd8a913-c2ae-a45e-1461-357f46105e34
* Content: [MR and Azure 302b - Custom vision - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-302b#chapter-9---create-the-customvisiontrainer-class)
* Content Source: [mixed-reality-docs/mr-azure-302b.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-302b.md)
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by elliotmoule** [comment]
Hi, @haveagit.

I'm having trouble understanding where you issue is; are you saying that you cannot compile the project using the code provided? 

If the above is true, can you please confirm that the following is correct for your project:
- You are using Unity 2017 LTS (anything later will not work).
- You have imported the Newtonsoft DLL plugins, and set them up correctly. 
- You have your project set to Universal Windows Platform.
- Remember, as per instructions, the MultipartObject class is OUTSIDE the CustomVisionObjects class, as are all other tags and objects. The CustomVisionObjects class itself should be empty.

**Comment by haveagit** [comment]
Hello, elliotmoule

Thank you for your reply.

>are you saying that you cannot compile the project using the code provided?

Yes. compile error occurred.

but I had skip reading 'outside' in Chapter 7.
I modified code refferd your advice Then compiling succeeded.

Thanks.

**Comment by elliotmoule** [comment]
Hi @haveagit,

Very pleased that you were able to solve your issue 👍 

If you are satisfied that your issue has been solved, please close the issue. 

Thanks for using the MR and Azure Docs, feel free to message if you have any other troubles.

Regards,

Elliot Moule.

**Comment by kaled1993** [comment]
Hi, 

the application stack on Analysis (red cursor)  in both training and analysis mode i donno from where the issue comes.
plz help 

thanks.

**Comment by elliotmoule** [comment]
> Hi,
> 
> the application stack on Analysis (red cursor) in both training and analysis mode i donno from where the issue comes.
> plz help
> 
> thanks.

Hi @kaled1993 ,

Are you able to provide some more information about your issue?

- What course (MR and Azure 3..?)
- Any errors that you are getting in the console.
- Screenshots of your issue.

Regards,

Elliot
