### ISSUE TITLE
Eye tracking not working in OpenXR

### ISSUE THREAD

**Issue by zorderjohn** [MicrosoftDocs/mixed-reality#529]
I was having a rough time making this to work using MRTK and OpenXR. I solved it using this:

https://localjoost.github.io/Getting-Eye-Tracking-to-work-with-OpenXR-on-HoloLens-2/

The step I was missing and not described anywhere was Adding The "Eye Gaze Interaction Profile" under The OpenXR dialog in Project settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3116f048-47d4-0036-fa01-5fdc4e68c750
* Version Independent ID: 7b0411d2-830d-b219-7942-00a407d46bf2
* Content: [Eye Tracking Basic Setup - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/eye-tracking/eye-tracking-basic-setup?view=mrtkunity-2021-05#eye-tracking-requirements-checklist)
* Content Source: [mrtk-unity/features/input/eye-tracking/eye-tracking-basic-setup.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/input/eye-tracking/eye-tracking-basic-setup.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by typride** [comment]
Added link to article where this topic is covered! Thanks for your feedback!
