### ISSUE TITLE
Wrong button blueprint used

### ISSUE THREAD

**Issue by js-dignitas** [MicrosoftDocs/mixed-reality#53]
Under "Adding a button" section the instructions say to use BP_SimpleButton.  You should actually use BP_ButtonHololens2, like the screenshot shows.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Hi @js-dignitas this update is going in today, thanks!
