### ISSUE TITLE
Missing info which HMD's support built in Bluetooth radio

### ISSUE THREAD

**Issue by TheJokingTeen** [MicrosoftDocs/mixed-reality#532]
Various parts of the enthousiast guide such as in controllers-in-wmr.md mention HMD's with integrated bluetooth, but there is no list for consumers to know if their HMD is supported.

**Comment by typride** [comment]
Hello! Thanks for your feedback. For your HMD, it would be best to search to see if it has integrated bluetooth then search to see if your motion controllers are compatible with your HMD or another PC/computer.

If you need help setting up your motion controllers with your HMD, this is a good article to start with: https://docs.microsoft.com/en-us/windows/mixed-reality/design/motion-controllers .

As for a list of all controllers and what HMDs they are compatible with, we aren't in a position to cover all options. It's best to search for compatibility for your specific device(s).

**Comment by TheJokingTeen** [comment]
If the before you buy FAQ has technical specifications, why can't it include bluetooth support info as well? [mixed-reality](https://github.com/MicrosoftDocs/mixed-reality)/[enthusiast-guide](https://github.com/MicrosoftDocs/mixed-reality/tree/docs/enthusiast-guide)/before-you-buy-faqs.md
