### ISSUE TITLE
Can we use Perception Simulation to send voice input? thanks

### ISSUE THREAD

**Issue by LimingRenPA** [MicrosoftDocs/mixed-reality#534]

**Comment by typride** [comment]
There is no Simulation API for injecting voice input programmatically in the current public release. That said, the HoloLens 2 Emulator allows using the PC microphone to manually inject voice input, and 3rd party virtual microphone software solutions can be used in an automated manner with the emulator, though we don't recommend any specific software solution. 

We can't guarantee the quality or security for any 3rd party tools or aforementioned manual solutions, but it may be possible to simulate voice input.
