### ISSUE TITLE
WIndows license for HoloLens 2 emulator

### ISSUE THREAD

**Issue by LimingRenPA** [MicrosoftDocs/mixed-reality#535]
Is a windows license needed for using the emulator?  I am getting this page when using HoloLens 2 emulator.

Thanks

![image](https://user-images.githubusercontent.com/74560586/156850201-345d1681-f6ee-4965-aa29-89ab0cfb8c57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c84d41-476f-d14d-814c-241283d8aaf4
* Version Independent ID: 28c84d41-476f-d14d-814c-241283d8aaf4
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by typride** [comment]
@LimingRenPA thanks for asking! Which version are you using?

 [HoloLens 2 Emulator (Windows Holographic, version 21H2 March 2022 Update)](https://go.microsoft.com/fwlink/?linkid=2189132).
[HoloLens Emulator (first Gen) and holographic project templates](https://go.microsoft.com/fwlink/?linkid=2065980).

**Comment by typride** [comment]
Closing issue for now. Based on other issues contributed by @LimingRenPA , it seems safe to assume that this issue was resolved and you've moved onto development with your device.
