### ISSUE TITLE
Buttons not documented in the Device Portal API

### ISSUE THREAD

**Issue by mattwojo** [MicrosoftDocs/mixed-reality#536]
Redirected from [issue 2572 filed in the Windows apps repo](https://github.com/MicrosoftDocs/windows-uwp/issues/2572) by @[Filimindji](https://github.com/Filimindji).

...referring to this page : https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/device-portal-api-reference#map-manager

and specifically about the **buttons (Reset System Map, Anchors Export System Map, Anchors Export System Map Export System Anchors, Upload a map, Upload an anchors file) that are not documented in the API.**

**Comment by typride** [comment]
Thanks @mattwojo! Upon inspection, it looks like these buttons are documented in the API.

@Filimindji , is this what you're looking for or is there something missing from these? 

[Reset System Map under 'Other'](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/device-portal-api-reference#other)
`Reset System Map: $.post("/api/holographic/mapmanager/resetmapandanchorsandsrdb")`

[Anchors Export System Map & Export System Map ... ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/device-portal-api-reference#export)
`$.post("/api/holographic/mapmanager/exportmapandanchors")`

Upload a map
[Upload a Map or Anchor](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/device-portal-api-reference#downloaduploaddelete-files)
`$.post("/api/holographic/mapmanager/download?FileName=" + spaceID)`

**Comment by typride** [comment]
Closing for now, but can reopen if issue is not resolved.
