### ISSUE TITLE
404 error for link to "Kinect"

### ISSUE THREAD

**Issue by kedarjoyner** [MicrosoftDocs/mixed-reality#537]
Received a 404 error when clicking on the linked "Kinect" text:
<img width="1253" alt="Screen Shot 2022-03-04 at 7 51 05 PM" src="https://user-images.githubusercontent.com/12139428/156862950-24c2d0c0-ca35-4e42-b1aa-95d4eabcb6fa.png">

Thank you for compiling all of this amazing content! Enjoying learning about mixed reality so far 🎉

**Comment by typride** [comment]
Updated the link! Thanks!

**Comment by typride** [comment]
Also, we very much appreciate your thanks! Very pleasing to know you're enjoying the learning process!
