### ISSUE TITLE
Cannot see HoloLens2 system keyboard display pad

### ISSUE THREAD

**Issue by rueilmanzambi** [MicrosoftDocs/mixed-reality#539]
Hello, I am building an app with MRTK in Unity and I am deploying it to the HoloLens 2. I am calling the system keyboard TouchScreenKeyboard, but it is not showing the display pad part of the keyboard, i.e., when I am entering the characters with the system keyboard inside the app, I cannot see what I am typing. I'am using the default keyboard.

**Comment by typride** [comment]
I'm including some relevant documentation here that may assist you.
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/example-scenes/hand-interaction-examples?view=mrtkunity-2021-05
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/ux-building-blocks/button?view=mrtkunity-2021-05

Note: "..the system keyboard will not show up when performing Unity Remoting from the editor to a HoloLens."
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/keyboard-input-in-unity

https://docs.unity3d.com/ScriptReference/TouchScreenKeyboard.Open.html
