### ISSUE TITLE
The Gaze part, Camera.main.transform.position

### ISSUE THREAD

**Issue by ZachNK** [MicrosoftDocs/mixed-reality#541]
In chapter 2 the Gaze part,
when I keep with the tutorial and I check what I made in the hololens,
I don't get it, What is the problem of

var headPosition = Camera.main.transform.position;

on the WorldCursor.cs?

On the Console statements, it said "Object reference not set to an instance of an object".

How can I solve this problem?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/ko-kr/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by elliotmoule** [comment]
From what I can see, this is in relation to Chapter 2, of MR Basics 101 (the World Cursor script)?

From your description, there is a good chance you have something wrong with the Camera in your scene. Please verify that you have at least one camera in your scene, and it has the **Tag:** MainCamera. 

![cameratag](https://user-images.githubusercontent.com/29968849/44966284-9e83a300-af7d-11e8-9ff3-39ed7eb78415.png)

Regards.

**Comment by keveleigh** [comment]
Agreed with the above. Likely, you don't have a camera in your scene tagged as the `MainCamera`.
