### ISSUE TITLE
Object Manipulator Behaviour: Child Game Object does move the parent.

### ISSUE THREAD

**Issue by julja94** [MicrosoftDocs/mixed-reality#542]
I came across an issue with the Object Manipulator component in my application. 
There is parent Game Object with an Object Manipulator script that functions as an origin for multiple other Game Objects, which are instantiated as children. These children have their own Object Manipulator component, that is disabled and only enabled if needed.

Now I want to move the parent (a cube mesh with an Box Collider) and it's children. This works as expected. 
But if I focus on a child Game Object with the Object Manipulator disabled, but enabled Box Collider, it moves the parent with all it's children. I didn't expect this behavior. 

Expected Behavior: If a Game Object with a Box Collider is the child of a Game Object with an Object Manipulator component it should not start the manipulation of the parent. 

When the Object Manipulator of the child is enabled, the transformation of the child is not affecting the parent. 

Is there a setting option I am missing? 

MRTK version: 2.5.7
Unity version: 2020.3.25f1

Example hierarchy: 
- Parent: Game Object with components: cube mesh, Box Collider, Object Manipulator (enabled) ...
-- Child: Game Object with components: some mesh, Box Collider, Object Manipulator (disabled) ... -> will move parent
-- Child: Game Object with components: some mesh, Box Collider, Object Manipulator (enabled) ... -> will not move parent

**Comment by typride** [comment]
Thanks, @julja94, for pointing this out. Will get back to you!

**Comment by Zee2** [comment]
If the parent ObjectManipulator is enabled, it will be triggered by interactions on child colliders. This is generally a Unity behavior wherein collider events bubble up. This is useful in cases where you are building composite collider arrangements built out of many sub-colliders, but can cause problems if/when you have nested interactables.

I would recommend enabling/disabling the collider of the child along with the corresponding ObjectManipulator and seeing if that fixes your issue(s).

**Comment by julja94** [comment]
Hey @Zee2 and @typride ,
thank you for your quick replies.

It is a good idea to disable die collider of the children, if the object ObjectManipulator ist disabled. But the children also have buttons from the MRTK toolbox, which have their own colliders I cannot disable. So now if I interact (far interaction) with a button it unfortunately moves the parent. 

My current solution is to disable the parent ObejctManipulator, when it is positioned and reenable it when needed. This way during the application the children will not affect the parents position. 

I can work with that. It still would be nice, if there is maybe a check, wether the collider selected is the same of the ObjectManipulator Game Object or not.
