### ISSUE TITLE
Simple spelling mistake 

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/mixed-reality#543]
clear the screen *too* black

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b548ae6-f9c1-f8ac-172b-efc80b7b1d26
* Version Independent ID: b5a2db60-a656-daae-ab4a-c47fda79791c
* Content: [Performance recommendations for Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/performance-recommendations-for-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/performance-recommendations-for-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/performance-recommendations-for-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **vinnietieto**

**Comment by typride** [comment]
PR made for spelling update. Will be merged soon.
