### ISSUE TITLE
How to manually re-sync corporate certificates

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/mixed-reality#546]
We have 2 Hololenses and are developing with Unity for it. With Unity 2018.2, they now implemented verification against platform-specific certificate stores.
Unfortunately, from this point on I can no longer use the app on those, because I have the described issue about missing certificates.
We have two different access points in our company I switched between, but that did not do anything.

How do I make sure the Lenses get their certificate stores updated correctly?

**Comment by Alexees** [comment]
Ok, it works again without any known reason... :(
Just tried it again out of curiosity on monday and it worked.

**Comment by Alexees** [comment]
I am not sure if Unity is investigating and this and in that, contacting Microsoft, but I found out how this could be reproduced. This is a reference to the Unity bug report:

https://fogbugz.unity3d.com/default.asp?1076758_6nsckgiqt4l4r34i

The Hololens that never visited our web addresses we send Webrequests to, will fail in doing so. It will only work if the lens visited those addresses via Edge browser once. Then in keeps working.

**Comment by comicxmz001** [comment]
@Alexees I ran into the same issue. For all the methods I've tried, yours is the only one that works at the moment -- Calling the exact API (not just the base URL) in edge browser.
