### ISSUE TITLE
Spectator View

### ISSUE THREAD

**Issue by menicon** [MicrosoftDocs/mixed-reality#548]
Hi,

I had been trying the Spectator view example, my iPhone was able to turn on my Hololens camera, but somehow my Hololens cannot scan the QR Code on my iPhone, is there any tutorial I can follow for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c80c33-09c9-2f47-7486-d6c406a9a1a4
* Version Independent ID: f8ae5662-23e0-141b-efcc-8e5fb3361193
* Content: [SpectatorView (Preview and Pro) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view)
* Content Source: [mixed-reality-docs/spectator-view.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spectator-view.md)
* Product: **windows**
* GitHub Login: @danielescudero
* Microsoft Alias: **daescu**

**Comment by YUEJINYUAN** [comment]
Hi menicon ,I'm trying spectator view Preview too. but I have some trouble with it ，I wanna your help. I can compile the preview example without error, but when I compiled it into hololens with VS2017, nothing (including cursors) was visible in hololens. Why?

**Comment by chrisfromwork** [comment]
Hello,

Detecting the ArUco marker requires building the SpectatorViewPlugin dll. You then have to add said dll and its dependencies into the your unity project's plugin directory (https://github.com/Microsoft/MixedRealityToolkit/tree/master/SpectatorViewPlugin).

If you have performed these steps, running the spectator view example under the visual studio debugger will show unity log output in the visual studio output window. Looking for warnings here may provide more information on what is going wrong (The main thread may time out while running the detection algorithm, something may be wrong with the image obtained from the HoloLens PV camera relative to what the detection algorithm expects, the dll's may not be called/configured correctly, etc). Did you see any warnings or errors in log output?
