### ISSUE TITLE
Various links in the package contents table are broken

### ISSUE THREAD

**Issue by elbuhofantasma** [MicrosoftDocs/mixed-reality#549]
The following links on this page are broken:

- BuildWindow
- ReserializeAssetsUtility
- ScreenshotUtility
- TextureCombinerWindow
- TestUtilities
- Samples~
- StandardAssets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32083af-77bd-e53a-c63e-3aefab07a190
* Version Independent ID: 487af5bb-e5f5-849b-7ee7-300a6a3ec761
* Content: [MRTK packages - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/packages/mrtk-packages?view=mrtkunity-2021-05#tools-package)
* Content Source: [mrtk-unity/packages/mrtk-packages.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/packages/mrtk-packages.md)
* Product: **mixed-reality**
* GitHub Login: @davidkline-ms
* Microsoft Alias: **davidkl**

**Comment by typride** [comment]
Working on this! Thank you for the issue!

**Comment by typride** [comment]
Thank you! I have updated this page with links for tools/utilities that have existing overviews or links. The others mentioned do not have an overview or tutorial associated with them.
