### ISSUE TITLE
The SampleQRCodes Unity project doesn't work on Hololens 2

### ISSUE THREAD

**Issue by tmhab** [MicrosoftDocs/mixed-reality#55]
Newer Unity versions (2020.1.6f1) when building the SampleQRCodes Unity project and deploying it to Hololens 2, no QR codes are being tracked and the Axis object is just stationary in front of eyes of the wearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by LuuSangCntt** [comment]
I hope you got the project running on Hololens 2. One thing you can check is the Mixed Reality Toolkit profile in the scene. I used the "XRSDKCustomProfile1" from the Example project.
