### ISSUE TITLE
Use of Simulation in Device Portal

### ISSUE THREAD

**Issue by raviteja-kurra** [MicrosoftDocs/mixed-reality#553]
What is the use of simulation in Device portal. How to use it?
there is no information regarding that in this document. it would be helpful for us if you can provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#simulation)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by pbarnettms** [comment]
Simulation allows you to tightly control input to HoloLens or Windows Mixed Reality that is usually read from the cameras and other sensors.  It is used by the HoloLens Emulator where there are no hardware sensors, but can also be used on a physical HoloLens devices for purposes such as test automation.  Please see https://docs.microsoft.com/en-us/windows/mixed-reality/perception-simulation for details on the APIs available for controlling the device when in simulation mode.  A HoloLens 2 device and Windows Mixed Reality can also manually be controlled when in simulation mode.  Please see the note about PerceptionSimulationInput at https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator.
