### ISSUE TITLE
Error Communicating with the mixed reality openxr service

### ISSUE THREAD

**Issue by robgrahamau** [MicrosoftDocs/mixed-reality#553]
No matter what I try and do I can not get the Developer Settings to work in the OpenXr Tools for WMR. I simply get the ERROR COMMUNICATING WITH THE MIXED REALITY OPENXR SERVICE.
However The service is running, shows as running in the windows services list, System status shows that I am running Runtime version 105.2102.11004, API version 1.0.22, Vendor Identifier 0x45e, Shows that XR extensions, etc. The home page says the service is running, The Demo works and runs though the ctrl+f2 option does not appaer to work.

I am on Windows 11  version 21h2, OS built 22000.593
Windows Mixed Reality is up to date and running fine.

I've searched online can't find anything short of people saying do a 'full pc reinstall' which is not a valid option. 

I've tried killing AV, Fire wall etc etc etc no luck.

**Comment by robgrahamau** [comment]
So a complete reinstall of WMR fixes this but appeared to downgrade me from run time 150.2102.1104 to 110.2202.1002 

Is it possible that the issue is related to windows 11's default WMR runtime version?

**Comment by brycehutchings** [comment]
Sorry to hear about your problems with the service, but glad it is working now. 110 is our most recent release. It sounds like you previously had 105 rather than 150, so you should be in good shape now.
