### ISSUE TITLE
Update to include the link to the recorded lecture

### ISSUE THREAD

**Issue by trnoble** [MicrosoftDocs/mixed-reality#554]
Hello Microsoft Team,

I am trying to view the recorded lectures for Journey into XR development. It appears that someone forgot to update the URL links to the recorded media for episodes 4 and 5. It would be great to continue viewing the whole series. Please address.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8249a505-fcfc-b123-b391-46365e0f1c34
* Version Independent ID: 8249a505-fcfc-b123-b391-46365e0f1c34
* Content: [Journey into Mixed Reality development (for beginners) - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/whats-new/journey-to-mr-series)
* Content Source: [mixed-reality-docs/mr-dev-docs/whats-new/journey-to-mr-series.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/whats-new/journey-to-mr-series.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by typride** [comment]
Episode links are being updated now. As links are acquired, they will be updated. Thank you!
