### ISSUE TITLE
What about WPA2-ENTERPRISE?

### ISSUE THREAD

**Issue by Shubb-Niggurath** [MicrosoftDocs/mixed-reality#554]
Hi, there is no information about connecting through RADIUS with certificate Wi-Fi. 

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: d65372fd-3490-185f-62c4-7370036bcf2a
* Version Independent ID: 25cb8eb0-5ffb-3e9e-7c9b-3055c7ab458b
* Content: [Connecting to Wi-Fi on HoloLens - Mixed Reality](https://docs.microsoft.com/pl-pl/windows/mixed-reality/connecting-to-wi-fi-on-hololens)
* Content Source: [mixed-reality-docs/connecting-to-wi-fi-on-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/connecting-to-wi-fi-on-hololens.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Certificate based wifi access requires the Commercial edition of HoloLens - See https://docs.microsoft.com/pl-pl/windows/mixed-reality/commercial-features
