### ISSUE TITLE
Broken link for setup for location based entertainment with Windows Mixed Reality

### ISSUE THREAD

**Issue by TheJokingTeen** [MicrosoftDocs/mixed-reality#556]
The link contained in the last entry of version history on [this](https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/mixed-reality-software) page, contains a broken link for a page about [setup for location based entertainment with Windows Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/location-based-experiences#setup)

**Comment by typride** [comment]
https://github.com/MicrosoftDocs/mixed-reality-pr/pull/3507

**Comment by TheJokingTeen** [comment]
> https://github.com/MicrosoftDocs/mixed-reality-pr/pull/3507
I don't understand... This link leads to a 404, is it private? Does that mean it's being worked on by the maintainers of the mixed-reality-pr repo?

**Comment by cheles** [comment]
@TheJokingTeen above link is internal. broken link was removed from public doc. https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/enterprise-lbe-faq#design-and-development-faq might be a good resource

**Comment by TheJokingTeen** [comment]
> @TheJokingTeen above link is internal. broken link was removed from public doc. https://docs.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/enterprise-lbe-faq#design-and-development-faq might be a good resource

Ah okay, makes sense

**Comment by typride** [comment]
More specifically, this heading is the place that might be most relevant! Thanks for sharing it and correcting my mistake,  @cheles !
