### ISSUE TITLE
Not Working with V2017 and Unity 2018.2.7f1.

### ISSUE THREAD

**Issue by ropinheiro** [MicrosoftDocs/mixed-reality#557]
There is a comment of another user stating that we should downgrade to Unity 2017.4.1. But I can't do that: I have already projects in the latest Unity version for current customers. Is there any workaround to make it work with latest Unity version?

The problem I'm experiencing are errors with the packages. E.g:

'(...)\MixedRealityIntroduction\Packages\com.unity.textmeshpro\Scripts\Runtime\FastAction.cs' could not be found. - Unity.TextMeshPro - (...)\MixedRealityIntroduction\App\GeneratedProjects\UWP\Unity.TextMeshPro\CSC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by alborzs** [comment]
Following the instructions, I am getting the exact same issues using V2017 and Unity 2.7f1.

**Comment by David-Warnke** [comment]
In Unity. Go to Window > Package Manager. Then remove TextMeshPro.

**Comment by cokefenta** [comment]
good  solution

**Comment by keveleigh** [comment]
Linking with https://github.com/Microsoft/HolographicAcademy/issues/55. Thanks for the solution!

**Comment by ShadowsOftheBeast** [comment]
here is my build settings:
https://www.flickr.com/gp/146001590@N06/8tR4jv

**Comment by Rakesh6720** [comment]
I'm having trouble with the Unity Analytics DLL.  Package Manager won't let me remove it like Text Mesh Pro.  Anyone else have the problem?
