### ISSUE TITLE
Affected versions for flickering on Unity + Hololens 2

### ISSUE THREAD

**Issue by RubenGarcia** [MicrosoftDocs/mixed-reality#558]
[Enter feedback here]

Please change
Please avoid Unity 2020.3.21f and 2020.3.22f,
to
Please avoid Unity 2020.3.21f, 2020.3.22f and 2020.3.23f

The linked bug report
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10288
indicateds .23f is also affected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8688c8ff-81f9-705a-24eb-c255e31c54f8
* Version Independent ID: 915f7e31-a006-a871-de27-14f9f87c3244
* Content: [MRTK-Unity Developer Documentation - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/index.md)
* Product: **mixed-reality**
* GitHub Login: @polar-kev
* Microsoft Alias: **kesemple**

**Comment by typride** [comment]
https://github.com/MicrosoftDocs/mixed-reality-pr/pull/3451

**Comment by RubenGarcia** [comment]
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/choosing-an-engine?tabs=unity
The page still has the old content.

**Comment by typride** [comment]
@RubenGarcia can you clarify or specify what's out of date?

**Comment by RubenGarcia** [comment]
I just checked it again and now all is good, thanks! 
Closing.
