### ISSUE TITLE
Prevent HoloLens from going to sleep

### ISSUE THREAD

**Issue by kknsy** [MicrosoftDocs/mixed-reality#559]
Does not work after the update,
http://127.0.0.1:10080/api/power/cfg/SCHEME_CURRENT/SUB_SLEEP/STANDBYIDLE?ValueAC=0&ValueDC=0
http://127.0.0.1:10080/api/power/cfg/SCHEME_CURRENT/SUB_SLEEP/VIDEOIDLE?ValueAC=0&ValueDC=0

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/give-us-feedback)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by azmartone** [comment]
You can simulate the api with a cURL command.

Load the developer portal for the Hololens on a desktop browser.
Open Chrome Inspector network tab.
Change the sleep setting.
Right click the api call associated with changing the sleep setting
Select copy > copy cURL, 
Change query parameters to 0, 
Paste the cURL command in a terminal and hit enter
Refresh the preferences in the portal page. 
Notice battery field is blank and plugged in is now changed to never
