### ISSUE TITLE
Link not working anymore

### ISSUE THREAD

**Issue by JamesBerlins** [MicrosoftDocs/mixed-reality#560]
[3.Click + next to On Add Tracked Geometry to add the node to the Event Graph.
You can find the full list of events in the [UARTrackableNotify](https://docs.unrealengine.com/API/Runtime/AugmentedReality/UARTrackableNotifyComponent/index.html) component API.

-> the link is not working anymore -> 404]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db9ec0f-8219-f292-1ac5-6ca607125b33
* Version Independent ID: a04e35e0-a4a8-2af9-88a7-a5d44f90901b
* Content: [QR codes in Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-qr-codes?tabs=426)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @vtieto
* Microsoft Alias: **vinnietieto**

**Comment by typride** [comment]
Thanks!!

**Comment by typride** [comment]
https://github.com/MicrosoftDocs/mixed-reality/pull/562
