### ISSUE TITLE
Bizzare error during VS build

### ISSUE THREAD

**Issue by paulmelis** [MicrosoftDocs/mixed-reality#565]
I'm on chapter 1 and get an error during VS build, see below. Notice the missing "H" in the path `C:\Users\Visualisatie\Desktop\HolographicAcademy-olograms-240...`. I have no idea where this comes from as the path never has to be entered manually (so I couldn't have made a typo). The project also plays without problems in Unity itself. I also searched all the file for "y-olograms" but none seem to match. I'm using Unity 2017.4.10f1 so had to import from the older version the project is provided for, perhaps that screwed things up. I also completely removed the project dir, unzipped again, restarted unity and did the whole of chapter 1 once more, but got the same error. I'm at a loss how to fix this, as all the other paths seem to be okay and the build partially completes.

```
2&gt;  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Visualisatie\Desktop\HolographicAcademy-olograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StandardEvents.dll'.
2&gt;     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2&gt;     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2&gt;     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2&gt;     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2&gt;     at Unity.LoadModulesStep.Execute()
2&gt;     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
2&gt;     at Unity.Operation.Execute()
2&gt;     at Unity.Program.Main(String[] args)
2&gt;C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\SharedHolograms.csproj(427,9): error MSB3073: The command ""C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\project.lock.json" -bits=32 -configuration=Release -removeDebuggableAttribute=False -uwpsdk=10.0.17134.0 -path="." -path="C:\Program Files\Unity 2017.4.10f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Release" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\Assembly-CSharp.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TilemapModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TextRenderingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TerrainPhysicsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UIElementsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TerrainModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpriteMaskModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SharedInternalsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StyleSheetsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpriteShapeModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VRModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VideoModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VehiclesModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.WindModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.WebModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestWWWModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityConnectModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityAnalyticsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UNETModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestTextureModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestAudioModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ScreenCaptureModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ClothModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AudioModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AssetBundleModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.DirectorModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.CrashReportingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.CoreModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ARModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AnimationModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AccessibilityModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ParticleSystemModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ParticlesLegacyModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.PhysicsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Physics2DModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.PerformanceReportingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.JSONSerializeModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.GridModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.GameCenterModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.InputModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.IMGUIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ImageConversionModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Timeline.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\nunit.framework.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UI.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpatialTracking.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.HoloLens.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StandardEvents.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\AudioIO2.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Networking.dll"" exited with code 1.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a79cabb-52f4-1cd5-d473-174391c73de3
* Version Independent ID: fa30affe-a552-a265-6626-855b2326bf02
* Content: [MR Sharing 240 - Multiple HoloLens devices - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-240#chapter-1---holo-world)
* Content Source: [mixed-reality-docs/holograms-240.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-240.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by elliotmoule** [comment]
> I'm on chapter 1 and get an error during VS build, see below. Notice the missing "H" in the path `C:\Users\Visualisatie\Desktop\HolographicAcademy-olograms-240...`. I have no idea where this comes from as the path never has to be entered manually (so I couldn't have made a typo). The project also plays without problems in Unity itself. I also searched all the file for "y-olograms" but none seem to match. I'm using Unity 2017.4.10f1 so had to import from the older version the project is provided for, perhaps that screwed things up. I also completely removed the project dir, unzipped again, restarted unity and did the whole of chapter 1 once more, but got the same error. I'm at a loss how to fix this, as all the other paths seem to be okay and the build partially completes.
> 
> ```
> 2&gt;  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Visualisatie\Desktop\HolographicAcademy-olograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StandardEvents.dll'.
> 2&gt;     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> 2&gt;     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
> 2&gt;     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
> 2&gt;     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
> 2&gt;     at Unity.LoadModulesStep.Execute()
> 2&gt;     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
> 2&gt;     at Unity.Operation.Execute()
> 2&gt;     at Unity.Program.Main(String[] args)
> 2&gt;C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\SharedHolograms.csproj(427,9): error MSB3073: The command ""C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\project.lock.json" -bits=32 -configuration=Release -removeDebuggableAttribute=False -uwpsdk=10.0.17134.0 -path="." -path="C:\Program Files\Unity 2017.4.10f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Release" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\Assembly-CSharp.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TilemapModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TextRenderingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TerrainPhysicsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UIElementsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.TerrainModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpriteMaskModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SharedInternalsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StyleSheetsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpriteShapeModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VRModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VideoModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.VehiclesModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.WindModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.WebModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestWWWModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityConnectModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityAnalyticsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UNETModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestTextureModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UnityWebRequestAudioModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ScreenCaptureModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ClothModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AudioModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AssetBundleModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.DirectorModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.CrashReportingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.CoreModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ARModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AnimationModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.AccessibilityModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ParticleSystemModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ParticlesLegacyModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.PhysicsModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Physics2DModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.PerformanceReportingModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.JSONSerializeModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.GridModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.GameCenterModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.InputModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.IMGUIModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.ImageConversionModule.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Timeline.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\nunit.framework.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.UI.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.SpatialTracking.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.HoloLens.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.StandardEvents.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\AudioIO2.dll" "C:\Users\Visualisatie\Desktop\HolographicAcademy-Holograms-240-SharedHolograms\SharedHolograms\HoloApp\SharedHolograms\UnityEngine.Networking.dll"" exited with code 1.
> ========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> ========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
> ```
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 4a79cabb-52f4-1cd5-d473-174391c73de3
> * Version Independent ID: fa30affe-a552-a265-6626-855b2326bf02
> * Content: [MR Sharing 240 - Multiple HoloLens devices - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-240#chapter-1---holo-world)
> * Content Source: [mixed-reality-docs/holograms-240.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-240.md)
> * Product: **windows**
> * GitHub Login: @keveleigh
> * Microsoft Alias: **kurtie**

Just a guess, but I think your project location string might be too long. As a rule of thumb, it's best to keep it as short as possible. Try moving the directory which contains the 'Assets' folder out, perhaps to your C drive itself, to validate whether that is the issue. Then, rebuild the project in Unity, and try again.

Best of luck,

Elliot Moule

**Comment by paulmelis** [comment]
Well, amazingly moving the folder to a shorter path solved the issue. My god, is this a limitation in Windows, Unity or Visual Studio?

**Comment by cokefenta** [comment]
always amazing, a shorter path can solve the issue.

**Comment by paulmelis** [comment]
Thanks for the tip, I'm going to close this one
