### ISSUE TITLE
File Explorer application

### ISSUE THREAD

**Issue by makowildcat** [MicrosoftDocs/mixed-reality#567]
Since a couple of months I think Hololens actually do have a File Explorer application but it is still written the opposite in the "Clarifications" part. Unless I am wrong on this, I guess this line should be removed:
"- Unlike Windows on a PC or phone, HoloLens does not have a File Explorer application."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22fa1254-3700-d522-9765-095c1a9aa359
* Version Independent ID: f0327126-9627-2132-2d12-1cd5d61338c8
* Content: [Saving and finding your files - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/saving-and-finding-your-files)
* Content Source: [mixed-reality-docs/saving-and-finding-your-files.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/saving-and-finding-your-files.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
You're totally right @makowildcat. When we caught up and released RS4 for HoloLens, it added a File Explorer so that note is no longer accurate. It'll take all of us to find all the places that content is out-of-date based on the newer HoloLens OS updates, so keep flagging them for me please!

**Comment by mattzmsft** [comment]
I updated the article to reflect the addition of File Explorer, MTP, and choosing your file picker. Thanks!
