### ISSUE TITLE
Remote rendering app running on XBOX Series X

### ISSUE THREAD

**Issue by ZelekM** [MicrosoftDocs/mixed-reality#568]
Hello,

do you know if it's possible to deploy remote rendering app to the new XBOX (UWP target, built in Unity) and stream the content to Hololens2?

**Comment by typride** [comment]
At the moment, I'm not aware of this being possible and don't think we have documentation on this scenario. Can you elaborate? You'd like to deploy a remote rendering app to the Xbox Series X? Are you thinking of Azure remote rendering?

**Comment by ZelekM** [comment]
Thanks for the response. 
I am using remote rendering from my local PC to Hololens 2. I think it's called Holographic Remoting.
[Microsoft Docs](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/holographic-remoting-overview)

My unity project can be deployed as a UWP app and run on my PC where I specify the IP address of Hololens 2. I've read here [github.com/microsoft/MixedRealityCompanionKit](https://github.com/microsoft/MixedRealityCompanionKit/blob/master/RemotingHostSample/README.md) that you can deploy it to XBox One. 

So my question is if you know if this is also supported on XBox Series X (or S)

**Comment by typride** [comment]
As of now, this is not supported or a topic of discussion. Thanks for your interest! I see why it's appealing as the hardware/software could be useful/powerful on the new Xbox.
