### ISSUE TITLE
Hololens IP Address

### ISSUE THREAD

**Issue by RussM4120** [MicrosoftDocs/mixed-reality#568]
Your documentation states: -
'Identifying the IP Address of your HoloLens on the Wi-Fi network
Using Settings
Bloom to pull up the Start menu
Place the Settings app in your world
Gaze to Network & Internet and select
Gaze to Advanced Options and select
The IP address will be shown next to IPv4 address'
Yet - when I gaze at Network & Internet and select - there is no 'Advanced Options' to gaze at or select - the only information presented is the MAC Address!

Is this an omission, or is something amiss with the setup of the HoloLens?
Regards
RussM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d65372fd-3490-185f-62c4-7370036bcf2a
* Version Independent ID: 25cb8eb0-5ffb-3e9e-7c9b-3055c7ab458b
* Content: [Connecting to Wi-Fi on HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/connecting-to-wi-fi-on-hololens)
* Content Source: [mixed-reality-docs/connecting-to-wi-fi-on-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/connecting-to-wi-fi-on-hololens.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by mattzmsft** [comment]
Hi @RussM4120, it's likely just a change in the Settings options as a result of OS updates to HoloLens in the time since this documentation was authored. Let me look into it and get back to you!

**Comment by mattzmsft** [comment]
Okay, figured it out: it's still in Settings > Network & Internet > Wi-Fi, but then scroll down past all the networks and select "Hardware properties" at the bottom. If you're connected to Wi-Fi, you'll see your IP address in there! I'll update the docs soon, unless you want to submit a PR to change it! We love public contributions :-)

**Comment by mattzmsft** [comment]
I went ahead and updated the article myself with the new instructions. Thanks again for flagging!
