### ISSUE TITLE
No Cliff House debugging

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/mixed-reality#570]
Only HoloLens covered, trying to debug a UWP app using a WMR headset. Attaching to it in Visual Studio not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2154095e-1d68-7c41-a41b-a24a1fc1a984
* Version Independent ID: d677a6ce-d535-92e2-373e-5b504658a50a
* Content: [Updating 2D UWP apps for Windows Mixed Reality - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/porting-apps/building-2d-apps)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/porting-apps/building-2d-apps.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/porting-apps/building-2d-apps.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by cheles** [comment]
this page https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/using-visual-studio?tabs=hl2#debugging-an-installed-or-running-app contains steps on how to debug UWP for WMR headsets and or emulators

**Comment by kcovert** [comment]
Thank you, was attaching to the wrong object for sure,

Kirk

**Comment by typride** [comment]
Closing issue as it seems resolved.
