### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by brunoleos** [MicrosoftDocs/mixed-reality#576]
The right link to the prefabs is https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit/UX/Prefabs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9f9ed3-b6cd-2a1c-c106-fd719dbfb624
* Version Independent ID: 507bf69d-3d81-4ac1-5106-c677e29ce7f0
* Content: [Text in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity)
* Content Source: [mixed-reality-docs/text-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/text-in-unity.md)
* Product: **windows**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by mattzmsft** [comment]
Thanks @brunoleos. Since you know where that incorrect link is in the doc, would you mind submitting a PR to replace the bad link with the correct one? Then I'll approve it right away.

**Comment by mattzmsft** [comment]
I found the link and corrected it. Thanks.
