### ISSUE TITLE
OnHandMeshUpdated not triggered

### ISSUE THREAD

**Issue by dsf5644s6sdf** [MicrosoftDocs/mixed-reality#578]
I'm trying to update my own hand mesh according to:
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/hand-tracking?view=mrtkunity-2021-05#hand-mesh-prefab

```
public void OnHandMeshUpdated(InputEventData<HandMeshInfo> eventData)
{
    print("Hand mesh update!");
    if (eventData.Handedness == myHandedness)
    {
        myMesh.vertices = eventData.InputData.vertices;
        myMesh.normals = eventData.InputData.normals;
        myMesh.triangles = eventData.InputData.triangles;

        if (eventData.InputData.uvs != null && eventData.InputData.uvs.Length > 0)
        {
            myMesh.uv = eventData.InputData.uvs;
        }
    }
}
```
![hand-mesh](https://user-images.githubusercontent.com/17873816/166966706-38881114-3158-4b73-86b4-f2a004af184f.png)

However, the method OnHandMeshUpdated(InputEventData<HandMeshInfo> eventData) never triggers. I made sure I set the Hand Mesh Visualization Modes to Everything in MRTK -> Articulated Hand Tracking. 

Unity: 2020.3.26f1
MRTK: 2.7.3

What am I missing?

**Comment by typride** [comment]
Documentation that may assist you: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/create-data-provider?view=mrtkunity-2021-05

I'm looking for assistance with this.

**Comment by keveleigh** [comment]
Hmm, are you registering this script as a global listener? For non-targeted events like the hand mesh, you'll want to explicitly register to recieve them: https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/features/input/input-events?view=mrtkunity-2021-05#register-for-global-input-events

**Comment by typride** [comment]
Closing issue for now. Can reopen if doc provided doesn't solve problem.
