### ISSUE TITLE
objects in .obj downloaded from Windows Device Portal

### ISSUE THREAD

**Issue by bilawal-mahmood** [MicrosoftDocs/mixed-reality#579]
How objects are being segmented in room scan? is it based on bounding volume of spatial mapping observer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e220dac9-c551-9639-3af0-39e0e7687fd0
* Version Independent ID: 6186d98f-44d0-53a5-8d54-4f77a7d07ef5
* Content: [MR Spatial 230 - Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230)
* Content Source: [mixed-reality-docs/holograms-230.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-230.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by mattzmsft** [comment]
Closing as it duplicates your other issue where you asked the same question.
