### ISSUE TITLE
OpenXR Fov in Unity Editor too small for Hololens 2

### ISSUE THREAD

**Issue by dsf5644s6sdf** [MicrosoftDocs/mixed-reality#579]
I have a problem after switching from Unity integrated XR to Open XR. The Unity Editor FOV 29 deg, although the Hololens 2 FOV is 54 deg. How can I increase the FOV of my Main Camera in Unity so it's the same as the actual Hololens 2 FOV through the visor? The FOV slider doesn't work once connected via Holographic Remoting.

![fov](https://user-images.githubusercontent.com/17873816/166966869-6286c53a-4e1e-4415-902b-f665af3ea105.png)

Unity: 2020.3.26f1
MRTK: 2.7.3
MR OpenXR Plugin: 1.2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db68623-3a1e-4502-cd27-f0f7d1369d10
* Version Independent ID: 9fd674c0-5be5-8b56-dbe4-31c03139ba9d
* Content: [OpenXR - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/native/openxr.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/native/openxr.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **vinnietieto**

**Comment by typride** [comment]
Hello! Does this documentation help you? https://docs.unity3d.com/ScriptReference/Camera-fieldOfView.html

**Comment by typride** [comment]
Closing for now. Can reopen if issue persists.
