### ISSUE TITLE
Link to "Using the Mixed Reality OpenXR Plugin for Unity guide" is broken

### ISSUE THREAD

**Issue by carllelandtaylor** [MicrosoftDocs/mixed-reality#580]
The link "Using the Mixed Reality OpenXR Plugin for Unity guide" https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/xr-project-setup is broken -- I get a "404 - Content Not Found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae640b1-6e0f-bd94-133f-ae39af0d390c
* Version Independent ID: 47d796b6-f4fe-a711-0feb-dde3987ee62f
* Content: [Getting started with MRTK and XR SDK - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by typride** [comment]
https://github.com/MicrosoftDocs/mixed-reality-pr/pull/3506

**Comment by cheles** [comment]
link has been fixed
