### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by muathdasan** [MicrosoftDocs/mixed-reality#583]
Good Article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2f0d209-1407-2f95-4c83-83acc8d5d980
* Version Independent ID: 2c9f9428-14e8-e5fb-beba-560bc00e9a4b
* Content: [Case study - My first year on the HoloLens design team - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-my-first-year-on-the-hololens-design-team)
* Content Source: [mixed-reality-docs/case-study-my-first-year-on-the-hololens-design-team.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/case-study-my-first-year-on-the-hololens-design-team.md)
* Product: **windows**
* GitHub Login: @designnomad
* Microsoft Alias: **haejinl**

**Comment by mattzmsft** [comment]
Thanks @muathdasan! I passed your compliment on to the author!
