### ISSUE TITLE
Very outdated mixed-reality/tree/docs/enthusiast-guide/immersive-headset-hardware-details.md

### ISSUE THREAD

**Issue by TheJokingTeen** [MicrosoftDocs/mixed-reality#587]
[immersive-headset-hardware-details](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/immersive-headset-hardware-details.md)
Still mentions old HMD's as main specs

**Comment by typride** [comment]
Resolved! Thank you
