### ISSUE TITLE
Tutorial does not describe what to expect after deploying to Hololens

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#59]
At the "Build and deploy the application" stage of the tutorial, the user has created an empty app and is now deploying that app to the Hololens. Since the tutorial does not describe what the user should see in their Hololens device once the app is deployed, it is very difficult for the user to confirm that the app is working correctly on device.

**Fix:** There should be a description of what the user should expect from an empty app deployed on a Hololens shown at the beginning of this section.

In addition, the "Build and deploy the application" section has enough content to be its own module in the tutorial series. App deployment is referred to several times in future tutorial modules so it would make sense for it to exist as its own module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter This is listed as completed in the spreadsheet Sean shared but there is nothing here?

**Comment by martinwilter** [comment]
@hferrone, please see https://github.com/MicrosoftDocs/mixed-reality/issues/58#issuecomment-713186547.

By the way, I see there already is some info about what to expect:

![image](https://user-images.githubusercontent.com/16746283/96653451-fb717d00-12ed-11eb-912a-05425d79103b.png)
