### ISSUE TITLE
Thanks. Very helpful.

### ISSUE THREAD

**Issue by krishx007** [MicrosoftDocs/mixed-reality#594]
Exactly what i was looking for. Very helpful. Thanks....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84ae485-589a-39ae-215b-2a180e256847
* Version Independent ID: 1e333459-27c2-0a15-e6f5-00dbc4e6b88f
* Content: [Clipping primitive - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/rendering/clipping-primitive?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/features/rendering/clipping-primitive.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/rendering/clipping-primitive.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by keveleigh** [comment]
Appreciate the kind words!
