### ISSUE TITLE
Question on Interaction Section

### ISSUE THREAD

**Issue by jmclamb** [MicrosoftDocs/mixed-reality#597]
I have imported my own hologram asset in place of the island.  Following the rest of the instructions and applying the scripts to my hologram and then building and deploying to HoloLens it appears the TapToPlace is not working with my hologram though it is configured.

The island hologram works without issue.

Any help/ideas is much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0756aac5-a082-94dd-f593-29821fa4d17d
* Version Independent ID: 35fa1b53-6b44-834e-7b8c-9b1120bea256
* Content: [MR Sharing 250 - HoloLens and immersive headsets - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-250)
* Content Source: [mixed-reality-docs/mixed-reality-250.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixed-reality-250.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@keveleigh has this been resolved?

**Comment by keveleigh** [comment]
@hferrone I'm not sure. Though, this project was based on the HoloToolkit. We now have an updated [TapToPlace](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MRTK/SDK/Features/Utilities/Solvers/TapToPlace.cs) component in the MRTK that may work better. I think it's fine to close this issue out.

**Comment by hferrone** [comment]
Oh great, if this was HoloToolkit then don't worry about it as it's deprecated.
