### ISSUE TITLE
MRTK profile tutorial missing explanations

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#60]
In the Overview this tutorial says that, 

> This particular example will show you how to hide the spatial awareness mesh by changing the settings of the Spatial Mesh Observer.

No where in the tutorial does it explain what a spatial awareness mesh is or why its settings should be changed. There is also no recommendation on which setting is best practice for future projects.

This tutorial is also missing general explanations on what a profile is and how it should be used. For someone new to Mixed Reality and MRTK, this can be confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f14ba9-dd4b-3bf7-f944-ccde6607484d
* Version Independent ID: acffbd71-617b-53de-b91c-ca2165242ae5
* Content: [Getting started tutorials - 3. Configuring the MRTK profiles - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-03)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-03.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-03.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@polar-kev Can you provide some technical explanations for these topics?

**Comment by hferrone** [comment]
@mr0ng @martinwilter This is listed as completed in the spreadsheet Sean shared but there is nothing here?

**Comment by martinwilter** [comment]
@hferrone, please see https://github.com/MicrosoftDocs/mixed-reality/issues/58#issuecomment-713186547.
