### ISSUE TITLE
Images are sized too small

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/mixed-reality#606]
Even when I make my browser the max width, the images are too small to easily read the relevant details from.  I need to copy the image link into its own tab then it's clear.  Maybe make clicking on the image go to the full image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4e3ce3e-cae0-dd85-ca0a-a71089b60e8d
* Version Independent ID: b4e3ce3e-cae0-dd85-ca0a-a71089b60e8d
* Content: [Initial setup for MRTK3.0-Unity - Mixed Reality Toolkit](https://review.docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk-3.0/initial-setup?view=mrtkunity-2021-05&branch=release-mrtk-3.0-dev-contributions)
* Content Source: [mrtk-unity/mrtk-3.0/initial-setup.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk-3.0/initial-setup.md)
* Product: **mixed-reality**
* GitHub Login: @qianw211
* Microsoft Alias: **qianwen**

**Comment by qianw211** [comment]
Hi @KevinKennedy, please check out the latest MRTK3 docs.  The link is: aka.ms/mrtk3. Thanks!

**Comment by KevinKennedy** [comment]
Text still is pretty hard to read on the XR Plug-in Management section.  Is there a way to easily let the user zoom in?  Edge lets you open the image in a new tab but that seems clunky to need to do it all the time
![image](https://user-images.githubusercontent.com/6423774/172920012-321b76ed-8f4b-42fe-b7ed-29e40d708f9b.png)

**Comment by cheles** [comment]
@KevinKennedy  hyperlinks to those specific resources have been added on all images so if you click on an image, you should be redirected to image resource.

**Comment by KevinKennedy** [comment]
Looks good
