### ISSUE TITLE
VS 2017 build error

### ISSUE THREAD

**Issue by xbandi** [MicrosoftDocs/mixed-reality#608]
After three weeks searched solution and tried uninstall and again install different version of VS and Unity, after that I have no any idea what is wrong.

In this online document I wrote all about my problem and other information
https://docs.google.com/document/d/1qa7yFakjwhA1pF9wVcKSWHQn01Fg7RRGYLoY8i72j2Q/edit?usp=sharing

Please, good people, help me solve this problem.

**Comment by jessemcculloch** [comment]
Please file a support case for this at https://support.microsoft.com/en-us/supportforbusiness/productselection?sapid=e9391227-fa6d-927b-0fff-f96288631b8f and our support team will contact you to try and help
