### ISSUE TITLE
Link for MRTKG Getting started Guide not working.

### ISSUE THREAD

**Issue by Dimoki** [MicrosoftDocs/mixed-reality#61]
Hey! The link for "MRTK getting started guide" is leading to a 404.

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95809b24-cc2f-3118-6d05-c504ed734cfc
* Version Independent ID: c9341566-b6b7-25bc-0121-1c6c30a43d49
* Content: [Getting started with MRTK version 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/mrtk-getting-started)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/mrtk-getting-started.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by hferrone** [comment]
Hey @Dimoki, sorry about that we recently updated our docs - it's working now :)
