### ISSUE TITLE
Link of “HoloLens 2 Mixed Reality Production” was expired

### ISSUE THREAD

**Issue by waynebaby** [MicrosoftDocs/mixed-reality#610]
In the ToC on the left, Tutorials->HoloLens 2 Mixed Reality Production link was directing to Unreal site/Home page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d81088-3130-6cf2-f874-63b5320f593a
* Version Independent ID: eafae35d-7c72-580f-799c-06f3ba4673e2
* Content: [Introducing MRTK for Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-mrtk-introduction)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-mrtk-introduction.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-mrtk-introduction.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by sorskoot** [comment]
The link in the TOC is directing to https://dev.epicgames.com/community/learning/courses/M97/hololens-2-mixed-reality-production-for-unreal-engine/orLB/introduction-to-hololens-2-mixed-reality-production-for-unreal-engine. This seems to be correct.

**Comment by typride** [comment]
Link is fixed already. Closing.
