### ISSUE TITLE
MRTK 2.8.0 but old document

### ISSUE THREAD

**Issue by JiangTao100** [MicrosoftDocs/mixed-reality#611]
[Enter feedback here]

Hello! I find that the doc of MRTK 2.8.0 displayed here is different from my unity’s MRTK2.8.0. For example, the steps of setting eye tracking in your doc is:
![image](https://user-images.githubusercontent.com/69242575/172289682-b29071a8-b989-4e6e-8678-ca0147820b5c.png)

But the setting in my project is:
![image](https://user-images.githubusercontent.com/69242575/172289715-9a357192-4163-408f-8ee3-c29bf7d4f949.png)

Do you find that there is much difference between them? I think that you are deploying the order version of MRTK rather than the latest .
When I wanna update MTRK I find this trouble, and when I access eye tracking data via EyeGazeProvider in VS it returns false. I guess there must be new change in it. Could you help me whit that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 892601fe-60b1-6af7-a91b-6260870a6147
* Version Independent ID: 892601fe-60b1-6af7-a91b-6260870a6147
* Content: [Eye Tracking Basic Setup - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/input/eye-tracking/eye-tracking-basic-setup?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/features/input/eye-tracking/eye-tracking-basic-setup.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/features/input/eye-tracking/eye-tracking-basic-setup.md)
* Product: **mixed-reality**
* GitHub Login: @CDiaz-MS
* Microsoft Alias: **cadia**

**Comment by MaxWang-MS** [comment]
Hi @keveleigh, could you take a look at the page to see if there's anything needs updating?

**Comment by JiangTao100** [comment]
@Hi,[keveleigh](https://github.com/keveleigh),have you seen this page?

**Comment by keveleigh** [comment]
Hey @JiangTao100, I just did a runthrough of these steps and updated them to the latest state. The docs changes are in PR and should go live shortly!
