### ISSUE TITLE
Advanced - Teleportation and Locomotion

### ISSUE THREAD

**Issue by elliotmoule** [MicrosoftDocs/mixed-reality#612]
I've integrated locomotion and teleportation into a scene I'm creating, though, can't seem to figure out how to register the motion controller/s as a Pointing device, so that I can use it to aim my teleportation, rather than Gaze. I see a place to register pointers on the Focus Manager, but not sure what component to drop in. Any direction would be helpful. 

Also, whilst here, is there a way to configure the fade canvas, fade speed, using the editor? Or best to just edit the code?

Thanks for you help.

Regards,

Elliot Moule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0448882-93e3-575f-219b-cd2f7cfdd1e3
* Version Independent ID: 12629ff6-4304-8838-9b46-86ce500feb6d
* Content: [MR Input 213 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-213)
* Content Source: [mixed-reality-docs/mixed-reality-213.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixed-reality-213.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@elliotmoule HoloToolkit has been deprecated, please take a look at Mixed Reality Toolkit for future MR development. Thanks!
