### ISSUE TITLE
can't install MRTK3 package

### ISSUE THREAD

**Issue by wfleming801** [MicrosoftDocs/mixed-reality#616]
I've tried various noted unity versions; closing and following the feature tool install (following along Path2). Then upon arriving at step 3, I cannot locate the 'MRTK3' entry in the project settings. I see MRTK in the packages list below on the main screen. I open Unity Package Manager to confirm the package was imported. In the 2021.3.4f1 version, there is a "Experimental packages in using" warning that appears -- per documentation, it is 'hiding' such packages so that they are not accidentally referenced in a production-level product. Could this be interfering with my import? I've looked for various options to permit experimental packages, but haven't found any such setting. Is there a development-mode I need to put Unity in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a45ca63-1167-32e9-02fa-0dc5bc7005fa
* Version Independent ID: 6a45ca63-1167-32e9-02fa-0dc5bc7005fa
* Content: [MRTK3 initial setup - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/setup)
* Content Source: [mrtk-unity/mrtk3-overview/setup.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/setup.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by MaxWang-MS** [comment]
Hi @wfleming801, please first confirm you are on the latest version of [Mixed Reality Feature Tool](https://aka.ms/mrfeaturetool). Then after opening the feature tool, click on the setting button on the lower left corner and go to the Feature tab. Ensure show preview releases is checked, click on OK, and then proceed. You should now be able to see a MRTK3 category under the Mixed Reality Toolkit category on the Discover Features page.

**Comment by MaxWang-MS** [comment]
Thanks for catching this gap! I will be updating our docs shortly.

**Comment by typride** [comment]
@MaxWang-MS once you get this, do you mind telling me so I can close this, or close it yourself! Thanks!

**Comment by MaxWang-MS** [comment]
It's fixed in our docs now!
