### ISSUE TITLE
Stuck at "Analysis..."

### ISSUE THREAD

**Issue by huynh-fr** [MicrosoftDocs/mixed-reality#616]
Hello,

- When I am in Analysis Mode and I did the tap gesture, the indicator turns red and I am stuck with the Camera Status : Analysis...
- When I am in Training Mode, I can take a picture and choose a Label to apply with the Voice recognizer. But when the App should upload the photo with the Label, I am again stuck in this state.

So, like others mentioned it, I think that I can't communicate with the server or something like that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889db7e9-a0ea-abb3-9b25-f9db5527655c
* Version Independent ID: 6fd8a913-c2ae-a45e-1461-357f46105e34
* Content: [MR and Azure 302b - Custom vision - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-302b)
* Content Source: [mixed-reality-docs/mr-azure-302b.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-302b.md)
* Product: **windows**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by jjjmmmxxx** [comment]
I had met the same problem as you.But I can unpload the picture and do training job.However,  I am stuck with the Camera Status : Analysis. 
What should I do?

**Comment by jjjmmmxxx** [comment]
Oh I had solved it . The problem was that I pasted the wrong prediction key .
