### ISSUE TITLE
Security certificate info needs updated

### ISSUE THREAD

**Issue by deadlyfingers** [MicrosoftDocs/mixed-reality#617]
You can no longer follow step 2 in the Security Certificate section - https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#security-certificate
The Security link mentioned no longer exists and is not on the new portal's menubar so you can't install cert on your local machine to trust the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e0e5f1-b23b-4909-c1ba-6dba39174d30
* Version Independent ID: b0a8777f-e04e-b645-d983-0acb94268f4c
* Content: [Using the Windows Device Portal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#security-certificate)
* Content Source: [mixed-reality-docs/using-the-windows-device-portal.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-device-portal.md)
* Product: **windows**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by jessemcculloch** [comment]
Fixed
