### ISSUE TITLE
Getting error after attempting to integrate Oculus package

### ISSUE THREAD

**Issue by BarboraAtVResearch** [MicrosoftDocs/mixed-reality#618]
Hello, I am following the above-described instructions and had some success in the past. But this time I got the following error after clicking on "Integrate Oculus Integration Unity Modules" - `Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation@251fc689f36f\Providers\Oculus\XRSDK\OculusXRSDKDeviceManagerProfile.cs(131,27): error CS0426: The type name 'ProcessorPerformanceLevel' does not exist in the type 'OVRManager'`

I have Unity 2019.4.40f, OVR v 35.0, MRTK 2.8.0.0 and I can't use unity 2020 due to poor performance issues when MRTK on Oculus. Thanks for pointing me to how to solve this problem.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d435ba10-401f-d197-24c9-6f31683b2cb9
* Version Independent ID: d435ba10-401f-d197-24c9-6f31683b2cb9
* Content: [Deploying to Oculus Quest - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/supported-devices/oculus-quest-mrtk?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/supported-devices/oculus-quest-mrtk.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/supported-devices/oculus-quest-mrtk.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by manel-graca** [comment]
Do you have more XR packages imported? That might cause issues. It has caused for me

**Comment by BarboraAtVResearch** [comment]
I finally managed to resolve the issue by switching to MRTK 2.7.x. However, I do not know how to resolve it with the current version. I do not have any more XR packages, except MRTK OpenXR which was installed automatically as a dependence via The Tool. I am using the new XR management system.

**Comment by RogPodge** [comment]
I see, we had a documentation issue. The latest version of MRTK supports Oculus Integration 39.0 as the minimum, as there have been breaking changes in the Oculus package :(.

Updating the docs now.

**Comment by RogPodge** [comment]
Should be updated!!

Sorry for all the confusion :(

**Comment by BarboraAtVResearch** [comment]
Thank you for the clarification :)
