### ISSUE TITLE
Incorrect button blueprint class listed?

### ISSUE THREAD

**Issue by paulmelis** [MicrosoftDocs/mixed-reality#62]
Under `Adding a button` step 1 it says to add a blueprint class of type `BP_SimpleButton`, but the image below that shows a `BP_ButtonHoloLens2` class being selected. That latter appears to be the correct class, based on the settings that need to be changed (i.e. icon).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Great catch @paulmelis!
