### ISSUE TITLE
If we wish to see more tags in Halolens, how can that be done?

### ISSUE THREAD

**Issue by h0339637** [MicrosoftDocs/mixed-reality#621]
If we wish to see more tags in Halolens, how can that be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/give-us-feedback)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Product: **windows**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by h0339637** [comment]
For example, a toy car, a cup, a key etc at the same time.

**Comment by h0339637** [comment]
Dear Jesse
As the example shows in MR and Azure 310 - Object detection - Mixed Reality only illustrate the possiblity of one object, that is the cup; however, we wish to use the object detection to detect a number of objects instead of one only through AI and then MR, as we have to open a folder for each of the pictures, how can we let the computer to identify more than one objects?
Many thanks and regards,Rita


I'm not sure I understand what you are looking for @h0339637. Can you clarify a little more what you are expecting to happen?

Thanks,
Jesse

**Comment by h0339637** [comment]
Dear sir/madam
In MR and Azure 310 - Object detection - Mixed Reality, there is only a cup which needed to be detected, however, the real case may need to identify the computer monitor and keyboard as well. The question is, how can we utilise the object detection and mixed reality in hololens to identify them together at once?
Many thanks and regards,Rita

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
MR and Azure 310 - Object detection - Mixed Reality

DrNeil

Complete this course to learn how to train a machine learning model, and then use the trained model to recognize...
 |

 |

 |




    Rita Li (<ritarec1@yahoo.com.hk>) 在 2018年10月22日星期一 下午1:35:50 [GMT+8] 寫道：  
 
 Dear Jesse
As the example shows in MR and Azure 310 - Object detection - Mixed Reality only illustrate the possiblity of one object, that is the cup; however, we wish to use the object detection to detect a number of objects instead of one only through AI and then MR, as we have to open a folder for each of the pictures, how can we let the computer to identify more than one objects?
Many thanks and regards,Rita


I'm not sure I understand what you are looking for @h0339637. Can you clarify a little more what you are expecting to happen?

Thanks,
Jesse

**Comment by jessemcculloch** [comment]
You would have to train your own model to identify the different objects that need to be identified
