### ISSUE TITLE
Wrong picture maybe?

### ISSUE THREAD

**Issue by dimitrijevic** [MicrosoftDocs/mixed-reality#623]
[Enter feedback here]

Why does the image show tooltip component when such a component isn't currently available in the MRTK3 (at least the one used for the IET tutorials repo)...if it is coming soon also I'd be interested in finding out when the progress indicator component is set to arrive? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d88288c-0382-7d08-f798-1e96eaa514bb
* Version Independent ID: 0d88288c-0382-7d08-f798-1e96eaa514bb
* Content: [Object Manipulator - MRTK3](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/object-manipulator)
* Content Source: [mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/object-manipulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-spatialmanipulation/packages/spatialmanipulation/object-manipulator.md)
* Product: **mixed-reality**
* GitHub Login: @Zee2
* Microsoft Alias: **finnsinclair**

**Comment by MaxWang-MS** [comment]
Hi @dimitrijevic, the tooltip component is indeed coming soon to MRTK3. I am not sure about the plans for progress indicator though.
