### ISSUE TITLE
Not showing the results in the video

### ISSUE THREAD

**Issue by aliaga-d** [MicrosoftDocs/mixed-reality#624]
Different than previous tutorials we don't see the Hololens results in these videos. I miss seeing those at the end of each Chapter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e220dac9-c551-9639-3af0-39e0e7687fd0
* Version Independent ID: 6186d98f-44d0-53a5-8d54-4f77a7d07ef5
* Content: [MR Spatial 230 - Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230)
* Content Source: [mixed-reality-docs/holograms-230.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-230.md)
* Product: **windows**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by keveleigh** [comment]
Thank you for the feedback! @jessemcculloch is currently reworking our Academy offerings, so we'll be sure to keep this in mind for the next iteration.
