### ISSUE TITLE
Link Dead

### ISSUE THREAD

**Issue by primepeter** [MicrosoftDocs/mixed-reality#625]
[Enter feedback here]
Link Dead:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/xr-project-setup
For The Term "OpenXR Plugin" under "HP Reverb G2 Controllers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 602d1467-5ad4-f38f-a1cc-443d95a57dcb
* Version Independent ID: 602d1467-5ad4-f38f-a1cc-443d95a57dcb
* Content: [Detecting controllers in MRTK2 - MRTK 2](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/supported-devices/controllers-mrtk?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/supported-devices/controllers-mrtk.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/supported-devices/controllers-mrtk.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by sorskoot** [comment]
Link on the deployed page on Microsoft Learn is working and links to https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/new-openxr-project-with-mrtk.
