### ISSUE TITLE
July update link error

### ISSUE THREAD

**Issue by a11303** [MicrosoftDocs/mixed-reality#628]
[Enter feedback here]

July update link error
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Version Independent ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Content: [HoloLens Emulator archive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/hololens-emulator-archive)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by MaxWang-MS** [comment]
It seems that the link is working. Please reopen the issue if you are still experiencing problems.
