### ISSUE TITLE
links is bad

### ISSUE THREAD

**Issue by a11303** [MicrosoftDocs/mixed-reality#629]
[Enter feedback here]

July 12, 2022 HoloLens 2 Emulator Links =June 14

The link refers to last month's version, please update the link quickly, by the way, this is the case for every monthly update, I hope it can reduce feedback
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Version Independent ID: bf19b222-f79a-c16b-ab29-f92c05a14651
* Content: [HoloLens Emulator archive - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/hololens-emulator-archive)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/hololens-emulator-archive.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by MaxWang-MS** [comment]
Hi @a11303, I just checked the link and it looked fine to me. Please reopen if you are still having problems.
