### ISSUE TITLE
Assets/MRTK folder empty after initializing new project

### ISSUE THREAD

**Issue by JamesFSAR** [MicrosoftDocs/mixed-reality#643]
Hello,
I just started a new project for Hololens 2 using Unity 2020/OpenXR/MRTK 2.8.2, and after following the instructions to set up a new project, I don't see anything in the Assets/MRTK folder, it is just empty.  How do I get the Hand Menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91cdafae-141d-704d-3a0b-35be1b3b4cf7
* Version Independent ID: 91cdafae-141d-704d-3a0b-35be1b3b4cf7
* Content: [Hand menu - MRTK 2](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/hand-menu?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/features/ux-building-blocks/hand-menu.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/features/ux-building-blocks/hand-menu.md)
* Product: **mixed-reality**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by MaxWang-MS** [comment]
It seems that you imported MRTK using the Mixed Reality Feature Tool, where MRTK is imported as UPM packages. You can locate imported UPM packages under the Project window -> Packages. Also make sure you go through our docs on [Unity packages](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/configuration/usingupm#managing-mixed-reality-features-with-the-unity-package-manager)
