### ISSUE TITLE
Device unresponsive after first test

### ISSUE THREAD

**Issue by sabarishnarain** [MicrosoftDocs/mixed-reality#644]
This is my 2nd attempt and the device has gone unresponsive after running the first sample test. 
Has anyone seen this problem ? 
Restarting the device can only visualize the "Hello" screen and then nothing.

**Comment by snarainvuforiaviewqa** [comment]
After quite a bit of troubleshooting, I noticed the control mode switches to simulation that suspends all sensors to detect human gestures which makes the device unresponsive. Switching it back to Default resolves this problem.
