### ISSUE TITLE
404 error on "API Reference" link

### ISSUE THREAD

**Issue by Fuanitou** [MicrosoftDocs/mixed-reality#648]
The API Reference link sends to a 404 page. This is the link: https://docs.microsoft.com/en-us/dotnet/api/Microsoft.MixedReality.Toolkit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6921655f-60c2-0b69-9edb-976b8ff36520
* Version Independent ID: 6921655f-60c2-0b69-9edb-976b8ff36520
* Content: [MRTK2-Unity Developer Documentation - MRTK 2](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/index.md)
* Product: **mixed-reality**
* GitHub Login: @polar-kev
* Microsoft Alias: **alexturn**

**Comment by cheles** [comment]
@Fuanitou which link are you referring from https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/?view=mrtkunity-2022-05 ? both "API Reference" link from left menu and the one from doc seems to work for me.

**Comment by Fuanitou** [comment]
@cheles It was the link on API reference and almost any other link that lead to the documentation, today it was suddenly working, not sure if it was a fault that happened only yesterday.
