### ISSUE TITLE
'Enable Tap to Place' voice command is not working on the device

### ISSUE THREAD

**Issue by dudziakl** [MicrosoftDocs/mixed-reality#65]
I have set all as it was described in the tutorial but last voice command 'Enable Tap to Place' works only in Unity Editor but doesn't on the HoloLens 2. I tried to keep cursor on the Rover, look at it etc. Speech confirmation tooltip doesn't pop up! I checked that eyes recognition was working fine on SeeItSayItLabels. Other voice commands that doesn't require focus are working fine. Maybe it is still an issue with "Is Focus Required" property as it was on MRTK 2.3? 

I was using Unity 2019.4.9f and MRTK 2.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e526277-fa7f-9d2a-faed-aed2d7555c93
* Version Independent ID: ee349afa-a729-60fd-0570-dfc3458e4cc5
* Content: [Getting started tutorials - 9. Using speech commands - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-09)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-09.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-09.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @dudziakl, 

Take a look at these two articles if you haven't already:
 - https://docs.microsoft.com/en-us/windows/mixed-reality/design/voice-input
 - https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Speech.html

@martinwilter Any ideas?

**Comment by martinwilter** [comment]
@hferrone, I'm guessing this is caused by the same bug that caused issue #64. Publishing the fix https://github.com/MicrosoftDocs/mixed-reality/issues/64#issuecomment-701024840 should prevent this from happening to future readers.
