### ISSUE TITLE
MRTK Feature Tool Fails to run on Win 11

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/mixed-reality#650]
Downloaded the MRTK Feature Tool per [instructions](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool) and attempted to start the tool following the [instructions](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/setup) from MRTK3 following Path 2 of instructions.
My system is latest Windows 11 Enterprise fully patched as of the date of this issue request. Visual Studio 2022 Enterprise was clean installed with NO prior versions of Visual Studio 2022. Unity Hub 3.2.0 is installed with Editor 2021.3.9f1 LTS.

1. Unity fails to create a new project (Failed to resolve project template [path to template]). I am used to Unity being a source of issues, untrustworthy, and buggy generally.
2. MRTK Feature Tool downloaded and extracted without issue. Attempting to start the EXE file results in a fatal error condition: To run this application you must install .NET. Do you wish to install? I selected Yes. Nothing happened because likely the installer found the system has the most current .NET version.

The following versions of .NET are installed: Framework 4.8.x (latest via Windows Update), .NET Core 3.1.422, .NET 6.0.303, .NET 6.0.400

In did note on the requirements the need for .NET 5 and Windows 10. If these are indeed requirements and current supported versions are not acceptable, then please indicate such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0405e5-aef5-5ed3-d9a1-960b4065300b
* Version Independent ID: dd9cd8d6-caea-6146-fd71-c5b3605435c4
* Content: [Welcome to the Mixed Reality Feature Tool - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by laultman** [comment]
Seems my issue is really a dup of #367

**Comment by MaxWang-MS** [comment]
This issue has been fixed in 1.0.2209.0. Please download the new version at https://aka.ms/mrfeaturetool.
