### ISSUE TITLE
Update docs for Unreal 4.27 release

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#653]
Need to get parity to Unreal docs to Microsoft docs:
    https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/XRDevelopment/AR/ARPlatforms/HoloLens/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c948d6e8-720f-2603-a760-dfc5ae5c7a25
* Version Independent ID: 70c418eb-71d6-aae8-f590-9da1077787c4
* Content: [Unreal Development Overview - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-development-overview?tabs=ue426%2Cmrtk%2Casa%2CD365)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by typride** [comment]
@snakex2000 can you elaborate on the parity you're talking about?

Thanks!

**Comment by snakex2000** [comment]
In review, the docs look more accurate than ever now for UE on Microsoft site.  This can be resolved & closed out.
