### ISSUE TITLE
Application Registration

### ISSUE THREAD

**Issue by godbrother** [MicrosoftDocs/mixed-reality#655]
Associated Windows Store app not listing registration portal(https://apps.dev.microsoft.com/#/appList). Step 2. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd7ea9f-c296-e074-2d84-50639a571052
* Version Independent ID: 506fc974-0cdf-9228-765b-77f807680e40
* Content: [MR and Azure 308 - Cross-device notifications - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-308)
* Content Source: [mixed-reality-docs/mr-azure-308.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-308.md)
* Product: **mixed-reality**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by hferrone** [comment]
App registration is now through the Azure portal.
