### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by mabinthecodemaven** [MicrosoftDocs/mixed-reality#656]
[Enter feedback here]
Where is the spatial awareness mesh display options?? I do not see this anywhere in my MRTK inspector tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06844159-dbd8-246c-5265-9757ef956d25
* Version Independent ID: 92f139c0-1b0f-4652-c8d2-7463aa3c44d9
* Content: [Setting up Photon Unity Networking - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-sharing-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **vinnietieto**

**Comment by MaxWang-MS** [comment]
Please refer to our docs [here](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/configuration/mixed-reality-configuration-guide?view=mrtkunity-2022-05#spatial-awareness-settings).
