### ISSUE TITLE
RS5 Emulator is missing

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/mixed-reality#656]
Now that RS5 is generally available, it'd be nice to have a corresponding emulator image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by ChimeraScorn** [comment]
The RS5  emulator is available at https://go.microsoft.com/fwlink/?linkid=2065980&clcid=0x409

**Comment by Holo-Krzysztof** [comment]
Very nice!
Could you also update the archive page? It still lists the April 2018 one as latest build.

**Comment by jessemcculloch** [comment]
These links were updated in PR #722 last week.

Thanks,
Jesse
