### ISSUE TITLE
"Creating User Interfaces" tutorial needs additional explanations

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#66]
This tutorial instructs on how to configure components but needs more explanation on what the components do. This tutorial is geared towards people getting started so it should explain the "why" behind the "what" every step of the way.

Interactable
The Interactable component is missing an explanation. An example of what could be included:
The Interactable component is an all-in-one container to make any object easily interactable and responsive to input. Interactable acts as a catch-all for all types of input including touch, hand rays, speech etc and funnel these interactions into events and visual theme responses.

OnClick()
Needs further explanation on how this works with the input system (controllers, hands, focus, pointers).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d5ccf2-6270-b146-f5ca-3da70c886028
* Version Independent ID: 23fdfa60-4d98-86d3-a069-fdd316a3bd23
* Content: [Getting started tutorials - 6. Creating user interfaces - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-06)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-06.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng @martinwilter This is listed as completed in the spreadsheet Sean shared but there is nothing here?

**Comment by martinwilter** [comment]
@hferrone, please see https://github.com/MicrosoftDocs/mixed-reality/issues/58#issuecomment-713186547.

**Comment by hferrone** [comment]
@martinwilter What's the status on this?

**Comment by martinwilter** [comment]
@hferrone, I can add some Tip tags and make a PR for this today.
