### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by miri-cmkl** [MicrosoftDocs/mixed-reality#660]
Please change:

_so that your application is runs and performs well_

to:

_to so that your application runs and performs well_

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71134e16-db2d-50e0-b21e-a8063e6dbf84
* Version Independent ID: 5b67a5ad-a7a9-9a84-f1ac-e9d14aaaf443
* Content: [Recommended settings for Unity - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/recommended-settings-for-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/recommended-settings-for-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/recommended-settings-for-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @vtieto
* Microsoft Alias: **vinnietieto**

**Comment by AK-codingmaniac** [comment]
Can I take this issue under HacktoberFest 2022?

**Comment by Mariangela** [comment]
!assign

Hi, can you please assign me to this issue.
