### ISSUE TITLE
[Question] Upload model to Hololens as spatial mapping mesh 

### ISSUE THREAD

**Issue by Alexees** [MicrosoftDocs/mixed-reality#660]
I was wondering if it was possible to skip the spatial mapping process altogether?
Since this does not seem to be documented or said anything about it and I also could not find anything I wanted to ask this:

If i was to scan a building with a laser scanner, generating a point cloud, is it possible to convert that cloud into a spatial mapping mesh and upload it to a Hololens to just use it?
This is probably more complicated, but I'd like to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d59acc0-cd69-18a6-7e1d-cc1374687942
* Version Independent ID: d5d76031-143d-a520-dee4-a7a2a11df3b7
* Content: [Case study - Expanding the spatial mapping capabilities of HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-expanding-the-spatial-mapping-capabilities-of-hololens)
* Content Source: [mixed-reality-docs/case-study-expanding-the-spatial-mapping-capabilities-of-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/case-study-expanding-the-spatial-mapping-capabilities-of-hololens.md)
* Product: **mixed-reality**
* GitHub Login: @jevertt
* Microsoft Alias: **jevertt**

**Comment by jevertt** [comment]
Your app could definitely do that. You'd need to figure out how to align the HoloLens anchors with the mesh you are uploading, but that is definitely a solvable problem. I do not believe you could force the HoloLens operating system to use that mesh. But, you app definitely could.

**Comment by Alexees** [comment]
@jevertt could you point me towards some documention explaining steps necessary?
What's the anatomy of such a mesh so I can convert lets say and fbx to it? I'm not looking into using a mesh and just a align it with the spatial map the hololens produced. Let's say The lens has initialized one room and I manually place two points. Given a world up and those two points I could overlay it with the spatial map the hololens created. BUT, can I ADD that mash AS a spatial map to the lenses information so it does not need to scan the rest of the rooms because I did that in a 3D modelling tool already?

**Comment by jevertt** [comment]
I don't believe there is any mechanism for forcing the HoloLens OS to use a mesh you provide. Your app, on the other hand, can do whatever it likes. The OS is providing meshes to your app via the observers. Your app can take them for some rooms and ignore them for rooms you scanned in another way (maybe you've manually placed those and then saved their location with persistent anchors). 

You can download the spatial mesh that has been scanned in the device portal - here's some discussion about how to do that: https://forums.hololens.com/discussion/775/downloading-offline-captured-spatial-mapping-data-over-usb. It comes in as an OBJ. 

There's some docs on spatial anchors here: https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-anchors

Hope that helps.

**Comment by Alexees** [comment]
@jevertt thanks for the links and your insights
