### ISSUE TITLE
Emulator not availible for Windows Home

### ISSUE THREAD

**Issue by telion2** [MicrosoftDocs/mixed-reality#661]
It seems that the Hololens Emulator is not availibe for Windows Home. Can that be changed in near future? It doesn't make sense to me to not support the Windows version that is most common among Windows users and developers when trying to make the Hololens popular. Thank you.

**Comment by jessemcculloch** [comment]
Hi @telion2 - This is purely a matter of Windows Home not having virtualization/Hyper-V support that is required for the HoloLens Emulator to work.

We understand that this is an issue for a population of people who want to develop for HoloLens but do not use a professional or enterprise SKU of Windows, however I don't think this is something that is going to change in the near future.
