### ISSUE TITLE
Documentation is partly outdated

### ISSUE THREAD

**Issue by telion2** [MicrosoftDocs/mixed-reality#662]
Windows Store in Unity became Universal Windows Platform 
and Checking C# Project seems to be depreciated since the .NET scripting backend for UWP will be removed in future releases of Unity. .NET is changed to IL2CPP or atleast this is what Unity is recomending. This made it partly difficult to follow the documentation. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/holograms-100)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ZeroLu** [comment]
@mattzmsft @telion2 How am I gonna build to visual studio if I chose the Scripting Backend to IL2PP? I have to choose .NET to be able to check "Unity C# projects" under Debugging in Build Settings.

**Comment by keveleigh** [comment]
@ZeroLu You can still build to Visual Studio without that option. That option was used in the past to help make script iteration / building faster, but is now incompatible with IL2CPP.

Building without that option still generates a VS solution, that you can then build from and deploy to your device
