### ISSUE TITLE
System Keyboard Overlay?

### ISSUE THREAD

**Issue by ei2kpi** [MicrosoftDocs/mixed-reality#663]
It looks like the latest RS5 release allows the system keyboard to overlay on top of immersive mode apps. I can't seem to find any content on how to trigger the system overlay from Unity / Native HoloLens apps... 

"Useful overlays in immersive mixed reality apps - You’ll now see overlays such as the keyboard, dialogs, file picker, etc. when using immersive mixed reality apps."
(from: https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes-october-2018)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b15a4f6-fb99-7a99-62ad-f22259d375ba
* Version Independent ID: 688c368c-839a-54e8-6f31-c22204fad338
* Content: [Keyboard input in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/keyboard-input-in-unity)
* Content Source: [mixed-reality-docs/keyboard-input-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/keyboard-input-in-unity.md)
* Product: **mixed-reality**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
@ei2kpi Hopefully this article can help - https://docs.microsoft.com/en-us/windows/mixed-reality/keyboard-input-in-unity
