### ISSUE TITLE
For the video its impossibel to view it, it says "This video is privat"

### ISSUE THREAD

**Issue by alexGreentown** [MicrosoftDocs/mixed-reality#663]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36ce5dc9-69a4-9264-d9ec-fe55866906aa
* Version Independent ID: 36ce5dc9-69a4-9264-d9ec-fe55866906aa
* Content: [How it works - Mixed Reality Capture Studios - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by annebelleo** [comment]
Duplicate of #642
