### ISSUE TITLE
Please include namespaces needed to run example code. 

### ISSUE THREAD

**Issue by datreed** [MicrosoftDocs/mixed-reality#664]
Why on earth would you give code examples without state which namespaces would need to be imported in order to support said examples? It would be a lot easier to get CoreServices.InputSystem.DetectedControllers to do things if you all would tell me where it lives in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 291b73e4-91d2-2224-304d-8b08adcad047
* Version Independent ID: 291b73e4-91d2-2224-304d-8b08adcad047
* Content: [Input State - MRTK 2](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/input/input-state?view=mrtkunity-2022-05)
* Content Source: [mrtk-unity/mrtk2/features/input/input-state.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk2/features/input/input-state.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by keveleigh** [comment]
Thanks for the heads up! I'll get this updated.
