### ISSUE TITLE
Project unable to build

### ISSUE THREAD

**Issue by chinmayks** [MicrosoftDocs/mixed-reality#666]
I was trying to build for the first time following instruction given in chapter 0 using 211: gesture source code and is throwing the following error. Though I have successfully build source code from chapter 210:Gaze and for this one made no changes, directly downloaded and just trying to build.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\project.lock.json" -bits=32 -configuration=Release -removeDebuggableAttribute=False -uwpsdk=10.0.17763.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Release" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\Assembly-CSharp.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.TextRenderingModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.TerrainPhysicsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.TerrainModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.TilemapModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UIElementsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.SharedInternalsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ScreenCaptureModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.SpriteMaskModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.StyleSheetsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.SpriteShapeModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.VideoModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.VehiclesModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityWebRequestWWWModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.VRModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.WindModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.WebModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityAnalyticsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UNETModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UIModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityConnectModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityWebRequestTextureModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityWebRequestModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UnityWebRequestAudioModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.AudioModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.AssetBundleModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ARModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ClothModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.DirectorModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.CrashReportingModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.CoreModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.AnimationModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.AIModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.AccessibilityModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ParticlesLegacyModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.JSONSerializeModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ParticleSystemModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.PhysicsModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.Physics2DModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.PerformanceReportingModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.GridModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.GameCenterModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.InputModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.IMGUIModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.ImageConversionModule.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\Newtonsoft.Json.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.Timeline.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\nunit.framework.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.UI.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.SpatialTracking.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.HoloLens.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.StandardEvents.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\UnityEngine.Networking.dll" "E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\GLTFSerializationUWP.dll"" exited with code 1.	

ModelExplorer	E:\1RIT\capstone\hololens_toolkit\HolographicAcademy-Holograms-211-Gesture\Starting\ModelExplorer\App\ModelExplorer\ModelExplorer.csproj	436	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05f996a9-6832-5352-7545-205a0a5f6372
* Version Independent ID: 9047846a-a2f0-9269-4dcd-5140b32ea2b4
* Content: [MR Input 211 - Gesture - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-211)
* Content Source: [mixed-reality-docs/holograms-211.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-211.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by cronomx** [comment]
Same problem here, did you managed to solve the issue?

**Comment by TheFridge76** [comment]
As your command seems to be longer than 8191 characters the problem is probably the cmd.exe command length limitation described here: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

In that case there should be an error in the Visual Studio output window that references a missing dll. In the path to the dll there is probably missing a single character which is the source of the error.

To avoid this, you could try shortening the name of the extracted source code ("HolographicAcademy-Holograms-211-Gesture") so that the whole command is shorter than 8192 characters. After that you'll probably have to delete the App folder and rebuild it to update all file references.

**Comment by hferrone** [comment]
@chinmayks HoloToolKit has been deprecated, please take a look at the Mixed Reality Toolkit for any further development. Thanks!
