### ISSUE TITLE
Hololens Miracast pin . Impossible to connect

### ISSUE THREAD

**Issue by jrobineau** [MicrosoftDocs/mixed-reality#667]
Hello,
I tryed to connect My hololens with new windows version with miracast connection process.
The miracast dongle is a MiraScreen and need a password to establish connection.
Hololens doesn't provide a screen to endable a password.
Is it possible to have a way to set up a password ?
Sincerely

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b99e8beb-e838-0146-8e52-37ef39ec5df7
* Version Independent ID: 5fdc588d-1823-2e35-2dfd-52d58711aca9
* Content: [HoloLens known issues - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hololens-known-issues)
* Content Source: [mixed-reality-docs/hololens-known-issues.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hololens-known-issues.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Hi @jrobineau,
I have run into this as well.  I don't believe the HoloLens allows you to connect to password protected Miracast devices.  I will update the documentation to call this out.

Thanks,
Jesse
