### ISSUE TITLE
Warnings importing Azure Spatial Anchors package

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#67]
Unity version 2019.4.10f1

This tutorial should call out that there are warnings related to legacy XR/XR SDK when importing this package and what to do about. The warning instructs the user to update to the new Unity XR plugin system so this tutorial should instruct the user on how to proceed.

![image](https://user-images.githubusercontent.com/30964480/94460781-18db7d00-016e-11eb-90d1-dc98bbb9c4a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure Spatial Anchors tutorials - 2. Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@mr0ng Can you or someone on the team assist?

**Comment by martinwilter** [comment]
Hi @hferrone, these warnings are thrown from ASA SDK (v2.2.1 is used in this tutorial) and can be ignored. Suggest to add a note under the image in the [Importing the tutorial assets](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02#importing-the-tutorial-assets) section:

> ![NOTE]
> If you see any CS0618 warnings regarding 'WorldAnchor.SetNativeSpatialAnchorPtr(IntPtr)' is obsolete, you can ignore these warnings.


```
> ![NOTE]
> If you see any CS0618 warnings regarding 'WorldAnchor.SetNativeSpatialAnchorPtr(IntPtr)' is obsolete, you can ignore these warnings.

```
