### ISSUE TITLE
Edit > Project Settings > Player > XR Settings-> Single pass not exist Unity 2022.1.21f

### ISSUE THREAD

**Issue by sergiosolorzano** [MicrosoftDocs/mixed-reality#672]
Im on Unity 2022.1.21f and this doesn't exist, where is it? 

Open Player XR Settings (go to Edit > Project Settings > Player > XR Settings)
Select Single Pass Instanced from the Stereo Rendering Method drop-down menu (Virtual Reality Supported checkbox must be checked)

Neither found in project settings->XR plugin management/Openxr
Select Single Pass Instanced from the Stereo Rendering Method drop-down menu (Virtual Reality Supported checkbox must be checked)

<img width="596" alt="image" src="https://user-images.githubusercontent.com/24430655/198625785-ef248e4c-3b02-45a9-87c1-a5da029d16b4.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71134e16-db2d-50e0-b21e-a8063e6dbf84
* Version Independent ID: 5b67a5ad-a7a9-9a84-f1ac-e9d14aaaf443
* Content: [Recommended settings for Unity - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/recommended-settings-for-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/recommended-settings-for-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/recommended-settings-for-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @vtieto
* Microsoft Alias: **vinnietieto**

**Comment by MaxWang-MS** [comment]
Hi @sergiosolorzano, the doc has been updated with up-to-date instructions since your original post. Here's a screenshot just in case:
![image](https://user-images.githubusercontent.com/68253937/202341067-523bed6c-72d8-435f-a836-3f271bb14961.png)
