### ISSUE TITLE
CS2001 Error every time I build

### ISSUE THREAD

**Issue by samitariq** [MicrosoftDocs/mixed-reality#675]
Hi - I am getting a CS2001 every time i build.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\105048354\Desktop\Origami\Origami\Packages\com.unity.textmeshpro\Scripts\Runtime\TMP_FontAsset.cs' could not be found.	Unity.TextMeshPro	C:\Users\105048354\Desktop\Origami\Origami\App\GeneratedProjects\UWP\Unity.TextMeshPro\CSC	1	Active

Lots of these. What can i do?

Thanks
Sami

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d680e05-a73a-321c-e7c8-8daa0a2c5249
* Version Independent ID: 8ef33125-aa37-cc1a-0264-bba3a12daf5d
* Content: [MR Basics 101E - Complete project with emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101e)
* Content Source: [mixed-reality-docs/holograms-101e.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-101e.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by jessemcculloch** [comment]
@samitariq - Based on the error you are getting, it looks like you are probably using Unity 2018, which includes TextMeshPro as a package automatically.  If this is the case, you actually need to use Unity 2017 for this tutorial, as it has not been tested with 2018.  You might be able to remove the TextMeshPro package from the project and see If that works, but there may be other errors that pop up as well.
