### ISSUE TITLE
Broken link to external Unreal site

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#676]
Link below is no longer valid on page:

"If you're new to Unreal development, don't jump in blind. Explore the Unreal [tutorial series](https://docs.unrealengine.com/GettingStarted/index.html) and look for assets"

The link specifically for [tutorial series]:
    Unreal [tutorial series](https://docs.unrealengine.com/GettingStarted/index.html)

===============================================
Gives following now:
   
   "https://docs.unrealengine.com/5.0/en-US/GettingStarted"

    404
   PAGE NOT FOUND

   The page you were looking for was not found. Please verify the link/URL or try starting back at our home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c948d6e8-720f-2603-a760-dfc5ae5c7a25
* Version Independent ID: 70c418eb-71d6-aae8-f590-9da1077787c4
* Content: [Unreal Development Overview - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-development-overview?tabs=ue427%2Cmrtk%2Casa%2CD365#2-core-building-blocks)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-development-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-development-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by typride** [comment]
PR for fix: pull 3896
