### ISSUE TITLE
Recommendation - Add Aquarium Tutorial and Figma Toolkit links to Main MRTK3 page

### ISSUE THREAD

**Issue by Victor-x1** [MicrosoftDocs/mixed-reality#677]
Recommendations:

1. Add a link to to checkout the MRTK3 "Aquarium" Tutorial. [Github](https://github.com/microsoft/MRTK3-iet-tutorials)
You can link to the following link for More information: [Microsoft Blog](https://techcommunity.microsoft.com/t5/mixed-reality-blog/mrtk3-in-editor-tutorials-for-unity/ba-p/3646376)

2.  Add a link to the Figma Toolkit for MRTK3 Preview [Figma](https://www.figma.com/community/file/1145959192595816999)

3. Add the following video:
TEC73 - Deploy Everywhere with MRTK3 and OpenXR [Youtube](https://www.youtube.com/watch?v=rOXHCruWiQsl)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf4a1898-af6b-be1b-4fa3-8c1269f855a9
* Version Independent ID: cf4a1898-af6b-be1b-4fa3-8c1269f855a9
* Content: [Mixed Reality Toolkit 3 Developer Documentation - MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/?view=mrtkunity-2021-05)
* Content Source: [mrtk-unity/mrtk3-overview/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/index.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by MaxWang-MS** [comment]
Hi @Victor-x1, thanks for the suggestion! I have added the links to our tutorial and Figma toolkit. I decided to not add a link to the YouTube video as we already have links to Microsoft Mixed Reality Dev Days 2022 talks on the page, which include one session that is very similar.
