### ISSUE TITLE
关于API调用

### ISSUE THREAD

**Issue by YUEJINYUAN** [MicrosoftDocs/mixed-reality#678]
设计师你好，我在尝试Unity+Hololens编程，并且试用Camera Capture UI API 的时候，发现我的VS2017没有所谓的Windows.Media.Capture 和 Windows.Storage 命名空间，我该怎么办？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e52f12b7-07cd-7c76-4805-768e8db8b773
* Version Independent ID: 5058f3e5-a549-3d47-e53b-f16d5a629df1
* Content: [Mixed reality capture for developers - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/mixed-reality-capture-for-developers)
* Content Source: [mixed-reality-docs/mixed-reality-capture-for-developers.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixed-reality-capture-for-developers.md)
* Product: **mixed-reality**
* GitHub Login: @wguyman
* Microsoft Alias: **wguyman**

**Comment by jessemcculloch** [comment]
你好 我首先要检查你是否安装了 windows sdk, 因为这就是这些 api 的可用性。

**Comment by jessemcculloch** [comment]
您正在使用 unity 吗？ 另外, 请原谅任何糟糕的翻译, 我正在使用一个工具从英语翻译成中文。

**Comment by YUEJINYUAN** [comment]
Oh! I'm sorry for my mistake. I'll talk to you directly in my mother tongue. I've been developing hololens in Unity for the last month. I think it's a great product. Do I need to provide you with screenshots anywhere? And then I noticed that part of it was because I wanted to achieve real-time video communication, and the hybrid reality capture in Unity didn't give me a good way to do that.

**Comment by jessemcculloch** [comment]
LOL, no worries!  

So, when in Unity, you often can't get references to the Windows API's from the Unity Visual Studio Solution scripts.  So as a first step, I would make a build from Unity, then open the Visual Studio project it creates, and see if you can reference the API's from there.

**Comment by jessemcculloch** [comment]
Also, i'm about to leave the office for the day, but I can pick up this conversation tomorrow.

**Comment by YUEJINYUAN** [comment]
As you said, I didn't see a reference to the UWP SDK when I wrote the script. I thought he would use it by default. So how can I get him to recognize my latest UWP SDK? Forgive my poor use of VS. I'm just a C# novice.and thank you for giving me valuable time.

**Comment by jessemcculloch** [comment]
HI @YUEJINYUAN - Are you still running into issues with this?
