### ISSUE TITLE
Mixed Reality Feature Tool Docs: Need to add what URL's need to be approved after installation to run on network

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/mixed-reality#679]
Issue report from forums:

https://learn.microsoft.com/en-us/answers/questions/1079490/mixedrealityfeaturetoolexe-open-issue.html

"I have try another network with same computer/setup and it work again. It seem that was a network security problem for my company, it block the "MixedRealityFeatureTool.exe".

Now, I need to an exemption for the network use for "MixedRealityFeatureTool.exe"

Suggestion:
Add to the Mixed Reality Feature Tool documentation what URL's are needed to be accessible from the user's client machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0405e5-aef5-5ed3-d9a1-960b4065300b
* Version Independent ID: dd9cd8d6-caea-6146-fd71-c5b3605435c4
* Content: [Welcome to the Mixed Reality Feature Tool - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/welcome-to-mr-feature-tool.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by qianw211** [comment]
The corporate firewall should allow certain URLs to pass, and we have listed the URLs in the latest doc update.

**Comment by snakex2000** [comment]
thank you!  Looks great!
