### ISSUE TITLE
Spatial Audio tutorial missing explanations

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#68]
This tutorial states that the user will learn how to use HRTK offload but there's no description of what HRTF offload is or why you would choose it.

There is also no explanation of what it means to "spatialize audio" and why you would want this.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d4fb4f8-cd18-1332-c10f-426451d48158
* Version Independent ID: b1e33de2-8c20-93e6-4500-3a31073be084
* Content: [Spatial audio tutorials - 1. Adding spatial audio to your project - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch1)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch1.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch1.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @kegodin
* Microsoft Alias: **kegodin**

**Comment by hferrone** [comment]
@kegodin Can you assist or tag someone who can?

**Comment by kegodin** [comment]
@NoelCross

**Comment by hferrone** [comment]
@NoelCross Can you provide some technical explanation content on the commenters callouts so I can make updates?
