### ISSUE TITLE
Can I remove the hololens wifi and Bluetooth modules from the physical hardware?

### ISSUE THREAD

**Issue by HuaChuan15** [MicrosoftDocs/mixed-reality#680]
[Enter feedback here]
Can I remove the hololens Wifi and Bluetooth modules from the physical hardware?
By removing the hardware instead of the way it is disabled in the system software.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b700ea1b-e555-eae5-6eb7-c1cbbdeb4d36
* Version Independent ID: 6b4f1f07-98ae-3ff1-b1f4-c5c7255c74ee
* Content: [HoloLens hardware details - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/hololens-hardware-details)
* Content Source: [mixed-reality-docs/hololens-hardware-details.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/hololens-hardware-details.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Hello @HuaChuan15,
The HoloLens is not a device that is self-serviceable.  There is a extremely good chance that you would render the device un-usable if you attempted to do so.
