### ISSUE TITLE
Reference Sample Scenes with no indication of where to find them.

### ISSUE THREAD

**Issue by AaronTaube** [MicrosoftDocs/mixed-reality#681]
Looking for CanvasExample.Unity and I cannot find any indication at all of where to find this sample scene or the project that it is a part of.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1117d3fc-ec4b-029a-a49c-a4b473cd0021
* Version Independent ID: 1117d3fc-ec4b-029a-a49c-a4b473cd0021
* Content: [Button - MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button)
* Content Source: [mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/button.md)
* Product: **mixed-reality**
* GitHub Login: @Zee2
* Microsoft Alias: **finnsinclair**

**Comment by MaxWang-MS** [comment]
Hi @AaronTaube, it's located inside our [sample Unity Project](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/setup#path-1-clone-the-repository-and-try-out-the-sample-unity-project). Here's a link to the file directly: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasExample.unity
