### ISSUE TITLE
Documentation error? WinMR vertical touchpad/joystick direction mismatch with Unity docs

### ISSUE THREAD

**Issue by horatiu665** [MicrosoftDocs/mixed-reality#686]
See the bottom of the Unity docs page:
https://docs.unity3d.com/Manual/Windows-Mixed-Reality-Input.html
It states that the positive direction for vertical axis is up, however on the WinMR page (link below) the info is reversed (positive is down). Could someone double check and fix whichever is the case? I am testing this on oculus and trying my best to reach WinMR devs because I'm fixing up my VR input wrapper causing bugs in my cross platform games...

link to WinMR input page https://docs.microsoft.com/en-gb/windows/mixed-reality/gestures-and-motion-controllers-in-unity

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7991d3-d96c-3695-c2e6-8abed3de51b2
* Version Independent ID: b8f20855-b2c4-dc12-34d7-5f0795cfb78b
* Content: [Gestures and motion controllers in Unity - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/gestures-and-motion-controllers-in-unity)
* Content Source: [mixed-reality-docs/gestures-and-motion-controllers-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/gestures-and-motion-controllers-in-unity.md)
* Product: **mixed-reality**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by jessemcculloch** [comment]
On the WinMR input page this is called out in the note at the bottom of the table....

![image](https://user-images.githubusercontent.com/11747005/50172925-00f17c80-02ab-11e9-8971-b6c4efceec5d.png)

**Comment by horatiu665** [comment]
I did not understand this inversion from the note. Yes, axis IDs differ, and while taking that into account the axis UP is still reversed compared to the Vive (or so the theory goes, until I can confirm myself with a test)
But thanks for the note! I will try to remember to update this post in February when I get my hands on WinMR and Vive again.
