### ISSUE TITLE
Unable to open URL： https://www.customvision.ai/ 

### ISSUE THREAD

**Issue by alialilc** [MicrosoftDocs/mixed-reality#689]
the page always shows : "The URL may be misspelled or the page you're looking for is no longer available."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889db7e9-a0ea-abb3-9b25-f9db5527655c
* Version Independent ID: 6fd8a913-c2ae-a45e-1461-357f46105e34
* Content: [MR and Azure 302b - Custom vision - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mr-azure-302b)
* Content Source: [mixed-reality-docs/mr-azure-302b.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mr-azure-302b.md)
* Product: **mixed-reality**
* GitHub Login: @DrNeil
* Microsoft Alias: **v-arood**

**Comment by jessemcculloch** [comment]
Hi @alialilc - I was just able to open that page without any problems, can you try again, and let me know either way, so I can close this issue if appropriate.

If it's still failing, can you let me know what browser you are using?  

Thanks,
Jesse

**Comment by alialilc** [comment]
> Hi @alialilc - I was just able to open that page without any problems, can you try again, and let me know either way, so I can close this issue if appropriate.
> 
> If it's still failing, can you let me know what browser you are using?
> 
> Thanks,
> Jesse

The browsers are safari, chrome, Edge. When I log in, the page always turn to "Whoops! We can't seem to find the page you are looking for."

**Comment by ceteongvanness** [comment]
Any update on this??

**Comment by jessemcculloch** [comment]
I was again able to open this without issue.  Perhaps this is a regional issue?  Can you let me know roughly where you are located?

**Comment by squdgy** [comment]
I am also seeing this issue - in both Firefox and Chrome, even in a Chrome incognito window. I do have both personal and business logins with the same email address, so I wonder if my problem could be related to that? I am located in northeastern US.
