### ISSUE TITLE
Expectations for testing spatialized audio not clear

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#69]
There's no description of what to expect when testing the spatialized button interaction sounds. The user cannot tell if this is working correctly or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d70ec56-d3e7-292b-58cd-2b44b053c04d
* Version Independent ID: c7cf87ae-9b0d-a94f-5463-673a0a1b3634
* Content: [Spatial audio tutorials - 2. Spatializing button interaction sounds - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch2)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @kegodin
* Microsoft Alias: **kegodin**

**Comment by hferrone** [comment]
@kegodin Can you assist or tag someone who can?

**Comment by hferrone** [comment]
@mr0ng @martinwilter This is listed as completed in the spreadsheet Sean shared but there is nothing here?

**Comment by martinwilter** [comment]
@hferrone, I'm not familiar with that spreadsheet, but I know we didn't create this tutorial series, I believe it was created internally, possibly by MRTK team.

Readers can test in Unity editor by entering game mode (ideally with looped audio), then move the object with the audio source from left to right and compare with and without spatial audio enabled (they can change those settings at runtime).

<br>

>Move the Spatial Blend slider to 3D (1)

This makes the audio 3D (spatialized).

<br>

>Check the Spatialize checkbox

This will enable the custom spatializer selected in Project Settings > Audio > Spatializer Plugin. This would typically be MS HRTF Spatializer.
