### ISSUE TITLE
Custom Places missing?

### ISSUE THREAD

**Issue by Virgilius1995** [MicrosoftDocs/mixed-reality#693]
I followed your guide and placed  Fantasy_Island aswel as my own custom environments in %LOCALAPPDATA%\Packages\EnvironmentsApp_cw5n1h2txyewy\LocalState. I've tried updating everything in windows update including Microsoft software and I still cant find fantasy island or the other in places when I'm in mixed reality portal.

**Comment by jessemcculloch** [comment]
Is this still an issue?  If so, can you find out what version of Windows 10 you are running?
