### ISSUE TITLE
Experience options outdated description

### ISSUE THREAD

**Issue by ErrorRaffyline0** [MicrosoftDocs/mixed-reality#695]
Experience options is now called "Frame rate". Automatic is now "Let Windows decide". Experience options description in [mixed-reality](https://github.com/MicrosoftDocs/mixed-reality)/[enthusiast-guide](https://github.com/MicrosoftDocs/mixed-reality/tree/docs/enthusiast-guide/using-wmr-faq.yml) also has these issues but also lists incomplete information regarding why your headset may not be able to run at 90Hz, suggesting this can only be caused by cabling issues, despite error code 13-14 listing an issue with resolutions on some systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 887a1485-cbe8-148c-66b5-62120a130f54
* Version Independent ID: a16efe87-0e43-c660-69c2-62bd7e7027e7
* Content: [Immersive hardware realted FAQ - Enthusiast Guide](https://learn.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/other-questions)
* Content Source: [enthusiast-guide/other-questions.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/other-questions.md)
* Product: **mixed-reality**
* Technology: **enthusiast-guide**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by qianw211** [comment]
We have updated the docs regarding "Experience options".

As for the additional comments about details related to 13-14 errors, we will address this among broader updates to the [Error Codes] (https://learn.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/error-codes) page in the near-term future.
