### ISSUE TITLE
Incomplete set of latest voice commands

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/mixed-reality#7]
It looks like the dev docs haven't been updated with the latest set of system voice commands from the 20H1 release documented here: https://docs.microsoft.com/en-us/hololens/hololens-cortana

This could cause issues for developers because the system commands are reserved from apps being able to use. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input?source=docs)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by hferrone** [comment]
@Hak0n Can you weigh in?

**Comment by tmlyon** [comment]
@hferrone Hakon is on a different team now, and I'm the subject matter expert for the voice commands.

**Comment by hferrone** [comment]
@tmlyon Great! What specific changes would you like me to make to the voice-input.md file?

**Comment by hferrone** [comment]
@tmlyon Following up :)

**Comment by tmlyon** [comment]
Hey @hferrone, it looks like the page has actually been updated with the ones that were missing now (photo/video capture). It would be good to add a link to this other page though (https://docs.microsoft.com/en-us/hololens/hololens-cortana) at the end of the voice command list, because I don't think these dev docs are guaranteed to be localized correctly, and the voice commands have to match what is in product for other languages.

**Comment by hferrone** [comment]
@tmlyon Will do, i'll be making this update in the private repo and closing this issue here. Thanks so much!
