### ISSUE TITLE
Typo and missing screenshot in spatial audio tutorial

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#70]
This description is missing a screenshot and contains a typo.

![image](https://user-images.githubusercontent.com/30964480/94462729-cd769e00-0170-11eb-87cb-0e4ede9fa5fc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d70ec56-d3e7-292b-58cd-2b44b053c04d
* Version Independent ID: c7cf87ae-9b0d-a94f-5463-673a0a1b3634
* Content: [Spatial audio tutorials - 2. Spatializing button interaction sounds - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch2)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/unity-spatial-audio-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @kegodin
* Microsoft Alias: **kegodin**

**Comment by hferrone** [comment]
@polar-kev Not sure what happened with this issue, but I searched the article you referenced and didn't find any of this text?

**Comment by polar-kev** [comment]
@hferrone, I raised the issue on the wrong page. The text can be found here, https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/unity-spatial-audio-ch4
