### ISSUE TITLE
MRTK3 Button Resizing example does not work

### ISSUE THREAD

**Issue by mmoerman** [MicrosoftDocs/mixed-reality#701]
On the following page:
https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-uxcore/packages/uxcore/canvas-ui.md

There is an indication that you should be able to resize the components within a canvas through some sort of interaction with a blue outline. And int he MRTKDevTemplate - CanvasExample there seems to be an indication thatr you can do so in the "Same layout, unconstrained size (Resize me)" window, but try as I might with an Oculus Quest I am unable to gain access to the resizing handles for the buttons. Is this feature not developed yet, or is there something I am missing?

**Comment by Zee2** [comment]
This is referring to how you can resize UI layouts in editor using the UGUI layout tools. This is not an in-game or on-device affordance. https://learn.unity.com/tutorial/working-with-ui-in-unity#

**Comment by mmoerman** [comment]
> This is referring to how you can resize UI layouts in editor using the UGUI layout tools. This is not an in-game or on-device affordance. https://learn.unity.com/tutorial/working-with-ui-in-unity#

Ok, might be good to make that clear in the docs, and possibly an interesting feature to consider in the future, but understood and thank you for the reply.
