### ISSUE TITLE
Won't work across multiple drives

### ISSUE THREAD

**Issue by JoshuaKahn** [MicrosoftDocs/mixed-reality#705]
Just an FYI; this tutorial won't work if VisualStudio (and possibly Unity) is installed across multiple drives. I had the IDE in the C drive with the 'Shared' Folder in the D drive, and the program couldn't find the right parts of the Windows SDK. By extension, the program won't be able to find the files needed to run the Hololens emulator, since it will be installed in the D drive as well.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d680e05-a73a-321c-e7c8-8daa0a2c5249
* Version Independent ID: 8ef33125-aa37-cc1a-0264-bba3a12daf5d
* Content: [MR Basics 101E - Complete project with emulator - Mixed Reality](https://docs.microsoft.com/en-gb/windows/mixed-reality/holograms-101e)
* Content Source: [mixed-reality-docs/holograms-101e.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-101e.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by JoshuaKahn** [comment]
I had to change the Shared folder by editing the registry value that told it where to be installed, since the location is set the first time you install Visual Studio.

**Comment by jessemcculloch** [comment]
@JoshuaKahn - Can I close this issue?  This seems to be something specific to Visual Studio, not mixed reality.
