### ISSUE TITLE
Bluetooth disconnecting, constant OS crashing

### ISSUE THREAD

**Issue by HyperLethalVector** [MicrosoftDocs/mixed-reality#706]
Hi, I'm having several issues with RS5,

1st, bluetooth connectivity is sporratic with the XBOX one controller, sometimes the controller stops responding until I re-open the 'settings' app.

second when I'm using multiple anchors in any application, the OS itself will crash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/give-us-feedback)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Please file a support request at https://aka.ms/HLSupport for these issues.

Thanks,
Jesse McCulloch
