### ISSUE TITLE
Downgrading to RS4 via WDRT

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/mixed-reality#708]
I've found this article which links to an RS1 system image: https://support.microsoft.com/en-us/help/12643/hololens-update-hololens

However, what if we'd like to go back to RS4 instead? There doesn't seem to be a possibility. Could you please provide a link to the latest RS4 system image?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75391ba-c896-4002-ab90-f872c56d68d3
* Version Independent ID: 519128a5-a472-fc42-ca48-0ce79f3ebc4c
* Content: [Reset or recover your HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/reset-or-recover-your-hololens)
* Content Source: [mixed-reality-docs/reset-or-recover-your-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/reset-or-recover-your-hololens.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
We don't have access to these images, but if you file a support case at https://support.microsoft.com/en-us/supportforbusiness/productselection?sapid=e9391227-fa6d-927b-0fff-f96288631b8f they should be able to assist
