### ISSUE TITLE
Recording options

### ISSUE THREAD

**Issue by tyl3r** [MicrosoftDocs/mixed-reality#712]
Recordings are automatically limited to 5 minutes and captured with a crap resolution. We need at least some options, like it is now is totally useless...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 224628bf-c0ec-6fd3-e5e3-c4783aedfe5a
* Version Independent ID: c7e321ca-4e76-ade5-ca5d-c4b0a0288125
* Content: [Mixed reality capture - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-capture)
* Content Source: [mixed-reality-docs/mixed-reality-capture.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mixed-reality-capture.md)
* Product: **mixed-reality**
* GitHub Login: @wguyman
* Microsoft Alias: **wguyman**

**Comment by jessemcculloch** [comment]
Please file this feedback via the feedback hub on the device, as that is the best place to have it tracked.  It's not really actionable via this forum, as these issues should really be about documentation.

Thanks,
Jesse
