### ISSUE TITLE
Switchable battery pack for HL2

### ISSUE THREAD

**Issue by zeroinfinityone** [MicrosoftDocs/mixed-reality#714]
i hope the new HL has a switchable battery.  I know it might seem more in MS interest to require experience-runners to buy more headsets but buying 2X the amount of headsets so that 1/2 of them can be charging while the other 1/2 are being used seems unnecessarily wasteful... it also creates a prohibitive entry price for certain business models (2X the price)... I bet it would pan out in MORE sales to have a 2nd battery you can change out.  When a headset gets used constantly and wears out faster, then the operator will buy new one(s) after they've made ROI.  What's everyone going to do with the obsolete hololenses btw? ... sell them, so then MS loses that sale of a new device to a used one.  Iteration will continue so the faster people wear them out BEFORE new versions are released, the more sales.  Phones last all day so you can charge at night... but 2 or 5hrs isn't enough.  A switchable battery option will increase sales acceleration.  It's an easy add-on sale too and mitigates battery-life problems/criticism. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0a0135-d443-a905-bd6a-5f6700afb4e4
* Version Independent ID: 27962279-8d07-cc59-a870-a58f37df7142
* Content: [Give us feedback - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/give-us-feedback)
* Content Source: [mixed-reality-docs/give-us-feedback.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/give-us-feedback.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
Thank you for the feedback, I have passed it onto the design team!
