### ISSUE TITLE
Socket Exception and error CS0246

### ISSUE THREAD

**Issue by Damarowsky** [MicrosoftDocs/mixed-reality#715]
I get three errors when I try to finish "Chapter 1: setting up the scene" by pressing play the first time.

(1): SocketException: The access to a socket was not allowed due to the access rights of the socket (translated from german):
 
System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) (at &lt;3845a180c26b4889bc2d47593a665814&gt;:0)
SyntaxTree.VisualStudio.Unity.Messaging.UdpSocket.Bind (System.Net.IPAddress address, System.Int32 port) (at &lt;7bfe50ea87ae444bb97944401234ceb7&gt;:0)
SyntaxTree.VisualStudio.Unity.Messaging.Messager..ctor (System.Int32 port) (at &lt;7bfe50ea87ae444bb97944401234ceb7&gt;:0)
SyntaxTree.VisualStudio.Unity.Messaging.Messager.BindTo (System.Int32 port) (at &lt;7bfe50ea87ae444bb97944401234ceb7&gt;:0)
SyntaxTree.VisualStudio.Unity.Bridge.VisualStudioIntegration+&lt;&gt;c__DisplayClass9_0.&lt;.cctor&gt;b__0 () (at &lt;843b7c5ab4d34b2491669c24f4d94522&gt;:0)
SyntaxTree.VisualStudio.Unity.Bridge.Project+&lt;&gt;c__DisplayClass40_0.&lt;RunOnceOnUpdate&gt;b__0 () (at &lt;843b7c5ab4d34b2491669c24f4d94522&gt;:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)

(2): Assets\Holograms\Support\Spatial Mapping\SpatialMapping.cs(24,13): error CS0246: The type or namespace name 'SpatialMappingRenderer' could not be found (are you missing a using directive or an assembly reference?)

(3): Assets\Holograms\Support\Spatial Mapping\SpatialMapping.cs(27,13): error CS0246: The type or namespace name 'SpatialMappingCollider' could not be found (are you missing a using directive or an assembly reference?)

----
Not sure how to fix any of them, as I'm beginner.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9d680e05-a73a-321c-e7c8-8daa0a2c5249
* Version Independent ID: 8ef33125-aa37-cc1a-0264-bba3a12daf5d
* Content: [MR Basics 101E - Complete project with emulator - Mixed Reality](https://docs.microsoft.com/de-de/windows/mixed-reality/holograms-101e)
* Content Source: [mixed-reality-docs/holograms-101e.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-101e.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by Damarowsky** [comment]
Ok on second try the socket error is gone but (2) and (3) remain.

**Comment by keveleigh** [comment]
For 2 and 3, likely the Windows Mixed Reality package didn't properly install itself. With some versions of Unity, it seems there's a dependency to either:

* Toggle the XR Supported checkbox under UWP Player Settings
* Go to Window -> Package Manager and ensure Windows Mixed Reality is downloaded and updated
