### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by alfred-msft** [MicrosoftDocs/mixed-reality#716]
The link in this sentence is broken:
You can use the QR tracking scrips in the MRTK scripts folder or write your own.
It should point to: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/htk_development/Assets/HoloToolkit-Preview/QRTracker/Scripts

Also note the typo in the sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking)
* Content Source: [mixed-reality-docs/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/qr-code-tracking.md)
* Product: **mixed-reality**
* GitHub Login: @Yoyozilla
* Microsoft Alias: **yoyoz**

**Comment by jessemcculloch** [comment]
Fixed with PR #721
