### ISSUE TITLE
trying to import in "easy way" a glb file in mixed reality home

### ISSUE THREAD

**Issue by singaii** [MicrosoftDocs/mixed-reality#717]
[Enter feedback here]
I am trying to import a 3d asset in mixed reality home in different way like the old version of 3d browsing app do with hologramms because it's unavailiable now directly in app. i make glb file with blender and kronos group blend file specification for gltf
I can use them like "place" in vr but i can't populate them with different glb file. I 'm trying to use this for interrior design and architecture.

Where i can find some help, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222adc1b-2b0f-580c-6667-1acd1b31e348
* Version Independent ID: 673c34dd-a47a-1b7a-0a49-b3826c143997
* Content: [Enable placement of 3D models in the home - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/enable-placement-of-3d-models-in-the-home)
* Content Source: [mixed-reality-docs/enable-placement-of-3d-models-in-the-home.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/enable-placement-of-3d-models-in-the-home.md)
* Product: **mixed-reality**
* GitHub Login: @thmignon
* Microsoft Alias: **thmignon**

**Comment by jessemcculloch** [comment]
Can you try using the 3D Viewer app.  This replaced the Holograms app, and should let you load your own files.

**Comment by singaii** [comment]
I was on windows insider program, i have re-install a clean windows 10 with update (but without insider program) and now i have acces to gbl import. I close the tread
