### ISSUE TITLE
HoloLens Support?

### ISSUE THREAD

**Issue by ModischFabrications** [MicrosoftDocs/mixed-reality#724]
Is there any planned release that supports the HoloLens? Can you name a broad timeline if it's planned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/qr-code-tracking)
* Content Source: [mixed-reality-docs/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/qr-code-tracking.md)
* Product: **mixed-reality**
* GitHub Login: @Yoyozilla
* Microsoft Alias: **yoyoz**

**Comment by jessemcculloch** [comment]
There is nothing we have announced at this time with regards to supporting QR code tracking on the HoloLens.

Thanks,
Jesse

**Comment by alexander-hofmann** [comment]
QRCodeWatcher.IsSupported() always returns false - webcam enabled on unity 2019.3.5f1 Personal, followed the HoloLens2 tutorial at https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base for some basics.
