### ISSUE TITLE
no longer need Windows Insider Preview Build 

### ISSUE THREAD

**Issue by boynet** [MicrosoftDocs/mixed-reality#727]
in "Enabling the Windows Mixed Reality simulator" step 1 it says: "Install the latest Windows Insider Preview Build" which is no longer true, the simulator is now in the normal windows build

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8bde5f8-e3c3-d0b2-3472-3a6d1439c164
* Version Independent ID: f996653f-3fef-4bf3-b034-f78c2562e0c0
* Content: [Using the Windows Mixed Reality simulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-mixed-reality-simulator)
* Content Source: [mixed-reality-docs/using-the-windows-mixed-reality-simulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-windows-mixed-reality-simulator.md)
* Product: **mixed-reality**
* GitHub Login: @JonMLyons
* Microsoft Alias: **jlyons**

**Comment by jessemcculloch** [comment]
This has been updated in PR #728, and will get pushed live with the next PR to our live branch.

Thanks for flagging!
