### ISSUE TITLE
First app deployed should not be an empty project

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#73]
In this getting started tutorial the user is instructed to deploy an empty project to their hololens. This means that nothing appears on the device when it is working properly. How are you supposed to know it worked if it’s empty? 

The first app deployed should include, at the minimum, a cube (or some other object), so the user can confirm that the app is working when running it on device.

**Additional feedback from Rebecca Burke Aguero on 03/15**

- "Before the “Building your application to your HoloLens 2” section, add a link or new section or some sort of reference to a tutorial for how to actually put things in your app! How are you supposed to know if your app works if it’s completely empty? "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@polar-kev Can you supply steps and screenshots and where in the tutorial this update would go and I can make the update?

**Comment by hferrone** [comment]
https://github.com/MicrosoftDocs/mixed-reality/issues/70

**Comment by polar-kev** [comment]
Under the section "Creating and configuring the scene", I would like to see instructions to:

1. Import a cube prefab into the scene
2. Apply the Object Manipulator and Near Interaction Grabbable scripts to the cube
3. Interact with the cube using input simulation in the Unity editor
4. Interact with the cube after deploying the app to the device

Stretch Goal: The cube should be a premade asset that has the words "Hello World" on all faces of the cube.

Without having an object in the scene, it's difficult to tell if the deployment is successful because the app doesn't actually do anything.

**Comment by polar-kev** [comment]
@mr0ng, would we be able to get some assistance here?

**Comment by varunsiddaraju** [comment]
Hi @polar-kev : We will work on this and will provide you the update.

**Comment by veeruby-developer** [comment]
@hferrone  this has been updated in the closed PR #255.
This issue can be closed.
