### ISSUE TITLE
Compile Errors?

### ISSUE THREAD

**Issue by DominionSoftware** [MicrosoftDocs/mixed-reality#733]
I'm trying the 101e and getting:
Assets\Holograms\Support\Spatial Mapping\SpatialMapping.cs(27,13): error CS0246: The type or namespace name 'SpatialMappingCollider' could not be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d680e05-a73a-321c-e7c8-8daa0a2c5249
* Version Independent ID: 8ef33125-aa37-cc1a-0264-bba3a12daf5d
* Content: [MR Basics 101E - Complete project with emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101e#before-you-start)
* Content Source: [mixed-reality-docs/holograms-101e.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-101e.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by ottomp24** [comment]
This is a "bug" in later versions of Unity 2018 and above when importing projects with an older version where those 2 classes are not automatically imported. Just go to XR Settings under Player settings and uncheck/check "Virtual Reality Supported". That will re-download the missing classes.

**Comment by faizan251298** [comment]
Hi ,I am trying the Tutorial **MR Basics 101** , the error 

> Assets\Holograms\Support\Spatial Mapping\SpatialMapping.cs(27,13): error CS0246: The type or namespace name 'SpatialMappingCollider' could not be found (are you missing a using directive or an assembly reference?)

is not getting resolved using the method of changing XR settings under Player settings

**Comment by hferrone** [comment]
@keveleigh Is this a known issue?

**Comment by keveleigh** [comment]
@hferrone I'm not aware of that being a known issue. In Unity 2019, it'd be good to double check that the Windows Mixed Reality package is installed in the Package Manager:

![image](https://user-images.githubusercontent.com/3580640/88864644-885add80-d1ba-11ea-8d65-5bb616c1f51d.png)

I think 2019 defaults to the Windows XR Plugin instead, which won't have that file.
