### ISSUE TITLE
Most of the github links to the UX section are broken

### ISSUE THREAD

**Issue by VincentGuigui** [MicrosoftDocs/mixed-reality#735]
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExample.md
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 086c41c2-a28e-c55c-40e6-af4f79ecfc01
* Version Independent ID: e094d1fd-cf87-4df3-80be-e1c88f3aab0c
* Content: [Interactable object - Mixed Reality](https://docs.microsoft.com/fr-fr/windows/mixed-reality/interactable-object)
* Content Source: [mixed-reality-docs/interactable-object.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/interactable-object.md)
* Product: **mixed-reality**
* GitHub Login: @cre8ivepark
* Microsoft Alias: **dongpark**

**Comment by jessemcculloch** [comment]
Thank you for submitting the fixes, I have just started the merge process to send them live.
