### ISSUE TITLE
Spatial Mapping for immersive headsets

### ISSUE THREAD

**Issue by HectorMeneses333** [MicrosoftDocs/mixed-reality#741]
It would be wonderful if spatial mapping was available for immersive headsets. Is that a feature you are considering to build? 
if not, maybe there should be a way to tag real objects positions from the immersive headset. Say, I want to know exactly where is my keyboard, my monitors, my coffee cup, etc so I can interact with them in both real life and VR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e220dac9-c551-9639-3af0-39e0e7687fd0
* Version Independent ID: 6186d98f-44d0-53a5-8d54-4f77a7d07ef5
* Content: [MR Spatial 230 - Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230)
* Content Source: [mixed-reality-docs/holograms-230.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-230.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by jessemcculloch** [comment]
@HectorMeneses333 
This isn't a capability that we have for immersive headsets.  If you can file this feedback via the windows feedback hub, the info will get in front of our engineering teams.

**Comment by WarHawk37** [comment]
@jessemcculloch 
Without Spatial Mapping how does it track its own position
