### ISSUE TITLE
App deploying, but empty? (MRTK Tutorial, Hololens 2)

### ISSUE THREAD

**Issue by KCollins** [MicrosoftDocs/mixed-reality#745]
I'm deploying remotely to my Hololens 2. I would expect to see the Near Cube/Far Cube setup I created in Unity per the tutorial. Deploying remotely from Visual Studio successfully creates an app in my App list called "MRTK Tutorial," but when I open that app I get the polygons-around-the-room screen, the Windows-loading logo, and then.... nothing. I'm back in my Home setting with the blank rectangular icon to launch/relaunch the MRTK Tutorial app. I've tried uninstalling and reinstalling the app on the Hololens multiple times, as well as rebooting the headset. Same issue seems to persist whether I'm using Debug or Deploy. What am I doing wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1d977b4-a9b1-4232-8033-a2f69fbf249e
* Version Independent ID: c1d977b4-a9b1-4232-8033-a2f69fbf249e
* Content: [Using Visual Studio to deploy and debug - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/using-visual-studio?tabs=hl2)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-visual-studio.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/using-visual-studio.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @vtieto
* Microsoft Alias: **vinnietieto**

**Comment by AMollis** [comment]
@KCollins , thank you for the issue.  However, it is not clear what tutorial is failing for you.  Can you please share the link to the tutorial?

**Comment by KCollins** [comment]
@AMollis Yes, it's this one here: https://learn.microsoft.com/en-us/training/modules/learn-mrtk-tutorials/1-7-exercise-hand-interaction-with-objectmanipulator
(Sorry about that. For some reason I assumed this thread was linked to the tutorial page...)

**Comment by KCollins** [comment]
@AMollis I went back to Unity and rebuilt it there, then went through the steps in Visual Studio a second time - now it's working! I'm not sure what I did differently.... Thanks for your time in any case.

**Comment by AMollis** [comment]
Thank you for following up @KCollins ...

Just a heads up, once [MRTK3 ](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/) releases, we will be releasing updates to the HoloLens tutorials.    Hopefully these updates will resolve the original problem you had.
