### ISSUE TITLE
Need a full example.

### ISSUE THREAD

**Issue by DominionSoftware** [MicrosoftDocs/mixed-reality#745]
Not enough information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 153e2533-1e2d-b1f2-a6cd-bcdad9855667
* Version Independent ID: e00e7aef-f656-48d5-4e9b-438da5f3334e
* Content: [Locatable camera in DirectX - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera-in-directx)
* Content Source: [mixed-reality-docs/locatable-camera-in-directx.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/locatable-camera-in-directx.md)
* Product: **mixed-reality**
* GitHub Login: @MikeRiches
* Microsoft Alias: **mriches**

**Comment by jessemcculloch** [comment]
@DominionSoftware - Can you provide more actionable info?  I don't really know what to do with this.

**Comment by DominionSoftware** [comment]
Yes, sorry.

Snip -
hr = pSample->GetUnknown(MFSampleExtension_Spatial_CameraCoordinateSystem, IID_PPV_ARGS(&spUnknown));
Snip-

What is pSample?



Rick Frank
Dominion Software, Inc.
825 Beacon Street
Newton, MA 02459
Medical, Scientific, and Industrial Software

On Jul 25, 2019, at 7:33 PM, Jesse McCulloch <notifications@github.com<mailto:notifications@github.com>> wrote:


@DominionSoftware<https://github.com/DominionSoftware> - Can you provide more actionable info? I don't really know what to do with this.

**Comment by jessemcculloch** [comment]
![image](https://user-images.githubusercontent.com/11747005/61981059-66c68500-afad-11e9-9bb7-648ced3bcec0.png)
It refers to IMFStreamSink::ProcessSample() as linked above the sample.
