### ISSUE TITLE
Wrong Link for "audio stream categories"

### ISSUE THREAD

**Issue by AtomScott** [MicrosoftDocs/mixed-reality#747]
The link from audio stream categories (under Communication) takes us to a 404 page.
I think the correct link is https://docs.microsoft.com/en-us/windows/desktop/api/audiosessiontypes/ne-audiosessiontypes-audio_stream_category, there is an extra _ before audio_stream_category in the broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659d52-b481-f97b-9824-58874adc0763
* Version Independent ID: b5f1e3d5-cb2d-445b-a737-38498f7863e5
* Content: [Voice input - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/voice-input#communication)
* Content Source: [mixed-reality-docs/voice-input.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/voice-input.md)
* Product: **mixed-reality**
* GitHub Login: @Hak0n
* Microsoft Alias: **hakons**

**Comment by jessemcculloch** [comment]
This is resolved
