### ISSUE TITLE
Outdated link 

### ISSUE THREAD

**Issue by DevSelchow** [MicrosoftDocs/mixed-reality#756]
[Enter feedback here]
Linked Git Repository in top Paragraph is "now locked, and will no longer be maintained."

Link is found in this sentence:
`As a result, we no longer ship our sample scenes inside the MRTK library/package itself. Instead, we maintain the UnityProjects folder at the top level of the [Git repository](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk3),`

Please link to where up to date MRTK3 sample scenes are currently found.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a8abaa-6a91-2e2c-6d06-17ac3a64ba77
* Version Independent ID: 81a8abaa-6a91-2e2c-6d06-17ac3a64ba77
* Content: [Exploring MRTK3 sample scenes - MRTK3](https://learn.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/exploring-features/mrtk3-sample-scenes)
* Content Source: [mrtk-unity/mrtk3-overview/getting-started/exploring-features/mrtk3-sample-scenes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/getting-started/exploring-features/mrtk3-sample-scenes.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by AMollis** [comment]
@marlenaklein-msft can you help with updating this MRTK3 documentation link?
