### ISSUE TITLE
Unable to proceed with HoloLens emulator installation

### ISSUE THREAD

**Issue by Srikor** [MicrosoftDocs/mixed-reality#758]
Unable to proceed with the installation of version 1252 of Hololens emulator. Getting this error although my internet connection is fine. Was able to install version 1244 installed though.

![image](https://github.com/MicrosoftDocs/mixed-reality/assets/59224063/00c36836-1533-4230-b0c5-e2b58cb772e6)

**Comment by AMollis** [comment]
@bryanmsft  ... can you help route this issue to the correct individual to investigate?
