### ISSUE TITLE
location of the prefabs

### ISSUE THREAD

**Issue by spany14** [MicrosoftDocs/mixed-reality#763]
Unity search function does not work here unfortunately and have to manually search where the prefabs are located. I was able to find the MRTK XR Rig but not the MRTKInputSimulator unfortunately

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e474ec07-5a01-cf13-14ff-a73573e73581
* Version Independent ID: e474ec07-5a01-cf13-14ff-a73573e73581
* Content: [Creating a new scene with MRTK3 - MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-scene)
* Content Source: [mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-scene.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/getting-started/setting-up/setup-new-scene.md)
* Product: **mixed-reality**
* GitHub Login: @RogPodge
* Microsoft Alias: **roliu**

**Comment by marlenaklein-msft** [comment]
Hi @spany14,

By the Unity search function do you mean this search on the Project window? Make sure your search is set to 'All' to include the MRTK prefabs.

![image](https://github.com/MicrosoftDocs/mixed-reality/assets/125413876/92ea6e8e-80ef-4487-baa7-2604cf6879ac)

You should also be able to find the input simulator under Packages/org.mixedrealitytoolkit.input/Assets/Prefabs/MRTKInputSimulator.prefab.

**Comment by AMollis** [comment]
@spany14  please follow-up with @marlenaklein-msft 's suggestion.  We are unable to reproduce this issue.   We will close as not repro.  Please open a new ticket if you are still having an issue.  Thank you!
