### ISSUE TITLE
Issue with values returned by /api/power/battery (GET)

### ISSUE THREAD

**Issue by contactgc** [MicrosoftDocs/mixed-reality#768]
Hi,

Until recently, we used the /api/power/battery API (GET) to get the battery level and, more importantly, the estimated time remaining, but since the latest updates we've been getting this:

```
{
    "AcOnline": 0,
    "BatteryPresent": 1,
    "Charging": 0,
    "DefaultAlert1": 221,
    "DefaultAlert2": 397,
    "EstimatedTime": 4294967295,
    "MaximumCapacity": 4415,
    "RemainingCapacity": 4415
}
```

4294967295 is the max uint value. It looks like the Hololens is not able to estimate the time left anymore. I don't know if it's related to this another issue with the WinRT API (https://github.com/MicrosoftDocs/winrt-api/issues/2456)  but unfortunately this is a handicap for us.

It would be great if this could be fixed.

Thank you.
Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8737fffe-c470-d22e-4d8e-6dc3604f6cba
* Version Independent ID: 8737fffe-c470-d22e-4d8e-6dc3604f6cba
* Content: [Device portal API reference - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/device-portal-api-reference)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/device-portal-api-reference.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/device-portal-api-reference.md)
* Service: **mixed-reality**
* Sub-service: **mr-dev**
* GitHub Login: @hamalawi
* Microsoft Alias: **moelhama**

**Comment by AMollis** [comment]
Hi @contactgc

This seems like a product valid issue.  Can you please up a support ticket @  https://aka.ms/hldevsupport, and someone on our support team will help resolve this product.

I'm closing this issue, since this is not a documentation bug.

CC: @RobertVS-MS
