### ISSUE TITLE
Any advice for stuck downloading (at 60%) for days?

### ISSUE THREAD

**Issue by Meigeall** [MicrosoftDocs/mixed-reality#773]
As googling this turns up several instances of other people in the same boat, do you have any idea how to move past this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cedf1af6-08a2-32c6-d530-383aec001ffd
* Version Independent ID: ccee7110-da58-bc2a-7268-8fec02d4753b
* Content: [Installation errors - Enthusiast Guide](https://learn.microsoft.com/en-us/windows/mixed-reality/enthusiast-guide/installation_errors)
* Content Source: [enthusiast-guide/installation_errors.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/enthusiast-guide/installation_errors.md)
* Service: **mixed-reality**
* Sub-service: **enthusiast-guide**
* GitHub Login: @Sean-Kerawala
* Microsoft Alias: **sekerawa**

**Comment by AMollis** [comment]
@Meigeall , thank you for your issue.  However this is not a documentation bug.  

Can you please open a new issue use the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) app in Windows.   The Feedback app will gather relevant telemetry and send it to the support team. The support team will then investigate.
