### ISSUE TITLE
KeywordRecognitionSubsystem CreateOrGetEventForKeyword can not input chinese

### ISSUE THREAD

**Issue by qq464418017** [MicrosoftDocs/mixed-reality#774]
var keywordRecognitionSubsystem = XRSubsystemHelpers.GetFirstRunningSubsystem<KeywordRecognitionSubsystem>();

        if (keywordRecognitionSubsystem != null)
        {
            keywordRecognitionSubsystem.CreateOrGetEventForKeyword("测试").AddListener(() => Debug.Log("Keyword recognized"));
        }
}
create keyword is chinese   unity is exit

**Comment by AMollis** [comment]
This is not valid documentation bug.  If you have feedback for the HoloLens development, please provide via the Feedback tool on an HL2 device.
