### ISSUE TITLE
Wrong UHoloLensARFunctionLibrary class 

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#78]
[Enter feedback here]
We might have listed the wrong method here
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-qr-codes#enabling-qr-detection
_Right before the usage, you should manually enable the tracking by calling UHoloLensARFunctionLibrary::**StartQRCodeCapture**(). After ending the QR code tracking, you should disable it by UHoloLensARFunctionLibrary::**StopCameraCapture**() to save the device resources._

It should be StartCameraCapture() https://docs.unrealengine.com/en-US/API/Plugins/HoloLensAR/UHoloLensARFunctionLibrary/index.html as this class doesn't have any StartQRCodeCapture()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db9ec0f-8219-f292-1ac5-6ca607125b33
* Version Independent ID: a04e35e0-a4a8-2af9-88a7-a5d44f90901b
* Content: [QR codes in Unreal - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-qr-codes)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/unreal-qr-codes.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by hferrone** [comment]
Thanks for catching this @cheles!
