### ISSUE TITLE
Can't See ButtonParent Within Hololens 2 App (2. Getting Started with Azure Spatial Anchors)

### ISSUE THREAD

**Issue by woojinko** [MicrosoftDocs/mixed-reality#81]
Hi all,

I'm going through your Azure Spatial Anchors Tutorial right now. https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02

I'm currently on step 2: Getting Started with Azure Spatial Anchors, and I've gotten through the directions up to "Trying the basic behaviors of Azure Spatial Anchors." However, when I try deploying on to my Hololens, I can't seem to see the ButtonParent asset with the buttons for trying all of the spatial anchor behavior. I see all the other prefabs (DebugWindow, Instructions, and ParentAnchor), but not the buttons.

Is there some visual option I need to change in order to see the buttons?

Thanks,
Woojin

**Comment by martinwilter** [comment]
Hi @woojinko,

This could be caused by this [solver issue](https://developercommunity.visualstudio.com/content/problem/1128346/arm64-c-164-165-regression.html).

To check if it is, you can try to disable smoothing:

![image](https://user-images.githubusercontent.com/16746283/95392870-5cd92b00-08ae-11eb-808b-c2b9d84db334.png)

Or if you have many solvers in your scene (this scene only has 2) you can instead, disable Graphics Jobs in Player settings:

![image](https://user-images.githubusercontent.com/16746283/95393071-ca855700-08ae-11eb-8afa-5d87c581b279.png)

and then in Visual Studio deploy with ARM instead of ARM 64.

Hope this solves this issue, but if not let me know and I'll be happy try to help.

**Comment by woojinko** [comment]
Hi @martinwilter 

Thanks for the quick reply! Disabling smoothing worked for me, thanks a ton for that tip. I did notice that deploying with ARM would lead to an empty scene on the Hololens, so I went back to ARM 64 and it worked well.

I am still running into an issue with Creating and Finding Spatial Anchors though.

This picture below shows the debug window output of clicking Create Azure Anchor for step 3/10 in the directions.
<img width="1280" alt="CreateSpatialAnchorPic" src="https://user-images.githubusercontent.com/35548021/95398648-3a014380-08bb-11eb-8685-0d03f150281a.png">

The debug window didn't seem to mention any errors necessarily, so I decided to go forward anyway. Later on, at step 8/10 Find Azure Anchor, I got this error message:
<img width="1280" alt="EmptyAnchorID" src="https://user-images.githubusercontent.com/35548021/95398756-8056a280-08bb-11eb-8fcd-52c5416d91b9.png">

It's a little blurry, but it says "Current Azure anchor ID is empty". Further down, upon trying step 9/10 Delete Azure Anchor, I got a NullException: value cannot be null.

This leads me to suspect that the azure spatial anchor wasn't successfully created in the first place. Do you have any tips for debugging this?

<img width="1279" alt="AzureID" src="https://user-images.githubusercontent.com/35548021/95398968-f5c27300-08bb-11eb-96d5-60c7ed04c10c.png">

These are my settings with the Spatial Anchor Id and Key filled in.

**Comment by martinwilter** [comment]
Glad to hear you were able to work around the solver issue, @woojinko.

For the ASA error, my first thought it is the same as issue https://github.com/MicrosoftDocs/mixed-reality/issues/77, here's my comment on the issue:

> Assuming you configured the account id and key correctly in your project and your HoloLens have internet access, this could potentially be caused by some recent changes to Azure Spatial Anchors portal where, unless you created the ASA resource using East US 2 location, you must now also configure the account domain in your project.
> 
> In recent ASA SDK versions, this can now be configured in Assets > AzureSpatialAnchors.SDK > Resources > SpatialAnchorConfig, however, this tutorial is using an older ASA SDK version (v2.2.1) where this configuration option is not available. So to verify if this is the issue I think the best option is to [create a new ASA resource](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens#create-a-spatial-anchors-resource) using location **East US 2** and then update your project to use that account id and key.
> 
> Please give this a try and let me know if it solved the issue. Thanks.

**Comment by woojinko** [comment]
Hi @martinwilter 

I gave it a shot with a new ASA in the East US 2 location and updating the spatial anchor manager to take in the new account id and key, but I'm still running into the same error.

Any other ideas on how to get around this?

**Comment by martinwilter** [comment]
Hi @woojinko, sorry to hear that. Maybe double check that your HoloLens can access internet by loading a web page and also verify that internet is enabled in your projects capabilities (you can run the MRTK project configurator again).

**Comment by woojinko** [comment]
Hi @martinwilter 

I've verified that my Hololens is connected to the internet and can load a web page.

Is this the right way to run the MRTK project configurator again? (right side of screenshot)
Additionally, I went to project/player settings and decided to check off EnterpriseAuthentication, InternetClientServer, and PrivateNetworkClientServer just in case (had not been checked off before). I can redeploy and try again with this.
<img width="1280" alt="ProjectConfig" src="https://user-images.githubusercontent.com/35548021/95498754-25738880-0959-11eb-8b83-1b6d21fdbd5f.png">

Lastly, I did a bit of googling, and it looks like https://social.msdn.microsoft.com/Forums/en-US/ac072b7f-ac15-4427-922c-0cef3bdd91d7/cloudspatialexception-error?forum=AzureDevTestLabs is a very similar issue. 

Their solution was "I was logged on my Hololens with a restricted account that prevented me from saving anchors to the cloud. Thanks for your help !"

How can I check if my account is restricted / allows me to save anchors to the cloud?

Thanks again!

**Comment by martinwilter** [comment]
Hi @woojinko,

Unfortunately, I'm not familiar with account restrictions, but if you are using your work or school account, it's very possible that it has some restrictions, if that's the case, maybe you can create your own account and use it instead. If your account is part of a family, the family manager could also have placed restrictions on the accounts.

From what I saw in your screenshot, your error looks different though. To eliminate the ASA resource being the issue, can you try theses credentials, I just loaded our demo app and verified they still work with this project:

Account ID: `b863c64a-be36-41d0-8388-84a3516c8680`
Key: `FpEaeJBOO5zdLd2LCjJ15/rVO+3ShxJo9oGxbDLHk38=`

Please let me know once you tested your app with this id/key, so I can remove them from the thread.

Thanks.

**Comment by woojinko** [comment]
Hi again @martinwilter 

This worked! I guess this means it has something to do with the ASA resource rather than any of my unity/hololens settings?

What should I do moving forward? Will I be able to constantly use this ASA resource you shared in the future as well? Or should I try to figure out why my own ASA resource isn't quite working correctly?

Thank you so much,
Woojin

**Comment by martinwilter** [comment]
Great to hear, @woojinko.

Yes, that should mean that the issue is related to the ASA resource and that your Unity project and HoloLens configuration is fine. You can use this id/key for a few days, but since they are on our account, you can't keep using them in the long run, so you will need to figure out what's going wrong when you create the ASA resource.

Maybe double check that the resource you created is on `East US 2`:

![image](https://user-images.githubusercontent.com/16746283/95514933-a9d20580-0971-11eb-8058-c329a1b06f8b.png)

Also verify that the account domain says `mixedreality.azure.com`.

**Comment by woojinko** [comment]
@martinwilter That makes complete sense, thanks!

Yeah that's pretty strange though - it seems like I have it set correctly (grayed out the sensitive info like you did):

<img width="1271" alt="ASA" src="https://user-images.githubusercontent.com/35548021/95517162-5792e380-0975-11eb-96a2-817e78051f36.png">

Is there anything else I could check? I was looking at my resource group too, but I can't find anything in particular that looks off,
<img width="1276" alt="ResourceGroup" src="https://user-images.githubusercontent.com/35548021/95517271-87da8200-0975-11eb-9a65-fb971e1016d5.png">

**Comment by woojinko** [comment]
Just wanted to follow up to let you know that I got it working for my own Spatial Anchor!!! I'm not entirely sure what changed, but it's definitely working now :) Thank you so much for all the help - I couldn't have gotten this working without your guidance!

I think it may be worth it to add the smoothing and East US 2 notes in the tutorial for future users, but of course this is entirely up to your team's discretion!

Thanks again,
Woojin

**Comment by martinwilter** [comment]
Hi @woojinko, I noticed your Microsoft account (in top right corner of the screenshots) appears to be managed by your university, so my guess would be that there are restrictions associated with the account that's causing this issue. So if you want to keep using that account, I suggest checking with your university if it's possible to remove those restrictions. Alternatively, and probably quicker, you can create a personal Microsoft account and create the ASA resource using that account.

**Comment by woojinko** [comment]
Hi @martinwilter,

Sounds good. I think actually then the step that solved this problem for me earlier must've been me upgrading my account. I selected the free "No Technical Support" subscription plan I believe.
