### ISSUE TITLE
QRCodeWatcher events (Added, Removed, Updated) lacks of explanations

### ISSUE THREAD

**Issue by Gregoire6Fr** [MicrosoftDocs/mixed-reality#83]
Theses events only have a single comment line to explain them so as user we lack of informations about it.
What's the difference between an Added and Updated ?
When the event Removed is called ?

**Comment by hferrone** [comment]
Hi @Gregoire6Fr , can you post the link to the doc you are referring too?

**Comment by Gregoire6Fr** [comment]
Hi, sorry for the lack of this info, here is the details from the specific doc.

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/fr-fr/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
Hi @Gregoire6Fr , the API reference is available at the bottom of the article (https://docs.microsoft.com/fr-fr/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking#qr-api-reference) and the events fire per their title - added fires when a new QR is added, updated fires when a QR code is updated, etc. Removed is called when the QR code is removed.

**Comment by LuuSangCntt** [comment]
From my experience, updated is called when the QR code is moved.
