### ISSUE TITLE
QRCode.LastDetectedTime return invalid value

### ISSUE THREAD

**Issue by Gregoire6Fr** [MicrosoftDocs/mixed-reality#84]
Hello there,

I'm under unity 2019.4.8f1 and the value returned by QRCode.LastDetectedTime is always the same (25/09/2020 in my case) regardless of the QRCode scanned.

**Comment by hferrone** [comment]
Hi @Gregoire6Fr, can you please post the doc you're referring too?

**Comment by Gregoire6Fr** [comment]
Hi, sorry for the lack of this info, here is the details from the specific doc.

* ID: 6572ea07-1ad5-ef4e-72de-e3f5f7e2b086
* Version Independent ID: f8a7b6db-5cd3-b895-0e5f-b079b60b8394
* Content: [QR code tracking - Mixed Reality](https://docs.microsoft.com/fr-fr/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/qr-code-tracking.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @dorreneb
* Microsoft Alias: **dobrown**

**Comment by hferrone** [comment]
@YashMaster Can you assist?

**Comment by YashMaster** [comment]
Thanks for tagging. I'll follow up with the team internally and ping back.

**Comment by hferrone** [comment]
@YashMaster Any updates on this?

**Comment by YashMaster** [comment]
Still following up!

**Comment by hferrone** [comment]
Hi @Gregoire6Fr, what Windows version are you working with, and are you using HoloLens and/or VR desktop?

**Comment by hferrone** [comment]
@chgatla-microsoft

**Comment by chgatla-microsoft** [comment]
@Gregoire6Fr can you please elaborate if you are seeing this in your own app or on the sample app also. Also can you confirm if this is on a hololens or on desktop? and you OS version, the sample app version or if this is only in your app then please share the QR nuget package version you are using.

**Comment by hferrone** [comment]
@Gregoire6Fr - can you also run the app from this release on your HoloLens (https://github.com/chgatla-microsoft/QRTracking/releases/tag/SampleQRCodes_1.0.98.0_Master_Test)

**Comment by ShogoTakagi** [comment]
Hi. I'm having same problem.
Strangely enough, QRCode.LastDetectedTime returns the time to about a month ago...

Project Environment:

Unity2019.4.4f1
LegacyXR(Windows Mixed Reality)
**Holographic Remoting**
MRTK2.5.0

Is there any information on the environment of holographic remoting?

**Comment by ShogoTakagi** [comment]
I created a minimal project that can reproduce the issue.
Please run it in a Holographic Remoting in editor.
https://github.com/ShogoTakagi/ForQRCodeIssue

More information on my environment:
Windows 10 Pro (64bit)
OS build: 19042.685

HoloLens2
Windows Holographic for Business
OS build: 10.0.19041.1134

**Comment by Gregoire6Fr** [comment]
Hey, sorry for the delay. 
I'm working with hololens 2 on my own app and the nuget version of the QR package I'm using is 0.5.2103.
I can't tell you the OS version because I do not have access to the hololens at the moment but I will send it to you when possible.

**Comment by hferrone** [comment]
@chgatla-microsoft Can you take a look at the new info/example project?

**Comment by chgatla-microsoft** [comment]
@Gregoire6Fr unfortunately remoting cannot translate time stamps properly. Do you have the issue when running the app on the device also did you run the sample app on the device to see if you see the same issue?

**Comment by hferrone** [comment]
@chgatla-microsoft Can you explain why it doesn't translate time stamps correctly during remoting? I'll need to update the docs at some point.

**Comment by chgatla-microsoft** [comment]
@hferrone Remoting works by processing the QR data on one device ( in this hololens) and then using them on another device PC unity editor. So when converting timestamps around they might have offset as the Time counters on each machine are different.

**Comment by hferrone** [comment]
@YashMaster Any updates on this from your end?

**Comment by chgatla-microsoft** [comment]
@Gregoire6Fr  or @ShogoTakagi  let me know if you repro this on the device ( not remoting). The remoting will have the issues as posted above ( This need some feature work in the remoting to handle different time stamps.) Let me know if you repro this on live device. Also when you repo (if this is your own app) please try the sample app also and see if that repros. Let me know the details of the OSbuild and the nuget version if it happens.

**Comment by Morgan-6Freedom** [comment]
> Hey, sorry for the delay.
> I'm working with hololens 2 on my own app and the nuget version of the QR package I'm using is 0.5.2103.
> I can't tell you the OS version because I do not have access to the hololens at the moment but I will send it to you when possible.

I work with @Gregoire6Fr and it was on OS V10.0.18362.1042
