### ISSUE TITLE
no PIN requirement arises when connect hololens with visual studio2017 in the first time. 

### ISSUE THREAD

**Issue by YuhengFan** [MicrosoftDocs/mixed-reality#841]
This issue troubles me a few days.when I open the sln generated from unity and deploy it.The problem come out just like the pictures blow.
![image](https://user-images.githubusercontent.com/45955069/53811802-1c5c5180-3f95-11e9-8c38-f32d88ec2e9c.png)
sincerely hoping your reply

**Comment by jessemcculloch** [comment]
This repo is for issues with the documentation.  For support help, please feel free to file a support case at this link - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapid=e9391227-fa6d-927b-0fff-f96288631b8f
