### ISSUE TITLE
Login - YUBIKEY USB/NFC login support for Hololens?

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/mixed-reality#844]
Hello, in recent MS publications, the latest from Satya Nadella says MS focus is without passwords. This is focusing on MSA/Tenant accounts which can use MFA, and Password-less logon with registered identity devices.  

Specifically MSA and Azure, AAD tenants can be configured for YUBIKEY or FEITIAN Identity based logins. 

These makers create devices as USB keys, and even a NFC enabled USB key-chain device, used for Identity purposes. 

Is this supported on HoloLens? May help to put information specific to Holo and latest login

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1842605-c123-49dd-9335-0b7cc0599165
* Version Independent ID: ba9b252f-0409-a848-3e5d-9d90ea93c422
* Content: [Accounts on HoloLens - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/accounts-on-hololens#feedback)
* Content Source: [mixed-reality-docs/accounts-on-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/accounts-on-hololens.md)
* Product: **mixed-reality**
* GitHub Login: @BrandonBray
* Microsoft Alias: **toddly**

**Comment by jessemcculloch** [comment]
Yubikey is not supported on HoloLens as there is neither a USB port, nor NFC capabilities on the device.  We do support using bio-metric authentication win HoloLens 2 using Iris login with Windows Hello
