### ISSUE TITLE
Yubikey - MFA?

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/mixed-reality#845]
In a Enterprise/Commercial release Microsoft is targeting password-less login to Azure. 

This release to Azure MFA is about FIDO, and FIDO 2 compliant login to modern windows device platforms, either with USB or NFC enabled USB identity devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0010c7a7-002c-feb5-b607-3426f8248d4b
* Version Independent ID: a2d3c4b9-3f8e-ba17-d623-65c0770bcaa4
* Content: [Commercial features - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/commercial-features)
* Content Source: [mixed-reality-docs/commercial-features.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/commercial-features.md)
* Product: **mixed-reality**
* GitHub Login: @xerxesb85
* Microsoft Alias: **xerxesb**

**Comment by jessemcculloch** [comment]
Yubikey is not supported on HoloLens as there is neither a USB port, nor NFC capabilities on the device.  We do support using bio-metric authentication win HoloLens 2 using Iris login with Windows Hello
