### ISSUE TITLE
device is still unresponsive

### ISSUE THREAD

**Issue by kbamps** [MicrosoftDocs/mixed-reality#846]
I have tried all above options, but non of them solved the problem. The hololens is still unresponsive en does not turn on. Furthermore,  the WDRT is not able to detect the Hololens even after I followed the instructions. 

Does anyone have a suggestion?

Thanks in advance

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b75391ba-c896-4002-ab90-f872c56d68d3
* Version Independent ID: 519128a5-a472-fc42-ca48-0ce79f3ebc4c
* Content: [Reset or recover your HoloLens - Mixed Reality](https://docs.microsoft.com/nl-nl/windows/mixed-reality/reset-or-recover-your-hololens#feedback)
* Content Source: [mixed-reality-docs/reset-or-recover-your-hololens.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/reset-or-recover-your-hololens.md)
* Product: **mixed-reality**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by jessemcculloch** [comment]
@kbamps - Please file a support request here - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapid=e9391227-fa6d-927b-0fff-f96288631b8f
