### ISSUE TITLE
See also porting link should be directly to MRTK porting info instead of to the general HoloLens 2 page

### ISSUE THREAD

**Issue by ForrestTrepte** [MicrosoftDocs/mixed-reality#864]
The link "Porting from HTK/MRTK to MRTK version 2" goes to https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide. But this is actually the porting guide for HoloLens 1 to HoloLens 2. Instead, I think this link should direct to https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Moving-your-project-from-HoloToolkit-2017-to-MixedRealityToolkit-v2, which is the specific page about porting MRTK1-&gt;MRTK2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95809b24-cc2f-3118-6d05-c504ed734cfc
* Version Independent ID: c9341566-b6b7-25bc-0121-1c6c30a43d49
* Content: [Getting started with MRTK version 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-getting-started)
* Content Source: [mixed-reality-docs/mrtk-getting-started.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrtk-getting-started.md)
* Product: **mixed-reality**
* GitHub Login: @jessemcculloch

**Comment by chrisfromwork** [comment]
Thank you for this feedback.

@keveleigh is this on your radar? I know you are writing richer documentation around hololens 2 porting

**Comment by jessemcculloch** [comment]
Resolved in PR #1489
