### ISSUE TITLE
About taking movable holograms

### ISSUE THREAD

**Issue by tiepu** [MicrosoftDocs/mixed-reality#868]
I have deployed the case and can also see and record color-changing holographic objects on the iPhone.But when I tried to make a movable object, it failed. Objects are movable in hololens, but static in the iPhone. Is there any solution?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d7c80c33-09c9-2f47-7486-d6c406a9a1a4
* Version Independent ID: f8ae5662-23e0-141b-efcc-8e5fb3361193
* Content: [Spectator View - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/spectator-view#feedback)
* Content Source: [mixed-reality-docs/spectator-view.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spectator-view.md)
* Product: **mixed-reality**
* GitHub Login: @chrisfromwork
* Microsoft Alias: **chriba**

**Comment by chrisfromwork** [comment]
Hello,

When you say movable object, what is driving the transform applied to the object? Is it being moved by user input? Spectator View is able to set up a shared coordinate space across devices. It doesn't however perform full scene synchronization. We are working on adding components to the MRTK that enable scene synchronization to help make this process easier, but don't have anything to point at as an example in this point of time.

In terms of unity scene synchronization, most of the spectator view preview (not the current refactor) uses UNet. UNet is in the process of being deprecated by Unity, but it does provide workflows for synchronizing scenes across devices. https://docs.unity3d.com/Manual/UNet.html
