### ISSUE TITLE
XR Settings mess things up for me

### ISSUE THREAD

**Issue by andreawie** [MicrosoftDocs/mixed-reality#88]
Hey,
so I found out through following each step and then building it after single one that when I check _**Virtual Reality Supported**_ under the **XR Settings** Visual Studio won't be able to find the Windows.mirage.pdb Symbol and I was not able to fix it any other way than unchecking it. 
But I also didn't find anyone with the same issue, so maybe it's just a problem on my end. Just thought I'd write that down here, in case someone else experiences the same issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
Hi @andreawie, can you tell me what version of Unity you're using? 

cc: @martinwilter

**Comment by andreawie** [comment]
Oh yeah, forgot to do that, sorry. 
**Unity:** 2019.4.12
**Visual Studio: Enterprise:** 2019 16.7.5
**HoloLens 2 Emulator:** 10.0.19041.1109

**Comment by martinwilter** [comment]
Hi @andreawie, do you face the same issue when deploying to device, or is it only related to the emulator?

**Comment by andreawie** [comment]
Here are the things that I've tried so far:

- Use Visual Studio 2017 instead of 2019

- Activate Windows Mixed Reality through the new XR-Plugin Management option instead of through Player-XR Settings 

- Messing around with the build Settings a little 

- Reinstalling Unity and the HoloLens 2 Emulator

I would try building and running it on the Emulator directly, but the Device Portal for the Emulator doesn't seem to be running as it should. At least it never asked me to type in a username and a password and when I request a pin to set one the Emulator will give me an animation as if it's loading something, but it will stop that 2 seconds after and go back to usual. 

I don't have the actual HoloLens 2 so I will just try to use Unreal Engine instead of Unity for now as I have spent too much time trying to make it work. If anyone has any suggestions on what to do, I'll try it as fast as I can though.

**Comment by martinwilter** [comment]
Thanks for the additional information, @andreawie. Since this issue seems to be related to the emulator and not this tutorial specifically, I recommend referring to the [Using the HoloLens Emulator](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-hololens-emulator) documentation. Did you check if you have all the system requirements?
__
<br>

@hferrone, it seems this issue might be better addressed by someone from the emulator docs team.

**Comment by andreawie** [comment]
@martinwilter Thank you for your response and yes, I do have all the system requirements. 

**--------------------- **Update** ----------------------------------**

I have now managed to run the app directly on the Emulator (You don't need a Device Portal Username and Password, that was my mistake) while having **Windows Mixed Reality** in the **XR Plug-In Management** turned on. 
However at first it didn't load the app properly, I was met with a blank screen after the loading animation. 
On another website, where they were talking about the Hololens 1 Emulator I saw someone say that they had to turn off **desktop accelerated graphics**. 
I tried that, and now I can at least see my objects. Next problem is that I have no controls, so I can't look or walk around, but that's another problem. 

So the problem occurs only when I try to run the project through Visual Studio, I have not found a solution for this yet. 
I will update once I find out something new.

**Comment by hferrone** [comment]
@evmill Is this something you can help with or ping someone on the Emulator/Device team?

**Comment by evmill** [comment]
@pbarnettms Would you be able to help with this?

**Comment by hferrone** [comment]
Hi @andreawie, loading symbols is handled by Visual Studio and the symbol server. You might not have the Microsoft symbol server enabled in the VS symbol settings, which you can find in the VS debug settings. (It should be enabled by default).

**Comment by andreawie** [comment]
I found out that turning **_Use desktop accelerated graphics_** off solves my problem.
