### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by paulmelis** [MicrosoftDocs/mixed-reality#884]
Under Shaders:
&gt; Use full floats for vertex position calculations. On HoloLens 2, use full floats for texture UV to avoid *artificats*

I'd love to see those ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2154cfc5-47bf-8c43-dc77-5e639fbf9773
* Version Independent ID: 93097dca-0667-945e-650e-1f824779c909
* Content: [Performance recommendations for HoloLens apps - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/performance-recommendations-for-hololens-apps)
* Content Source: [mixed-reality-docs/performance-recommendations-for-hololens-apps.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/performance-recommendations-for-hololens-apps.md)
* Product: **mixed-reality**
* GitHub Login: @chbecker-ms
* Microsoft Alias: **chbecker**

**Comment by jessemcculloch** [comment]
This page is no longer, closing this issue
