### ISSUE TITLE
Can't see cube when deployed via VS 2017

### ISSUE THREAD

**Issue by lesterkell** [MicrosoftDocs/mixed-reality#889]
I can see the cube on my hololens when I connect to it via Unity, but when deploying it to the hololens through Visual Studio 2017 I can see no objects when running the app.  Am I missing something?
Unity 2018.3.9f1
Visual Studio 2017 Pro 15.9.10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8969b329-9061-f1c0-70c7-b99aa0aa1b94
* Version Independent ID: a80974ef-fbc2-7559-7711-b899e349c010
* Content: [MR Basics 100 - Getting started with Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-100#feedback)
* Content Source: [mixed-reality-docs/holograms-100.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-100.md)
* Product: **mixed-reality**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by chrisfromwork** [comment]
Hello,

If the cube is at the origin, you may be unable to see it. What is the cubes position in Unity?

**Comment by jessemcculloch** [comment]
@lesterkell - Can you provide the info that @chrisfromwork requested?  If not, I will close this issue on Monday.  Thanks, Jesse

**Comment by salinhard** [comment]
@lesterkell - I have the same issue, did you solve it?

**Comment by lesterkell** [comment]
@salinhard - At the time of writing this I was using Unity 2018.3.9f1.  I tried unity 2019 to no avail, then I installed unity 2017.4.25f1 (LTS) which worked well for me.  I read that I should upgrade to 2018.4.8f1 as it's LTS as well.  Also Unity is stopping support on .net from 2019 onwards so thought it best to try and get it working with IL2CP instead of .net.  When I tried 2018.4.8f1, it wouldn't work for me, I ran into the same problem with not being able to see the cube when deployed fully to the headset.  I can see the cube when playing it remotely through unity but not when compiled and deployed through Visual Studio.  At this point, I hadn't even tried converting it to IL2CP so I can't blame that yet as 2018 supports both .net and IL2CP.  I don't understand why 2017 works and 2018 doesn't for me.

IL2CP

**Comment by lesterkell** [comment]
@chrisfromwork - As stated in my last comment, it works when I use Unity 2017 but not Unity 2018.4.8f1.  When I try and load the app on the hololens, I don't even get the Unity splash screen.  Just nothing at all is displayed.  I can still bloom and exit the app ok.  I can see the cube when I play it in unity with remote to the hololens.  I haven't tried IL2CP on 2018.4.8f1 but did try it on version 2018.3.9f1 and no joy as in my first comment. Thanks for the support.

Position of cube is: X = 0,Y = 0,Z = 3

**Comment by salinhard** [comment]
@lesterkell - I have the same issu, I can see the cube with the unity editor and with the hololen remote player, but when I deploy on hololens or on emuletor I have only a black screen.
I'm trying with Unity 2018.4.8f1 and Visual Studio 2017, both with IL2CP and .net but does not work.
I will try some other example, thank you for your info

**Comment by salinhard** [comment]
@lesterkell - Ok, I realized what I was doing wrong
In playerSettings -> XR Settings -> WSA Holographic Remoting Support was checked, and it need to be unchecked.
Now it works perfectly and it start with the Unity splash screen as expected

**Comment by lesterkell** [comment]
@salinhard - Thank you for the feedback.  I'll give that a try tonight and see if it solves my problem as well.  I thought the instructions said is had to be checked?

**Comment by amrtavarshini** [comment]
@salinhard mine isn't checked and I still can't see the cube. @lesterkell did you manage to fix the issue?

**Comment by funkju** [comment]
I am having this issue as well on Unity 2018.4.21f1

**Comment by varshinily** [comment]
@funkju unfortunately, the tutorials are a bit outdated so there are things that you would have to do that aren't covered.

Make sure that in **File → Build Settings**, the platform is set to `Universal Windows Platform`, Unity C# Project is checked, Target Device is set to `HoloLens`, Architecture to `x64,` Build Type to `D3D`, Build Configuration to `Release`.

Then go to **Edit → Project Settings → Player → XR Settings**, `Virtual Reality Supported` is checked with Windows Mixed Reality as the selected option, a Depth Format set to `16-bit depth`, and the Stereo Rendering Mode set to S`ingle Pass Instanced`.

Then go to **Edit → Project Settings → Player → Other Settings**, and make sure under **Configuration**, the Scripting Backend is set to `.NET`

Then go to **Edit → Project Settings → Quality**, and make sure that `Very Low` is selected under the Windows Store symbol.

After you create the code, in Build Settings, click on `Add Open Scenes` and then click Build. Once you login to the emulator or HoloLens, go to All Apps and then click on **MixedRealityIntroduction** (or the name you gave it) and you will see the cube.
