### ISSUE TITLE
Instruction clarification & update regarding XR Plug-in Management

### ISSUE THREAD

**Issue by BitterDone** [MicrosoftDocs/mixed-reality#90]
A couple instructions updates

`After Unity has finished importing the Windows Mixed Reality SDK, the MRTK Project Configurator window should appear again. If it doesn't, use the Unity menu to open it.` can be clarified to `use the Mixed Reality Toolkit menu`, because "Unity menu" is too vague for new users

`In the Project Settings window, select Player > XR Settings, then use the Depth Format dropdown to select 16-bit depth` is slightly out of date with respect to the current menu path. With XR Plug-in Managment, the path to changing the Depth Buffer Format is now `In the Project Settings window, select XR Plug-in Management > Windows Mixed Reality, then use the Depth Buffer Format dropdown`

Thank you for all the hard work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d36428-004c-e29f-ac5a-602bcbabdb25
* Version Independent ID: 01015fb5-d01b-c738-6671-9a0ca9af000e
* Content: [Getting started tutorials - 2. Initializing your project and deploying your first application - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-base-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment]
@martinwilter Can you confirm?

**Comment by martinwilter** [comment]
Hi @hferrone,

> `After Unity has finished importing the Windows Mixed Reality SDK, the MRTK Project Configurator window should appear again. If it doesn't, use the Unity menu to open it.` can be clarified to `use the Mixed Reality Toolkit menu`, because "Unity menu" is too vague for new users

The full menu path is written out in step 1:

![image](https://user-images.githubusercontent.com/16746283/96069992-2a05d880-0e54-11eb-81a5-98e5d868dac0.png)

so we didn't feel it was necessary to write it out in step 2:

![image](https://user-images.githubusercontent.com/16746283/96070054-499d0100-0e54-11eb-892d-34619de4579c.png)

but there should be any problem repeating it. I think either way is fine.
__

<br>

> `In the Project Settings window, select Player > XR Settings, then use the Depth Format dropdown to select 16-bit depth` is slightly out of date with respect to the current menu path. With XR Plug-in Managment, the path to changing the Depth Buffer Format is now `In the Project Settings window, select XR Plug-in Management > Windows Mixed Reality, then use the Depth Buffer Format dropdown`

This tutorial is using the legacy XR system, so I think it needs to stay as is until tutorial has been updated to use the new XR plugin system.
