### ISSUE TITLE
question about the example of a spatial mapping mesh covering a room

### ISSUE THREAD

**Issue by firebrain7** [MicrosoftDocs/mixed-reality#909]
the green mesh spatial mapping image in the front of the article is really amazing. so how to generate the image of high precision like this using my Hololens?
Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62a0220-8d95-be66-37a2-6265a98f0566
* Version Independent ID: 878bfd78-acd8-8605-e6ef-5f0b85f9943c
* Content: [Spatial mapping - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping#feedback)
* Content Source: [mixed-reality-docs/spatial-mapping.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-mapping.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by ashishonce** [comment]
Interesting thing will be to create spatial maps with different precision and ability to visualize them at runtime

**Comment by firebrain7** [comment]
great job.
how long it will be released?

**Comment by jessemcculloch** [comment]
@firebrain7 - The visualization you are seeing is one you can do today using the MRTK and Spatial Mapping.  It's just using the spatial mapping and putting the texture on the spatial map mesh.

**Comment by firebrain7** [comment]
> @firebrain7 - The visualization you are seeing is one you can do today using the MRTK and Spatial Mapping. It's just using the spatial mapping and putting the texture on the spatial map mesh.

thanks a lot. I have use spatial mapping and shader to render the environment model, without the MRTK. But the accuracy is not as good as I expected. 
So do you mean that MRTK could enhance the accuracy of spatial mapping?

**Comment by jessemcculloch** [comment]
Yes, using the spatial understanding components of the old MRTK, once you finalized your mesh you could get that level of accuracy when the mesh was finalized
