### ISSUE TITLE
Deprecated code in examples for Unity 2019.4.10f1

### ISSUE THREAD

**Issue by tmhab** [MicrosoftDocs/mixed-reality#91]
In Unity 2019.4.10f1 the code presented in the examples is deprecated, with a note about it being removed in Unity 2020.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d3daf6-e9f9-d400-1941-ab76efed39ef
* Version Independent ID: f8a2ed75-804a-18f2-4d97-eb7737b0de75
* Content: [Persistence in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/persistence-in-unity)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/persistence-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/persistence-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
Hi @tmhab, we are working on updating all our Unity content to use XR SDK instead of the legacy APIs. Be on the lookout for new content :) For now, you'll need to refer to Unity docs and their XR APIs.

**Comment by tmhab** [comment]
Thank you for the heads-up @hferrone, I will be looking forward to reading it in the future 👍
