### ISSUE TITLE
Is it possible to store spatial anchors longer than 24h on android?

### ISSUE THREAD

**Issue by mbuessecker** [MicrosoftDocs/mixed-reality#913]
I tried out the sample project from Azure Spatial Anchors for android and everything worked. I can add an anchor from one smartphone and locate it from another smartphone. The problem is that I cannot locate the anchor after approximately 24h. I know that it is possible to set an expire date, but I did not and I haven't seen it in the code. Is there a time limit for storing the spatial anchors similar to ARCore Cloud Anchors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e059cb3-ec5c-1e05-e47c-c326b65b9e4a
* Version Independent ID: 9af0eb99-5180-dceb-8c83-c28bc28a399e
* Content: [Spatial anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-anchors#feedback)
* Content Source: [mixed-reality-docs/spatial-anchors.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-anchors.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by vriveras** [comment]
It is possible to store spatial anchors for longer than 24h. The service doesn’t delete any of your anchor information unless you explicitly set the expiration time on the anchor or delete the anchor manually.
If you are currently using the sharing anchor sample the original version of the sample was clearing your application storage every time.

```
if (!this.initializing.Wait(0))                 
{                   
    this.initializing.Set();                     
    await this.dbCache.DeleteIfExistsAsync();\\ here the database gets deleted
    await this.dbCache.CreateAsync(); 
    this.initialized.Set();
}
```
This pull request changed this behavior https://github.com/Azure/azure-spatial-anchors-samples/pull/9

**Comment by mbuessecker** [comment]
Thank you!
