### ISSUE TITLE
Updating tutorial assets 

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/mixed-reality#92]
[Enter feedback here]
We should link to latest ASA release. We fixed some bugs in 2.4.0 and from 2.5.0 we removed unitypackages and moved to UPM 

- _ASA supports multiple Azure regions. Consumers should explicitly set the AccountDomain property on the SessionConfiguration object to the Account Domain shown in the Azure Portal for their ASA account. If AccountDomain is unset, the SDK uses “mixedreality.azure.com”, which only works for accounts in the East US 2 region._

- _The Unity SDK is now available as UPM packages. You can find more information about setting up our new UPM packages here. This will be the last release of the Unity Asset package._

Newest Azure Spatial Anchors is 2.6.0 https://github.com/Azure/azure-spatial-anchors-samples/releases/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Azure Spatial Anchors tutorials - 2. Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02#importing-the-tutorial-assets)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by martinwilter** [comment]
Hi @hferrone, I agree ASA should be updated, it would resolve the issue that some readers are facing re the domain. However, before updating link to ASA SDK and docs, I believe the project needs to be tested with the latest SDK version to verify it still works as expected with the latest ASA SDK version.

**Comment by cheles** [comment]
before going down that path, we might mention at least re the domain issue that was fixed in 2.4.0
Also, on the side menu under Sample apps we have Hololens 2- Surfaces. Surfaces redirects to https://docs.microsoft.com/en-us/ Is that still available or hasn't been ported to docs?

**Comment by msftradford** [comment]
@cheles, thanks for bringing this to our attention. we're working on updating the entire tutorial to modern ASA (#31365908). I'm not sure about the surfaces links, probably best to file a separate issue.
