### ISSUE TITLE
The SU sample code references the ToUnity() extension function, however this function is not in the SU SDK for Unity

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/mixed-reality#93]
The SU sample code references the ToUnity() extension function, however this function is not in the SU SDK for Unity.

Where is this extension function coming from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ada88-8eb6-0e07-0b90-02b8b87179bf
* Version Independent ID: 9bb41118-53ab-73c6-5908-83f0c2334536
* Content: [Scene understanding SDK - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/scene-understanding-sdk)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/scene-understanding-SDK.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/scene-understanding-SDK.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @SzymonS
* Microsoft Alias: **szymons**

**Comment by hferrone** [comment]
@SzymonS, is this something you can assist with or ping someone who can?

**Comment by hferrone** [comment]
Hi @AMollis, this doc has been updated! For reference - https://github.com/MicrosoftDocs/mixed-reality/pull/140
