### ISSUE TITLE
Broken link to Unity docs

### ISSUE THREAD

**Issue by fnunnari** [MicrosoftDocs/mixed-reality#936]
Link to "You can find more details on how to use these components at the Unity documentation site."
https://docs.unity3d.com/Manual/windowsholographic-sm-component.html
is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcba0969-c41e-3177-0b1b-a75167bbe753
* Version Independent ID: 88232eae-3a56-e764-b6b5-d87a02d50061
* Content: [Spatial mapping in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping-in-unity#feedback)
* Content Source: [mixed-reality-docs/spatial-mapping-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spatial-mapping-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by ashishonce** [comment]
is someone really going through these feedbacks?

**Comment by thetuvix** [comment]
Apologies for the delay!

We're currently revamping all of these pages to demonstrate the new [Spatial Awareness features in MRTK v2](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.html), but I've pushed a [commit](https://github.com/MicrosoftDocs/mixed-reality/commit/5e84a8e36f8547644ac24452651be4aa54c202d9) to fix up the current page in the meantime.  It should go live soon.

Thanks for the feedback!

**Comment by jessemcculloch** [comment]
Fixed
