### ISSUE TITLE
SU Documentation mentions non-existing SceneQuad API GetOcclusionMask

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/mixed-reality#94]
The documentation mentions a GetOcclusionMask() SceneQuad method, but doesn't describe what it does.  Also this method doesn't appear on the SceneQuad.

There is a SceneQuad::GetSurfaceMask, but again the documentation doesn't describe this method.  

Please remove reference to SceneQuad::GetOcclusionMask and add reference to SceneQuad::GetSurfaceMask.  And provide a description for SceneQuad::GetSurfaceMask

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ada88-8eb6-0e07-0b90-02b8b87179bf
* Version Independent ID: 9bb41118-53ab-73c6-5908-83f0c2334536
* Content: [Scene understanding SDK - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/scene-understanding-sdk#scenecomponents)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/scene-understanding-SDK.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/scene-understanding-SDK.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @SzymonS
* Microsoft Alias: **szymons**

**Comment by hferrone** [comment]
@SzymonS, is this something you can assist with or ping someone who can?

**Comment by hferrone** [comment]
Hi @AMollis, this doc has been updated! For reference - https://github.com/MicrosoftDocs/mixed-reality/pull/140
