### ISSUE TITLE
Autofocus occurs every two seconds

### ISSUE THREAD

**Issue by tiepu** [MicrosoftDocs/mixed-reality#943]
When shooting on the iPhone,The camera is always focusing.About once every two seconds.It affects the shooting effect very much.Did it make any settings?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d7c80c33-09c9-2f47-7486-d6c406a9a1a4
* Version Independent ID: f8ae5662-23e0-141b-efcc-8e5fb3361193
* Content: [Spectator View - Mixed Reality](https://docs.microsoft.com/zh-cn/windows/mixed-reality/spectator-view#feedback)
* Content Source: [mixed-reality-docs/spectator-view.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/spectator-view.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @chrisfromwork
* Microsoft Alias: **chriba**

**Comment by chrisfromwork** [comment]
I don't believe that any of the code in the MRTK would be responsible for this focus change. You may be able to set an autofocus property specific to arkit/iOS:
https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2942262-isautofocusenabled

I'm not sure if this is easily accessible through Unity's arkit wrapper.
