### ISSUE TITLE
TouchScreenKeyboard.done is deprecated

### ISSUE THREAD

**Issue by FelixWeichselgartner** [MicrosoftDocs/mixed-reality#95]
Unity says that TouchScreenKeyboard.done is deprecated. Maybe the documentation should be update. TY.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b15a4f6-fb99-7a99-62ad-f22259d375ba
* Version Independent ID: 688c368c-839a-54e8-6f31-c22204fad338
* Content: [Keyboard input in Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/keyboard-input-in-unity#alternative-keyboard-options)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/keyboard-input-in-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/keyboard-input-in-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @thetuvix
* Microsoft Alias: **alexturn**

**Comment by hferrone** [comment]
Hi @FelixWeichselgartner, thanks for bringing this up. We'll update to use https://docs.unity3d.com/ScriptReference/TouchScreenKeyboard.Status.Done.html
