### ISSUE TITLE
Videos and assets wrong

### ISSUE THREAD

**Issue by BjoernGit** [MicrosoftDocs/mixed-reality#968]
Hi All,
I've come over a few problems in the videos in the basic training and this GAZE Tut. I was able to finish the Basic training after a lot of struggle because a lot of information is wrong or misleading or it doesnt work in a certain version of Unity. I can just suggest everyone who reads this to install at least one LTS version of Unity like 2017.4.15 and Mixed reality Toolkit 2017.4.3.0 which worked for me in the basic course. The latest version of unity seams to work good for this course. The following list only contains infos about the GAZE 210 first two videos to give a few examples of problems:

1:36 Quality and Performance doesnt exist in any of the tested Verisons of Unity. Is it an even older Version? Why not an LTS in the video? For the Hololens 2 I would like you to use an LTS Version if possible with the Holo2 features.

3:38 Deleting the Camera and putting a camera in from the provided assets.
This prefab camera doesnt exist but well I try the normal cam. Worked so far.

Vid2:
1:19 Gaze Manager is structured completely different. What is Stabilizer and Gaze Transform? Its not present in the Video.

Its a lot of trial and error and guesswork. If you are putting out a new Hololens 2 Course in the near future I wouldnt actually care too much about the errors in the current tutorials. Also I understand that the focus is on the latest hardware. But honestly at the moment its very frustrating and I think thats not what you want your customers to feel when learning the essentials of your new technology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c49bf7f-19f2-3dae-0a5c-562ef686e4ea
* Version Independent ID: 6bf4877d-e20b-e055-1ee4-ab6d5d6c7976
* Content: [MR Input 210 - Gaze - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-210#feedback)
* Content Source: [mixed-reality-docs/holograms-210.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-210.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by hferrone** [comment]
@BjoernGit HoloToolKit has been deprecated. Please take a look at the Mixed Reality Toolkit for Unity or Unreal. Thanks!
