### ISSUE TITLE
Improperly formatted note

### ISSUE THREAD

**Issue by RickyRoeslerMS** [MicrosoftDocs/mixed-reality#976]
The note about "Avoid GetComponent(string)" isn't properly formatted so it shows up like this:

[!NOTE] Avoid GetComponent(string)...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b548ae6-f9c1-f8ac-172b-efc80b7b1d26
* Version Independent ID: b5a2db60-a656-daae-ab4a-c47fda79791c
* Content: [Performance recommendations for Unity - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/performance-recommendations-for-unity#feedback)
* Content Source: [mixed-reality-docs/performance-recommendations-for-unity.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/performance-recommendations-for-unity.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @Troy-Ferrell
* Microsoft Alias: **trferrel**

**Comment by Troy-Ferrell** [comment]
Thanks for the find! Fixed
