### ISSUE TITLE
Consider adding a couple more addtional learnings section

### ISSUE THREAD

**Issue by dconleyMSFT** [MicrosoftDocs/mixed-reality#994]
[Enter feedback here]

- Set DepthLSR from SetFocusPlane - Ideally utilize 16-bit depth-buffer for better performance
- Set Single Pass Instanced Rendering Path
- Setup MRTK v2 profiles after port - Turn off teleport & boundry services (generally only needed for VR)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee0cfd0-8f75-e71c-a947-0f131e360ed5
* Version Independent ID: bf6057d7-09ca-be04-578b-af44aab5785c
* Content: [Getting your app ready for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-porting-guide#feedback)
* Content Source: [mixed-reality-docs/mrtk-porting-guide.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrtk-porting-guide.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @author:grbury
* Microsoft Alias: **grbury**

**Comment by jessemcculloch** [comment]
Resolved with PR #1253
